objects/Account.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Premium</fullName>
                    <default>true</default>
                    <label>PREMIUM</label>
                </value>
                <value>
                    <fullName>Standard</fullName>
                    <label>STANDARD</label>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <label>NORMAL</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CQS_Progetto__c.object
<CustomObject>
    <description>This object is a CQS&apos;s Object. It is used to store Projects information. Events and Inspections are related with it. Furthermore it could be used to check new Events/Inspections insert</description>
    <fields>
        <fullName>CQS_Pro_Area__c</fullName>
        <label>Area/Lotto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CQS_Pro_Impresa_Affidataria__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Impresa Affidataria</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>OF_CQS_Anagrafica__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Imprese in raggruppamento, Impresa</value>
            </filterItems>
            <filterItems>
                <field>OF_CQS_Anagrafica__c.CQS_Check_Affidataria__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OF_CQS_Anagrafica__c</referenceTo>
        <relationshipLabel>Progetti</relationshipLabel>
        <relationshipName>Progetti</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Progetto</label>
    <nameField>
        <label>Progetto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progetti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OF_CQS_Anagrafica__c.object
<CustomObject>
    <fields>
        <fullName>CQS_Check_Affidataria__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Attributo che caratterizza un&apos; impresa titolare di contratto d’appalto con OF</inlineHelpText>
        <label>Affidataria</label>
        <type>Checkbox</type>
    </fields>
    <label>Anagrafica</label>
    <nameField>
        <label>Ragione Sociale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anagrafiche</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OF_CQS_Evento__c.object
<CustomObject>
    <fields>
        <fullName>CQS_Ev_Lettera_D_Ordine__c</fullName>
        <label>Lettera D&apos;Ordine</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CQS_Ev_Progetto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Progetto</label>
        <referenceTo>CQS_Progetto__c</referenceTo>
        <relationshipLabel>Eventi</relationshipLabel>
        <relationshipName>Eventi</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Data_Evento__c</fullName>
        <label>Data Evento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Diffida__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Diffida</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Impresa_Esecutrice_Eventi__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Selezionare Impresa esecutrice utilizzando il comando di ricerca</inlineHelpText>
        <label>Impresa Esecutrice</label>
        <referenceTo>OF_CQS_Anagrafica__c</referenceTo>
        <relationshipLabel>Eventi Impresa Esecutrice</relationshipLabel>
        <relationshipName>Eventi_Impresa_Esecutrice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Impresa_Mandataria__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Selezionare Impresa affidataria utilizzando il comando di ricerca.</inlineHelpText>
        <label>Impresa Affidataria</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 1)</booleanFilter>
            <filterItems>
                <field>OF_CQS_Anagrafica__c.CQS_Check_Affidataria__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>OF_CQS_Anagrafica__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Imprese in raggruppamento</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OF_CQS_Anagrafica__c</referenceTo>
        <relationshipLabel>Eventi Impresa Mandataria</relationshipLabel>
        <relationshipName>Eventi_Impresa_Mandataria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Inadempienze_Operative__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inadempienze Operative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Richiesta_Danni__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Richiesta Danni</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Rispetto_Procedura__c</fullName>
        <inlineHelpText>Segnalare l’eventuale mancanza del rispetto dell’area di franco, ritardo nella comunicazione, mancanza di planimetrie degli enti, mancanza di cartografia georadar in cantiere, ecc.</inlineHelpText>
        <label>Rispetto Procedura</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sì</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>NP</fullName>
                </value>
                <value>
                    <fullName>N.P.</fullName>
                    <isActive>false</isActive>
                    <label>N.P.</label>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <isActive>false</isActive>
                    <label>N/A</label>
                </value>
                <value>
                    <fullName>SÃ¬</fullName>
                    <isActive>false</isActive>
                    <label>SÃ¬</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Evento</label>
    <nameField>
        <displayFormat>Inc-{0000000}</displayFormat>
        <label>Evento Numero</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventi</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TEMPLOG__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>TEMPLOG</label>
    <nameField>
        <label>TEMPLOG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TEMPLOG</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CQS_Evento_Trigger_Test.cls
@isTest
public class CQS_Evento_Trigger_Test{
    public static testmethod void CQS_Evento_TriggerMethod(){
    Id RecordTypeIdevent = Schema.SObjectType.OF_CQS_Evento__c.getRecordTypeInfosByName().get('Bad Practice').getRecordTypeId();
    
     Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
      User u2 = new User(Alias = 'nUser1a', Email='newuser1a@testorg.com',
         EmailEncodingKey='UTF-8', LastName='Testing1a', LanguageLocaleKey='en_US',
         LocaleSidKey='en_US', ProfileId = p.Id,
         TimeZoneSidKey='America/Los_Angeles', UserName='newuser1a@testorg.com');
         
          System.runAs(u2) {
    Account acc = new account();
    acc.name = 'Test';
    insert acc;
    
    OF_CQS_Anagrafica__c anag = new OF_CQS_Anagrafica__c();
    anag.CQS_Check_Affidataria__c = true;
    insert anag;
 CQS_Progetto__c pro = new CQS_Progetto__c();
        pro.CQS_Pro_Area__c = 'Test';
        pro.CQS_Pro_Impresa_Affidataria__c = anag.Id;
        insert pro;
    
    OF_CQS_Evento__c even = new OF_CQS_Evento__c();
    even.OF_CQS_Impresa_Mandataria__c = anag.Id;
    even.OF_CQS_Impresa_Esecutrice_Eventi__c = anag.id;
    even.CQS_Ev_Lettera_D_Ordine__c = 'Test';
    even.OF_CQS_Data_Evento__c = System.today();
    even.OF_CQS_Rispetto_Procedura__c = 'Sì';
    even.OF_CQS_Diffida__c  = FALSE;
    even.CQS_Ev_Progetto__c=pro.id;
    even.OF_CQS_Inadempienze_Operative__c = FALSE;
    even.recordtypeid=RecordTypeIdevent;
    even.OF_CQS_Richiesta_Danni__c  = true;
    insert even;
    
    TEMPLOG__c tem = new TEMPLOG__c();
    tem.Class__c = 'Test';
    insert tem;
    }
    }
}