objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Comune__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Indirizzo__c</fullName>
        <label>Indirizzo</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Numero_Civico__c</fullName>
        <label>Numero Civico</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Particella_Toponomastica__c</fullName>
        <label>Particella Toponomastica</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Phone_2__c</fullName>
        <label>Phone 2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Comune__c</fullName>
        <formula>Account.BillingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Comune</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IDContratto__c</fullName>
        <label>ID Contratto</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <description>Campo che indica il tipo di servizio (GPON Passiva o Open Stream).
Utilizzato per filtrare i casi negli asset intervento a vuoto</description>
        <label>Servizio</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                    <default>true</default>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IdContratto__c</fullName>
        <label>Id Contratto</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_TermPayment__c</fullName>
        <label>TermPayment</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SuspendedDate__c</fullName>
        <label>SuspendedDate</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>EOF_Comune__c</fullName>
        <label>Comune</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_INDIRIZZO__c</fullName>
        <label>Indirizzo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_NUMERO_CIVICO__c</fullName>
        <label>Numero Civico</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_PARTICELLA_TOPONOMASTICA__c</fullName>
        <label>Particella Toponomastica</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EOF_Notify__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Notifiche</relationshipLabel>
        <relationshipName>Notifiche</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Notifica</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notify Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifiche</pluralLabel>
    <recordTypes>
        <fullName>EOF_BILL_Contract</fullName>
        <active>true</active>
        <description>Record Type per la gestione del WS per la sincronizzazione del billing dei contratti</description>
        <label>Billing Contract Record Type</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_BillingElement__c.object
<CustomObject>
    <fields>
        <fullName>OF_Attivo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attivo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CatalogoCommerciale__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; OF_CommercialElement__r.OF_Servizio__r.OF_CatalogoCommerciale__c, OF_CommercialElement__r.OF_Servizio__r.OF_CatalogoCommerciale__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Catalogo commerciale</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_CommercialElement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Commercial element</label>
        <referenceTo>OF_CommercialElement__c</referenceTo>
        <relationshipLabel>Billing elements</relationshipLabel>
        <relationshipName>BillingElements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_DataFineValidita__c</fullName>
        <label>Data fine validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataInizioValidita__c</fullName>
        <label>Data inizio validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; OF_CommercialElement__r.OF_Servizio__c, OF_CommercialElement__r.OF_Servizio__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servizio</label>
        <type>Text</type>
    </fields>
    <label>Billing element</label>
    <nameField>
        <label>Billing element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_CatalogoCommerciale__c.object
<CustomObject>
    <fields>
        <fullName>OF_Attivo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attivo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_DataFineValidita__c</fullName>
        <label>Data fine validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataInizioValidita__c</fullName>
        <label>Data inizio validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Catalogo commerciale</label>
    <nameField>
        <label>Catalogo commerciale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cataloghi commerciali</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_CommercialElement__c.object
<CustomObject>
    <fields>
        <fullName>OF_Attivo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attivo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CatalogoCommerciale__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; OF_Servizio__r.OF_CatalogoCommerciale__c, OF_Servizio__r.OF_CatalogoCommerciale__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Catalogo commerciale</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_DataFineValidita__c</fullName>
        <label>Data fine validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataInizioValidita__c</fullName>
        <label>Data inizio validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Servizio</label>
        <referenceTo>OF_Servizio__c</referenceTo>
        <relationshipLabel>Commercial elements</relationshipLabel>
        <relationshipName>CommercialElements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Commercial element</label>
    <nameField>
        <label>Commercial element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_CommercialElementIstanziato__c.object
<CustomObject>
    <fields>
        <fullName>Comune__c</fullName>
        <formula>Asset_Verticale__r.Comune__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Comune</label>
        <type>Text</type>
    </fields>
    <label>Commercial element istanziato</label>
    <nameField>
        <displayFormat>CEI-{00000}</displayFormat>
        <label>Commercial element istanziato Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial element istanziati</pluralLabel>
    <recordTypes>
        <fullName>Verticale</fullName>
        <active>true</active>
        <label>Verticale</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Enable_PO_UpdateOppCase_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_Enable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Enable PO_UpdateOppCase Trigger</label>
</CustomObject>

objects/OF_Puntamento_Callout__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_OGW__c</fullName>
        <label>OGW</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Puntamento Callout</label>
</CustomObject>

objects/OF_Servizio__c.object
<CustomObject>
    <fields>
        <fullName>OF_Attivo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attivo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CatalogoCommerciale__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Catalogo commerciale</label>
        <referenceTo>OF_CatalogoCommerciale__c</referenceTo>
        <relationshipLabel>Servizi</relationshipLabel>
        <relationshipName>Servizi</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_DataFineValidita__c</fullName>
        <label>Data fine validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataInizioValidita__c</fullName>
        <label>Data inizio validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_Durata_Servizio__c</fullName>
        <formula>OF_DataFineValidita__c -  OF_DataInizioValidita__c</formula>
        <label>OF_Durata_Servizio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OF_Servizio_Code__c</fullName>
        <description>Codice del Servizio</description>
        <label>Servizio Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Servizio</label>
    <nameField>
        <label>Servizio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servizi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Tibco_userID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Metodo per recuperare lo UserID di Tibco</description>
    <fields>
        <fullName>OF_Tibco_ID__c</fullName>
        <label>Tibco ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Tibco userID</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>OF_DataFineValidita__c</fullName>
        <formula>OF_BillingElement__r.OF_DataFineValidita__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Data fine validità</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataInizioValidita__c</fullName>
        <formula>OF_BillingElement__r.OF_DataInizioValidita__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Data inizio validità</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <formula>OF_BillingElement__r.OF_CommercialElement__r.OF_Servizio__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servizio</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SyncBillingContractUtils_Test.cls
@isTest
public class SyncBillingContractUtils_Test {
    
    @testSetup 
    public static void testSetUpData() {
        Insert new OF_Puntamento_Callout__c(Name = 'OGW',OF_OGW__c = 'Test');
        Insert new OF_Tibco_userID__c(Name = 'Tibco UserID',OF_Tibco_ID__c= 'Test');
        Insert new OF_Enable_PO_UpdateOppCase_Trigger__c(Name = 'Status',OF_Enable_Trigger__c= true);
        
    }
    
    static testmethod Map<String,String> RecordType()
    { 
        List<RecordType> rtypes = [Select developerName, Id From RecordType where (sObjectType='Case' OR sObjectType='Account' OR sObjectType='Contact' OR sObjectType = 'EOF_EAI_Service_Log__c' OR sObjectType = 'EOF_Notify__c')  and isActive=true];
        
        Map<String,String> RecordType = new Map<String,String>{};
        
        for(RecordType rt: rtypes)
            RecordType.put(rt.developerName,rt.Id);
                
       return RecordType;
    }

     public static testMethod void test_checkField1(){
         
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         
         SyncBillingContractUtils.checkField(wrp);
    }
    
    public static testMethod void test_checkField2(){
         
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         wrp.action = 'modify';
         SyncBillingContractUtils.checkField(wrp);
    }
    
     public static testMethod void test_checkField3(){
         
         Account acc = new Account();
         acc.Name = 'OpenFiber';
         insert acc;
        
         Contract contratto = new Contract();
         contratto.OF_IdContratto__c = 'TEST_TIS_001';
         contratto.AccountId = acc.id;
         contratto.Status = 'Sospeso';
         insert contratto;
         
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         wrp.con = contratto;
         wrp.action = 'modify';
         wrp.operationType = 'Create';
         SyncBillingContractUtils.checkField(wrp);
    }
    
    public static testMethod void test_checkField4(){
         
         Account acc = new Account();
         acc.Name = 'OpenFiber';
         insert acc;
        
         Contract contratto = new Contract();
         contratto.OF_IdContratto__c = null;
         contratto.AccountId = acc.id;
         contratto.Status = 'Attivo';
         insert contratto;
        
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         wrp.con = contratto;
         wrp.action = 'modify';
         wrp.operationType = 'Create';
         SyncBillingContractUtils.checkField(wrp);
    }

    public static testMethod void test_checkField6(){
         
         Account acc = new Account();
         acc.Name = 'OpenFiber';
         acc.AccountNumber = '123456789123456789123456789123456789';
         insert acc;
        
         Contract contratto = new Contract();
         contratto.OF_IdContratto__c = 'TEST_TIS_001';
         contratto.AccountId = acc.id;
         contratto.Status = 'Attivo';
         insert contratto;
         
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         wrp.con = contratto;
         wrp.action = 'modify';
         wrp.operationType = 'Create';
         SyncBillingContractUtils.checkField(wrp);
    }

     public static testMethod void test_createListLogA(){
         
         Map<String,String> RecordTypeMap = RecordType();
         
         Account acc = new Account();
         acc.Name = 'OpenFiber';
         insert acc;
        
         Contract contratto = new Contract();
         contratto.OF_IdContratto__c = 'TEST_TIS_001';
         contratto.AccountId = acc.id;
         insert contratto;
        
         EOF_Notify__c notifica = new EOF_Notify__c();
         notifica.Contract__c = contratto.Id;
         notifica.RecordTypeId = RecordTypeMap.get('EOF_BILL_Contract');
         insert notifica;
         
         List<EOF_Notify__c> notifiche = new List<EOF_Notify__c>();
         notifiche.add(notifica);
         
         List<string> errors = new List<string>();
         errors.add('Test1');
         errors.add('Test2');
         
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         
         SyncBillingContractUtils.createListLog(notifiche,errors,'request','response','codice','esito','message');
    }
   
    public static testMethod void test_createListLogB(){
         
         Account acc = new Account();
         acc.Name = 'OpenFiber';
         insert acc;
        
         Contract contratto = new Contract();
         contratto.OF_IdContratto__c = 'TEST_TIS_001';
         contratto.AccountId = acc.id;
         insert contratto;
        
         EOF_Notify__c notifica = new EOF_Notify__c();
         notifica.Contract__c = contratto.Id;
         insert notifica;
         
         List<EOF_Notify__c> notifiche = new List<EOF_Notify__c>();
         notifiche.add(notifica);
         
         List<string> errors = new List<string>();
         errors.add('Test1');
         errors.add('Test2');
         
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         
         SyncBillingContractUtils.createListLog(notifiche,errors,'','response','codice','esito','message');
    }
   
    public static testMethod void test_callWSContractA(){
    
        Map<String,String> RecordTypeMap = RecordType();
         
         Account acc = new Account();
         acc.Name = 'OpenFiber';
         insert acc;
         
        
         Contract contratto = new Contract();
         contratto.OF_IdContratto__c = 'TEST_TIS_001';
         contratto.AccountId = acc.id;
         contratto.StartDate = system.today();
         contratto.ContractTerm = 5;
         insert contratto;
        
         Contract contratto1 = [select id,name,EndDate,NS_Rif__c,Status,StartDate,ContractNumber,SuspendedDate__c,
                                OF_TermPayment__c,OF_IdContratto__c,BillingFrequency__c,ContractTerm,Account.AccountNumber,
                                AccountId from Contract];
         
         //insert contratto;
        
         EOF_Notify__c notifica = new EOF_Notify__c();
         notifica.Contract__c = contratto1.Id;
         notifica.RecordTypeId = RecordTypeMap.get('EOF_BILL_Contract');
         insert notifica;
       
         Test.startTest();
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         wrp.con = contratto1;
         Test.setMock(WebServiceMock.class, new SyncBillingContractUtils_Mock());
         SyncBillingContractUtils.callWSContract(wrp,'');
         Test.stopTest();
    }
 
   
     public static testMethod void test_createResponse(){
         
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         OF_Billing_Outbound_Schema2.BillingAgreementManagerResponseType res = new OF_Billing_Outbound_Schema2.BillingAgreementManagerResponseType();
         SyncBillingContractUtils.createResponse(res);
    }
    
    public static testMethod void test_createLog(){
         Account acc = new Account();
         acc.Name = 'OpenFiber';
         insert acc;
        
         Contract contratto = new Contract();
         contratto.OF_IdContratto__c = 'TEST_TIS_001';
         contratto.AccountId = acc.id;
         insert contratto;
        
         EOF_Notify__c notifica1 = new EOF_Notify__c();
         notifica1.Contract__c = contratto.Id;
         insert notifica1;
        
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         string notifica  = notifica1.id;
         SyncBillingContractUtils.createLog(notifica,'request','response','codice','esito','message');
    }
    
    public static testMethod void test_createLogB(){
         Account acc = new Account();
         acc.Name = 'OpenFiber';
         insert acc;
        
         Contract contratto = new Contract();
         contratto.OF_IdContratto__c = 'TEST_TIS_001';
         contratto.AccountId = acc.id;
         insert contratto;
        
         EOF_Notify__c notifica1 = new EOF_Notify__c();
         notifica1.Contract__c = contratto.Id;
         insert notifica1;
        
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         string notifica  = notifica1.id;
         SyncBillingContractUtils.createLog(notifica,'','response','codice','esito','message');
    }
    
     public static testMethod void test_createLogC(){
         Account acc = new Account();
         acc.Name = 'OpenFiber';
         insert acc;
        
         Contract contratto = new Contract();
         contratto.OF_IdContratto__c = 'TEST_TIS_001';
         contratto.AccountId = acc.id;
         insert contratto;
        
         EOF_Notify__c notifica1 = new EOF_Notify__c();
         notifica1.Contract__c = contratto.Id;
         insert notifica1;
        
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         string notifica  = notifica1.id;
         SyncBillingContractUtils.createLog(notifica,'','','codice','esito','message');
    }
    
   public static testMethod void test_createNotify(){
        
         Account acc = new Account();
         acc.Name = 'OpenFiber';
         insert acc;
        
         Contract contratto = new Contract();
         contratto.OF_IdContratto__c = 'TEST_TIS_001';
         contratto.AccountId = acc.id;
         insert contratto;
        
         EOF_Notify__c notifica = new EOF_Notify__c();
         notifica.Contract__c = contratto.Id;
         insert notifica;
         
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         wrp.con = contratto;
         SyncBillingContractUtils.createNotify(wrp);
    }
    
     public static testMethod void test_createRequest(){
        
         Account acc = new Account();
         acc.Name = 'OpenFiber';
         insert acc;
        
         Contract contratto = new Contract();
         contratto.OF_IdContratto__c = 'TEST_TIS_001';
         contratto.NS_Rif__c='';
         contratto.AccountId = acc.id;
         //contratto.EndDate = system.today();
         insert contratto;
         Date myDatD = contratto.Enddate;
        
         EOF_Notify__c notifica = new EOF_Notify__c();
         notifica.Contract__c = contratto.Id;
         insert notifica;
         
         SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
         wrp.con = contratto;
         SyncBillingContractUtils.createRequest(wrp,notifica.Id,'TimeStamp','Status');
    }
    
    //FIBERLEASE
    /*
    public static testMethod void test_callWSAssetFattibilitaCustom()
    {
       
        String AccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account acc = new Account();
        acc.Lastname = 'TestAccount';
        acc.Phone = '0000';
        acc.EOF_Phone_2__c = '0000';
        acc.EOF_Provincia__c = 'Milano';
        acc.EOF_Comune__c = 'Milano';
        acc.EOF_Indirizzo__c = 'Piazzale Gorini';
        acc.RecordTYpeId = AccountRecordTypeId;
        acc.EOF_Particella_Toponomastica__c = '123';
        acc.EOF_Numero_Civico__c = '7';
        acc.AccountNumber='123456';
        insert acc;
        
        Account acc1=[select id,AccountNumber,Lastname,Phone,EOF_Phone_2__c from Account];
        
        Contract contratto = new Contract();
        contratto.OF_IdContratto__c = 'TEST_TIS_001';
        contratto.AccountId = acc.id;
        insert contratto;
        
        Contract contratto1=[select id,OF_IdContratto__c,AccountId,Account.AccountNumber,ContractNumber,BillingFrequency__c from Contract];

        
        FiberLeaseDaGIS__c gi = new FiberLeaseDaGIS__c();
        gi.AnnoFatt__c='2019';
        gi.Comune__c='test';
        gi.ContractId__c=contratto1.id;
        gi.Lavorato__c= true;
        gi.Mese__c=2;
        
        insert gi;
        
        FiberLeaseDaGIS__c gi1=[select id,AnnoFatt__c,Mese__c,Comune__c,
                                ContractId__c,ContractId__r.OF_IdContratto__c,
                                ContractId__r.AccountId,ContractId__r.Account.AccountNumber,
                                ContractId__r.ContractNumber,ContractId__r.BillingFrequency__c 
                                from FiberLeaseDaGIS__c];

        
        
        OF_CatalogoCommerciale__c catalogo = new OF_CatalogoCommerciale__c();
        Date inizio = Date.newInstance(2016,1,1);
        Date fine = Date.newInstance(2099,12,31);
        catalogo.name = 'Catalogo_Test';
        catalogo.OF_Attivo__c = true;
        catalogo.OF_DataInizioValidita__c = inizio;
        catalogo.OF_DataFineValidita__c = fine;
        insert catalogo;
        
        OF_Servizio__c servizio = new OF_Servizio__c();
        servizio.name = 'VERTICALE';
        Date inizio1 = Date.newInstance(2016,1,1);
        Date fine1 = Date.newInstance(2099,12,31);
        servizio.OF_Attivo__c = true;
        servizio.OF_DataInizioValidita__c = inizio1;
        servizio.OF_DataFineValidita__c = fine1;
        servizio.OF_CatalogoCommerciale__c = catalogo.id;
        servizio.OF_Servizio_Code__c='test';
        //servizio.OF_Durata_Servizio__c=4.2;
        insert servizio;
        
        OF_CommercialElement__c ce = new OF_CommercialElement__c();
        
        Date inizio2 = Date.newInstance(2016,1,1);
        Date fine2 = Date.newInstance(2099,12,31);
        ce.name = 'Servizio Verticale';
        ce.OF_Attivo__c = true;
        ce.OF_DataInizioValidita__c = inizio2;
        ce.OF_DataFineValidita__c = fine2;
        ce.OF_Servizio__c = servizio.id;
        ce.OF_Commercial_Element_Code__c='test';
        
        insert ce;
        
        OF_CommercialElementIstanziato__c CEI=new OF_CommercialElementIstanziato__c();
        //CEI.Name='Test';
        String CeiRecordTypeId = Schema.SObjectType.OF_CommercialElementIstanziato__c.getRecordTypeInfosByName().get('PO_CEI_FiberLease').getRecordTypeId();
        CEI.FiberLeaseDaGISId__c=gi.id;
        CEI.OF_Stato__c='Attivo';
        CEI.UpdateBilling__c= true;
        CEI.OF_CommercialElement__c=ce.id;
        CEI.RecordTypeId=CeiRecordTypeId;
        CEI.OF_DataAttivazione__c=DATETIME.now();
        
        insert CEI;
        

        OF_CommercialElementIstanziato__c cei1 = [SELECT id, RecordType.DeveloperName, OF_DataAttivazione__c,OF_DataCessazione__c,OF_Stato__c,
Name,OF_BillingSyncronized__c,FiberLeaseDaGISId__c,FiberLeaseDaGISId__r.ContractId__r.ContractNumber,
FiberLeaseDaGISId__r.ContractId__r.Account.AccountNumber,
FiberLeaseDaGISId__r.ContractId__r.OF_IdContratto__c,
FiberLeaseDaGISId__r.Comune__c,
OF_CommercialElement__r.OF_Commercial_Element_Code__c,
OF_CommercialElement__r.OF_Servizio__r.OF_Servizio_Code__c,
OF_CommercialElement__r.OF_Servizio__r.OF_DataInizioValidita__c,
OF_CommercialElement__r.OF_Servizio__r.OF_DataFineValidita__c 
From OF_CommercialElementIstanziato__c 
where RecordType.DeveloperName='PO_CEI_FiberLease' and FiberLeaseDaGISId__r.Lavorato__c = true limit 1];
        
        // Instantiate the Pricebook2 record first, setting the Id
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        
        // Run an update DML on the Pricebook2 record
        // This is the weird workaround that enables IsStandard to become true
        // on the PricebookEntry record
        update standardPricebook;
        
        // Re-Query for the Pricebook2 record, for debugging
        standardPricebook = [SELECT IsStandard
                             FROM Pricebook2
                             WHERE Id = : standardPricebook.Id];
        
                OF_BillingElement__c bill = new OF_BillingElement__c();
        bill.Name='test';
        bill.OF_Billing_Element_Code__c ='1234';
        bill.OF_CommercialElement__c = ce.id;
        bill.OF_DataInizioValidita__c = ce.OF_DataInizioValidita__c;
        bill.OF_DataFineValidita__c = ce.OF_DataFineValidita__c;
        insert bill;
        
        // Create the Product
        Product2 testProduct = new Product2(
            OF_BillingElement__c = bill.id,
            Name = 'Contributo Verticale',
            IsActive = true
        );
        insert testProduct;
        
        // Create the PricebookEntry
        PricebookEntry testPbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = testProduct.Id,
            UnitPrice = 100,
            IsActive = true,
            numCoppia__c = 10,
            OF_CommercialElementIstanziato__c=CEI.id,
            OF_DataAttivazione2__c=datetime.now()
        );
        insert testPbe;

        SyncBillingContractUtils.CallFiberLease(new list<OF_CommercialElementIstanziato__c> {CEI1});
        
    }
    */
}