objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bozza</fullName>
                </value>
                <value>
                    <fullName>Attivo</fullName>
                </value>
                <value>
                    <fullName>Non Attivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SyncBilling__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SyncBilling</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TaxationCode__c</fullName>
        <label>TaxationCode</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VATNumber__c</fullName>
        <label>VATNumber</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>OLO</fullName>
        <active>true</active>
        <description>Use this account to store OLO information.</description>
        <label>OLO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OF_SyncBillingAccountTrigger_Test.cls
@isTest
public class OF_SyncBillingAccountTrigger_Test {

    public static testMethod void test1(){
    
    Test.StartTest();
    String AccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
    Account acc = new Account();
    acc.Name = 'Test';
    acc.AccountNumber = '123';
    acc.VATNumber__c = 'Test';
    acc.TaxationCode__c = 123;
    acc.Status__c = 'Bozza';
    acc.RecordTYpeId = AccountRecordTypeId ;
    acc.EOF_Codice_Operatore__c= 'Te';
    acc.StartDate__c = system.today();
    insert acc;
    acc.Status__c = 'Attivo';
    update acc;
    Test.StopTest();
    
    }
    public static testMethod void test2(){
    
    Test.StartTest();
    String AccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
    Account acc = new Account();
    acc.Name = 'Test';
    acc.AccountNumber = '123';
    acc.VATNumber__c = 'Test';
    acc.TaxationCode__c = 123;
    acc.SyncBilling__c = False;
    acc.Status__c = 'Attivo';
    acc.RecordTYpeId = AccountRecordTypeId ;
    acc.EOF_Codice_Operatore__c= 'Te';
    acc.StartDate__c = system.today();
    insert acc;
    acc.Status__c = 'Bozza';
    update acc;
    Test.StopTest();
    
    }
}