objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore_WS__c</fullName>
        <label>Codice Operatore</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VF</fullName>
                </value>
                <value>
                    <fullName>WN</fullName>
                </value>
                <value>
                    <fullName>TIS</fullName>
                </value>
                <value>
                    <fullName>GOI</fullName>
                </value>
                <value>
                    <fullName>CNN</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>FAS</fullName>
                </value>
                <value>
                    <fullName>PLA</fullName>
                </value>
                <value>
                    <fullName>CWN</fullName>
                </value>
                <value>
                    <fullName>4IS</fullName>
                </value>
                <value>
                    <fullName>XMA</fullName>
                </value>
                <value>
                    <fullName>WAR</fullName>
                </value>
                <value>
                    <fullName>UND</fullName>
                </value>
                <value>
                    <fullName>SPE</fullName>
                </value>
                <value>
                    <fullName>UMB</fullName>
                </value>
                <value>
                    <fullName>NEX</fullName>
                </value>
                <value>
                    <fullName>NOI</fullName>
                </value>
                <value>
                    <fullName>RAF</fullName>
                </value>
                <value>
                    <fullName>PAN</fullName>
                </value>
                <value>
                    <fullName>SHS</fullName>
                </value>
                <value>
                    <fullName>ALT</fullName>
                </value>
                <value>
                    <fullName>SIR</fullName>
                </value>
                <value>
                    <fullName>HAL</fullName>
                </value>
                <value>
                    <fullName>BRI</fullName>
                </value>
                <value>
                    <fullName>LAW</fullName>
                </value>
                <value>
                    <fullName>ACA</fullName>
                </value>
                <value>
                    <fullName>FST</fullName>
                </value>
                <value>
                    <fullName>INT</fullName>
                </value>
                <value>
                    <fullName>UNC</fullName>
                </value>
                <value>
                    <fullName>SAI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <externalId>true</externalId>
        <label>Codice Ordine OLO</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EOF_Comune_WS__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Prevista_Attivazione__c</fullName>
        <label>Data Prevista Attivazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EOF_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da lavorare</fullName>
                </value>
                <value>
                    <fullName>Appuntamento Fissato</fullName>
                </value>
                <value>
                    <fullName>Da contattare</fullName>
                </value>
                <value>
                    <fullName>Desospeso</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione</fullName>
                </value>
                <value>
                    <fullName>In Verifica BO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Sospeso BO</fullName>
                </value>
                <value>
                    <fullName>Sospeso Tecn.</fullName>
                </value>
                <value>
                    <fullName>In assegnazione</fullName>
                </value>
                <value>
                    <fullName>Espletato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato KO</fullName>
                </value>
                <value>
                    <fullName>Espletato KO</fullName>
                </value>
                <value>
                    <fullName>Accettato KO</fullName>
                </value>
                <value>
                    <fullName>In Verifica Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Network Creation</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Delivery</fullName>
                </value>
                <value>
                    <fullName>Completato</fullName>
                </value>
                <value>
                    <fullName>Offerta Creata</fullName>
                </value>
                <value>
                    <fullName>Offerta Presentata</fullName>
                </value>
                <value>
                    <fullName>Richiesta modifica offerta da Cliente</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Referente Fattibilità</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Tecnico Fattibilità</fullName>
                </value>
                <value>
                    <fullName>Sospeso OM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_GPON_Vincolante__c</fullName>
        <label>GPON Vincolante</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_ID_Building_WS__c</fullName>
        <externalId>true</externalId>
        <label>ID Building</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Id_Notifica__c</fullName>
        <label>Id Notifica</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Identificativo_del_POP__c</fullName>
        <label>Identificativo del POP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Numero_Civico_WS__c</fullName>
        <label>Numero Civico</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Numero_Telefonico_Principale_Linea__c</fullName>
        <label>Numero Telefonico Principale Linea</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Orario_Appuntamento__c</fullName>
        <label>Orario Appuntamento</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Recapito_Test_Linea__c</fullName>
        <label>Recapito Test Linea</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_SLA_Premium_Assurance__c</fullName>
        <label>SLA Premium Assurance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Telefono_Referente_OLO_Onfield_Notec__c</fullName>
        <label>Telefono Referente OLO Onfield Notech</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipologia_Apparato__c</fullName>
        <label>Tipologia Apparato</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipologia_Servizio__c</fullName>
        <label>Tipologia Servizio</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO_TP_Causale_Apertura_Segnalazione__c</fullName>
        <label>Causale Apertura Segnalazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_TP_Codice_Ordine_Ticket_Provisioning__c</fullName>
        <externalId>true</externalId>
        <label>Codice Ordine OLO</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_TP_Descrizione_Causale__c</fullName>
        <label>Descrizione Causale</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>EOF_Caso_Attivazione</fullName>
        <active>true</active>
        <businessProcess>EOF Support Process</businessProcess>
        <label>EOF Caso - Attivazione</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <label>Codice Ordine OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_DATA_PREVISTA_ATTIVAZIONE__c</fullName>
        <label>Data Prevista Attivazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EOF_GPON_VINCOLANTE__c</fullName>
        <label>GPON Vincolante</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Notifica__c</fullName>
        <label>ID Notifica</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_NUMERO_TELEFONICO_PRINCIPALE_LINEA__c</fullName>
        <label>Numero Telefonico Principale Linea</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ORARIO_APPUNTAMENTO__c</fullName>
        <label>Orario Appuntamento</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_RECAPITO_TEST_LINEA__c</fullName>
        <label>Recapito Test Linea</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_SLA_PREMIUM_ASSURANCE__c</fullName>
        <label>Sla Premium Assurance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_TELEFONO_REFERENTE_OLO_ONFIELD_NOTEC__c</fullName>
        <label>Telefono Referente OLO OnField NoTech</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_TIPOLOGIA_APPARATO__c</fullName>
        <label>Tipologia Apparato</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_TIPOLOGIA_SERVIZIO__c</fullName>
        <label>Tipologia Servizio</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_TP_Causale_Apertura_Segnalazione__c</fullName>
        <label>Causale Apertura Segnalazione</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Segnalazione Provisioning</fullName>
                </value>
                <value>
                    <fullName>Problema Tecnico/Applicativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO_TP_Codice_Ordine_Ticket_Provisioning__c</fullName>
        <externalId>true</externalId>
        <label>Codice Ordine Ticket Provisioning</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Enable_PO_UpdateOppCase_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_Enable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Enable PO_UpdateOppCase Trigger</label>
</CustomObject>

objects/OF_Tibco_userID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Metodo per recuperare lo UserID di Tibco</description>
    <fields>
        <fullName>OF_Tibco_ID__c</fullName>
        <label>Tibco ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Tibco userID</label>
</CustomObject>

classes/PO_TP_COMP_InserimentoTP_Controller_TEST.cls
@isTest
public class PO_TP_COMP_InserimentoTP_Controller_TEST{
    
    public static OF_Tibco_userID__c UserTibcoCreation(){
     
        OF_Tibco_userID__c tibco_user = new OF_Tibco_userID__c();
        tibco_user.Name = 'Tibco UserID';
        tibco_user.OF_Tibco_ID__c = '00558000001f743AAA';   
        insert tibco_user;
        return tibco_user;
    }  
    
    static testmethod void test_method1()
    {       
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];

        OF_Enable_PO_UpdateOppCase_Trigger__c trig_PO_Upd = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trig_PO_Upd.Name = 'Status';
        trig_PO_Upd.OF_Enable_Trigger__c = true;
        insert trig_PO_Upd; 

        OF_Tibco_userID__c utente_tibco = UserTibcoCreation();   
     
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PO - TP - TicketProvisioning Case').getRecordTypeId();
        Case c = new Case();
        c.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c.Subject = 'Segnalazione Provisioning';
        c.Status = 'Acquisito';
        c.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.Origin = 'Portal';
        insert c;
        
        Case c1 = new Case();
        c1.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c1.Subject = 'Segnalazione Provisioning';
        c1.Status = 'Accettato';
        c1.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_01';
        c1.EOF_Codice_Operatore_WS__c = 'VF';
        c1.OwnerId = userInfo.getUserId();
        c1.RecordTypeId = CaseRecordTypeId;
        c1.Origin = 'Portal';
        insert c1;

        case casoAttivazione = new case();
        RecordType rt = [Select id from RecordType where recordtype.developername = 'EOF_Caso_Attivazione'];
        casoAttivazione.Subject = 'Richiesta di attivazione';
        casoAttivazione.EOF_Codice_Ordine_OLO__c = 'TEST_76';
        casoAttivazione.EOF_Data_Prevista_Attivazione__c = system.today();
        casoAttivazione.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        casoAttivazione.Status = 'Acquisito';
        casoAttivazione.EOF_Fase__c = 'In Verifica BO';
        casoAttivazione.Type = '1';
        casoAttivazione.EOF_Tipologia_Servizio__c = 'test';
        casoAttivazione.EOF_Codice_Operatore_WS__c = 'VF';
        casoAttivazione.EOF_SLA_Premium_Assurance__c ='Y';
        casoAttivazione.Account = TestDataFactory.acc;
        casoAttivazione.EOF_Identificativo_del_POP__c = 'PG_01';
        casoAttivazione.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        casoAttivazione.EOF_Numero_Civico_WS__c = '7';
        casoAttivazione.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        casoAttivazione.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        casoAttivazione.EOF_Recapito_Test_Linea__c = '111';
        casoAttivazione.EOF_Tipologia_Apparato__c = 'test';
        casoAttivazione.OwnerId = userInfo.getUserId();
        casoAttivazione.RecordTypeId = rt.id;
        casoAttivazione.EOF_Id_Notifica__c = 'test_01';
        casoAttivazione.Origin = 'Web';
        casoAttivazione.Priority = 'Medium';
        casoAttivazione.EOF_GPON_Vincolante__c = 'Y';        
        insert casoAttivazione;
        
        case casoAttivazione2 = new case();

        casoAttivazione2.Subject = 'Richiesta di attivazione';
        casoAttivazione2.EOF_Codice_Ordine_OLO__c = 'TEST_01';
        casoAttivazione2.EOF_Data_Prevista_Attivazione__c = system.today();
        casoAttivazione2.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        casoAttivazione2.Status = 'Acquisito';
        casoAttivazione2.EOF_Fase__c = 'In Verifica BO';
        casoAttivazione2.Type = '1';
        casoAttivazione2.EOF_Tipologia_Servizio__c = 'test';
        casoAttivazione2.EOF_Codice_Operatore_WS__c = 'VF';
        casoAttivazione2.EOF_SLA_Premium_Assurance__c ='Y';
        casoAttivazione2.Account = TestDataFactory.acc;
        casoAttivazione2.EOF_Comune_WS__c = 'Milano';
        casoAttivazione2.EOF_Identificativo_del_POP__c = 'MI_01';
        casoAttivazione2.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        casoAttivazione2.EOF_Numero_Civico_WS__c = '7';
        casoAttivazione2.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        casoAttivazione2.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        casoAttivazione2.EOF_Recapito_Test_Linea__c = '111';
        casoAttivazione2.EOF_Tipologia_Apparato__c = 'test';
        casoAttivazione2.OwnerId = userInfo.getUserId();
        casoAttivazione2.RecordTypeId = rt.id;
        casoAttivazione2.EOF_Id_Notifica__c = 'test_01';
        casoAttivazione2.Origin = 'Web';
        casoAttivazione2.Priority = 'Medium';
        casoAttivazione2.EOF_GPON_Vincolante__c = 'Y';        
        insert casoAttivazione2;

        Test.StartTest();            
        PO_TP_COMP_InserimentoTP_Controller ins_cont = new PO_TP_COMP_InserimentoTP_Controller();
        ins_cont.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        ins_cont.slToInsert.EOF_Codice_Operatore__c = 'VF';
        ins_cont.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        ins_cont.salvaC();
        
        c.status = 'Annullato';
        update c;
        ins_cont.salvaC();

        PageReference annulla = ins_cont.AnnullaS();
        PageReference escalation = ins_cont.vaiInEscalation();
        ins_cont.calcDescCaus();
        ins_cont.salvaC();

        Test.StopTest();
    }
    //EC 2018 - 10 - 30 start
    
    static testmethod void test_method2()
    {       
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];

        OF_Enable_PO_UpdateOppCase_Trigger__c trig_PO_Upd = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trig_PO_Upd.Name = 'Status';
        trig_PO_Upd.OF_Enable_Trigger__c = true;
        insert trig_PO_Upd; 

        OF_Tibco_userID__c utente_tibco = UserTibcoCreation();  
		
		string statoASistema;
		User userPoloMilano	=[Select id,Alias,Email,EmailEncodingKey,LastName,ProfileId,UserName,UserRoleId 
								from User where name = 'Segnalazioni Provisioning Polo Milano'];
		List<Case> ListaTicketProv = new List<Case>();								
     
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PO - TP - TicketProvisioning Case').getRecordTypeId();
        

        case casoAttivazione = new case();
        RecordType rt = [Select id from RecordType where recordtype.developername = 'EOF_Caso_Attivazione'];
        casoAttivazione.Subject = 'Richiesta di attivazione';
        casoAttivazione.EOF_Codice_Ordine_OLO__c = 'TEST_76';
        casoAttivazione.EOF_Data_Prevista_Attivazione__c = system.today();
        casoAttivazione.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        casoAttivazione.Status = 'Acquisito';
        casoAttivazione.EOF_Fase__c = 'In Verifica BO';
        casoAttivazione.Type = '1';
        casoAttivazione.EOF_Tipologia_Servizio__c = 'test';
        casoAttivazione.EOF_Codice_Operatore_WS__c = 'VF';
        casoAttivazione.EOF_SLA_Premium_Assurance__c ='Y';
        casoAttivazione.Account = TestDataFactory.acc;
        casoAttivazione.EOF_Identificativo_del_POP__c = 'PG_01';
        casoAttivazione.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        casoAttivazione.EOF_Numero_Civico_WS__c = '7';
        casoAttivazione.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        casoAttivazione.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        casoAttivazione.EOF_Recapito_Test_Linea__c = '111';
        casoAttivazione.EOF_Tipologia_Apparato__c = 'test';
        casoAttivazione.OwnerId = userInfo.getUserId();
        casoAttivazione.RecordTypeId = rt.id;
        casoAttivazione.EOF_Id_Notifica__c = 'test_01';
        casoAttivazione.Origin = 'Web';
        casoAttivazione.Priority = 'Medium';
        casoAttivazione.EOF_GPON_Vincolante__c = 'Y';        
        insert casoAttivazione;
        
        case casoAttivazione2 = new case();

        casoAttivazione2.Subject = 'Richiesta di attivazione';
        casoAttivazione2.EOF_Codice_Ordine_OLO__c = 'TEST_01';
        casoAttivazione2.EOF_Data_Prevista_Attivazione__c = system.today();
        casoAttivazione2.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        casoAttivazione2.Status = 'Acquisito';
        casoAttivazione2.EOF_Fase__c = 'In Verifica BO';
        casoAttivazione2.Type = '1';
        casoAttivazione2.EOF_Tipologia_Servizio__c = 'test';
        casoAttivazione2.EOF_Codice_Operatore_WS__c = 'VF';
        casoAttivazione2.EOF_SLA_Premium_Assurance__c ='Y';
        casoAttivazione2.Account = TestDataFactory.acc;
        casoAttivazione2.EOF_Comune_WS__c = 'Milano';
        casoAttivazione2.EOF_Identificativo_del_POP__c = 'MI_01';
        casoAttivazione2.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        casoAttivazione2.EOF_Numero_Civico_WS__c = '7';
        casoAttivazione2.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        casoAttivazione2.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        casoAttivazione2.EOF_Recapito_Test_Linea__c = '111';
        casoAttivazione2.EOF_Tipologia_Apparato__c = 'test';
        casoAttivazione2.OwnerId = userInfo.getUserId();
        casoAttivazione2.RecordTypeId = rt.id;
        casoAttivazione2.EOF_Id_Notifica__c = 'test_01';
        casoAttivazione2.Origin = 'Web';
        casoAttivazione2.Priority = 'Medium';
        casoAttivazione2.EOF_GPON_Vincolante__c = 'Y';        
        insert casoAttivazione2;
		
		Case c = new Case();
        c.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c.Subject = 'Segnalazione Provisioning';
        c.Status = 'Acquisito';
        c.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.Origin = 'Portal';
        insert c;
		
		Case cbis = new Case();
        cbis.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        cbis.Subject = 'Segnalazione Provisioning';
        cbis.Status = 'Acquisito';
        cbis.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        cbis.EOF_Codice_Operatore_WS__c = 'VF';
        cbis.OwnerId = userInfo.getUserId();
        cbis.RecordTypeId = CaseRecordTypeId;
        cbis.Origin = 'Portal';
		try{
        insert cbis;
        }
		Catch(Exception e){
			System.debug('giustamente non inseriamo cbis perché già esiste un ticket provisioning uguale.');
		}
		
        Case c1 = new Case();
        c1.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c1.Subject = 'Segnalazione Provisioning';
        c1.Status = 'Accettato';
        c1.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_01';
        c1.EOF_Codice_Operatore_WS__c = 'VF';
        c1.OwnerId = userInfo.getUserId();
        c1.RecordTypeId = CaseRecordTypeId;
        c1.Origin = 'Portal';
        insert c1;
		
		Case c2 = new Case();
        c2.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c2.Subject = 'Segnalazione Provisioning';
        c2.Status = 'Acquisito';
        c2.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        c2.EOF_Codice_Operatore_WS__c = 'TIS';
        c2.OwnerId = userInfo.getUserId();
        c2.RecordTypeId = CaseRecordTypeId;
        c2.Origin = 'Portal';
		try{
        insert c2;
		}
		Catch(Exception e){
			System.debug('giustamente non inserisce il ticket perché il codice operatore è diverso da quello presente a sistema');
			
		}
		
		Case c3 = new Case();
        c3.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c3.Subject = 'Segnalazione Provisioning';
        c3.Status = 'Acquisito';
        c3.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'CIAONE_20181030';
        c3.EOF_Codice_Operatore_WS__c = 'VF';
        c3.OwnerId = userInfo.getUserId();
        c3.RecordTypeId = CaseRecordTypeId;
        c3.Origin = 'Portal';
		insert c3;

        Test.StartTest();            
        PO_TP_COMP_InserimentoTP_Controller ins_cont = new PO_TP_COMP_InserimentoTP_Controller();
        ins_cont.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'CIAONE_20181030';
        ins_cont.slToInsert.EOF_Codice_Operatore__c = 'VF';
        ins_cont.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        ins_cont.salvaC();
        
        c.status = 'Annullato';
        update c;
        ins_cont.salvaC();

        PageReference annulla = ins_cont.AnnullaS();
        PageReference escalation = ins_cont.vaiInEscalation();
        ins_cont.calcDescCaus();
        ins_cont.salvaC();

        Test.StopTest();
    }
    
     static testmethod void test_method3()
    {       
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];

        OF_Enable_PO_UpdateOppCase_Trigger__c trig_PO_Upd = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trig_PO_Upd.Name = 'Status';
        trig_PO_Upd.OF_Enable_Trigger__c = true;
        insert trig_PO_Upd; 

        OF_Tibco_userID__c utente_tibco = UserTibcoCreation();  
		
		string statoASistema;
		User userPoloMilano	=[Select id,Alias,Email,EmailEncodingKey,LastName,ProfileId,UserName,UserRoleId 
								from User where name = 'Segnalazioni Provisioning Polo Milano'];
		List<Case> ListaTicketProv = new List<Case>();								
     
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PO - TP - TicketProvisioning Case').getRecordTypeId();
        
		
        case casoAttivazione = new case();
        RecordType rt = [Select id from RecordType where recordtype.developername = 'EOF_Caso_Attivazione'];
        casoAttivazione.Subject = 'Richiesta di attivazione';
        casoAttivazione.EOF_Codice_Ordine_OLO__c = 'TEST_76';
        casoAttivazione.EOF_Data_Prevista_Attivazione__c = system.today();
        casoAttivazione.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        casoAttivazione.Status = 'Acquisito';
        casoAttivazione.EOF_Fase__c = 'In Verifica BO';
        casoAttivazione.Type = '1';
        casoAttivazione.EOF_Tipologia_Servizio__c = 'test';
        casoAttivazione.EOF_Codice_Operatore_WS__c = 'VF';
        casoAttivazione.EOF_SLA_Premium_Assurance__c ='Y';
        casoAttivazione.Account = TestDataFactory.acc;
		casoAttivazione.EOF_Comune_WS__c='Milano';
        casoAttivazione.EOF_Identificativo_del_POP__c = 'PG_01';
        casoAttivazione.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        casoAttivazione.EOF_Numero_Civico_WS__c = '7';
        casoAttivazione.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        casoAttivazione.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        casoAttivazione.EOF_Recapito_Test_Linea__c = '111';
        casoAttivazione.EOF_Tipologia_Apparato__c = 'test';
        casoAttivazione.OwnerId = userInfo.getUserId();
        casoAttivazione.RecordTypeId = rt.id;
        casoAttivazione.EOF_Id_Notifica__c = 'test_01';
        casoAttivazione.Origin = 'Web';
        casoAttivazione.Priority = 'Medium';
        casoAttivazione.EOF_GPON_Vincolante__c = 'Y';        
        insert casoAttivazione;
        
        case casoAttivazione2 = new case();

        casoAttivazione2.Subject = 'Richiesta di attivazione';
        casoAttivazione2.EOF_Codice_Ordine_OLO__c = 'TEST_01';
        casoAttivazione2.EOF_Data_Prevista_Attivazione__c = system.today();
        casoAttivazione2.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        casoAttivazione2.Status = 'Acquisito';
        casoAttivazione2.EOF_Fase__c = 'In Verifica BO';
        casoAttivazione2.Type = '1';
        casoAttivazione2.EOF_Tipologia_Servizio__c = 'test';
        casoAttivazione2.EOF_Codice_Operatore_WS__c = 'VF';
        casoAttivazione2.EOF_SLA_Premium_Assurance__c ='Y';
        casoAttivazione2.Account = TestDataFactory.acc;
        casoAttivazione2.EOF_Comune_WS__c = 'Milano';
        casoAttivazione2.EOF_Identificativo_del_POP__c = 'MI_01';
        casoAttivazione2.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        casoAttivazione2.EOF_Numero_Civico_WS__c = '7';
        casoAttivazione2.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        casoAttivazione2.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        casoAttivazione2.EOF_Recapito_Test_Linea__c = '111';
        casoAttivazione2.EOF_Tipologia_Apparato__c = 'test';
        casoAttivazione2.OwnerId = userInfo.getUserId();
        casoAttivazione2.RecordTypeId = rt.id;
        casoAttivazione2.EOF_Id_Notifica__c = 'test_01';
        casoAttivazione2.Origin = 'Web';
        casoAttivazione2.Priority = 'Medium';
        casoAttivazione2.EOF_GPON_Vincolante__c = 'Y';        
        insert casoAttivazione2;
		
		Case c = new Case();
        c.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c.Subject = 'Segnalazione Provisioning';
        c.Status = 'Acquisito';
        c.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.Origin = 'Portal';
        insert c;
		
		Case cbis = new Case();
        cbis.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        cbis.Subject = 'Segnalazione Provisioning';
        cbis.Status = 'Acquisito';
        cbis.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        cbis.EOF_Codice_Operatore_WS__c = 'VF';
        cbis.OwnerId = userInfo.getUserId();
        cbis.RecordTypeId = CaseRecordTypeId;
        cbis.Origin = 'Portal';
		try{
        insert cbis;
        }
		Catch(Exception e){
			System.debug('giustamente non inseriamo cbis perché già esiste un ticket provisioning uguale.');
		}
		
        Case c1 = new Case();
        c1.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c1.Subject = 'Segnalazione Provisioning';
        c1.Status = 'Accettato';
        c1.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_01';
        c1.EOF_Codice_Operatore_WS__c = 'VF';
		c1.EOF_Comune_WS__c = 'Milano';
        c1.OwnerId = userInfo.getUserId();
        c1.RecordTypeId = CaseRecordTypeId;
        c1.Origin = 'Portal';
        insert c1;
		
		Case c2 = new Case();
        c2.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c2.Subject = 'Segnalazione Provisioning';
		c2.EOF_Comune_WS__c = 'Milano';
        c2.Status = 'Acquisito';
        c2.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        c2.EOF_Codice_Operatore_WS__c = 'TIS';
        c2.OwnerId = userInfo.getUserId();
        c2.RecordTypeId = CaseRecordTypeId;
        c2.Origin = 'Portal';
		try{
        insert c2;
		}
		Catch(Exception e){
			System.debug('giustamente non inserisce il ticket perché il codice operatore è diverso da quello presente a sistema');
			
		}
       /* 
        Case c3 = new Case();
        c3.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c3.Subject = 'Segnalazione Provisioning';
        c3.Status = 'Acquisito';
        c3.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'CIAONE_20181030';
        c3.EOF_Codice_Operatore_WS__c = 'VF';
        c3.OwnerId = userInfo.getUserId();
        c3.EOF_Comune_WS__c = 'Milano';
		c3.RecordTypeId = CaseRecordTypeId;
        c3.Origin = 'Portal';
		insert c3;
        */
		
		Case c34 = new Case();
        c34.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c34.Subject = 'Segnalazione Provisioning';
        c34.Status = 'Acquisito';
        c34.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'CIAONE_20181030';
        c34.EOF_Codice_Operatore_WS__c = 'VF';
        c34.OwnerId = userInfo.getUserId();
        c34.EOF_Comune_WS__c = 'Milano';
		c34.RecordTypeId = CaseRecordTypeId;
        c34.Origin = 'Portal';
		insert c34;
        Datetime dataDaSettare = Datetime.now().addDays(-8);
		Test.setCreatedDate(c34.Id, dataDaSettare);
       
		Test.StartTest(); 
                 
        PO_TP_COMP_InserimentoTP_Controller ins_cont = new PO_TP_COMP_InserimentoTP_Controller();
        ins_cont.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'CIAONE_20181030';
        ins_cont.slToInsert.EOF_Codice_Operatore__c = 'VF';
        ins_cont.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        ins_cont.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        ins_cont.salvaC();
        
        PO_TP_COMP_InserimentoTP_Controller ins_cont2 = new PO_TP_COMP_InserimentoTP_Controller();
        ins_cont2.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'CIAONE_20181030';
        ins_cont2.slToInsert.EOF_Codice_Operatore__c = 'TIS';
        ins_cont2.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont2.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        ins_cont2.salvaC();
        
        PO_TP_COMP_InserimentoTP_Controller ins_cont3 = new PO_TP_COMP_InserimentoTP_Controller();
        ins_cont3.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'CIAONE_20181030';
        ins_cont3.slToInsert.EOF_Codice_Operatore__c = 'VF';
        ins_cont3.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont3.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
		
        ins_cont3.salvaC();
        
        Test.StopTest();
    }
    
      static testmethod void test_method4()
    {       
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];

        OF_Enable_PO_UpdateOppCase_Trigger__c trig_PO_Upd = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trig_PO_Upd.Name = 'Status';
        trig_PO_Upd.OF_Enable_Trigger__c = true;
        insert trig_PO_Upd; 

        OF_Tibco_userID__c utente_tibco = UserTibcoCreation();  
		
		string statoASistema;
		User userPoloMilano	=[Select id,Alias,Email,EmailEncodingKey,LastName,ProfileId,UserName,UserRoleId 
								from User where name = 'Segnalazioni Provisioning Polo Milano'];
		List<Case> ListaTicketProv = new List<Case>();								
     
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PO - TP - TicketProvisioning Case').getRecordTypeId();
        
		
        case casoAttivazione = new case();
        RecordType rt = [Select id from RecordType where recordtype.developername = 'EOF_Caso_Attivazione'];
        casoAttivazione.Subject = 'Richiesta di attivazione';
        casoAttivazione.EOF_Codice_Ordine_OLO__c = 'TEST_76';
        casoAttivazione.EOF_Data_Prevista_Attivazione__c = system.today();
        casoAttivazione.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        casoAttivazione.Status = 'Acquisito';
        casoAttivazione.EOF_Fase__c = 'In Verifica BO';
        casoAttivazione.Type = '1';
        casoAttivazione.EOF_Tipologia_Servizio__c = 'test';
        casoAttivazione.EOF_Codice_Operatore_WS__c = 'VF';
        casoAttivazione.EOF_SLA_Premium_Assurance__c ='Y';
        casoAttivazione.Account = TestDataFactory.acc;
		casoAttivazione.EOF_Comune_WS__c='Milano';
        casoAttivazione.EOF_Identificativo_del_POP__c = 'PG_01';
        casoAttivazione.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        casoAttivazione.EOF_Numero_Civico_WS__c = '7';
        casoAttivazione.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        casoAttivazione.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        casoAttivazione.EOF_Recapito_Test_Linea__c = '111';
        casoAttivazione.EOF_Tipologia_Apparato__c = 'test';
        casoAttivazione.OwnerId = userInfo.getUserId();
        casoAttivazione.RecordTypeId = rt.id;
        casoAttivazione.EOF_Id_Notifica__c = 'test_01';
        casoAttivazione.Origin = 'Web';
        casoAttivazione.Priority = 'Medium';
        casoAttivazione.EOF_GPON_Vincolante__c = 'Y';        
        insert casoAttivazione;
        
        /*
        Case c1 = new Case();
        c1.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        c1.Subject = 'Segnalazione Provisioning';
        c1.Status = 'Accettato';
        c1.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        c1.EOF_Codice_Operatore_WS__c = 'VF';
		c1.EOF_Comune_WS__c = 'Milano';
        c1.OwnerId = userInfo.getUserId();
        c1.RecordTypeId = CaseRecordTypeId;
        c1.Origin = 'Portal';
        */
		Test.StartTest(); 
                 
        PO_TP_COMP_InserimentoTP_Controller ins_cont = new PO_TP_COMP_InserimentoTP_Controller();
		
        ins_cont.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        ins_cont.slToInsert.EOF_Codice_Operatore__c = 'VF';
        ins_cont.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        
        ins_cont.salvaC();
        
        PO_TP_COMP_InserimentoTP_Controller ins_cont2 = new PO_TP_COMP_InserimentoTP_Controller();
        ins_cont2.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        ins_cont2.slToInsert.EOF_Codice_Operatore__c = 'TIS';
        ins_cont2.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont2.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        ins_cont2.salvaC();
        
        PO_TP_COMP_InserimentoTP_Controller ins_cont3 = new PO_TP_COMP_InserimentoTP_Controller();
        ins_cont3.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        ins_cont3.slToInsert.EOF_Codice_Operatore__c = 'VF';
        ins_cont3.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont3.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
		
        ins_cont3.salvaC();
        
        Test.StopTest();
    }
    
      static testmethod void test_method5()
    {       
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];

        OF_Enable_PO_UpdateOppCase_Trigger__c trig_PO_Upd = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trig_PO_Upd.Name = 'Status';
        trig_PO_Upd.OF_Enable_Trigger__c = true;
        insert trig_PO_Upd; 

        OF_Tibco_userID__c utente_tibco = UserTibcoCreation();  
		
		string statoASistema;
		User userPoloMilano	=[Select id,Alias,Email,EmailEncodingKey,LastName,ProfileId,UserName,UserRoleId 
								from User where name = 'Segnalazioni Provisioning Polo Milano'];
		List<Case> ListaTicketProv = new List<Case>();								
     
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PO - TP - TicketProvisioning Case').getRecordTypeId();
        
		EOF_EAI_Service_Log__c slToInsert2 = new EOF_EAI_Service_Log__c();
		slToInsert2.PO_TP_Causale_Apertura_Segnalazione__c='Segnalazione Provisioning';
		slToInsert2.PO_TP_Codice_Ordine_Ticket_Provisioning__c='TEST_76';
		slToInsert2.EOF_STATO_ORDINE__c='Acquisito';
		slToInsert2.PO_TP_Descrizione_Causale__c='Sollecito';
		slToInsert2.PO_TP_Dettaglio_Richiesta__c='Descrizione Causale Test';
		slToInsert2.PO_TP_Sottocausale__c='Sollecito attivazione';
		insert slToInsert2;
		
		Test.StartTest(); 
                 
        PO_TP_COMP_InserimentoTP_Controller ins_cont = new PO_TP_COMP_InserimentoTP_Controller();
		
        ins_cont.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        ins_cont.slToInsert.EOF_Codice_Operatore__c = 'VF';
        ins_cont.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        
        ins_cont.salvaC();
        
        PO_TP_COMP_InserimentoTP_Controller ins_cont2 = new PO_TP_COMP_InserimentoTP_Controller();
        ins_cont2.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c='Segnalazione Provisioning';
		ins_cont2.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c='SP_TEST_001';
		ins_cont2.slToInsert.EOF_STATO_ORDINE__c='Acquisito';
		ins_cont2.slToInsert.PO_TP_Descrizione_Causale__c='Sollecito';
		ins_cont2.slToInsert.PO_TP_Dettaglio_Richiesta__c='Descrizione Causale Test';
		ins_cont2.slToInsert.PO_TP_Sottocausale__c='Sollecito attivazione';
		ins_cont2.salvaC();
        
        PO_TP_COMP_InserimentoTP_Controller ins_cont3 = new PO_TP_COMP_InserimentoTP_Controller();
        ins_cont3.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
        ins_cont3.slToInsert.EOF_Codice_Operatore__c = 'VF';
        ins_cont3.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont3.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
		
        ins_cont3.salvaC();
        
        Test.StopTest();
    }
    
       static testmethod void test_method7()
    {       
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];

        OF_Enable_PO_UpdateOppCase_Trigger__c trig_PO_Upd = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trig_PO_Upd.Name = 'Status';
        trig_PO_Upd.OF_Enable_Trigger__c = true;
        insert trig_PO_Upd; 

        OF_Tibco_userID__c utente_tibco = UserTibcoCreation();  
		
		string statoASistema;
		User userPoloMilano	=[Select id,Alias,Email,EmailEncodingKey,LastName,ProfileId,UserName,UserRoleId 
								from User where name = 'Segnalazioni Provisioning Polo Milano'];
		List<Case> ListaTicketProv = new List<Case>();								
     
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PO - TP - TicketProvisioning Case').getRecordTypeId();
        
		
        case casoAttivazione = new case();
        RecordType rt = [Select id from RecordType where recordtype.developername = 'EOF_Caso_Attivazione'];
        casoAttivazione.Subject = 'Richiesta di attivazione';
        casoAttivazione.EOF_Codice_Ordine_OLO__c = 'TEST_76';
        casoAttivazione.EOF_Data_Prevista_Attivazione__c = system.today();
        casoAttivazione.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        casoAttivazione.Status = 'Espletato';
        casoAttivazione.EOF_Fase__c = 'In Verifica BO';
        casoAttivazione.Type = '1';
        casoAttivazione.EOF_Tipologia_Servizio__c = 'test';
        casoAttivazione.EOF_Codice_Operatore_WS__c = 'VF';
        casoAttivazione.EOF_SLA_Premium_Assurance__c ='Y';
        casoAttivazione.Account = TestDataFactory.acc;
		casoAttivazione.EOF_Comune_WS__c='Milano';
        casoAttivazione.EOF_Identificativo_del_POP__c = 'PG_01';
        casoAttivazione.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        casoAttivazione.EOF_Numero_Civico_WS__c = '7';
        casoAttivazione.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        casoAttivazione.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        casoAttivazione.EOF_Recapito_Test_Linea__c = '111';
        casoAttivazione.EOF_Tipologia_Apparato__c = 'test';
        casoAttivazione.OwnerId = userInfo.getUserId();
        casoAttivazione.RecordTypeId = rt.id;
        casoAttivazione.EOF_Id_Notifica__c = 'test_01';
        casoAttivazione.Origin = 'Web';
        casoAttivazione.Priority = 'Medium';
        casoAttivazione.EOF_GPON_Vincolante__c = 'Y';        
        insert casoAttivazione;
        
		Test.StartTest(); 
        
        PO_TP_COMP_InserimentoTP_Controller ins_cont2 = new PO_TP_COMP_InserimentoTP_Controller();
        ins_cont2.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = casoAttivazione.EOF_Codice_Ordine_OLO__c;
        ins_cont2.slToInsert.EOF_Codice_Operatore__c = 'TIS';
        ins_cont2.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont2.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
        ins_cont2.salvaC();
        
        PO_TP_COMP_InserimentoTP_Controller ins_cont3 = new PO_TP_COMP_InserimentoTP_Controller();
        ins_cont3.slToInsert.PO_TP_Codice_Ordine_Ticket_Provisioning__c = casoAttivazione.EOF_Codice_Ordine_OLO__c;
        ins_cont3.slToInsert.EOF_Codice_Operatore__c = 'VF';
        ins_cont3.slToInsert.PO_TP_Descrizione_Causale__c = 'Sollecito';
        ins_cont3.slToInsert.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
		
        ins_cont3.salvaC();
        
        Test.StopTest();
    }
    
    //EC 2018 - 10 - 30 end
    
    static testmethod void test_methodTrigger1()
    {       
        OF_Enable_PO_UpdateOppCase_Trigger__c trig_PO_Upd = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trig_PO_Upd.Name = 'Status';
        trig_PO_Upd.OF_Enable_Trigger__c = true;
        insert trig_PO_Upd; 

        OF_Tibco_userID__c utente_tibco = UserTibcoCreation();   

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        User standard = new User(alias = 'standtZ',email='test_standarduser@testorg.com',emailencodingkey='UTF-8',
                                    lastname='Testing', languagelocalekey='en_US', localesidkey='en_US', ProfileId = p.Id, 
                                    timezonesidkey='America/Los_Angeles',username='test_standarduser@prova.com');
        insert standard;

        Test.StartTest(); 
        System.runAs(standard)
        {            
            String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PO - TP - TicketProvisioning Case').getRecordTypeId();
            Case c = new Case();
            c.PO_TP_Causale_Apertura_Segnalazione__c = 'Segnalazione Provisioning';
            c.Subject = 'Segnalazione Provisioning';
            c.Status = 'Acquisito';
            c.PO_TP_Codice_Ordine_Ticket_Provisioning__c = 'TEST_76';
            c.EOF_Codice_Operatore_WS__c = 'VF';
            c.OwnerId = standard.id;
            c.RecordTypeId = CaseRecordTypeId;
            c.Origin = 'Portal';
            insert c;     
            
            try{
                c.Status = 'In Lavorazione';    
                update c;  
            } 
            catch(Exception e)
            {
                System.debug(e);
            }
        }
        Test.StopTest();
    }
    
    static testmethod void test_methodTrigger2()
    {       
        OF_Enable_PO_UpdateOppCase_Trigger__c trig_PO_Upd = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trig_PO_Upd.Name = 'Status';
        trig_PO_Upd.OF_Enable_Trigger__c = true;
        insert trig_PO_Upd; 

        OF_Tibco_userID__c utente_tibco = UserTibcoCreation();   
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        User standard = new User(alias = 'standtZ',email='test_standarduser@testorg.com',emailencodingkey='UTF-8',
                                    lastname='Testing', languagelocalekey='en_US', localesidkey='en_US', ProfileId = p.Id, 
                                    timezonesidkey='America/Los_Angeles',username='test_standarduser@prova.com');
        insert standard;

        Test.StartTest(); 
        System.runAs(standard)
        {            
            String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PO - TP - TicketProvisioning Case').getRecordTypeId();
            Case c = new Case();
            c.PO_TP_Causale_Apertura_Segnalazione__c = 'Problema tecnico/applicativo';
            c.Subject = 'Incident Management';
            c.Status = 'Acquisito';
            c.EOF_Codice_Operatore_WS__c = 'VF';
            c.OwnerId = standard.id;
            c.RecordTypeId = CaseRecordTypeId;
            c.Origin = 'Portal';
            insert c;     
            
            try{
                c.Status = 'In Lavorazione';    
                update c;  
            } 
            catch(Exception e)
            {
                System.debug(e);
            }
        }
        Test.StopTest();
    }  
    
    
}