objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Comune__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OLO</fullName>
        <active>true</active>
        <description>Use this account to store OLO information.</description>
        <label>OLO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Comune__c</fullName>
        <label>Comune</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Notifica__c</fullName>
        <label>Data Notifica</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EOF_SL_Riferimento__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SL Riferimento</label>
        <referenceTo>EOF_EAI_Service_Log__c</referenceTo>
        <relationshipLabel>EAI Service Logs (SL Riferimento)</relationshipLabel>
        <relationshipName>EAI_Service_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_STATO_ORDINE__c</fullName>
        <label>Stato Ordine</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Stato_Richiesta__c</fullName>
        <label>Stato Richiesta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipo_Comunicazione_String__c</fullName>
        <label>Tipo Comunicazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Id_Comune__c</fullName>
        <description>Campo per salvare id comune</description>
        <label>OF_Id_Comune</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_PROFILO_VLAN__c</fullName>
        <label>Profilo VLan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Nome_Progetto__c</fullName>
        <label>Nome Progetto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Offerta__c</fullName>
        <label>Offerta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P2P Base</fullName>
                </value>
                <value>
                    <fullName>P2P Attiva</fullName>
                </value>
                <value>
                    <fullName>Fiber Link</fullName>
                </value>
                <value>
                    <fullName>IRU</fullName>
                </value>
                <value>
                    <fullName>Fiber Lease</fullName>
                </value>
                <value>
                    <fullName>Evento Temporaneo</fullName>
                </value>
                <value>
                    <fullName>KIT</fullName>
                </value>
                <value>
                    <fullName>Backhauling</fullName>
                </value>
                <value>
                    <fullName>Dark Fiber</fullName>
                </value>
                <value>
                    <fullName>E-Access</fullName>
                </value>
                <value>
                    <fullName>E-Line</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO_SA_Data_Inserimento_Ordine__c</fullName>
        <label>Data Inserimento Ordine</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PO_Tipo_di_collegamento__c</fullName>
        <label>Tipo di Collegamento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Backhauling</fullName>
                </value>
                <value>
                    <fullName>BTS</fullName>
                </value>
                <value>
                    <fullName>Point-to-Point</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Anello</fullName>
                </value>
                <value>
                    <fullName>BACKBONE</fullName>
                </value>
                <value>
                    <fullName>P2P - Cliente</fullName>
                </value>
                <value>
                    <fullName>Dark Fiber</fullName>
                </value>
                <value>
                    <fullName>SDH</fullName>
                </value>
                <value>
                    <fullName>DWDM</fullName>
                </value>
                <value>
                    <fullName>IP</fullName>
                </value>
                <value>
                    <fullName>Layer 2</fullName>
                </value>
                <value>
                    <fullName>NGN</fullName>
                </value>
                <value>
                    <fullName>MSAN</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>E-Access</fullName>
                </value>
                <value>
                    <fullName>E-Line</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <recordTypes>
        <fullName>P2P_Attiva_Collegamento</fullName>
        <active>true</active>
        <label>P2P Attiva Collegamento</label>
    </recordTypes>
    <recordTypes>
        <fullName>PO_P2PAttiva_Request</fullName>
        <active>true</active>
        <label>P2P Attiva Request</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_ElencoComuniItaliani__c.object
<CustomObject>
    <fields>
        <fullName>OF_CodiceIstat__c</fullName>
        <externalId>true</externalId>
        <label>Codice Istat</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OF_Comune__c</fullName>
        <label>Comune</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>ElencoComuniItaliani</label>
    <nameField>
        <displayFormat>ISTAT-{000000}</displayFormat>
        <label>ISTAT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ElenchiComuniItaliani</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OLO_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_Olo_Id__c</fullName>
        <label>Olo Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>OLO ID</label>
</CustomObject>

classes/PO_P2PAttiva_InserisciVLAN_CtrlTest.cls
@isTest
public class PO_P2PAttiva_InserisciVLAN_CtrlTest {
    @testSetup
    public static void testSetUpData() {
        
        //Recupero tutti i recordType
        List<RecordType> rtList = [SELECT developername, Id 
                                   FROM RecordType
                                   WHERE isActive = true];
        //Popolo una map con tutti i recordType avente come key il developername e come Value l'id
        Map<String,String> rtMap = new Map<String,String>();
        for(RecordType rt : rtList){
            rtMap.put(rt.developername, rt.Id);
        }
        
        account acc = new account();
        acc.EOF_Codice_Operatore__c= 'VF';
        acc.name = 'test';        
        insert acc; 
        
        OLO_ID__c olo = new OLO_ID__c();
        olo.name = 'VF';
        olo.OF_Olo_Id__c = acc.Id;
        insert olo;         
        
        OF_ElencoComuniItaliani__c comune = new OF_ElencoComuniItaliani__c();
        comune.OF_CodiceIstat__c = 'Test';
        comune.OF_Provincia__c = 'Test';
        comune.OF_Comune__c = 'Test';
        insert comune;
        
        //ParentLog
        EOF_EAI_Service_Log__c parentLog = new EOF_EAI_Service_Log__c();	
        parentLog.RecordTypeId = rtMap.get('PO_P2PAttiva_Request');
        parentLog.PO_SA_Data_Inserimento_Ordine__c = datetime.now();
        parentLog.EOF_Data_Notifica__c = datetime.now();
        parentLog.EOF_Tipo_Comunicazione_String__c = 'Ordine di Attivazione';
        parentLog.EOF_Stato_Richiesta__c= 'Bozza Portale';
        parentLog.EOF_STATO_ORDINE__c = 'Bozza Portale';
        parentLog.EOF_Codice_Operatore__c = acc.EOF_Codice_Operatore__c;
        parentLog.PO_Nome_Progetto__c = 'TEST_AA';
        parentLog.PO_Offerta__c = 'P2P Attiva';
        //Faccio insert e subito dopo update, perchè al posto di LOG - inserisco il codice operatore OLO(Necessario?)
        insert parentLog;
        
        //ChildLog
        EOF_EAI_Service_Log__c childLog = new EOF_EAI_Service_Log__c();	
        childLog.RecordTypeId = rtMap.get('P2P_Attiva_Collegamento');
        childLog.PO_Offerta__c = 'P2P Attiva';
        childLog.PO_Tipo_di_collegamento__c = 'Point-to-Point';
        childLog.EOF_Stato_Richiesta__c = 'Bozza Portale';
        childLog.EOF_STATO_ORDINE__c = 'Bozza Portale';
        childLog.EOF_Codice_Operatore__c = acc.EOF_Codice_Operatore__c;
        childLog.EOF_Comune__c =  [SELECT OF_Comune__c FROM OF_ElencoComuniItaliani__c WHERE Id = :comune.Id].OF_Comune__c;
        childLog.OF_Id_Comune__c = comune.Id;
        childLog.EOF_SL_Riferimento__c = parentLog.Id;
        childLog.PO_Nome_Progetto__c = 'TEST_AA_child';
        insert childLog;
    }
    
    static testMethod void testMethod1(){
        EOF_EAI_Service_Log__c parentLog = [SELECT Id FROM EOF_EAI_Service_Log__c WHERE PO_Nome_Progetto__c = 'TEST_AA' LIMIT 1];
        EOF_EAI_Service_Log__c childLog = [SELECT Id FROM EOF_EAI_Service_Log__c WHERE PO_Nome_Progetto__c = 'TEST_AA_child' LIMIT 1];
        //Inizia lo scope del test
        Test.startTest();
        //Setto la vfp
        Test.setCurrentPage(Page.PO_P2PAttiva_InserisciVLAN);
        //Setto l'id del childLog
        ApexPages.currentPage().getParameters().put('cLogId', childLog.Id);
        PO_P2PAttiva_InserisciVLAN_Controller ctrl = new PO_P2PAttiva_InserisciVLAN_Controller();
        ctrl.slVlan.OF_SA_PROFILO_VLAN__c = '';
        ctrl.modifyPicklist();
        ctrl.mappingPicklist();
        ctrl.slVlan.OF_SA_PROFILO_VLAN__c = '0';
        ctrl.modifyPicklist();
        ctrl.mappingPicklist();
        ctrl.slVlan.OF_SA_PROFILO_VLAN__c = '3';
        ctrl.modifyPicklist();
        ctrl.mappingPicklist();
        ctrl.slVlan.OF_SA_PROFILO_VLAN__c = '5';
        ctrl.modifyPicklist();
        ctrl.mappingPicklist();
        //
        ctrl.InserisciVLAN();
        ctrl.updateVLAN();
        ctrl.inserisciNuovoKit();
        ctrl.annullaVLAN();
        //Fine scope del test
        Test.stopTest();
    }
}