objects/Account.object
<CustomObject>
    <fields>
        <fullName>OF_BillingSyncronized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Serve per segnalare che c&apos;è stata almeno una sincronizzazione con il billing</description>
        <label>OF_BillingSyncronized</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                    <default>true</default>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_BillingSyncronized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OF_BillingSyncronized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_IdContratto__c</fullName>
        <label>Id Contratto</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_TermPayment__c</fullName>
        <label>TermPayment</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SuspendedDate__c</fullName>
        <label>SuspendedDate</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_Notify__c.object
<CustomObject>
    <label>Notifica</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notify Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifiche</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OF_SyncBillingContract_Batch.cls
global  class OF_SyncBillingContract_Batch implements Database.AllowsCallouts,Database.Batchable<sObject>, Database.Stateful{
    
    private String IdContratto;
    private String ActionType;
    private String operationType;
    
    public OF_SyncBillingContract_Batch(String ConId, string Action, string Operation) {
        IdContratto = ConId;
        ActionType = Action;
        operationType = Operation;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id,Status,StartDate,Name, EndDate,ContractNumber,Account.AccountNumber,NS_Rif__c,OF_BillingSyncronized__c, SuspendedDate__c, OF_TermPayment__c, BillingFrequency__c, ContractTerm, OF_IdContratto__c  FROM contract where Id = \'' + IdContratto + '\' Limit 1' ;
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contract> scope) { 
        
        system.debug('@@@@ scope : '+ scope);
        List<String> errors = new List<String>();
        List<SyncBillingContractUtils.Wrapper> Wrperrors = new List<SyncBillingContractUtils.Wrapper>();
        
        
        for(Contract con : scope){          
            
            SyncBillingContractUtils.Wrapper wrp = new SyncBillingContractUtils.Wrapper();
            wrp.con=con;
            wrp.action=ActionType; 
            wrp.operationType = operationType;
            string check = SyncBillingContractUtils.checkField(wrp);
            if(check.equals('true'))
            { 
                SyncBillingContractUtils.callWSContract(wrp, '');
            }
            else
            {
                Wrperrors.add(wrp);
                errors.add(check);
            }
        }
        //creare notifiche e log
        List<EOF_Notify__c> notif = SyncBillingContractUtils.createListNotify(Wrperrors); 
        SyncBillingContractUtils.createListLog(notif,errors, '', '', '','', '');
    }   
    
    global void finish(Database.BatchableContext BC) {
    }
    
}