objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Comune__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Indirizzo__c</fullName>
        <label>Indirizzo</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Numero_Civico__c</fullName>
        <label>Numero Civico</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Particella_Toponomastica__c</fullName>
        <label>Particella Toponomastica</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Phone_2__c</fullName>
        <label>Phone 2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>EOF_Comune__c</fullName>
        <formula>Network_Inventory__r.EOF_Comune__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Comune</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Risorsa__c</fullName>
        <label>ID Risorsa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Identificativo_del_POP__c</fullName>
        <formula>Network_Inventory__r.EOF_Pop__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Identificativo del POP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Indirizzo__c</fullName>
        <formula>Network_Inventory__r.EOF_Indirizzo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Indirizzo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Particella_Toponomastica__c</fullName>
        <formula>Network_Inventory__r.EOF_Particella_Top__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Particella Toponomastica</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Provincia__c</fullName>
        <formula>Network_Inventory__r.EOF_Provincia__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provincia</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <externalId>true</externalId>
        <label>Codice Ordine OLO</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EOF_Comune__c</fullName>
        <formula>Account.BillingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Comune</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referente Tecnico OLO</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.EOF_Account_OLO__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da lavorare</fullName>
                </value>
                <value>
                    <fullName>Appuntamento Fissato</fullName>
                </value>
                <value>
                    <fullName>Da contattare</fullName>
                </value>
                <value>
                    <fullName>Desospeso</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione</fullName>
                </value>
                <value>
                    <fullName>In Verifica BO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Sospeso BO</fullName>
                </value>
                <value>
                    <fullName>Sospeso Tecn.</fullName>
                </value>
                <value>
                    <fullName>In assegnazione</fullName>
                </value>
                <value>
                    <fullName>Espletato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato KO</fullName>
                </value>
                <value>
                    <fullName>Espletato KO</fullName>
                </value>
                <value>
                    <fullName>Accettato KO</fullName>
                </value>
                <value>
                    <fullName>In Verifica Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Network Creation</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Delivery</fullName>
                </value>
                <value>
                    <fullName>Completato</fullName>
                </value>
                <value>
                    <fullName>Offerta Creata</fullName>
                </value>
                <value>
                    <fullName>Offerta Presentata</fullName>
                </value>
                <value>
                    <fullName>Richiesta modifica offerta da Cliente</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Referente Fattibilità</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Tecnico Fattibilità</fullName>
                </value>
                <value>
                    <fullName>Sospeso OM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Id_Notifica__c</fullName>
        <label>Id Notifica</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Id_Risorsa__c</fullName>
        <label>Id Risorsa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Identificativo_del_POP__c</fullName>
        <label>Identificativo del POP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Esito_Consegna_Apparato__c</fullName>
        <label>Esito Consegna Apparato</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IDContratto__c</fullName>
        <label>ID Contratto</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Profilo__c</fullName>
        <label>Profilo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Case_Collegamento__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case Collegamento</description>
        <label>Case Collegamento</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases (Case Collegamento)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_Richiesta_a_fattibilit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Richiesta a fattibilità</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Collegamenti</relationshipLabel>
        <relationshipName>Collegamenti</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IdContratto__c</fullName>
        <label>Id Contratto</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>EAI Service Logs (Caso)</relationshipLabel>
        <relationshipName>EAI_Service_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <label>Codice Ordine OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Comune__c</fullName>
        <label>Comune</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Notifica__c</fullName>
        <label>ID Notifica</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Risorsa__c</fullName>
        <label>ID Risorsa</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_INDIRIZZO__c</fullName>
        <label>Indirizzo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_NUMERO_CIVICO__c</fullName>
        <label>Numero Civico</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_PARTICELLA_TOPONOMASTICA__c</fullName>
        <label>Particella Toponomastica</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_ACK__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ACK</label>
        <type>Checkbox</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <recordTypes>
        <fullName>FiberRequest</fullName>
        <active>true</active>
        <label>FiberRequest</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Enable_PO_UpdateOppCase_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_Enable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Enable PO_UpdateOppCase Trigger</label>
</CustomObject>

objects/OF_Tibco_userID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Metodo per recuperare lo UserID di Tibco</description>
    <fields>
        <fullName>OF_Tibco_ID__c</fullName>
        <label>Tibco ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Tibco userID</label>
</CustomObject>

classes/PO_P2PAtt_CompletaOrdine_Cntrl_Test.cls
@isTest
public class PO_P2PAtt_CompletaOrdine_Cntrl_Test {

      public static testMethod void Method1()
    {
         OF_Tibco_userID__c tibco = new OF_Tibco_userID__c();
        tibco.Name = 'Tibco UserID';
        tibco.OF_Tibco_ID__c = '00558000001f743AAA';
        insert tibco;
        
        OF_Enable_PO_UpdateOppCase_Trigger__c IpCustom= new OF_Enable_PO_UpdateOppCase_Trigger__c();
        IpCustom.Name = 'Status';
        IpCustom.OF_Enable_Trigger__c = true;
        insert IpCustom; 
    
         String AccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account acc = new Account();
        acc.Lastname = 'TestAccount';
        acc.Phone = '0000';
        acc.EOF_Phone_2__c = '0000';
        acc.EOF_Provincia__c = 'Milano';
        acc.EOF_Comune__c = 'Milano';
        acc.EOF_Indirizzo__c = 'Piazzale Gorini';
        acc.RecordTYpeId = AccountRecordTypeId ;
        acc.EOF_Particella_Toponomastica__c = '123';
        acc.EOF_Numero_Civico__c = '7';
        insert acc;
        
        Contract contratto = new Contract();
        contratto.OF_IdContratto__c = 'TEST_TIS_001';
        contratto.AccountId = acc.id;
        insert contratto;
        
        Asset asset_1 = new Asset();
        asset_1.Name = 'IDR1234';
        asset_1.Status = 'Attivo';
        asset_1.EOF_ID_Risorsa__c = 'IDR1234';
        asset_1.accountId = acc.id;
        asset_1.OF_Contract__c = contratto.Id;
        insert asset_1;
        
         Case c2 = new Case();
        String CaseRecordTypeId2 = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso Attivazione OPENSTREAM CeD').getRecordTypeId();
        c2.AccountId = acc.id;
        c2.EOF_Codice_Ordine_OLO__c = 'Test122';
        c2.EOF_Contact__c = null;
        c2.EOF_Id_Risorsa__c='test122';
        c2.status = 'Accettato';
        c2.EOF_FASE__C = 'NA122';
        c2.OF_SA_Profilo__c='1';
        c2.RecordTypeId=CaseRecordTypeId2;
        c2.AssetId=asset_1.id;
        c2.EOF_Identificativo_del_POP__c='test1122';
        c2.OF_Esito_Consegna_Apparato__c='2';   
       // c2.PO_Case_Collegamento__c=c.id;
        //c1.PO_Richiesta_a_fattibilit__c=c.id;
        c2.NS_Rif__c='TEST';
        insert c2;
        
        Case c = new Case();
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso Attivazione OPENSTREAM CeD').getRecordTypeId();
        c.AccountId = acc.id;
        c.EOF_Codice_Ordine_OLO__c = 'Test';
        c.EOF_Contact__c = null;
        c.EOF_Id_Risorsa__c='test';
        c.status = 'Accettato';
        c.EOF_FASE__C = 'NA';
        c.OF_SA_Profilo__c='1';
        c.RecordTypeId=CaseRecordTypeId;
        c.AssetId=asset_1.id;
        c.EOF_Identificativo_del_POP__c='test';
        c.OF_Esito_Consegna_Apparato__c='2';
        c.PO_Richiesta_a_fattibilit__c=c2.id;
        c.NS_Rif__c='TEST';
        insert c;
        
        Case c1 = new Case();
        String CaseRecordTypeId1 = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso Attivazione OPENSTREAM CeD').getRecordTypeId();
        c1.AccountId = acc.id;
        c1.EOF_Codice_Ordine_OLO__c = 'Test1';
        c1.EOF_Contact__c = null;
        c1.EOF_Id_Risorsa__c='test1';
        c1.status = 'Accettato';
        c1.EOF_FASE__C = 'NA1';
        c1.OF_SA_Profilo__c='1';
        c1.RecordTypeId=CaseRecordTypeId1;
        c1.AssetId=asset_1.id;
        c1.EOF_Identificativo_del_POP__c='test11';
        c1.OF_Esito_Consegna_Apparato__c='2';   
        c1.PO_Case_Collegamento__c=c.id;
        //c1.PO_Richiesta_a_fattibilit__c=c.id;
        c1.ParentId=c.id;
        //c1.NS_Rif__c='TEST';
        insert c1;
        
        
        String eaiRecordType = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('FiberRequest').getRecordTypeId();
        EOF_EAI_Service_Log__c  eaiLog = new EOF_EAI_Service_Log__c();
        eaiLog.Caso__c  = c.Id;
        eaiLog.EOF_ID_Notifica__c = 'test_01';
        eaiLog.EOF_Codice_Ordine_OLO__c = '02112016_37';
        eaiLog.recordTypeId = eaiRecordType;
        eaiLog.OF_SA_ACK__c = true;
        insert eaiLog; 
         
        EOF_EAI_Service_Log__c theLogOrder = new EOF_EAI_Service_Log__c(); 
        theLogOrder.Caso__c  = c1.Id; 
        insert theLogOrder;
  
        ApexPages.currentPage().getParameters().put('ordercaseditId',c1.id);
        PO_P2PAtt_CompletaOrdine_Cntrl PPC=new PO_P2PAtt_CompletaOrdine_Cntrl();
        string nsrif='test';
        PPC.aggiornaTuttiGliOrdini(c1.id, nsrif);
        PPC.orderAnnulla();
        PPC.date4 = '22/01/2019';
        PPC.SaveOrderCase();
        
        
        
    }
}