objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Comune__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Indirizzo__c</fullName>
        <label>Indirizzo</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Numero_Civico__c</fullName>
        <label>Numero Civico</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Particella_Toponomastica__c</fullName>
        <label>Particella Toponomastica</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Phone_2__c</fullName>
        <label>Phone 2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Comune__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Comune__c</fullName>
        <formula>Network_Inventory__r.EOF_Comune__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Comune</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Risorsa__c</fullName>
        <label>ID Risorsa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Indirizzo__c</fullName>
        <formula>Network_Inventory__r.EOF_Indirizzo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Indirizzo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Particella_Toponomastica__c</fullName>
        <formula>Network_Inventory__r.EOF_Particella_Top__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Particella Toponomastica</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Provincia__c</fullName>
        <formula>Network_Inventory__r.EOF_Provincia__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provincia</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Civico__c</fullName>
        <label>Civico</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Comune__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ID_Building__c</fullName>
        <label>ID Building</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Indirizzo__c</fullName>
        <label>Indirizzo</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Particella_Toponomastica__c</fullName>
        <label>Particella Toponomastica</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OF_Asset_Verticale__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Asset Verticali</relationshipLabel>
        <relationshipName>Asset_Verticali</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cardinalita_Scala__c</fullName>
        <label>Cardinalità Scala</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Civico__c</fullName>
        <label>Civico</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comune__c</fullName>
        <label>Comune</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Attivazione__c</fullName>
        <label>Data Attivazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_DB_Building__c</fullName>
        <label>ID_DB_Building</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_DB_Scala_Palazzina__c</fullName>
        <label>ID DB Scala Palazzina</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_GIS_Scala_Palazzina__c</fullName>
        <label>ID GIS Scala Palazzina</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Indirizzo__c</fullName>
        <label>Indirizzo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inviato_PostGreSQL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inviato_PostGreSQL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Particella_Toponomastica__c</fullName>
        <label>Particella Toponomastica</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Asset Verticale</label>
    <nameField>
        <label>Asset Verticale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Verticali</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Billing_Element_Verticale__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Verticale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Verticale</label>
        <referenceTo>OF_Asset_Verticale__c</referenceTo>
        <relationshipLabel>Billing Elements Verticale</relationshipLabel>
        <relationshipName>Billing_Elements_Verticale</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Billing Elements Verticale</relationshipLabel>
        <relationshipName>Billing_Elements_Verticale</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Civico__c</fullName>
        <label>Civico</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comune__c</fullName>
        <label>Comune</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Attivazione__c</fullName>
        <label>Data Attivazione</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID_DB_Scala_palazzina__c</fullName>
        <label>ID_DB_Scala_palazzina</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Risorsa__c</fullName>
        <label>ID Risorsa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Indirizzo__c</fullName>
        <label>Indirizzo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inviato_PostGreSQL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inviato_PostGreSQL</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Element Verticale</label>
    <nameField>
        <label>Billing Element Verticale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Elements Verticale</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Staging_PNI__c.object
<CustomObject>
    <fields>
        <fullName>OF_Civico__c</fullName>
        <label>OF_Civico</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Comune__c</fullName>
        <label>OF_Comune</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ID_Building__c</fullName>
        <label>OF_ID_Building</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Indirizzo__c</fullName>
        <label>OF_Indirizzo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Particella_Toponomastica__c</fullName>
        <label>OF_Particella_Toponomastica</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Staging</label>
    <nameField>
        <label>OF_Staging_PNI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Verticali__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Email_CC__c</fullName>
        <defaultValue>&apos;dl-it-atos-oftibco@atos.net&apos;</defaultValue>
        <description>dl-it-atos-oftibco@atos.net</description>
        <label>Email_CC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <defaultValue>&apos;openfiber.itsupport@enel.com&apos;</defaultValue>
        <description>Openfiber.itsupport@enel.com</description>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_from__c</fullName>
        <defaultValue>&apos;Delivery Services Openfiber&apos;</defaultValue>
        <label>Email_from</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextBody__c</fullName>
        <defaultValue>&quot;Ciao,in allegato il file contenente gli ID Risorsa CRM, per i quali vi chiedo cortesemente l estrazione dei dati toponomastici, gli identificativi building, palazzina e scala, secondo il tracciato condiviso.&quot;</defaultValue>
        <label>TextBody</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>delayAlgoritmo__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Il valore contenuto in questo campo rappresenta i minuti di delay utilizzato per lo scheduling del batch dell&apos;algoritmo</description>
        <label>delayAlgoritmo</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>delayBonifica__c</fullName>
        <defaultValue>240</defaultValue>
        <description>il valore indica i minuti con cui viene schedulata la classe di bonifica finale del processo</description>
        <label>delayBonifica</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>emailSubject__c</fullName>
        <defaultValue>&apos;Estrazione PNI per Verticali &apos;</defaultValue>
        <label>emailSubject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>giorniTolleranza__c</fullName>
        <defaultValue>-2</defaultValue>
        <label>giorniTolleranza</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>limitBatch__c</fullName>
        <defaultValue>10</defaultValue>
        <description>limite di righe elaborate per singolo run del batch dell&apos;algoritmo</description>
        <label>limitBatch</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Verticali</label>
</CustomObject>

classes/BatchSendAssetVerticali_TEST.cls
@isTest
private class BatchSendAssetVerticali_TEST {
    
    public static Verticali__c createVerticaliCustomSetting() {

        Verticali__c cs = new Verticali__c();
        cs.Name='test';
        cs.delayAlgoritmo__c = 1;
        cs.delayBonifica__c = 240;
        cs.Email__c = 'test@test.org';
        cs.Email_CC__c = 'test@test.org';
        cs.Email_from__c = 'Contattaci OpenFiber';
        cs.emailSubject__c = 'subj';
        cs.giorniTolleranza__c = -2;
        cs.limitBatch__c = 10;
        cs.TextBody__c = 'text';
        
        insert cs;
        return cs;
    } 
    
    public static OF_Asset_Verticale__c assetVerticaleCreation1()
    {
        OF_Asset_Verticale__c va = new OF_Asset_Verticale__c();
        
        //va.stato__c = 'Attivo';
        va.Indirizzo__c = 'Nazionale'; 
        va.Civico__c = '34';
        va.Comune__c = 'Milano';
        va.ID_DB_Building__c = 'ID_DB_001';
        va.ID_DB_Scala_Palazzina__c = 'AX001'; 
        va.ID_GIS_Scala_Palazzina__c = 'AX001'; 
        va.Particella_Toponomastica__c = 'Via';
        va.Cardinalita_Scala__c = 1;
        insert va;
        
        return va;
    }
    
    public static OF_Asset_Verticale__c assetVerticaleCreation2()
    {
        OF_Asset_Verticale__c va = new OF_Asset_Verticale__c();
        
        //va.stato__c = 'Attivo';
        va.Indirizzo__c = 'Nazionale'; 
        va.Civico__c = '34';
        va.Comune__c = 'Milano';
        va.ID_DB_Building__c = 'ID_DB_001';
        va.ID_DB_Scala_Palazzina__c = 'AX001'; 
        va.ID_GIS_Scala_Palazzina__c = 'AX001'; 
        va.Particella_Toponomastica__c = 'Via';
        va.Cardinalita_Scala__c = 1;
        va.Inviato_PostGreSQL__c = true;
        insert va;
        
        return va;
    }
    
    public static Account accountCreation()
    {
        String AccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account acc = new Account();
        acc.Lastname = 'TestAccount';
        acc.Phone = '0000';
        acc.EOF_Phone_2__c = '0000';
        acc.EOF_Provincia__c = 'Milano';
        acc.EOF_Comune__c = 'Milano';
        acc.EOF_Indirizzo__c = 'Piazzale Gorini';
        acc.RecordTYpeId = AccountRecordTypeId ;
        acc.EOF_Particella_Toponomastica__c = '123';
        acc.EOF_Numero_Civico__c = '7';
        insert acc;
        
        return acc;
    }
    
    public static Asset assetCreation(Account acc){

        String assetRecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Open Stream').getRecordTypeId();
        Asset asset_1 = new Asset();
        asset_1.Name = 'IDR1234';
        asset_1.Status = 'Attivo';
        asset_1.EOF_ID_Risorsa__c = '1234567890123456789';
        asset_1.recordTypeId = assetRecordTypeId;
        asset_1.accountId = acc.id;
        //asset_1.EOF_ID_Risorsa__c = 'xxxx';
        asset_1.OF_ID_Building__c = 'yyyyy';
		asset_1.OF_Particella_Toponomastica__c  ='VIA';
        asset_1.OF_Indirizzo__c = 'JJJJJ';  
        asset_1.OF_Civico__c ='9';  
        asset_1.OF_Comune__c ='Napoli';        
        insert asset_1;

        return asset_1;
    }
    
    public static OF_Billing_Element_Verticale__c billingElementVCreation(Asset asset_t, OF_Asset_Verticale__c va)
    {
        OF_Billing_Element_Verticale__c verticalBE = new OF_Billing_Element_Verticale__c();
        verticalBE.name = 'BEV-'+asset_t.EOF_ID_Risorsa__c;
        verticalBE.ID_Risorsa__c = asset_t.EOF_ID_Risorsa__c;
        verticalBE.Data_Attivazione__c = System.now();
        //Relaziono il BE Verticale all'Asset Standard
        verticalBE.Asset__c = asset_t.id;
        //Relaziono il BE Verticale all'Asset Verticale
        verticalBE.Asset_Verticale__c = va.id;
        insert verticalBE;
        return verticalBE;
    }
    
      public static OF_Staging_PNI__c stagingCreation()
    {
        OF_Staging_PNI__c stg = new OF_Staging_PNI__c();
        stg.OF_Comune__c='Napoli';
        insert stg;
        
        return stg;
    }

    private static testMethod void test_batch() {
       
        Test.startTest();
        
        createVerticaliCustomSetting();
        Account acc = accountCreation();
        Asset stdAsset = assetCreation(acc);
        OF_Asset_Verticale__c va1 = assetVerticaleCreation1();
        OF_Billing_Element_Verticale__c bev1 = billingElementVCreation(stdAsset, va1);
        
        BatchSendAssetVerticali batchSend = new BatchSendAssetVerticali();
        
        OF_Asset_Verticale__c va2 = assetVerticaleCreation2();
        OF_Billing_Element_Verticale__c bev2 = billingElementVCreation(stdAsset, va2);
        BatchSendAssetVerticali batchSend2 = new BatchSendAssetVerticali();
        
        DataBase.executeBatch(batchSend2); 
        
        Test.stopTest();
    }
    
    private static testMethod void test_batch2() {
       
        
        
        Test.startTest();
        createVerticaliCustomSetting();
            OF_Staging_PNI__c stg2 = stagingCreation();
    
            DataBase.executeBatch(new OF_PNI_DeleteStaging_Batch());
            Test.stopTest();
     
    }
    
    public static testMethod void BonificaAssetVerticali_schedTestMethod() {
        
        Verticali__c cs = new Verticali__c();
		cs.Name = 'test';
		cs.delayAlgoritmo__c = 1;
		cs.delayBonifica__c = 240;
		cs.Email__c = 'test@test.org';
		cs.Email_CC__c = 'test@test.org';
		cs.Email_from__c = 'Delivery Services Openfiber';
		cs.emailSubject__c = 'subj';
		cs.giorniTolleranza__c = -2;
		cs.limitBatch__c = 10;
		cs.TextBody__c = 'text';

		insert cs;
        
        DateTime jobAlgoritmo = System.now().addMinutes(1);
        String hour = String.valueOf(jobAlgoritmo.hour());
        String min = String.valueOf(jobAlgoritmo.minute()); 
        String ss = String.valueOf(jobAlgoritmo.second());

        //parse to cron expression
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' * * ?';
        Test.startTest();
        BatchSendAssetVerticali_sched t2 = new BatchSendAssetVerticali_sched();
        system.schedule('test 02', nextFireTime, t2);
        Test.stopTest();
        
    }
}