objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OLO</fullName>
        <active>true</active>
        <description>Use this account to store OLO information.</description>
        <label>OLO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OLO_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_Olo_Id__c</fullName>
        <label>Olo Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>OLO ID</label>
</CustomObject>

classes/OF_CV_CreaRegola_Controller_Test.cls
@isTest
public class OF_CV_CreaRegola_Controller_Test {
	@testSetup
    public static void testSetUpData() {
        account acc = new account();
        acc.EOF_Codice_Operatore__c= 'VF';
        acc.name = 'test';        
        insert acc; 
        
        OLO_ID__c olo = new OLO_ID__c();
        olo.name = 'VF';
        olo.OF_Olo_Id__c = acc.Id;
        insert olo;
    }
    //OLO_ID__c
    static testMethod void testMethod1(){
        OF_CV_CreaRegola_Controller tmp = new OF_CV_CreaRegola_Controller();
        tmp.servizi = new List<Case>();
        tmp.getOptOperatori();
        tmp.getOptServizi();
        tmp.getStati();
        tmp.sceltaPop();
        tmp.annulla();
    }
}