objects/Account.object
<CustomObject>
    <fields>
        <fullName>BillingEmail__c</fullName>
        <label>BillingEmail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Premium</fullName>
                    <default>true</default>
                    <label>PREMIUM</label>
                </value>
                <value>
                    <fullName>Standard</fullName>
                    <label>STANDARD</label>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <label>NORMAL</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PEC__c</fullName>
        <label>PEC</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bozza</fullName>
                </value>
                <value>
                    <fullName>Attivo</fullName>
                </value>
                <value>
                    <fullName>Non Attivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaxationCode__c</fullName>
        <label>TaxationCode</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VATNumber__c</fullName>
        <label>VATNumber</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                    <default>true</default>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OF_Contract_Code__c</fullName>
        <label>OF_Contract_Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OF_IdContratto__c</fullName>
        <label>Id Contratto</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_TermPayment__c</fullName>
        <label>TermPayment</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SuspendedDate__c</fullName>
        <label>SuspendedDate</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_Notify__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Notifiche</relationshipLabel>
        <relationshipName>Notifiche</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commercial_element_istanziato__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial element istanziato</label>
        <referenceTo>OF_CommercialElementIstanziato__c</referenceTo>
        <relationshipLabel>Notifiche</relationshipLabel>
        <relationshipName>Notifiche</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Notifiche</relationshipLabel>
        <relationshipName>Notifiche</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>EOF Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Notifica__c</fullName>
        <label>ID Notifica</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Billing_OperationType__c</fullName>
        <label>OF_Billing_OperationType</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Billing_Type__c</fullName>
        <label>OF_Billing_Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Notifica</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notify Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifiche</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_CommercialElementIstanziato__c.object
<CustomObject>
    <label>Commercial element istanziato</label>
    <nameField>
        <displayFormat>CEI-{00000}</displayFormat>
        <label>Commercial element istanziato Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial element istanziati</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OF_Billing_RetrySchedule.cls
global class OF_Billing_RetrySchedule implements Schedulable,Database.AllowsCallouts {
    global string IdNotifica{get;set;}
    public OF_Billing_RetrySchedule(String IdNot) { 
        IdNotifica = IdNot;
    }
    global void execute(SchedulableContext SC){     
        EOF_Notify__c notifica = [select id,OF_Billing_Type__c, EOF_ID_Notifica__c, OF_Billing_OperationType__c,Commercial_element_istanziato__r.Id,  Account__r.Id , Contract__r.Id from EOF_Notify__c where EOF_ID_Notifica__c=:IdNotifica Limit 1];
        if(notifica.Account__r.Id!=null)
        {
            Account acc = [Select id,AccountNumber,RecordTypeId, Name,EOF_Codice_Operatore__c, BillingCity, BillingCountry, BillingEmail__c, BillingPostalCode, BillingState, BillingStreet, Status__c, StartDate__c, TaxationCode__c,VATNumber__c, PEC__c, Class__c,  Industry from Account where Id =: notifica.Account__r.Id Limit 1];
            
            SyncBillingAccountUtils.Wrapper wrp = new SyncBillingAccountUtils.Wrapper();
            wrp.acc=acc;
            wrp.action = notifica.OF_Billing_Type__c;
            
            string check = SyncBillingAccountUtils.checkFields(wrp);
            if('true'.equals(check)){
                
                String jsonString = JSON.serialize(wrp);
                CallAccount(jsonString,IdNotifica); 
            }
            
        }
        else if(notifica.Contract__r.Id!=null)
        {
            Contract con = [SELECT Id,Status,StartDate,Name,OF_Contract_Code__c, Account.AccountNumber, ContractNumber, EndDate, SuspendedDate__c, OF_TermPayment__c, BillingFrequency__c, ContractTerm, OF_IdContratto__c  FROM contract where Id =:notifica.Contract__r.Id Limit 1];
            SyncBillingContractUtils.Wrapper wrpC = new SyncBillingContractUtils.Wrapper();
            wrpC.action = notifica.OF_Billing_Type__c;
            wrpC.operationType=notifica.OF_Billing_OperationType__c;
            wrpc.con= con; 
            
            string check = SyncBillingContractUtils.CheckField(wrpC); 
            if('true'.equals(check))
            {
                String jsonString = JSON.serialize(wrpC);
                CallContract(jsonString,IdNotifica);
            }
        }
        else if(notifica.Commercial_element_istanziato__c!=null)
       /* {
            if('PO_CEI_FiberLease'.equals(notifica.Commercial_element_istanziato__r.RecordType.DeveloperName)){
                SyncBillingContractUtils.CallCei(notifica.Commercial_element_istanziato__c,notifica.EOF_ID_Notifica__c);
            }
            else*/{
                SyncBillingAssetUtils.CallCei(notifica.Commercial_element_istanziato__c,notifica.EOF_ID_Notifica__c);
           // }
        }
    }
    @future(callout=true)
    public static void CallContract(String JsonString,string Idnotifica){
        SyncBillingContractUtils.Wrapper wrp =  (SyncBillingContractUtils.Wrapper)Json.deserialize(jsonString, SyncBillingContractUtils.Wrapper.class);
        SyncBillingContractUtils.callWSContract(wrp,Idnotifica);
    }
    @future(callout=true)
    public static void CallAccount (String JsonString,string Idnotifica){

        SyncBillingAccountUtils.Wrapper wrp =  (SyncBillingAccountUtils.Wrapper)Json.deserialize(jsonString, SyncBillingAccountUtils.Wrapper.class);
        SyncBillingAccountUtils.callWSAccount(wrp,Idnotifica);
        
    }
}