objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OLO</fullName>
        <active>true</active>
        <description>Use this account to store OLO information.</description>
        <label>OLO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Account_OLO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLO</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>OLO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Operatore_WS__c</fullName>
        <label>Codice Operatore</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VF</fullName>
                </value>
                <value>
                    <fullName>WN</fullName>
                </value>
                <value>
                    <fullName>TIS</fullName>
                </value>
                <value>
                    <fullName>GOI</fullName>
                </value>
                <value>
                    <fullName>CNN</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>FAS</fullName>
                </value>
                <value>
                    <fullName>PLA</fullName>
                </value>
                <value>
                    <fullName>CWN</fullName>
                </value>
                <value>
                    <fullName>4IS</fullName>
                </value>
                <value>
                    <fullName>XMA</fullName>
                </value>
                <value>
                    <fullName>WAR</fullName>
                </value>
                <value>
                    <fullName>UND</fullName>
                </value>
                <value>
                    <fullName>SPE</fullName>
                </value>
                <value>
                    <fullName>UMB</fullName>
                </value>
                <value>
                    <fullName>NEX</fullName>
                </value>
                <value>
                    <fullName>NOI</fullName>
                </value>
                <value>
                    <fullName>RAF</fullName>
                </value>
                <value>
                    <fullName>PAN</fullName>
                </value>
                <value>
                    <fullName>SHS</fullName>
                </value>
                <value>
                    <fullName>ALT</fullName>
                </value>
                <value>
                    <fullName>SIR</fullName>
                </value>
                <value>
                    <fullName>HAL</fullName>
                </value>
                <value>
                    <fullName>BRI</fullName>
                </value>
                <value>
                    <fullName>LAW</fullName>
                </value>
                <value>
                    <fullName>ACA</fullName>
                </value>
                <value>
                    <fullName>FST</fullName>
                </value>
                <value>
                    <fullName>INT</fullName>
                </value>
                <value>
                    <fullName>UNC</fullName>
                </value>
                <value>
                    <fullName>SAI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <externalId>true</externalId>
        <label>Codice Ordine OLO</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EOF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referente Tecnico OLO</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.EOF_Account_OLO__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Notifica__c</fullName>
        <label>Data Notifica</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Prevista_Attivazione__c</fullName>
        <label>Data Prevista Attivazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EOF_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da lavorare</fullName>
                </value>
                <value>
                    <fullName>Appuntamento Fissato</fullName>
                </value>
                <value>
                    <fullName>Da contattare</fullName>
                </value>
                <value>
                    <fullName>Desospeso</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione</fullName>
                </value>
                <value>
                    <fullName>In Verifica BO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Sospeso BO</fullName>
                </value>
                <value>
                    <fullName>Sospeso Tecn.</fullName>
                </value>
                <value>
                    <fullName>In assegnazione</fullName>
                </value>
                <value>
                    <fullName>Espletato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato KO</fullName>
                </value>
                <value>
                    <fullName>Espletato KO</fullName>
                </value>
                <value>
                    <fullName>Accettato KO</fullName>
                </value>
                <value>
                    <fullName>In Verifica Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Network Creation</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Delivery</fullName>
                </value>
                <value>
                    <fullName>Completato</fullName>
                </value>
                <value>
                    <fullName>Offerta Creata</fullName>
                </value>
                <value>
                    <fullName>Offerta Presentata</fullName>
                </value>
                <value>
                    <fullName>Richiesta modifica offerta da Cliente</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Referente Fattibilità</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Tecnico Fattibilità</fullName>
                </value>
                <value>
                    <fullName>Sospeso OM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_ID_Building_WS__c</fullName>
        <externalId>true</externalId>
        <label>ID Building</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IDContratto__c</fullName>
        <label>ID Contratto</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>EOF_Caso_Attivazione_OPENSTREAM_CeD</fullName>
        <active>true</active>
        <businessProcess>EOF Support Process</businessProcess>
        <description>RecordType per le request di attivazione dei servizi Attivi afferenti ai cluster C e D</description>
        <label>EOF Caso Attivazione OPENSTREAM CeD</label>
    </recordTypes>
    <recordTypes>
        <fullName>OF_SA_Attivazione</fullName>
        <active>true</active>
        <businessProcess>EOF Support Process</businessProcess>
        <label>EOF_Caso_Attivazione_OPENSTREAM</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CONFIGURAZIONE_PROXY_PORTALE__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Comune__c</fullName>
        <label>Comune</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POP__c</fullName>
        <label>POP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tipo_Lavorazione__c</fullName>
        <label>Tipo_Lavorazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CONFIGURAZIONE PROXY PORTALE</label>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>OF_IdContratto__c</fullName>
        <label>Id Contratto</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <label>Codice Ordine OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Notifica__c</fullName>
        <label>Data Notifica</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>POP__c</fullName>
        <label>POP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <recordTypes>
        <fullName>FiberRequest</fullName>
        <active>true</active>
        <label>FiberRequest</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_AreaGeograficaCustom__c.object
<CustomObject>
    <fields>
        <fullName>OF_Comune__c</fullName>
        <label>Comune</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Istat__c</fullName>
        <label>ISTAT</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Regione__c</fullName>
        <label>Regione</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Area geografica</label>
    <nameField>
        <displayFormat>ISTAT-{000000}</displayFormat>
        <label>ISTAT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Area geografica</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_ElencoComuniItaliani__c.object
<CustomObject>
    <fields>
        <fullName>OF_CodiceIstat__c</fullName>
        <externalId>true</externalId>
        <label>Codice Istat</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OF_Comune__c</fullName>
        <label>Comune</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Regione__c</fullName>
        <label>Regione</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Ripartizionegeografica__c</fullName>
        <label>Ripartizione geografica</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Ripartizione_geografica_NC__c</fullName>
        <label>Ripartizione geografica NC</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Titolarit_NC__c</fullName>
        <label>Titolarità NC</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>ElencoComuniItaliani</label>
    <nameField>
        <displayFormat>ISTAT-{000000}</displayFormat>
        <label>ISTAT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ElenchiComuniItaliani</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/POP__c.object
<CustomObject>
    <fields>
        <fullName>Comune__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>POP</label>
    <nameField>
        <label>POP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Semaforo_Proxy_Portale__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Semaforo_Proxy_Portale_Attivazione__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Semaforo Proxy Portale Attivazione</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Semaforo_Proxy_Portale_Cessazione__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Semaforo Proxy Portale Cessazione</label>
        <type>Checkbox</type>
    </fields>
    <label>Semaforo Proxy Portale</label>
</CustomObject>

classes/PO_COMP_AttivazInserita_Contrl_TEST.cls
@isTest
public class PO_COMP_AttivazInserita_Contrl_TEST {
    
    public static testmethod void test1(){
          OF_ElencoComuniItaliani__c eci = new OF_ElencoComuniItaliani__c();
         eci.OF_CodiceIstat__c = '015146';
		 eci.OF_Comune__c = 'Milano';
		 eci.OF_Provincia__c = 'Milano';
		 eci.OF_Regione__c ='Lombardia';
         eci.OF_Ripartizionegeografica__c ='Nord-ovest';
        // eci.PO_Ripartizione_geografica_NC__c ='';
         //eci.PO_Titolarit_NC__c ='';
         insert eci; 
        
         OF_AreaGeograficaCustom__c ac = new OF_AreaGeograficaCustom__c();
         ac.OF_Comune__c = 'Milano';
         ac.OF_Istat__c='015146';
         insert ac;
        
         Semaforo_Proxy_Portale__c spp = new Semaforo_Proxy_Portale__c();
 		 spp.Name='Semaforo Proxy Portale Attivazione';
         spp.Semaforo_Proxy_Portale_Attivazione__c=false;
         spp.Semaforo_Proxy_Portale_Cessazione__c=false;
         insert spp;
        
        
        CONFIGURAZIONE_PROXY_PORTALE__c cpp = new CONFIGURAZIONE_PROXY_PORTALE__c();
        cpp.Name='MI_CESSAZIONE';
        cpp.POP__c='MI/FCO/2';
        cpp.Tipo_Lavorazione__c='Cessazione';
        cpp.Data__c=system.today().addDays(-14);
        cpp.Comune__c='';
        insert cpp;
        
        Semaforo_Proxy_Portale__c spp1 = new Semaforo_Proxy_Portale__c();
        spp1.Name='Semaforo Proxy Portale Cessazione';
        spp1.Semaforo_Proxy_Portale_Attivazione__c=false;
        spp1.Semaforo_Proxy_Portale_Cessazione__c=false;
        insert spp1;
        
        //String busAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Business').getRecordTypeId();
        id accOloRTid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
        
        //OF_SA_GE_UtilsNew.caseOriginale = TestDataFactory.c1;
      //  TestDataFactory.CreateTestRecords('EOF_Caso_Attivazione_OPENSTREAM', null, null);
        
        // business account creation        
        String busAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Business').getRecordTypeId();
        Account bus = new Account();
        bus.name = 'Test';
        bus.RecordTypeId = busAccountRecordTypeId;
        insert bus;
        // end business account creation
         Account accOLO = new Account();
        accOLO.Name = 'Tiscali';
        accOLO.EOF_Codice_Operatore__c = 'TIS';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = accOloRTid;
        insert accOLO;
        
        // creazione contratto
        Contract contratto = new Contract();
        contratto.OF_IdContratto__c = 'TEST_TIS_001';
        contratto.AccountId = accOLO.id;
        insert contratto;
        
       Case c1 = new case();
            c1.EOF_Account_OLO__c = accOLO.id;
            c1.EOF_Codice_Ordine_OLO__c = 'Test';
            c1.EOF_Codice_Operatore_WS__c ='TIS';
            c1.EOF_Contact__c = null;
            c1.status = 'Acquisito';
            c1.EOF_FASE__C = 'Da Lavorare';
            c1.EOF_ID_Building_WS__c ='ID_Building001';
            c1.RecordTypeId =[Select id from RecordType where DeveloperName ='OF_SA_Attivazione' LIMIT 1].get(0).id;// OF_SA_GE_Utils.rtMap.get('EOF_Caso_Attivazione_OPENSTREAM_CeD');
            c1.EOF_DATA_NOTIFICA__c=system.now();
            c1.EOF_Data_Prevista_Attivazione__c=system.today();
            c1.OF_SA_Tipo_Lavorazione__c='Attivazione';
            c1.OF_SA_Interfaccia_OM__c='Nuova IF';
            c1.OF_OM_Nuovo_Flusso__c= true;
            c1.EOF_Identificativo_del_POP__c='MI/FCO/2';
            insert c1;
            
            OF_Generatore_ID_Servizio__c g = new OF_Generatore_ID_Servizio__c();
            g.OF_Case_Id__c=c1.Id;
            insert g;
            String gid=g.id;
         gid= gid.abbreviate(10);
            c1.OF_SA_ID_Servizio__c=gid;
            update c1;
        OF_SA_GE_UtilsNew.caseOriginale = c1; //.EOF_ID_Building_WS__c='TEST_000001';
       // update  OF_SA_GE_UtilsNew.caseOriginale;
        //service log creation 
        
        EOF_EAI_Service_Log__c sl = new EOF_EAI_Service_Log__c();
        sl.RecordTypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('PO - SA - FiberRequest').getRecordTypeId(); 
        sl.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sl.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sl.EOF_ID_Notifica__c ='';
        sl.EOF_STATO_ORDINE__c ='Acquisito';
        sl.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c='qwer';
        
        insert sl;
        PO_COMP_AttivazioneInserita_Controller.slOrig = sl;
        // end service log creation
        
        // vlan service log creation
        EOF_EAI_Service_Log__c sv = new EOF_EAI_Service_Log__c();
        sv.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Vlan').getRecordTypeId();
        sv.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sv.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sv.OF_SA_VLan_Log__c=sl.id;       
        insert sv; 
        // end vlan service log creation
        
        // cpe service log creation
        EOF_EAI_Service_Log__c sc = new EOF_EAI_Service_Log__c();
        sc.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        sc.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sc.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sc.OF_SA_Cpe_Log__c=sl.id;
        sc.OF_SA_Azione_APPARATO__c='1';
        insert sc;
        // end cpe service log creation
        
        // servizi aggiuntivi service log creation
        EOF_EAI_Service_Log__c sa = new EOF_EAI_Service_Log__c();
        sa.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Servizi Aggiuntivi').getRecordTypeId();
        sa.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sa.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sa.OF_SA_Servizi_Aggiuntivi_Log__c=sl.id;
        sa.OF_SA_INFORMAZIONI_SERVIZIO__c='213';
        insert sa;
        // end servivi aggiuntivi service log creation
        
        Test.setCurrentPageReference(new PageReference('PO_OpenStreamService_InsertNewRequest')); 
        System.currentPageReference().getParameters().put('origId', sl.id);
        
        test.startTest();
        PO_COMP_AttivazioneInserita_Controller pai = new PO_COMP_AttivazioneInserita_Controller();
        pai.inserisciVLAN();
        pai.editsl();
        pai.deletesl();
        pai.inserisciApparato();
        pai.inserisciServAgg();
        //pai.deleteVLAN();
        pai.editVLAN();
        //pai.deleteApparato();
        pai.editApparato();
        //pai.deleteServAgg();
        pai.editServAgg();
        pai.confermaRequest();
        pai.sl = sa;
        pai.InoltraRequest();
        pai.annullaInoltro();
        pai.insNewReq();
        pai.goToRicIns();
        test.stopTest();
        
    }
    
    public static testmethod void test2(){
           OF_ElencoComuniItaliani__c eci = new OF_ElencoComuniItaliani__c();
         eci.OF_CodiceIstat__c = '015146';
		 eci.OF_Comune__c = 'Milano';
		 eci.OF_Provincia__c = 'Milano';
		 eci.OF_Regione__c ='Lombardia';
         eci.OF_Ripartizionegeografica__c ='Nord-ovest';
        // eci.PO_Ripartizione_geografica_NC__c ='';
         //eci.PO_Titolarit_NC__c ='';
         insert eci; 
        
         OF_AreaGeograficaCustom__c ac = new OF_AreaGeograficaCustom__c();
         ac.OF_Comune__c = 'Milano';
         ac.OF_Istat__c='015146';
         insert ac;
        
         Semaforo_Proxy_Portale__c spp = new Semaforo_Proxy_Portale__c();
 		 spp.Name='Semaforo Proxy Portale Attivazione';
         spp.Semaforo_Proxy_Portale_Attivazione__c=false;
         spp.Semaforo_Proxy_Portale_Cessazione__c=false;
         insert spp;
        
        
        CONFIGURAZIONE_PROXY_PORTALE__c cpp = new CONFIGURAZIONE_PROXY_PORTALE__c();
        cpp.Name='MI_CESSAZIONE';
        cpp.POP__c='MI/FCO/2';
        cpp.Tipo_Lavorazione__c='Cessazione';
        cpp.Data__c=system.today().addDays(-14);
        cpp.Comune__c='';
        insert cpp;
        
        Semaforo_Proxy_Portale__c spp1 = new Semaforo_Proxy_Portale__c();
        spp1.Name='Semaforo Proxy Portale Cessazione';
        spp1.Semaforo_Proxy_Portale_Attivazione__c=false;
        spp1.Semaforo_Proxy_Portale_Cessazione__c=false;
        insert spp1;
        
   id accOloRTid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId(); 
        
        Account accOLO2 = new Account();
        accOLO2.Name = 'Vodafone';
        accOLO2.EOF_Codice_Operatore__c = 'VF';
        accOLO2.Type = 'OLO';
        accOLO2.Industry = 'Telecommunications';
        accOLO2.RecordTYpeId = accOloRTid;
        insert accOLO2;
        
        Account accOLO = new Account();
        accOLO.Name = 'Tiscali';
        accOLO.EOF_Codice_Operatore__c = 'TIS';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = accOloRTid;
        insert accOLO;
        
        // creazione contratto
        Contract contratto = new Contract();
        contratto.OF_IdContratto__c = 'TEST_TIS_001';
        contratto.AccountId = accOLO.id;
        insert contratto;
        
       Case c1 = new case();
            c1.EOF_Account_OLO__c = accOLO.id;
            c1.EOF_Codice_Ordine_OLO__c = 'Test';
            c1.EOF_Codice_Operatore_WS__c ='TIS';
            c1.EOF_Contact__c = null;
            c1.status = 'Acquisito';
            c1.EOF_FASE__C = 'Da Lavorare';
            c1.EOF_ID_Building_WS__c ='ID_Building001';
            c1.RecordTypeId =[Select id from RecordType where DeveloperName ='OF_SA_Attivazione' LIMIT 1].get(0).id;// OF_SA_GE_Utils.rtMap.get('EOF_Caso_Attivazione_OPENSTREAM_CeD');
            c1.EOF_DATA_NOTIFICA__c=system.now();
            c1.EOF_Data_Prevista_Attivazione__c=system.today();
            c1.OF_SA_Tipo_Lavorazione__c='Attivazione';
            c1.OF_SA_Interfaccia_OM__c='Nuova IF';
            c1.OF_OM_Nuovo_Flusso__c= true;
            c1.EOF_Identificativo_del_POP__c='MI/FCO/2';
            insert c1;
            
            OF_Generatore_ID_Servizio__c g = new OF_Generatore_ID_Servizio__c();
            g.OF_Case_Id__c=c1.Id;
            insert g;
             String gid=g.id;
         gid= gid.abbreviate(10);
            c1.OF_SA_ID_Servizio__c=gid;
            update c1;
        
        // business account creation        
        String busAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Business').getRecordTypeId();
        Account bus = new Account();
        bus.name = 'Test';
        bus.RecordTypeId = busAccountRecordTypeId;
        insert bus;
        // end business account creation
        
        //service log creation 
        
        EOF_EAI_Service_Log__c sl = new EOF_EAI_Service_Log__c();
        sl.RecordTypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('PO - SA - FiberRequest').getRecordTypeId(); 
        sl.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sl.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sl.EOF_ID_Notifica__c ='';
        sl.EOF_STATO_ORDINE__c ='Acquisito';
        sl.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c='';
        
        insert sl;
        PO_COMP_AttivazioneInserita_Controller.slOrig = sl;
        // end service log creation
        
        // vlan service log creation
        EOF_EAI_Service_Log__c sv = new EOF_EAI_Service_Log__c();
        sv.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Vlan').getRecordTypeId();
        sv.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sv.EOF_Data_Notifica__c=c1.EOF_Data_Notifica__c;
        sv.OF_SA_VLan_Log__c=sl.id;       
        insert sv; 
        // end vlan service log creation
        
        // cpe service log creation
        EOF_EAI_Service_Log__c sc = new EOF_EAI_Service_Log__c();
        sc.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        sc.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sc.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sc.OF_SA_Cpe_Log__c=sl.id;
        sc.OF_SA_Azione_APPARATO__c='1';
        insert sc;
        // end cpe service log creation
        
        // servizi aggiuntivi service log creation
        EOF_EAI_Service_Log__c sa = new EOF_EAI_Service_Log__c();
        sa.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Servizi Aggiuntivi').getRecordTypeId();
        sa.EOF_Codice_Ordine_OLO__c =c1.EOF_Codice_Ordine_OLO__c;
        sa.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sa.OF_SA_Servizi_Aggiuntivi_Log__c=sl.id;
        sa.OF_SA_INFORMAZIONI_SERVIZIO__c='213';
        insert sa;
        // end servivi aggiuntivi service log creation
        OF_SA_GE_UtilsNew.caseOriginale=c1;
        
        Test.setCurrentPageReference(new PageReference('PO_OpenStreamService_InsertNewRequest')); 
        System.currentPageReference().getParameters().put('proc', 'confirmPageATT');
        
        test.startTest();
        PO_COMP_AttivazioneInserita_Controller pai = new PO_COMP_AttivazioneInserita_Controller();
        
        pai.inserisciVLAN();
        pai.editsl();
        pai.deletesl();
        pai.inserisciApparato();
        pai.inserisciServAgg();
        //pai.deleteVLAN();
        pai.editVLAN();
        //pai.deleteApparato();
        pai.editApparato();
        //pai.deleteServAgg();
        pai.editServAgg();
        pai.confermaRequest();
        pai.InoltraRequest();
        pai.annullaInoltro();
        pai.insNewReq();
        pai.goToRicIns();
        test.stopTest();
        
    }
    
    public static testmethod void test3(){
        
           OF_ElencoComuniItaliani__c eci = new OF_ElencoComuniItaliani__c();
         eci.OF_CodiceIstat__c = '015146';
		 eci.OF_Comune__c = 'Milano';
		 eci.OF_Provincia__c = 'Milano';
		 eci.OF_Regione__c ='Lombardia';
         eci.OF_Ripartizionegeografica__c ='Nord-ovest';
        // eci.PO_Ripartizione_geografica_NC__c ='';
         //eci.PO_Titolarit_NC__c ='';
         insert eci; 
        
         OF_AreaGeograficaCustom__c ac = new OF_AreaGeograficaCustom__c();
         ac.OF_Comune__c = 'Milano';
         ac.OF_Istat__c='015146';
         insert ac;
        
         Semaforo_Proxy_Portale__c spp = new Semaforo_Proxy_Portale__c();
 		 spp.Name='Semaforo Proxy Portale Attivazione';
         spp.Semaforo_Proxy_Portale_Attivazione__c=false;
         spp.Semaforo_Proxy_Portale_Cessazione__c=false;
         insert spp;
        
        
        CONFIGURAZIONE_PROXY_PORTALE__c cpp = new CONFIGURAZIONE_PROXY_PORTALE__c();
        cpp.Name='MI_CESSAZIONE';
        cpp.POP__c='MI/FCO/2';
        cpp.Tipo_Lavorazione__c='Cessazione';
        cpp.Data__c=system.today().addDays(-14);
        cpp.Comune__c='';
        insert cpp;
        
        Semaforo_Proxy_Portale__c spp1 = new Semaforo_Proxy_Portale__c();
        spp1.Name='Semaforo Proxy Portale Cessazione';
        spp1.Semaforo_Proxy_Portale_Attivazione__c=false;
        spp1.Semaforo_Proxy_Portale_Cessazione__c=false;
        insert spp1;
        
           id accOloRTid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId(); 
        
        Account accOLO2 = new Account();
        accOLO2.Name = 'Vodafone';
        accOLO2.EOF_Codice_Operatore__c = 'VF';
        accOLO2.Type = 'OLO';
        accOLO2.Industry = 'Telecommunications';
        accOLO2.RecordTYpeId = accOloRTid;
        insert accOLO2;
        
        Account accOLO = new Account();
        accOLO.Name = 'Tiscali';
        accOLO.EOF_Codice_Operatore__c = 'TIS';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = accOloRTid;
        insert accOLO;
        
        // creazione contratto
        Contract contratto = new Contract();
        contratto.OF_IdContratto__c = 'TEST_TIS_001';
        contratto.AccountId = accOLO.id;
        insert contratto;
        
       Case c1 = new case();
            c1.EOF_Account_OLO__c = accOLO.id;
            c1.EOF_Codice_Ordine_OLO__c = 'Test';
            c1.EOF_Codice_Operatore_WS__c ='TIS';
            c1.EOF_Contact__c = null;
            c1.status = 'Acquisito';
            c1.EOF_FASE__C = 'Da Lavorare';
            c1.EOF_ID_Building_WS__c ='ID_Building001';
            c1.RecordTypeId =[Select id from RecordType where DeveloperName ='OF_SA_Attivazione' LIMIT 1].get(0).id;// OF_SA_GE_Utils.rtMap.get('EOF_Caso_Attivazione_OPENSTREAM_CeD');
            c1.EOF_DATA_NOTIFICA__c=system.now();
            c1.EOF_Data_Prevista_Attivazione__c=system.today();
            c1.OF_SA_Tipo_Lavorazione__c='Attivazione';
            c1.OF_SA_Interfaccia_OM__c='Nuova IF';
            c1.OF_OM_Nuovo_Flusso__c= true;
            c1.EOF_Identificativo_del_POP__c='MI/FCO/2';
            insert c1;
            
            OF_Generatore_ID_Servizio__c g = new OF_Generatore_ID_Servizio__c();
            g.OF_Case_Id__c=c1.Id;
            insert g;
             String gid=g.id;
         gid= gid.abbreviate(10);
            c1.OF_SA_ID_Servizio__c=gid;
            update c1;
        
        // business account creation        
        String busAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Business').getRecordTypeId();
        Account bus = new Account();
        bus.name = 'Test';
        bus.RecordTypeId = busAccountRecordTypeId;
        insert bus;
        // end business account creation
        
        
        //service log creation 
        
        EOF_EAI_Service_Log__c sl = new EOF_EAI_Service_Log__c();
        sl.RecordTypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('PO - SA - FiberRequest').getRecordTypeId(); 
        sl.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sl.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sl.EOF_ID_Notifica__c ='';
        sl.EOF_STATO_ORDINE__c ='Acquisito';
        sl.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c='qwer';
        
        insert sl;
        PO_COMP_AttivazioneInserita_Controller.slOrig = sl;
        // end service log creation
        
        // vlan service log creation
        EOF_EAI_Service_Log__c sv = new EOF_EAI_Service_Log__c();
        sv.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Vlan').getRecordTypeId();
        sv.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sv.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sv.OF_SA_VLan_Log__c=sl.id;       
        insert sv; 
        // end vlan service log creation
        
        // cpe service log creation
        EOF_EAI_Service_Log__c sc = new EOF_EAI_Service_Log__c();
        sc.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        sc.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sc.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sc.OF_SA_Cpe_Log__c=sl.id;
        sc.OF_SA_Azione_APPARATO__c='1';
        insert sc;
        // end cpe service log creation
        
        // servizi aggiuntivi service log creation
        EOF_EAI_Service_Log__c sa = new EOF_EAI_Service_Log__c();
        sa.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Servizi Aggiuntivi').getRecordTypeId();
        sa.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sa.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sa.OF_SA_Servizi_Aggiuntivi_Log__c=sl.id;
        sa.OF_SA_INFORMAZIONI_SERVIZIO__c='213';
        insert sa;
        // end servivi aggiuntivi service log creation
        OF_SA_GE_UtilsNew.caseOriginale=c1;
        Test.setCurrentPageReference(new PageReference('PO_OpenStreamService_InsertNewRequest')); 
        System.currentPageReference().getParameters().put('proc', 'successInsertATT');
        
        test.startTest();
        PO_COMP_AttivazioneInserita_Controller pai = new PO_COMP_AttivazioneInserita_Controller();
        
        pai.inserisciVLAN();
        pai.editsl();
        pai.deletesl();
        pai.inserisciApparato();
        pai.inserisciServAgg();
        //pai.deleteVLAN();
        pai.editVLAN();
        //pai.deleteApparato();
        pai.editApparato();
        //pai.deleteServAgg();
        pai.editServAgg();
        pai.confermaRequest();
        pai.InoltraRequest();
        pai.annullaInoltro();
        pai.insNewReq();
        pai.goToRicIns();
        test.stopTest();
        
    }
    
    public static testmethod void test4(){
        
           OF_ElencoComuniItaliani__c eci = new OF_ElencoComuniItaliani__c();
         eci.OF_CodiceIstat__c = '015146';
		 eci.OF_Comune__c = 'Milano';
		 eci.OF_Provincia__c = 'Milano';
		 eci.OF_Regione__c ='Lombardia';
         eci.OF_Ripartizionegeografica__c ='Nord-ovest';
        // eci.PO_Ripartizione_geografica_NC__c ='';
         //eci.PO_Titolarit_NC__c ='';
         insert eci; 
        
         OF_AreaGeograficaCustom__c ac = new OF_AreaGeograficaCustom__c();
         ac.OF_Comune__c = 'Milano';
         ac.OF_Istat__c='015146';
         insert ac;
        
         Semaforo_Proxy_Portale__c spp = new Semaforo_Proxy_Portale__c();
 		 spp.Name='Semaforo Proxy Portale Attivazione';
         spp.Semaforo_Proxy_Portale_Attivazione__c=false;
         spp.Semaforo_Proxy_Portale_Cessazione__c=false;
         insert spp;
        
        
        CONFIGURAZIONE_PROXY_PORTALE__c cpp = new CONFIGURAZIONE_PROXY_PORTALE__c();
        cpp.Name='MI_CESSAZIONE';
        cpp.POP__c='MI/FCO/2';
        cpp.Tipo_Lavorazione__c='Cessazione';
        cpp.Data__c=system.today().addDays(-14);
        cpp.Comune__c='';
        insert cpp;
        
        Semaforo_Proxy_Portale__c spp1 = new Semaforo_Proxy_Portale__c();
        spp1.Name='Semaforo Proxy Portale Cessazione';
        spp1.Semaforo_Proxy_Portale_Attivazione__c=false;
        spp1.Semaforo_Proxy_Portale_Cessazione__c=false;
        insert spp1;
        

          id accOloRTid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId(); 
        
        Account accOLO2 = new Account();
        accOLO2.Name = 'Vodafone';
        accOLO2.EOF_Codice_Operatore__c = 'VF';
        accOLO2.Type = 'OLO';
        accOLO2.Industry = 'Telecommunications';
        accOLO2.RecordTYpeId = accOloRTid;
        insert accOLO2;
        
        Account accOLO = new Account();
        accOLO.Name = 'Tiscali';
        accOLO.EOF_Codice_Operatore__c = 'TIS';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = accOloRTid;
        insert accOLO;
        
        // creazione contratto
        Contract contratto = new Contract();
        contratto.OF_IdContratto__c = 'TEST_TIS_001';
        contratto.AccountId = accOLO.id;
        insert contratto;
        
       Case c1 = new case();
            c1.EOF_Account_OLO__c = accOLO.id;
            c1.EOF_Codice_Ordine_OLO__c = 'Test';
            c1.EOF_Codice_Operatore_WS__c ='TIS';
            c1.EOF_Contact__c = null;
            c1.status = 'Acquisito';
            c1.EOF_FASE__C = 'Da Lavorare';
            c1.EOF_ID_Building_WS__c ='ID_Building001';
            c1.RecordTypeId =[Select id from RecordType where DeveloperName ='OF_SA_Attivazione' LIMIT 1].get(0).id;// OF_SA_GE_Utils.rtMap.get('EOF_Caso_Attivazione_OPENSTREAM_CeD');
            c1.EOF_DATA_NOTIFICA__c=system.now();
            c1.EOF_Data_Prevista_Attivazione__c=system.today();
            c1.OF_SA_Tipo_Lavorazione__c='Attivazione';
            c1.OF_SA_Interfaccia_OM__c='Nuova IF';
            c1.OF_OM_Nuovo_Flusso__c= true;
            c1.EOF_Identificativo_del_POP__c='MI/FCO/2';
            insert c1;
            
            OF_Generatore_ID_Servizio__c g = new OF_Generatore_ID_Servizio__c();
            g.OF_Case_Id__c=c1.Id;
            insert g;
             String gid=g.id;
         gid= gid.abbreviate(10);
            c1.OF_SA_ID_Servizio__c=gid;
            update c1;
        
        // business account creation        
        String busAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Business').getRecordTypeId();
        Account bus = new Account();
        bus.name = 'Test';
        bus.RecordTypeId = busAccountRecordTypeId;
        insert bus;
        // end business account creation
        
        //service log creation 
        
        EOF_EAI_Service_Log__c sl = new EOF_EAI_Service_Log__c();
        sl.RecordTypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('PO - SA - FiberRequest').getRecordTypeId(); 
        sl.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sl.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sl.EOF_ID_Notifica__c ='';
        sl.EOF_STATO_ORDINE__c ='Acquisito';
        sl.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c='qwer';
        
        insert sl;
        PO_COMP_AttivazioneInserita_Controller.slOrig = sl;
        // end service log creation
        
        // vlan service log creation
        EOF_EAI_Service_Log__c sv = new EOF_EAI_Service_Log__c();
        sv.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Vlan').getRecordTypeId();
        sv.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sv.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sv.OF_SA_VLan_Log__c=sl.id;       
        insert sv; 
        // end vlan service log creation
        
        // cpe service log creation
        EOF_EAI_Service_Log__c sc = new EOF_EAI_Service_Log__c();
        sc.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        sc.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sc.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sc.OF_SA_Cpe_Log__c=sl.id;
        sc.OF_SA_Azione_APPARATO__c='1';
        insert sc;
        // end cpe service log creation
        
        // servizi aggiuntivi service log creation
        EOF_EAI_Service_Log__c sa = new EOF_EAI_Service_Log__c();
        sa.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Servizi Aggiuntivi').getRecordTypeId();
        sa.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sa.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sa.OF_SA_Servizi_Aggiuntivi_Log__c=sl.id;
        sa.OF_SA_INFORMAZIONI_SERVIZIO__c='213';
        insert sa;
        // end servivi aggiuntivi service log creation
        OF_SA_GE_UtilsNew.caseOriginale=c1;
        Test.setCurrentPageReference(new PageReference('PO_OpenStreamService_InsertNewRequest')); 
        System.currentPageReference().getParameters().put('proc', 'errorInsertATT');
        
        test.startTest();
        PO_COMP_AttivazioneInserita_Controller pai = new PO_COMP_AttivazioneInserita_Controller();
        
        pai.inserisciVLAN();
        pai.editsl();
        pai.deletesl();
        pai.inserisciApparato();
        pai.inserisciServAgg();
        //pai.deleteVLAN();
        pai.editVLAN();
        //pai.deleteApparato();
        pai.editApparato();
        //pai.deleteServAgg();
        pai.editServAgg();
        pai.confermaRequest();
        pai.InoltraRequest();
        pai.annullaInoltro();
        pai.insNewReq();
        pai.goToRicIns();
        test.stopTest();
        
    }
    
    public static testmethod void test5(){
        
           OF_ElencoComuniItaliani__c eci = new OF_ElencoComuniItaliani__c();
         eci.OF_CodiceIstat__c = '015146';
		 eci.OF_Comune__c = 'Milano';
		 eci.OF_Provincia__c = 'Milano';
		 eci.OF_Regione__c ='Lombardia';
         eci.OF_Ripartizionegeografica__c ='Nord-ovest';
        // eci.PO_Ripartizione_geografica_NC__c ='';
         //eci.PO_Titolarit_NC__c ='';
         insert eci; 
        
         OF_AreaGeograficaCustom__c ac = new OF_AreaGeograficaCustom__c();
         ac.OF_Comune__c = 'Milano';
         ac.OF_Istat__c='015146';
         insert ac;
        
         Semaforo_Proxy_Portale__c spp = new Semaforo_Proxy_Portale__c();
 		 spp.Name='Semaforo Proxy Portale Attivazione';
         spp.Semaforo_Proxy_Portale_Attivazione__c=false;
         spp.Semaforo_Proxy_Portale_Cessazione__c=false;
         insert spp;
        
        
        CONFIGURAZIONE_PROXY_PORTALE__c cpp = new CONFIGURAZIONE_PROXY_PORTALE__c();
        cpp.Name='MI_CESSAZIONE';
        cpp.POP__c='MI/FCO/2';
        cpp.Tipo_Lavorazione__c='Cessazione';
        cpp.Data__c=system.today().addDays(-14);
        cpp.Comune__c='';
        insert cpp;
        
        Semaforo_Proxy_Portale__c spp1 = new Semaforo_Proxy_Portale__c();
        spp1.Name='Semaforo Proxy Portale Cessazione';
        spp1.Semaforo_Proxy_Portale_Attivazione__c=false;
        spp1.Semaforo_Proxy_Portale_Cessazione__c=false;
        insert spp1;
        
   id accOloRTid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId(); 
        
        Account accOLO2 = new Account();
        accOLO2.Name = 'Vodafone';
        accOLO2.EOF_Codice_Operatore__c = 'VF';
        accOLO2.Type = 'OLO';
        accOLO2.Industry = 'Telecommunications';
        accOLO2.RecordTYpeId = accOloRTid;
        insert accOLO2;
        
        Account accOLO = new Account();
        accOLO.Name = 'Tiscali';
        accOLO.EOF_Codice_Operatore__c = 'TIS';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = accOloRTid;
        insert accOLO;
        
        // creazione contratto
        Contract contratto = new Contract();
        contratto.OF_IdContratto__c = 'TEST_TIS_001';
        contratto.AccountId = accOLO.id;
        insert contratto;
        
       Case c1 = new case();
            c1.EOF_Account_OLO__c = accOLO.id;
            c1.EOF_Codice_Ordine_OLO__c = 'Test';
            c1.EOF_Codice_Operatore_WS__c ='TIS';
            c1.EOF_Contact__c = null;
            c1.status = 'Acquisito';
            c1.EOF_FASE__C = 'Da Lavorare';
            c1.EOF_ID_Building_WS__c ='ID_Building001';
            c1.RecordTypeId =[Select id from RecordType where DeveloperName ='OF_SA_Attivazione' LIMIT 1].get(0).id;// OF_SA_GE_Utils.rtMap.get('EOF_Caso_Attivazione_OPENSTREAM_CeD');
            c1.EOF_DATA_NOTIFICA__c=system.now();
            c1.EOF_Data_Prevista_Attivazione__c=system.today();
            c1.OF_SA_Tipo_Lavorazione__c='Attivazione';
            c1.OF_SA_Interfaccia_OM__c='Nuova IF';
            c1.OF_OM_Nuovo_Flusso__c= true;
            c1.EOF_Identificativo_del_POP__c='MI/FCO/2';
            insert c1;
            
            OF_Generatore_ID_Servizio__c g = new OF_Generatore_ID_Servizio__c();
            g.OF_Case_Id__c=c1.Id;
            insert g;
             String gid=g.id;
         gid= gid.abbreviate(10);
            c1.OF_SA_ID_Servizio__c=gid;
            update c1;
        
       // TestDataFactory.CreateTestRecords('EOF_Caso_Attivazione_OPENSTREAM', null, null);
        
        // business account creation        
        String busAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Business').getRecordTypeId();
        Account bus = new Account();
        bus.name = 'Test';
        bus.RecordTypeId = busAccountRecordTypeId;
        insert bus;
        // end business account creation
        
        //service log creation 
        
        EOF_EAI_Service_Log__c sl = new EOF_EAI_Service_Log__c();
        sl.RecordTypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('PO - SA - FiberRequest').getRecordTypeId(); 
        sl.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sl.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sl.EOF_ID_Notifica__c ='';
        sl.EOF_STATO_ORDINE__c ='Acquisito';
        sl.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c='qwer';
        insert sl;
        PO_COMP_AttivazioneInserita_Controller.slOrig = sl;
        // end service log creation
        
        // vlan service log creation
        EOF_EAI_Service_Log__c sv = new EOF_EAI_Service_Log__c();
        sv.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Vlan').getRecordTypeId();
        sv.EOF_Codice_Ordine_OLO__c =c1.EOF_Codice_Ordine_OLO__c;
        sv.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sv.OF_SA_VLan_Log__c=sl.id;       
        insert sv; 
        // end vlan service log creation
        
        // cpe service log creation
        EOF_EAI_Service_Log__c sc = new EOF_EAI_Service_Log__c();
        sc.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        sc.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sc.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sc.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c='qwer';
        sc.OF_SA_Azione_APPARATO__c='1';
        sc.OF_SA_Cpe_Log__c=sl.id;
        insert sc;
        // end cpe service log creation
        
        // servizi aggiuntivi service log creation
        EOF_EAI_Service_Log__c sa = new EOF_EAI_Service_Log__c();
        sa.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Servizi Aggiuntivi').getRecordTypeId();
        sa.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sa.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sa.OF_SA_Servizi_Aggiuntivi_Log__c=sl.id;
        sa.OF_SA_INFORMAZIONI_SERVIZIO__c='213';
        insert sa;
        // end servivi aggiuntivi service log creation
        OF_SA_GE_UtilsNew.caseOriginale=c1;
        Test.setCurrentPageReference(new PageReference('PO_OpenStreamService_InsertNewRequest')); 
        System.currentPageReference().getParameters().put('origId', sl.id);
        
        test.startTest();
        PO_COMP_AttivazioneInserita_Controller pai = new PO_COMP_AttivazioneInserita_Controller();
        pai.inserisciVLAN();
        pai.editsl();
        pai.deletesl();
        pai.inserisciApparato();
        pai.inserisciServAgg();
        //pai.deleteVLAN();
        pai.editVLAN();
        //pai.deleteApparato();
        pai.editApparato();
        //pai.deleteServAgg();
        pai.editServAgg();
        pai.confermaRequest();
        pai.InoltraRequest();
        pai.annullaInoltro();
        pai.insNewReq();
        pai.goToRicIns();
        test.stopTest();
        
    }
    
    public static testmethod void test6(){
         OF_ElencoComuniItaliani__c eci = new OF_ElencoComuniItaliani__c();
         eci.OF_CodiceIstat__c = '015146';
		 eci.OF_Comune__c = 'Milano';
		 eci.OF_Provincia__c = 'Milano';
		 eci.OF_Regione__c ='Lombardia';
         eci.OF_Ripartizionegeografica__c ='Nord-ovest';
        // eci.PO_Ripartizione_geografica_NC__c ='';
         //eci.PO_Titolarit_NC__c ='';
         insert eci; 
        
         OF_AreaGeograficaCustom__c ac = new OF_AreaGeograficaCustom__c();
         ac.OF_Comune__c = 'Milano';
         ac.OF_Istat__c='015146';
         insert ac;
        
         Semaforo_Proxy_Portale__c spp = new Semaforo_Proxy_Portale__c();
 		 spp.Name='Semaforo Proxy Portale Attivazione';
         spp.Semaforo_Proxy_Portale_Attivazione__c=false;
         spp.Semaforo_Proxy_Portale_Cessazione__c=false;
         insert spp;
        
        
        CONFIGURAZIONE_PROXY_PORTALE__c cpp = new CONFIGURAZIONE_PROXY_PORTALE__c();
        cpp.Name='MI_CESSAZIONE';
        cpp.POP__c='MI/FCO/2';
        cpp.Tipo_Lavorazione__c='Cessazione';
        cpp.Data__c=system.today().addDays(-14);
        cpp.Comune__c='';
        insert cpp;
        
        Semaforo_Proxy_Portale__c spp1 = new Semaforo_Proxy_Portale__c();
        spp1.Name='Semaforo Proxy Portale Cessazione';
        spp1.Semaforo_Proxy_Portale_Attivazione__c=false;
        spp1.Semaforo_Proxy_Portale_Cessazione__c=false;
        insert spp1;
        
   id accOloRTid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId(); 
        
        Account accOLO2 = new Account();
        accOLO2.Name = 'Vodafone';
        accOLO2.EOF_Codice_Operatore__c = 'VF';
        accOLO2.Type = 'OLO';
        accOLO2.Industry = 'Telecommunications';
        accOLO2.RecordTYpeId = accOloRTid;
        insert accOLO2;
        
        Account accOLO = new Account();
        accOLO.Name = 'Tiscali';
        accOLO.EOF_Codice_Operatore__c = 'TIS';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = accOloRTid;
        insert accOLO;
        
        // creazione contratto
        Contract contratto = new Contract();
        contratto.OF_IdContratto__c = 'TEST_TIS_001';
        contratto.AccountId = accOLO.id;
        insert contratto;
        
       Case c1 = new case();
            c1.EOF_Account_OLO__c = accOLO.id;
            c1.EOF_Codice_Ordine_OLO__c = 'Test';
            c1.EOF_Codice_Operatore_WS__c ='TIS';
            c1.EOF_Contact__c = null;
            c1.status = 'Acquisito';
            c1.EOF_FASE__C = 'Da Lavorare';
            c1.EOF_ID_Building_WS__c ='ID_Building001';
            c1.RecordTypeId =[Select id from RecordType where DeveloperName ='OF_SA_Attivazione' LIMIT 1].get(0).id;// OF_SA_GE_Utils.rtMap.get('EOF_Caso_Attivazione_OPENSTREAM_CeD');
            c1.EOF_DATA_NOTIFICA__c=system.now();
            c1.EOF_Data_Prevista_Attivazione__c=system.today();
            c1.OF_SA_Tipo_Lavorazione__c='Attivazione';
            c1.OF_SA_Interfaccia_OM__c='Nuova IF';
            c1.OF_OM_Nuovo_Flusso__c= true;
            c1.EOF_Identificativo_del_POP__c='MI/FCO/2';
            insert c1;
            
            OF_Generatore_ID_Servizio__c g = new OF_Generatore_ID_Servizio__c();
            g.OF_Case_Id__c=c1.Id;
            insert g;
             String gid=g.id;
         gid= gid.abbreviate(10);
            c1.OF_SA_ID_Servizio__c=gid;
            update c1;
        
       // TestDataFactory.CreateTestRecords('EOF_Caso_Attivazione_OPENSTREAM', null, null);
        
        // business account creation        
        String busAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Business').getRecordTypeId();
        Account bus = new Account();
        bus.name = 'Test';
        bus.RecordTypeId = busAccountRecordTypeId;
        insert bus;
        // end business account creation
        
        //service log creation 
        
        EOF_EAI_Service_Log__c sl = new EOF_EAI_Service_Log__c();
        sl.RecordTypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('PO - SA - FiberRequest').getRecordTypeId(); 
        sl.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sl.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sl.EOF_ID_Notifica__c ='';
        sl.EOF_STATO_ORDINE__c ='Acquisito';
        sl.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c='qwer';
        insert sl;
        PO_COMP_AttivazioneInserita_Controller.slOrig = sl;
        // end service log creation
        
        // vlan service log creation
        EOF_EAI_Service_Log__c sv = new EOF_EAI_Service_Log__c();
        sv.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Vlan').getRecordTypeId();
        sv.EOF_Codice_Ordine_OLO__c =c1.EOF_Codice_Ordine_OLO__c;
        sv.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sv.OF_SA_VLan_Log__c=sl.id;       
        insert sv; 
        // end vlan service log creation
        
        // cpe service log creation
        EOF_EAI_Service_Log__c sc = new EOF_EAI_Service_Log__c();
        sc.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        sc.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sc.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sc.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c='qwer';
        sc.OF_SA_Azione_APPARATO__c='1';
        sc.OF_SA_Cpe_Log__c=sl.id;
        insert sc;
        // end cpe service log creation
        
        // servizi aggiuntivi service log creation
        EOF_EAI_Service_Log__c sa = new EOF_EAI_Service_Log__c();
        sa.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Servizi Aggiuntivi').getRecordTypeId();
        sa.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sa.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sa.OF_SA_Servizi_Aggiuntivi_Log__c=sl.id;
        sa.OF_SA_INFORMAZIONI_SERVIZIO__c='213';
        insert sa;
        // end servivi aggiuntivi service log creation
        OF_SA_GE_UtilsNew.caseOriginale=c1;
        Test.setCurrentPageReference(new PageReference('PO_OpenStreamService_InsertNewRequest')); 
        System.currentPageReference().getParameters().put('origId', sl.id);
       	
        //PO_COMP_AttivazioneInserita_Controller.IdVLAN= sv.id; //.IdVLAN = sv;
        //VLANToDelete.Id=IdVLAN;
        test.startTest();
        PO_COMP_AttivazioneInserita_Controller pai = new PO_COMP_AttivazioneInserita_Controller();
        
        pai.IdVLAN =sv.id;
        pai.deleteVLAN();
        
        pai.IdApparato=sc.id;
        pai.deleteApparato();
        
        pai.IdServAgg= sa.id;
        pai.deleteServAgg();
       
        test.stopTest();
        
    }
    
     public static testmethod void test1b(){
          OF_ElencoComuniItaliani__c eci = new OF_ElencoComuniItaliani__c();
         eci.OF_CodiceIstat__c = '015146';
		 eci.OF_Comune__c = 'Milano';
		 eci.OF_Provincia__c = 'Milano';
		 eci.OF_Regione__c ='Lombardia';
         eci.OF_Ripartizionegeografica__c ='Nord-ovest';
        // eci.PO_Ripartizione_geografica_NC__c ='';
         //eci.PO_Titolarit_NC__c ='';
         insert eci; 
        
         OF_AreaGeograficaCustom__c ac = new OF_AreaGeograficaCustom__c();
         ac.OF_Comune__c = 'Milano';
         ac.OF_Istat__c='015146';
         insert ac;
        
         Semaforo_Proxy_Portale__c spp = new Semaforo_Proxy_Portale__c();
 		 spp.Name='Semaforo Proxy Portale Attivazione';
         spp.Semaforo_Proxy_Portale_Attivazione__c=true;
         spp.Semaforo_Proxy_Portale_Cessazione__c=true;
         insert spp;
        
        
        CONFIGURAZIONE_PROXY_PORTALE__c cpp = new CONFIGURAZIONE_PROXY_PORTALE__c();
        cpp.Name='MI_CESSAZIONE';
        cpp.POP__c='MI/FCO/2';
        cpp.Tipo_Lavorazione__c='Cessazione';
        cpp.Data__c=system.today().addDays(-14);
        cpp.Comune__c='';
        insert cpp;
        
        Semaforo_Proxy_Portale__c spp1 = new Semaforo_Proxy_Portale__c();
        spp1.Name='Semaforo Proxy Portale Cessazione';
        spp1.Semaforo_Proxy_Portale_Attivazione__c=true;
        spp1.Semaforo_Proxy_Portale_Cessazione__c=true;
        insert spp1;
        
        //String busAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Business').getRecordTypeId();
        id accOloRTid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
        
        //OF_SA_GE_UtilsNew.caseOriginale = TestDataFactory.c1;
      //  TestDataFactory.CreateTestRecords('EOF_Caso_Attivazione_OPENSTREAM', null, null);
        
        // business account creation        
        String busAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Business').getRecordTypeId();
        Account bus = new Account();
        bus.name = 'Test';
        bus.RecordTypeId = busAccountRecordTypeId;
        insert bus;
        // end business account creation
         Account accOLO = new Account();
        accOLO.Name = 'Tiscali';
        accOLO.EOF_Codice_Operatore__c = 'TIS';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = accOloRTid;
        insert accOLO;
        
        // creazione contratto
        Contract contratto = new Contract();
        contratto.OF_IdContratto__c = 'TEST_TIS_001';
        contratto.AccountId = accOLO.id;
        insert contratto;
        
       Case c1 = new case();
            c1.EOF_Account_OLO__c = accOLO.id;
            c1.EOF_Codice_Ordine_OLO__c = 'Test';
            c1.EOF_Codice_Operatore_WS__c ='TIS';
            c1.EOF_Contact__c = null;
            c1.status = 'Acquisito';
            c1.EOF_FASE__C = 'Da Lavorare';
            c1.EOF_ID_Building_WS__c ='ID_Building001';
            c1.RecordTypeId =[Select id from RecordType where DeveloperName ='OF_SA_Attivazione' LIMIT 1].get(0).id;// OF_SA_GE_Utils.rtMap.get('EOF_Caso_Attivazione_OPENSTREAM_CeD');
            c1.EOF_DATA_NOTIFICA__c=system.now();
            c1.EOF_Data_Prevista_Attivazione__c=system.today();
            c1.OF_SA_Tipo_Lavorazione__c='Attivazione';
            c1.OF_SA_Interfaccia_OM__c='Nuova IF';
            c1.OF_OM_Nuovo_Flusso__c= true;
            c1.EOF_Identificativo_del_POP__c='MI/FCO/2';
            insert c1;
            
            OF_Generatore_ID_Servizio__c g = new OF_Generatore_ID_Servizio__c();
            g.OF_Case_Id__c=c1.Id;
            insert g;
            String gid=g.id;
         gid= gid.abbreviate(10);
            c1.OF_SA_ID_Servizio__c=gid;
            update c1;
        OF_SA_GE_UtilsNew.caseOriginale = c1; //.EOF_ID_Building_WS__c='TEST_000001';
       // update  OF_SA_GE_UtilsNew.caseOriginale;
        //service log creation 
        
        EOF_EAI_Service_Log__c sl = new EOF_EAI_Service_Log__c();
        sl.RecordTypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('PO - SA - FiberRequest').getRecordTypeId(); 
        sl.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sl.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sl.EOF_ID_Notifica__c ='';
        sl.EOF_STATO_ORDINE__c ='Acquisito';
        sl.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c='qwer';
        sl.OF_SA_Interfaccia_OM__c='Nuova IF';
        insert sl;
        PO_COMP_AttivazioneInserita_Controller.slOrig = sl;
        // end service log creation
        
        // vlan service log creation
        EOF_EAI_Service_Log__c sv = new EOF_EAI_Service_Log__c();
        sv.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Vlan').getRecordTypeId();
        sv.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sv.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sv.OF_SA_VLan_Log__c=sl.id;       
        insert sv; 
        // end vlan service log creation
        
        // cpe service log creation
        EOF_EAI_Service_Log__c sc = new EOF_EAI_Service_Log__c();
        sc.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        sc.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sc.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sc.OF_SA_Cpe_Log__c=sl.id;
        sc.OF_SA_Azione_APPARATO__c='1';
        insert sc;
        // end cpe service log creation
        
        // servizi aggiuntivi service log creation
        EOF_EAI_Service_Log__c sa = new EOF_EAI_Service_Log__c();
        sa.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Servizi Aggiuntivi').getRecordTypeId();
        sa.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sa.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sa.OF_SA_Servizi_Aggiuntivi_Log__c=sl.id;
        sa.OF_SA_INFORMAZIONI_SERVIZIO__c='213';
        insert sa;
        // end servivi aggiuntivi service log creation
        
        Test.setCurrentPageReference(new PageReference('PO_OpenStreamService_InsertNewRequest')); 
        System.currentPageReference().getParameters().put('origId', sl.id);
        
        test.startTest();
        PO_COMP_AttivazioneInserita_Controller pai = new PO_COMP_AttivazioneInserita_Controller();
        pai.inserisciVLAN();
        pai.editsl();
        pai.deletesl();
        pai.inserisciApparato();
        pai.inserisciServAgg();
        //pai.deleteVLAN();
        pai.editVLAN();
        //pai.deleteApparato();
        pai.editApparato();
        //pai.deleteServAgg();
        pai.editServAgg();
        pai.confermaRequest();
        pai.sl = sa;
        pai.InoltraRequest();
        pai.annullaInoltro();
        pai.insNewReq();
        pai.goToRicIns();
        test.stopTest();
        
    }
    
    public static testmethod void test2b(){
           OF_ElencoComuniItaliani__c eci = new OF_ElencoComuniItaliani__c();
         eci.OF_CodiceIstat__c = '015146';
		 eci.OF_Comune__c = 'Milano';
		 eci.OF_Provincia__c = 'Milano';
		 eci.OF_Regione__c ='Lombardia';
         eci.OF_Ripartizionegeografica__c ='Nord-ovest';
        // eci.PO_Ripartizione_geografica_NC__c ='';
         //eci.PO_Titolarit_NC__c ='';
         insert eci; 
        
         OF_AreaGeograficaCustom__c ac = new OF_AreaGeograficaCustom__c();
         ac.OF_Comune__c = 'Milano';
         ac.OF_Istat__c='015146';
         insert ac;
        
         Semaforo_Proxy_Portale__c spp = new Semaforo_Proxy_Portale__c();
 		 spp.Name='Semaforo Proxy Portale Attivazione';
         spp.Semaforo_Proxy_Portale_Attivazione__c=true;
         spp.Semaforo_Proxy_Portale_Cessazione__c=true;
         insert spp;
        
        
        CONFIGURAZIONE_PROXY_PORTALE__c cpp = new CONFIGURAZIONE_PROXY_PORTALE__c();
        cpp.Name='MI_CESSAZIONE';
        cpp.POP__c='MI/FCO/2';
        cpp.Tipo_Lavorazione__c='Cessazione';
        cpp.Data__c=system.today().addDays(-14);
        cpp.Comune__c='';
        insert cpp;
        
        Semaforo_Proxy_Portale__c spp1 = new Semaforo_Proxy_Portale__c();
        spp1.Name='Semaforo Proxy Portale Cessazione';
        spp1.Semaforo_Proxy_Portale_Attivazione__c=true;
        spp1.Semaforo_Proxy_Portale_Cessazione__c=true;
        insert spp1;
        
   id accOloRTid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId(); 
        
        Account accOLO2 = new Account();
        accOLO2.Name = 'Vodafone';
        accOLO2.EOF_Codice_Operatore__c = 'VF';
        accOLO2.Type = 'OLO';
        accOLO2.Industry = 'Telecommunications';
        accOLO2.RecordTYpeId = accOloRTid;
        insert accOLO2;
        
        Account accOLO = new Account();
        accOLO.Name = 'Tiscali';
        accOLO.EOF_Codice_Operatore__c = 'TIS';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = accOloRTid;
        insert accOLO;
        
        // creazione contratto
        Contract contratto = new Contract();
        contratto.OF_IdContratto__c = 'TEST_TIS_001';
        contratto.AccountId = accOLO.id;
        insert contratto;
        
       Case c1 = new case();
            c1.EOF_Account_OLO__c = accOLO.id;
            c1.EOF_Codice_Ordine_OLO__c = 'Test';
            c1.EOF_Codice_Operatore_WS__c ='TIS';
            c1.EOF_Contact__c = null;
            c1.status = 'Acquisito';
            c1.EOF_FASE__C = 'Da Lavorare';
            c1.EOF_ID_Building_WS__c ='ID_Building001';
            c1.RecordTypeId =[Select id from RecordType where DeveloperName ='OF_SA_Attivazione' LIMIT 1].get(0).id;// OF_SA_GE_Utils.rtMap.get('EOF_Caso_Attivazione_OPENSTREAM_CeD');
            c1.EOF_DATA_NOTIFICA__c=system.now();
            c1.EOF_Data_Prevista_Attivazione__c=system.today();
            c1.OF_SA_Tipo_Lavorazione__c='Attivazione';
            c1.OF_SA_Interfaccia_OM__c='Nuova IF';
            c1.OF_OM_Nuovo_Flusso__c= true;
            c1.EOF_Identificativo_del_POP__c='MI/FCO/2';
            insert c1;
            
            OF_Generatore_ID_Servizio__c g = new OF_Generatore_ID_Servizio__c();
            g.OF_Case_Id__c=c1.Id;
            insert g;
             String gid=g.id;
         gid= gid.abbreviate(10);
            c1.OF_SA_ID_Servizio__c=gid;
            update c1;
        
        // business account creation        
        String busAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Business').getRecordTypeId();
        Account bus = new Account();
        bus.name = 'Test';
        bus.RecordTypeId = busAccountRecordTypeId;
        insert bus;
        // end business account creation
        
        //service log creation 
        
        EOF_EAI_Service_Log__c sl = new EOF_EAI_Service_Log__c();
        sl.RecordTypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('PO - SA - FiberRequest').getRecordTypeId(); 
        sl.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sl.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sl.EOF_ID_Notifica__c ='';
        sl.EOF_STATO_ORDINE__c ='Acquisito';
        sl.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c='';
		sl.OF_SA_Interfaccia_OM__c='Nuova IF';
        
        insert sl;
        PO_COMP_AttivazioneInserita_Controller.slOrig = sl;
        // end service log creation
        
        // vlan service log creation
        EOF_EAI_Service_Log__c sv = new EOF_EAI_Service_Log__c();
        sv.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Vlan').getRecordTypeId();
        sv.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sv.EOF_Data_Notifica__c=c1.EOF_Data_Notifica__c;
        sv.OF_SA_VLan_Log__c=sl.id;       
        insert sv; 
        // end vlan service log creation
        
        // cpe service log creation
        EOF_EAI_Service_Log__c sc = new EOF_EAI_Service_Log__c();
        sc.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        sc.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sc.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sc.OF_SA_Cpe_Log__c=sl.id;
        sc.OF_SA_Azione_APPARATO__c='1';
        insert sc;
        // end cpe service log creation
        
        // servizi aggiuntivi service log creation
        EOF_EAI_Service_Log__c sa = new EOF_EAI_Service_Log__c();
        sa.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Servizi Aggiuntivi').getRecordTypeId();
        sa.EOF_Codice_Ordine_OLO__c =c1.EOF_Codice_Ordine_OLO__c;
        sa.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sa.OF_SA_Servizi_Aggiuntivi_Log__c=sl.id;
        sa.OF_SA_INFORMAZIONI_SERVIZIO__c='213';
        insert sa;
        // end servivi aggiuntivi service log creation
        OF_SA_GE_UtilsNew.caseOriginale=c1;
        
        Test.setCurrentPageReference(new PageReference('PO_OpenStreamService_InsertNewRequest')); 
        System.currentPageReference().getParameters().put('proc', 'confirmPageATT');
        
        test.startTest();
        PO_COMP_AttivazioneInserita_Controller pai = new PO_COMP_AttivazioneInserita_Controller();
        
        pai.inserisciVLAN();
        pai.editsl();
        pai.deletesl();
        pai.inserisciApparato();
        pai.inserisciServAgg();
        //pai.deleteVLAN();
        pai.editVLAN();
        //pai.deleteApparato();
        pai.editApparato();
        //pai.deleteServAgg();
        pai.editServAgg();
        pai.confermaRequest();
        pai.InoltraRequest();
        pai.annullaInoltro();
        pai.insNewReq();
        pai.goToRicIns();
        test.stopTest();
        
    }
	
	public static testmethod void test4b(){
        
           OF_ElencoComuniItaliani__c eci = new OF_ElencoComuniItaliani__c();
         eci.OF_CodiceIstat__c = '015146';
		 eci.OF_Comune__c = 'Milano';
		 eci.OF_Provincia__c = 'Milano';
		 eci.OF_Regione__c ='Lombardia';
         eci.OF_Ripartizionegeografica__c ='Nord-ovest';
        // eci.PO_Ripartizione_geografica_NC__c ='';
         //eci.PO_Titolarit_NC__c ='';
         insert eci; 
        
         OF_AreaGeograficaCustom__c ac = new OF_AreaGeograficaCustom__c();
         ac.OF_Comune__c = 'Milano';
         ac.OF_Istat__c='015146';
         insert ac;
        
         Semaforo_Proxy_Portale__c spp = new Semaforo_Proxy_Portale__c();
 		 spp.Name='Semaforo Proxy Portale Attivazione';
         spp.Semaforo_Proxy_Portale_Attivazione__c=true;
         spp.Semaforo_Proxy_Portale_Cessazione__c=true;
         insert spp;
        
        
        CONFIGURAZIONE_PROXY_PORTALE__c cpp = new CONFIGURAZIONE_PROXY_PORTALE__c();
        cpp.Name='MI_CESSAZIONE';
        cpp.POP__c='MI/FCO/2';
        cpp.Tipo_Lavorazione__c='Cessazione';
        cpp.Data__c=system.today().addDays(-14);
        cpp.Comune__c='';
        insert cpp;
        
        Semaforo_Proxy_Portale__c spp1 = new Semaforo_Proxy_Portale__c();
        spp1.Name='Semaforo Proxy Portale Cessazione';
        spp1.Semaforo_Proxy_Portale_Attivazione__c=true;
        spp1.Semaforo_Proxy_Portale_Cessazione__c=true;
        insert spp1;
        

          id accOloRTid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId(); 
        
        Account accOLO2 = new Account();
        accOLO2.Name = 'Vodafone';
        accOLO2.EOF_Codice_Operatore__c = 'VF';
        accOLO2.Type = 'OLO';
        accOLO2.Industry = 'Telecommunications';
        accOLO2.RecordTYpeId = accOloRTid;
        insert accOLO2;
        
        Account accOLO = new Account();
        accOLO.Name = 'Tiscali';
        accOLO.EOF_Codice_Operatore__c = 'TIS';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = accOloRTid;
        insert accOLO;
        
        // creazione contratto
        Contract contratto = new Contract();
        contratto.OF_IdContratto__c = 'TEST_TIS_001';
        contratto.AccountId = accOLO.id;
        insert contratto;
        
       Case c1 = new case();
            c1.EOF_Account_OLO__c = accOLO.id;
            c1.EOF_Codice_Ordine_OLO__c = 'Test';
            c1.EOF_Codice_Operatore_WS__c ='TIS';
            c1.EOF_Contact__c = null;
            c1.status = 'Acquisito';
            c1.EOF_FASE__C = 'Da Lavorare';
            c1.EOF_ID_Building_WS__c ='ID_Building001';
            c1.RecordTypeId =[Select id from RecordType where DeveloperName ='OF_SA_Attivazione' LIMIT 1].get(0).id;// OF_SA_GE_Utils.rtMap.get('EOF_Caso_Attivazione_OPENSTREAM_CeD');
            c1.EOF_DATA_NOTIFICA__c=system.now();
            c1.EOF_Data_Prevista_Attivazione__c=system.today();
            c1.OF_SA_Tipo_Lavorazione__c='Attivazione';
            c1.OF_SA_Interfaccia_OM__c='Nuova IF';
            c1.OF_OM_Nuovo_Flusso__c= true;
            c1.EOF_Identificativo_del_POP__c='MI/FCO/2';
            insert c1;
            
            OF_Generatore_ID_Servizio__c g = new OF_Generatore_ID_Servizio__c();
            g.OF_Case_Id__c=c1.Id;
            insert g;
             String gid=g.id;
         gid= gid.abbreviate(10);
            c1.OF_SA_ID_Servizio__c=gid;
            update c1;
        
        // business account creation        
        String busAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Business').getRecordTypeId();
        Account bus = new Account();
        bus.name = 'Test';
        bus.RecordTypeId = busAccountRecordTypeId;
        insert bus;
        // end business account creation
        
        //service log creation 
        
        EOF_EAI_Service_Log__c sl = new EOF_EAI_Service_Log__c();
        sl.RecordTypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('PO - SA - FiberRequest').getRecordTypeId(); 
        sl.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sl.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sl.EOF_ID_Notifica__c ='';
        sl.EOF_STATO_ORDINE__c ='Acquisito';
        sl.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c='qwer';
		sl.OF_SA_Interfaccia_OM__c='Nuova IF';
        
        insert sl;
        PO_COMP_AttivazioneInserita_Controller.slOrig = sl;
        // end service log creation
        
        // vlan service log creation
        EOF_EAI_Service_Log__c sv = new EOF_EAI_Service_Log__c();
        sv.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Vlan').getRecordTypeId();
        sv.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sv.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sv.OF_SA_VLan_Log__c=sl.id;       
        insert sv; 
        // end vlan service log creation
        
        // cpe service log creation
        EOF_EAI_Service_Log__c sc = new EOF_EAI_Service_Log__c();
        sc.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        sc.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sc.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sc.OF_SA_Cpe_Log__c=sl.id;
        sc.OF_SA_Azione_APPARATO__c='1';
        insert sc;
        // end cpe service log creation
        
        // servizi aggiuntivi service log creation
        EOF_EAI_Service_Log__c sa = new EOF_EAI_Service_Log__c();
        sa.recordtypeId=Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Servizi Aggiuntivi').getRecordTypeId();
        sa.EOF_Codice_Ordine_OLO__c = c1.EOF_Codice_Ordine_OLO__c;
        sa.EOF_Data_Notifica__c= c1.EOF_Data_Notifica__c;
        sa.OF_SA_Servizi_Aggiuntivi_Log__c=sl.id;
        sa.OF_SA_INFORMAZIONI_SERVIZIO__c='213';
        insert sa;
        // end servivi aggiuntivi service log creation
        OF_SA_GE_UtilsNew.caseOriginale=c1;
        Test.setCurrentPageReference(new PageReference('PO_OpenStreamService_InsertNewRequest')); 
        System.currentPageReference().getParameters().put('proc', 'errorInsertATT');
        
        test.startTest();
        PO_COMP_AttivazioneInserita_Controller pai = new PO_COMP_AttivazioneInserita_Controller();
        
        pai.inserisciVLAN();
        pai.editsl();
        pai.deletesl();
        pai.inserisciApparato();
        pai.inserisciServAgg();
        //pai.deleteVLAN();
        pai.editVLAN();
        //pai.deleteApparato();
        pai.editApparato();
        //pai.deleteServAgg();
        pai.editServAgg();
        pai.confermaRequest();
        pai.InoltraRequest();
        pai.annullaInoltro();
        pai.insNewReq();
        pai.goToRicIns();
        test.stopTest();
        
    }
    
}