objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OLO</fullName>
        <active>true</active>
        <description>Use this account to store OLO information.</description>
        <label>OLO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Account_OLO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLO</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>OLO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Operatore_WS__c</fullName>
        <label>Codice Operatore</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VF</fullName>
                </value>
                <value>
                    <fullName>WN</fullName>
                </value>
                <value>
                    <fullName>TIS</fullName>
                </value>
                <value>
                    <fullName>GOI</fullName>
                </value>
                <value>
                    <fullName>CNN</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>FAS</fullName>
                </value>
                <value>
                    <fullName>PLA</fullName>
                </value>
                <value>
                    <fullName>CWN</fullName>
                </value>
                <value>
                    <fullName>4IS</fullName>
                </value>
                <value>
                    <fullName>XMA</fullName>
                </value>
                <value>
                    <fullName>WAR</fullName>
                </value>
                <value>
                    <fullName>UND</fullName>
                </value>
                <value>
                    <fullName>SPE</fullName>
                </value>
                <value>
                    <fullName>UMB</fullName>
                </value>
                <value>
                    <fullName>NEX</fullName>
                </value>
                <value>
                    <fullName>NOI</fullName>
                </value>
                <value>
                    <fullName>RAF</fullName>
                </value>
                <value>
                    <fullName>PAN</fullName>
                </value>
                <value>
                    <fullName>SHS</fullName>
                </value>
                <value>
                    <fullName>ALT</fullName>
                </value>
                <value>
                    <fullName>SIR</fullName>
                </value>
                <value>
                    <fullName>HAL</fullName>
                </value>
                <value>
                    <fullName>BRI</fullName>
                </value>
                <value>
                    <fullName>LAW</fullName>
                </value>
                <value>
                    <fullName>ACA</fullName>
                </value>
                <value>
                    <fullName>FST</fullName>
                </value>
                <value>
                    <fullName>INT</fullName>
                </value>
                <value>
                    <fullName>UNC</fullName>
                </value>
                <value>
                    <fullName>SAI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <externalId>true</externalId>
        <label>Codice Ordine OLO</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EOF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referente Tecnico OLO</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.EOF_Account_OLO__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da lavorare</fullName>
                </value>
                <value>
                    <fullName>Appuntamento Fissato</fullName>
                </value>
                <value>
                    <fullName>Da contattare</fullName>
                </value>
                <value>
                    <fullName>Desospeso</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione</fullName>
                </value>
                <value>
                    <fullName>In Verifica BO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Sospeso BO</fullName>
                </value>
                <value>
                    <fullName>Sospeso Tecn.</fullName>
                </value>
                <value>
                    <fullName>In assegnazione</fullName>
                </value>
                <value>
                    <fullName>Espletato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato KO</fullName>
                </value>
                <value>
                    <fullName>Espletato KO</fullName>
                </value>
                <value>
                    <fullName>Accettato KO</fullName>
                </value>
                <value>
                    <fullName>In Verifica Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Network Creation</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Delivery</fullName>
                </value>
                <value>
                    <fullName>Completato</fullName>
                </value>
                <value>
                    <fullName>Offerta Creata</fullName>
                </value>
                <value>
                    <fullName>Offerta Presentata</fullName>
                </value>
                <value>
                    <fullName>Richiesta modifica offerta da Cliente</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Referente Fattibilità</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Tecnico Fattibilità</fullName>
                </value>
                <value>
                    <fullName>Sospeso OM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OF_Bonifica_Locked_Row__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bonifica Locked Row</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_OM_Nuovo_Flusso__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OF_OM_Nuovo_Flusso</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_Response_Da_OLO__c</fullName>
        <label>Response Da OLO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Response_Da_OM__c</fullName>
        <label>Response Da OM</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>EOF_Caso_ChangeOrder_OPENSTREAM</fullName>
        <active>true</active>
        <businessProcess>EOF Support Process</businessProcess>
        <label>EOF_Caso_ChangeOrder_OPENSTREAM</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>EAI Service Logs (Caso)</relationshipLabel>
        <relationshipName>EAI_Service_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <label>Codice Ordine OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipo_Comunicazione_String__c</fullName>
        <label>Tipo Comunicazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipo_Comunicazione__c</fullName>
        <label>Tipo Comunicazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_OM_Nuovo_Flusso__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OF_OM_Nuovo_Flusso</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_SA_Cpe_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cpe Log</label>
        <referenceTo>EOF_EAI_Service_Log__c</referenceTo>
        <relationshipLabel>Cpe</relationshipLabel>
        <relationshipName>OF_SA_Cpe</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_SA_Direzione_Flusso__c</fullName>
        <label>Direzione Flusso</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <recordTypes>
        <fullName>ACK</fullName>
        <active>true</active>
        <label>ACK</label>
    </recordTypes>
    <recordTypes>
        <fullName>FiberNotify</fullName>
        <active>true</active>
        <label>FiberNotify</label>
    </recordTypes>
    <recordTypes>
        <fullName>FiberRequest</fullName>
        <active>true</active>
        <label>FiberRequest</label>
    </recordTypes>
    <recordTypes>
        <fullName>NACK</fullName>
        <active>true</active>
        <label>NACK</label>
    </recordTypes>
    <recordTypes>
        <fullName>OF_SA_FiberRequest</fullName>
        <active>true</active>
        <label>OF - SA - FiberRequest</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_CommercialElementIstanziato__c.object
<CustomObject>
    <label>Commercial element istanziato</label>
    <nameField>
        <displayFormat>CEI-{00000}</displayFormat>
        <label>Commercial element istanziato Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial element istanziati</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Enable_PO_UpdateOppCase_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_Enable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Enable PO_UpdateOppCase Trigger</label>
</CustomObject>

objects/OF_Puntamento_Callout__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_OGW__c</fullName>
        <label>OGW</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Puntamento Callout</label>
</CustomObject>

objects/OF_Tibco_userID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Metodo per recuperare lo UserID di Tibco</description>
    <fields>
        <fullName>OF_Tibco_ID__c</fullName>
        <label>Tibco ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Tibco userID</label>
</CustomObject>

classes/EOF_SendRetry_Test.cls
@isTest
public class EOF_SendRetry_Test
{
    @testSetup 
    public static void testSetUpData() {
        Insert new OF_Puntamento_Callout__c(Name = 'OGW',OF_OGW__c = 'Test');
        Insert new OF_Tibco_userID__c(Name = 'Tibco UserID',OF_Tibco_ID__c= 'Test');
        Insert new OF_Enable_PO_UpdateOppCase_Trigger__c(Name = 'Status',OF_Enable_Trigger__c= true);
    }
    
    static testmethod Map<String,String> RecordType(){       
        List<RecordType> rtypes = [Select Name, Id From RecordType where (sObjectType='Case' OR sObjectType='Account' OR sObjectType='Contact' OR sObjectType = 'EOF_EAI_Service_Log__c' OR sObjectType = 'OF_CommercialElementIstanziato__c')  and isActive=true];
        Map<String,String> RecordType = new Map<String,String>{};
        for(RecordType rt: rtypes){
            RecordType.put(rt.Name,rt.Id);  
        }      
        return RecordType;
    }
  
    static testmethod void Method1()
    {
        Map<String,String> RecordTypeMap = RecordType();

        OF_Tibco_userID__c tibco=new OF_Tibco_userID__c();
        tibco.OF_Tibco_ID__c='test';
        tibco.name='Tibco UserID';
        insert tibco;
        
        OF_Enable_PO_UpdateOppCase_Trigger__c abilitaTrig =new OF_Enable_PO_UpdateOppCase_Trigger__c();
        abilitaTrig.name='Status';
        abilitaTrig.OF_Enable_Trigger__c=true;
        insert abilitaTrig;        
        
        Account accOloWIND = new Account();       
        accOloWIND.Name = 'Wind';
        accOloWIND.EOF_Codice_Operatore__c = 'WN';
        accOloWIND.Type = 'OLO';
        accOloWIND.Industry = 'Telecommunications';
        accOloWIND.RecordTYpeId = RecordTypeMap.get('OLO');        
        insert accOloWIND; 
        
        contact con = new contact();
        con.AccountId = accOloWIND.id;
        String ConRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Referente Tecnico OLO').getRecordTypeId();
        
        con.RecordTypeId = ConRecordTypeId; //RecordTypeMap.get('Referente Tecnico OLO');
        con.FirstName = 'Gianni';
        con.LastName = 'Bugno';
        con.Phone = '333';
        con.Email = 'test@test.it'; 
        insert con;
        
        List<Case> caseListNACK1 = new List<Case>();
        Map<String,Id> recordTypeMap1 = new Map<String,Id>();
        List<RecordType> allCaseTypes = [select Id, DeveloperName from RecordType where SObjectType = 'Case' ];
        for (RecordType r : allCaseTypes) 
        {
            recordTypeMap1.put(r.DeveloperName,r.Id);
        }
    
        Case c = new Case();
        c.RecordTypeId = RecordTypeMap.get('EOF_Caso_Cessazione_OPENSTREAM');
        c.EOF_Account_OLO__c = accOloWIND.id;
        c.EOF_Contact__c = con.id;
        c.status = 'Ricevuto';
        c.EOF_FASE__C = 'NA';
        c.EOF_Codice_Ordine_OLO__c='Test';
        c.EOF_Codice_Operatore_WS__c ='VF';  
        c.OF_Bonifica_Locked_Row__c = true;
        c.OF_Response_Da_OLO__c='NACK TECNICO';
        // c.RecordTypeId = recordTypeMap1.get('OF_SA_FIberRequest');
        //caseListNACK1.add(c);
        //insert caseListNACK1;
        c.OF_OM_Nuovo_Flusso__c = True;
        insert c;
        
     
        String ListRecordTypePassId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = ListRecordTypePassId ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        insert slFiberReq;
        
        EOF_EAI_Service_Log__c slFiberReq1 = new EOF_EAI_Service_Log__c();
        slFiberReq1.eof_tipo_comunicazione_String__c='OLO->SF - ACK - ActivationRequest';        
        slFiberReq1.EOF_Codice_Ordine_OLo__C = 'Test';
        insert slFiberReq1;
        
        String ListRecordTypePassId1 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberNotify').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq2 = new EOF_EAI_Service_Log__c();
        slFiberReq2.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq2.RecordTypeId = ListRecordTypePassId1 ;
        slFiberReq2.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq2.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq2.Caso__c = c.id;        
        insert slFiberReq2;
        
        String ListRecordTypePassId3 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq3 = new EOF_EAI_Service_Log__c();
        slFiberReq3.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq3.RecordTypeId = ListRecordTypePassId3 ;
        slFiberReq3.OF_SA_Cpe_Log__c = slFiberReq.id;
        slFiberReq3.EOF_Codice_Ordine_OLo__C = 'Test';        
        insert slFiberReq3;
        
        //BusinessHours bh_dac = [SELECT Id FROM BusinessHours WHERE Name='DAC'];
        OF_SA_GE_Utils.caseOriginale = c;
        OF_SA_GE_Utils.slOLOSF = slFiberReq;
        
        OF_Puntamento_Callout__c pnt= new OF_Puntamento_Callout__c();
        pnt.name='OGW';
        pnt.OF_OGW__c ='OFS-SVIL-WS';
        insert pnt;
        
        OF_Enable_PO_UpdateOppCase_Trigger__c trg = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trg.Name = 'Status';
        trg.OF_Enable_Trigger__c = false;
        insert trg;
        
        Test.starttest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());        
        
        List<Case> caseListNACK =[select Id,EOF_Codice_Ordine_OLO__C,recordtype.developername 
                                  from Case 
                                  where OF_Response_Da_OLO__c='NACK TECNICO' 
                                  OR OF_Response_Da_OM__c='NACK TECNICO' limit 3];
        EOF_SendRetry sh1 = new EOF_SendRetry();      
        String sch = '0  00 1 3 * ?';
        system.schedule('Retry Job 2a', sch, sh1);
        
        Test.stopTest();
    }
    
    static testmethod void Method1A()
    {
        Map<String,String> RecordTypeMap = RecordType();

        OF_Tibco_userID__c tibco=new OF_Tibco_userID__c();
        tibco.OF_Tibco_ID__c='test';
        tibco.name='Tibco UserID';
        insert tibco;
        
        OF_Enable_PO_UpdateOppCase_Trigger__c abilitaTrig =new OF_Enable_PO_UpdateOppCase_Trigger__c();
        abilitaTrig.name='Status';
        abilitaTrig.OF_Enable_Trigger__c=true;
        insert abilitaTrig;        
        
        Account accOloWIND = new Account();       
        accOloWIND.Name = 'Wind';
        accOloWIND.EOF_Codice_Operatore__c = 'WN';
        accOloWIND.Type = 'OLO';
        accOloWIND.Industry = 'Telecommunications';
        accOloWIND.RecordTYpeId = RecordTypeMap.get('OLO');        
        insert accOloWIND; 
        
        contact con = new contact();
        con.AccountId = accOloWIND.id;
        String ConRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Referente Tecnico OLO').getRecordTypeId();
        
        con.RecordTypeId = ConRecordTypeId; //RecordTypeMap.get('Referente Tecnico OLO');
        con.FirstName = 'Gianni';
        con.LastName = 'Bugno';
        con.Phone = '333';
        con.Email = 'test@test.it'; 
        insert con;
        
        List<Case> caseListNACK1 = new List<Case>();
        Map<String,Id> recordTypeMap1 = new Map<String,Id>();
        List<RecordType> allCaseTypes = [select Id, DeveloperName from RecordType where SObjectType = 'Case' ];
        for (RecordType r : allCaseTypes) 
        {
            recordTypeMap1.put(r.DeveloperName,r.Id);
        }
    
        Case c = new Case();
        c.RecordTypeId = RecordTypeMap.get('EOF_Caso_Cessazione_OPENSTREAM');
        c.EOF_Account_OLO__c = accOloWIND.id;
        c.EOF_Contact__c = con.id;
        c.status = 'Ricevuto';
        c.EOF_FASE__C = 'NA';
        c.EOF_Codice_Ordine_OLO__c='Test';
        c.EOF_Codice_Operatore_WS__c ='VF';  
        c.OF_Bonifica_Locked_Row__c = true;
        c.OF_Response_Da_OLO__c='NACK TECNICO';
        // c.RecordTypeId = recordTypeMap1.get('OF_SA_FIberRequest');
        //caseListNACK1.add(c);
        //insert caseListNACK1;
        c.OF_OM_Nuovo_Flusso__c = False;
        insert c;
        
     
        String ListRecordTypePassId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = ListRecordTypePassId ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        insert slFiberReq;
        
        EOF_EAI_Service_Log__c slFiberReq1 = new EOF_EAI_Service_Log__c();
        slFiberReq1.eof_tipo_comunicazione_String__c='OLO->SF - ACK - ActivationRequest';        
        slFiberReq1.EOF_Codice_Ordine_OLo__C = 'Test';
        insert slFiberReq1;
        
        String ListRecordTypePassId1 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberNotify').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq2 = new EOF_EAI_Service_Log__c();
        slFiberReq2.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq2.RecordTypeId = ListRecordTypePassId1 ;
        slFiberReq2.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq2.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq2.Caso__c = c.id;        
        insert slFiberReq2;
        
        String ListRecordTypePassId3 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq3 = new EOF_EAI_Service_Log__c();
        slFiberReq3.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq3.RecordTypeId = ListRecordTypePassId3 ;
        slFiberReq3.OF_SA_Cpe_Log__c = slFiberReq.id;
        slFiberReq3.EOF_Codice_Ordine_OLo__C = 'Test';        
        insert slFiberReq3;
        
        //BusinessHours bh_dac = [SELECT Id FROM BusinessHours WHERE Name='DAC'];
        OF_SA_GE_Utils.caseOriginale = c;
        OF_SA_GE_Utils.slOLOSF = slFiberReq;
        
        OF_Puntamento_Callout__c pnt= new OF_Puntamento_Callout__c();
        pnt.name='OGW';
        pnt.OF_OGW__c ='OFS-SVIL-WS';
        insert pnt;
        
        OF_Enable_PO_UpdateOppCase_Trigger__c trg = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trg.Name = 'Status';
        trg.OF_Enable_Trigger__c = false;
        insert trg;
        
        Test.starttest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());        
        
        List<Case> caseListNACK =[select Id,EOF_Codice_Ordine_OLO__C,recordtype.developername 
                                  from Case 
                                  where OF_Response_Da_OLO__c='NACK TECNICO' 
                                  OR OF_Response_Da_OM__c='NACK TECNICO' limit 3];
        EOF_SendRetry sh1 = new EOF_SendRetry();      
        String sch = '0  00 1 3 * ?';
        system.schedule('Retry Job 2b', sch, sh1);
        
        Test.stopTest();
    }
   
    static testmethod void Method2()
    {
        Map<String,String> RecordTypeMap = RecordType();
        
        Account accOloWIND = new Account();       
        accOloWIND.Name = 'Wind';
        accOloWIND.EOF_Codice_Operatore__c = 'WN';
        accOloWIND.Type = 'OLO';
        accOloWIND.Industry = 'Telecommunications';
        accOloWIND.RecordTYpeId = RecordTypeMap.get('OLO');        
        insert accOloWIND; 
        
        contact con = new contact();
        con.AccountId = accOloWIND.id;
        con.RecordTypeId = RecordTypeMap.get('Referente Tecnico OLO');
        con.FirstName = 'Gianni';
        con.LastName = 'Bugno';
        con.Phone = '333';
        con.Email = 'test@test.it'; 
        insert con;
        
        Case c2 = new Case();
        c2.RecordTypeId = RecordTypeMap.get('EOF Caso - Attivazione');
        c2.eof_account_OLO__c=accOloWIND.Id;
        c2.EOF_Contact__c = con.id;
        c2.status = 'Ricevuto';
        c2.EOF_FASE__C = 'NA';
        c2.EOF_Codice_Ordine_OLO__c='Test';
        c2.EOF_Codice_Operatore_WS__c ='VF';  
        c2.OF_Bonifica_Locked_Row__c = true;
        c2.OF_Response_Da_OLO__c='NACK TECNICO';
        insert c2;
        
        String ListRecordTypePassId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = ListRecordTypePassId ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        insert slFiberReq;
        
        EOF_EAI_Service_Log__c slFiberReq1 = new EOF_EAI_Service_Log__c();
        slFiberReq1.eof_tipo_comunicazione_String__c='OLO->SF - ACK - ActivationRequest';        
        slFiberReq1.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq1.RecordTypeId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('FiberNotify').getRecordTypeId();
        slFiberReq1.Caso__c = c2.id; 
        insert slFiberReq1;
        
        String ListRecordTypePassId1 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberNotify').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq2 = new EOF_EAI_Service_Log__c();
        slFiberReq2.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq2.RecordTypeId = ListRecordTypePassId1 ;
        slFiberReq2.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq2.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq2.Caso__c = c2.id;        
        insert slFiberReq2;
        
        String ListRecordTypePassId3 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq3 = new EOF_EAI_Service_Log__c();
        slFiberReq3.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq3.RecordTypeId = ListRecordTypePassId3 ;
        slFiberReq3.OF_SA_Cpe_Log__c = slFiberReq.id;
        slFiberReq3.EOF_Codice_Ordine_OLo__C = 'Test';        
        insert slFiberReq3;
        
        //BusinessHours bh_dac = [SELECT Id FROM BusinessHours WHERE Name='DAC'];
        OF_SA_GE_Utils.caseOriginale = c2;
        OF_SA_GE_Utils.slOLOSF = slFiberReq;
        
        OF_Puntamento_Callout__c pnt= new OF_Puntamento_Callout__c();
        pnt.name='OGW';
        pnt.OF_OGW__c ='OFS-SVIL-WS';
        insert pnt;
        
        OF_Enable_PO_UpdateOppCase_Trigger__c trg = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trg.Name = 'Status';
        trg.OF_Enable_Trigger__c = false;
        insert trg;
        
        Test.starttest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());        
        
        List<Case> caseListNACK =[select Id,EOF_Codice_Ordine_OLO__C,recordtype.developername from Case where OF_Response_Da_OLO__c='NACK TECNICO' OR OF_Response_Da_OM__c='NACK TECNICO' limit 3];
        EOF_SendRetry sh1 = new EOF_SendRetry();      
        String sch = '0  00 1 3 * ?';
        system.schedule('Retry Job 2c', sch, sh1);
        Test.stopTest();
    }
    
    static testmethod void Method2A()
    {
        Map<String,String> RecordTypeMap = RecordType();
        
        Account accOloWIND = new Account();       
        accOloWIND.Name = 'Wind';
        accOloWIND.EOF_Codice_Operatore__c = 'WN';
        accOloWIND.Type = 'OLO';
        accOloWIND.Industry = 'Telecommunications';
        accOloWIND.RecordTYpeId = RecordTypeMap.get('OLO');        
        insert accOloWIND; 
        
        contact con = new contact();
        con.AccountId = accOloWIND.id;
        con.RecordTypeId = RecordTypeMap.get('Referente Tecnico OLO');
        con.FirstName = 'Gianni';
        con.LastName = 'Bugno';
        con.Phone = '333';
        con.Email = 'test@test.it'; 
        insert con;
        
        Case c2 = new Case();
        c2.RecordTypeId = RecordTypeMap.get('EOF Caso - Attivazione');
        c2.eof_account_OLO__c=accOloWIND.Id;
        c2.EOF_Contact__c = con.id;
        c2.status = 'Ricevuto';
        c2.EOF_FASE__C = 'NA';
        c2.EOF_Codice_Ordine_OLO__c='Test';
        c2.EOF_Codice_Operatore_WS__c ='VF';  
        c2.OF_Bonifica_Locked_Row__c = true;
        c2.OF_Response_Da_OLO__c='NACK TECNICO';
        c2.OF_OM_Nuovo_Flusso__c = True;
        insert c2;
        
        String ListRecordTypePassId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = ListRecordTypePassId ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        insert slFiberReq;
        
        EOF_EAI_Service_Log__c slFiberReq1 = new EOF_EAI_Service_Log__c();
        slFiberReq1.eof_tipo_comunicazione_String__c='OLO->SF - ACK - ActivationRequest';        
        slFiberReq1.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq1.RecordTypeId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('FiberNotify').getRecordTypeId();
        slFiberReq1.Caso__c = c2.id; 
        insert slFiberReq1;
        
        String ListRecordTypePassId1 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberNotify').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq2 = new EOF_EAI_Service_Log__c();
        slFiberReq2.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq2.RecordTypeId = ListRecordTypePassId1 ;
        slFiberReq2.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq2.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq2.Caso__c = c2.id;        
        insert slFiberReq2;
        
        String ListRecordTypePassId3 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq3 = new EOF_EAI_Service_Log__c();
        slFiberReq3.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq3.RecordTypeId = ListRecordTypePassId3 ;
        slFiberReq3.OF_SA_Cpe_Log__c = slFiberReq.id;
        slFiberReq3.EOF_Codice_Ordine_OLo__C = 'Test';        
        insert slFiberReq3;
        
        //BusinessHours bh_dac = [SELECT Id FROM BusinessHours WHERE Name='DAC'];
        OF_SA_GE_Utils.caseOriginale = c2;
        OF_SA_GE_Utils.slOLOSF = slFiberReq;
        
        OF_Puntamento_Callout__c pnt= new OF_Puntamento_Callout__c();
        pnt.name='OGW';
        pnt.OF_OGW__c ='OFS-SVIL-WS';
        insert pnt;
        
        OF_Enable_PO_UpdateOppCase_Trigger__c trg = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trg.Name = 'Status';
        trg.OF_Enable_Trigger__c = false;
        insert trg;
        
        Test.starttest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());        
        
        List<Case> caseListNACK =[select Id,EOF_Codice_Ordine_OLO__C,recordtype.developername from Case where OF_Response_Da_OLO__c='NACK TECNICO' OR OF_Response_Da_OM__c='NACK TECNICO' limit 3];
        EOF_SendRetry sh1 = new EOF_SendRetry();      
        String sch = '0  00 1 3 * ?';
        system.schedule('Retry Job 2d', sch, sh1);
        Test.stopTest();
    }
    
     static testmethod void Method3A()
    {
        Map<String,String> RecordTypeMap = RecordType();
        
        Account accOloWIND = new Account();       
        accOloWIND.Name = 'Wind';
        accOloWIND.EOF_Codice_Operatore__c = 'WN';
        accOloWIND.Type = 'OLO';
        accOloWIND.Industry = 'Telecommunications';
        accOloWIND.RecordTYpeId = RecordTypeMap.get('OLO');        
        insert accOloWIND; 
        
        contact con = new contact();
        con.AccountId = accOloWIND.id;
        con.RecordTypeId = RecordTypeMap.get('Referente Tecnico OLO');
        con.FirstName = 'Gianni';
        con.LastName = 'Bugno';
        con.Phone = '333';
        con.Email = 'test@test.it'; 
        insert con;
        
        Case c2 = new Case();
        c2.RecordTypeId = RecordTypeMap.get('EOF_Caso_ChangeOrder_OPENSTREAM');
        c2.eof_account_OLO__c=accOloWIND.Id;
        c2.EOF_Contact__c = con.id;
        c2.status = 'Ricevuto';
        c2.EOF_FASE__C = 'NA';
        c2.EOF_Codice_Ordine_OLO__c='Test';
        c2.EOF_Codice_Operatore_WS__c ='VF';  
        c2.OF_Bonifica_Locked_Row__c = true;
        c2.OF_Response_Da_OLO__c='NACK TECNICO';
        c2.OF_OM_Nuovo_Flusso__c = True;
        insert c2;
        
        String ListRecordTypePassId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = ListRecordTypePassId ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        insert slFiberReq;
        
        EOF_EAI_Service_Log__c slFiberReq1 = new EOF_EAI_Service_Log__c();
        slFiberReq1.eof_tipo_comunicazione_String__c='OLO->SF - ACK - ActivationRequest';        
        slFiberReq1.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq1.RecordTypeId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('FiberNotify').getRecordTypeId();
        slFiberReq1.Caso__c = c2.id; 
        insert slFiberReq1;
        
        String ListRecordTypePassId1 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberNotify').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq2 = new EOF_EAI_Service_Log__c();
        slFiberReq2.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq2.RecordTypeId = ListRecordTypePassId1 ;
        slFiberReq2.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq2.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq2.Caso__c = c2.id;        
        insert slFiberReq2;
        
        String ListRecordTypePassId3 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq3 = new EOF_EAI_Service_Log__c();
        slFiberReq3.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq3.RecordTypeId = ListRecordTypePassId3 ;
        slFiberReq3.OF_SA_Cpe_Log__c = slFiberReq.id;
        slFiberReq3.EOF_Codice_Ordine_OLo__C = 'Test';        
        insert slFiberReq3;
        
        //BusinessHours bh_dac = [SELECT Id FROM BusinessHours WHERE Name='DAC'];
        OF_SA_GE_Utils.caseOriginale = c2;
        OF_SA_GE_Utils.slOLOSF = slFiberReq;
        
        OF_Puntamento_Callout__c pnt= new OF_Puntamento_Callout__c();
        pnt.name='OGW';
        pnt.OF_OGW__c ='OFS-SVIL-WS';
        insert pnt;
        
        OF_Enable_PO_UpdateOppCase_Trigger__c trg = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trg.Name = 'Status';
        trg.OF_Enable_Trigger__c = false;
        insert trg;
        
        Test.starttest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());        
        
        List<Case> caseListNACK =[select Id,EOF_Codice_Ordine_OLO__C,recordtype.developername from Case where OF_Response_Da_OLO__c='NACK TECNICO' OR OF_Response_Da_OM__c='NACK TECNICO' limit 3];
        EOF_SendRetry sh1 = new EOF_SendRetry();      
        String sch = '0  00 1 3 * ?';
        system.schedule('Retry Job 2e', sch, sh1);
        Test.stopTest();
    }
    
     static testmethod void Method4A()
    {
        Map<String,String> RecordTypeMap = RecordType();
        
        Account accOloWIND = new Account();       
        accOloWIND.Name = 'Wind';
        accOloWIND.EOF_Codice_Operatore__c = 'WN';
        accOloWIND.Type = 'OLO';
        accOloWIND.Industry = 'Telecommunications';
        accOloWIND.RecordTYpeId = RecordTypeMap.get('OLO');        
        insert accOloWIND; 
        
        contact con = new contact();
        con.AccountId = accOloWIND.id;
        con.RecordTypeId = RecordTypeMap.get('Referente Tecnico OLO');
        con.FirstName = 'Gianni';
        con.LastName = 'Bugno';
        con.Phone = '333';
        con.Email = 'test@test.it'; 
        insert con;
        
        Case c2 = new Case();
        c2.RecordTypeId = RecordTypeMap.get('Trouble Ticket');
        c2.eof_account_OLO__c=accOloWIND.Id;
        c2.EOF_Contact__c = con.id;
        c2.status = 'Ricevuto';
        c2.EOF_FASE__C = 'NA';
        c2.EOF_Codice_Ordine_OLO__c='Test';
        c2.EOF_Codice_Operatore_WS__c ='VF';  
        c2.OF_Bonifica_Locked_Row__c = true;
        c2.OF_Response_Da_OLO__c='NACK TECNICO';
        c2.OF_OM_Nuovo_Flusso__c = True;
        insert c2;
        
        String ListRecordTypePassId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = ListRecordTypePassId ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        insert slFiberReq;
        
        EOF_EAI_Service_Log__c slFiberReq1 = new EOF_EAI_Service_Log__c();
        slFiberReq1.eof_tipo_comunicazione_String__c='OLO->SF - ACK - ActivationRequest';        
        slFiberReq1.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq1.RecordTypeId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('FiberNotify').getRecordTypeId();
        slFiberReq1.Caso__c = c2.id; 
        insert slFiberReq1;
        
        String ListRecordTypePassId1 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberNotify').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq2 = new EOF_EAI_Service_Log__c();
        slFiberReq2.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq2.RecordTypeId = ListRecordTypePassId1 ;
        slFiberReq2.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq2.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq2.Caso__c = c2.id;        
        insert slFiberReq2;
        
        String ListRecordTypePassId3 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq3 = new EOF_EAI_Service_Log__c();
        slFiberReq3.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq3.RecordTypeId = ListRecordTypePassId3 ;
        slFiberReq3.OF_SA_Cpe_Log__c = slFiberReq.id;
        slFiberReq3.EOF_Codice_Ordine_OLo__C = 'Test';        
        insert slFiberReq3;
        
        //BusinessHours bh_dac = [SELECT Id FROM BusinessHours WHERE Name='DAC'];
        OF_SA_GE_Utils.caseOriginale = c2;
        OF_SA_GE_Utils.slOLOSF = slFiberReq;
        
        OF_Puntamento_Callout__c pnt= new OF_Puntamento_Callout__c();
        pnt.name='OGW';
        pnt.OF_OGW__c ='OFS-SVIL-WS';
        insert pnt;
        
        OF_Enable_PO_UpdateOppCase_Trigger__c trg = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trg.Name = 'Status';
        trg.OF_Enable_Trigger__c = false;
        insert trg;
        
        Test.starttest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());        
        
        List<Case> caseListNACK =[select Id,EOF_Codice_Ordine_OLO__C,recordtype.developername from Case where OF_Response_Da_OLO__c='NACK TECNICO' OR OF_Response_Da_OM__c='NACK TECNICO' limit 3];
        EOF_SendRetry sh1 = new EOF_SendRetry();      
        String sch = '0  00 1 3 * ?';
        system.schedule('Retry Job 2f', sch, sh1);
        Test.stopTest();
    }
    
    static testmethod void Method5A()
    {
        Map<String,String> RecordTypeMap = RecordType();
        
        Account accOloWIND = new Account();       
        accOloWIND.Name = 'Wind';
        accOloWIND.EOF_Codice_Operatore__c = 'WN';
        accOloWIND.Type = 'OLO';
        accOloWIND.Industry = 'Telecommunications';
        accOloWIND.RecordTYpeId = RecordTypeMap.get('OLO');        
        insert accOloWIND; 
        
        contact con = new contact();
        con.AccountId = accOloWIND.id;
        con.RecordTypeId = RecordTypeMap.get('Referente Tecnico OLO');
        con.FirstName = 'Gianni';
        con.LastName = 'Bugno';
        con.Phone = '333';
        con.Email = 'test@test.it'; 
        insert con;
        
        Case c2 = new Case();
        c2.RecordTypeId = RecordTypeMap.get('PO PreProvisioning VLAN');
        c2.eof_account_OLO__c=accOloWIND.Id;
        c2.EOF_Contact__c = con.id;
        c2.status = 'Ricevuto';
        c2.EOF_FASE__C = 'NA';
        c2.EOF_Codice_Ordine_OLO__c='Test';
        c2.EOF_Codice_Operatore_WS__c ='VF';  
        c2.OF_Bonifica_Locked_Row__c = true;
        c2.OF_Response_Da_OLO__c='NACK TECNICO';
        c2.OF_OM_Nuovo_Flusso__c = True;
        insert c2;
        
        String ListRecordTypePassId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = ListRecordTypePassId ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        insert slFiberReq;
        
        EOF_EAI_Service_Log__c slFiberReq1 = new EOF_EAI_Service_Log__c();
        slFiberReq1.eof_tipo_comunicazione_String__c='OLO->SF - ACK - ActivationRequest';        
        slFiberReq1.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq1.RecordTypeId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('FiberNotify').getRecordTypeId();
        slFiberReq1.Caso__c = c2.id; 
        insert slFiberReq1;
        
        String ListRecordTypePassId1 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberNotify').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq2 = new EOF_EAI_Service_Log__c();
        slFiberReq2.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq2.RecordTypeId = ListRecordTypePassId1 ;
        slFiberReq2.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq2.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq2.Caso__c = c2.id;        
        insert slFiberReq2;
        
        String ListRecordTypePassId3 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq3 = new EOF_EAI_Service_Log__c();
        slFiberReq3.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq3.RecordTypeId = ListRecordTypePassId3 ;
        slFiberReq3.OF_SA_Cpe_Log__c = slFiberReq.id;
        slFiberReq3.EOF_Codice_Ordine_OLo__C = 'Test';        
        insert slFiberReq3;
        
        //BusinessHours bh_dac = [SELECT Id FROM BusinessHours WHERE Name='DAC'];
        OF_SA_GE_Utils.caseOriginale = c2;
        OF_SA_GE_Utils.slOLOSF = slFiberReq;
        
        OF_Puntamento_Callout__c pnt= new OF_Puntamento_Callout__c();
        pnt.name='OGW';
        pnt.OF_OGW__c ='OFS-SVIL-WS';
        insert pnt;
        
        OF_Enable_PO_UpdateOppCase_Trigger__c trg = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trg.Name = 'Status';
        trg.OF_Enable_Trigger__c = false;
        insert trg;
        
        Test.starttest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());        
        
        List<Case> caseListNACK =[select Id,EOF_Codice_Ordine_OLO__C,recordtype.developername from Case where OF_Response_Da_OLO__c='NACK TECNICO' OR OF_Response_Da_OM__c='NACK TECNICO' limit 3];
        EOF_SendRetry sh1 = new EOF_SendRetry();      
        String sch = '0  00 1 3 * ?';
        system.schedule('Retry Job 2g', sch, sh1);
        Test.stopTest();
    }
    
    /*
    static testmethod void Method3()
    {
        Map<String,String> RecordTypeMap = RecordType();
        
        Account accOloWIND = new Account();       
        accOloWIND.Name = 'Wind';
        accOloWIND.EOF_Codice_Operatore__c = 'WN';
        accOloWIND.Type = 'OLO';
        accOloWIND.Industry = 'Telecommunications';
        accOloWIND.RecordTYpeId = RecordTypeMap.get('OLO');        
        insert accOloWIND; 
        
        contact con = new contact();
        con.AccountId = accOloWIND.id;
        con.RecordTypeId = RecordTypeMap.get('Referente Tecnico OLO');
        con.FirstName = 'Gianni';
        con.LastName = 'Bugno';
        con.Phone = '333';
        con.Email = 'test@test.it'; 
        insert con;
        
        List<Case> caseToInsert = new List<Case>();
        for(integer i=0;i<27;i++){
            Case c = new Case();
            c.RecordTypeId = RecordTypeMap.get('EOF_Caso_Cessazione_OPENSTREAM');
            c.EOF_Account_OLO__c = accOloWIND.id;
            c.EOF_Contact__c = con.id;
            c.status = 'Ricevuto';
            c.EOF_FASE__C = 'NA';
            c.EOF_Codice_Ordine_OLO__c='Test';
            c.EOF_Codice_Operatore_WS__c ='VF';  
            c.OF_Bonifica_Locked_Row__c = true;
            c.OF_Response_Da_OLO__c='NACK TECNICO';
            caseToInsert.add(c);
        }
        for(integer i=0;i<27;i++){
            Case c2 = new Case();
            c2.RecordTypeId = RecordTypeMap.get('EOF Caso - Attivazione');
            c2.eof_account_OLO__c=accOloWIND.Id;
            c2.EOF_Contact__c = con.id;
            c2.status = 'Ricevuto';
            c2.EOF_FASE__C = 'NA';
            c2.EOF_Codice_Ordine_OLO__c='Test';
            c2.EOF_Codice_Operatore_WS__c ='VF';  
            c2.OF_Bonifica_Locked_Row__c = true;
            c2.OF_Response_Da_OLO__c='NACK TECNICO';
            caseToInsert.add(c2);
        }
        insert caseToInsert;
        
        String ListRecordTypePassId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = ListRecordTypePassId ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq.Caso__c = caseToInsert[0].id;
        insert slFiberReq;
        
        EOF_EAI_Service_Log__c slFiberReq1 = new EOF_EAI_Service_Log__c();
        slFiberReq1.eof_tipo_comunicazione_String__c='OLO->SF - ACK - ActivationRequest';        
        slFiberReq1.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq1.RecordTypeId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('FiberNotify').getRecordTypeId();
        slFiberReq1.Caso__c = caseToInsert[0].id; 
        insert slFiberReq1;
        
        EOF_EAI_Service_Log__c slFiberReq2 = new EOF_EAI_Service_Log__c();
        slFiberReq2.eof_tipo_comunicazione_String__c='OLO->SF - ACK - ActivationRequest';        
        slFiberReq2.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq2.RecordTypeId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('FiberRequest').getRecordTypeId();
        slFiberReq2.Caso__c = caseToInsert[0].id; 
        slFiberReq2.eof_tipo_comunicazione__c='1';
        insert slFiberReq2;
        
        String ListRecordTypePassId1 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberNotify').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq3 = new EOF_EAI_Service_Log__c();
        slFiberReq3.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq3.RecordTypeId = ListRecordTypePassId1 ;
        slFiberReq3.EOF_Codice_Ordine_OLo__C = 'Test';
        slFiberReq3.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq3.Caso__c = caseToInsert[0].id;        
        insert slFiberReq3;
        
        String ListRecordTypePassId3 = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - Cpe').getRecordTypeId();
        EOF_EAI_Service_Log__c slFiberReq4 = new EOF_EAI_Service_Log__c();
        slFiberReq4.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq4.RecordTypeId = ListRecordTypePassId3 ;
        slFiberReq4.OF_SA_Cpe_Log__c = slFiberReq.id;
        slFiberReq4.EOF_Codice_Ordine_OLo__C = 'Test';        
        insert slFiberReq4;
        
        //BusinessHours bh_dac = [SELECT Id FROM BusinessHours WHERE Name='DAC'];
        OF_SA_GE_Utils.caseOriginale = caseToInsert[0];
        OF_SA_GE_Utils.slOLOSF = slFiberReq;
        
        OF_Puntamento_Callout__c pnt= new OF_Puntamento_Callout__c();
        pnt.name='OGW';
        pnt.OF_OGW__c ='OFS-SVIL-WS';
        insert pnt;
        
        OF_Enable_PO_UpdateOppCase_Trigger__c trg = new OF_Enable_PO_UpdateOppCase_Trigger__c();
        trg.Name = 'Status';
        trg.OF_Enable_Trigger__c = false;
        insert trg;
        
        Test.starttest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());        
       
        List<Case> caseListNACK =[select Id,EOF_Codice_Ordine_OLO__C,recordtype.developername from Case where OF_Response_Da_OLO__c='NACK TECNICO' OR OF_Response_Da_OM__c='NACK TECNICO' limit 3];
        EOF_SendRetry sh1 = new EOF_SendRetry();      
        String sch = '0  00 1 3 * ?';
        system.schedule('Retry Job 2', sch, sh1);
        Test.stopTest();

    } 
    */
     
}