objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OLO</fullName>
        <active>true</active>
        <description>Use this account to store OLO information.</description>
        <label>OLO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Account_OLO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLO</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>OLO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Operatore_WS__c</fullName>
        <label>Codice Operatore</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VF</fullName>
                </value>
                <value>
                    <fullName>WN</fullName>
                </value>
                <value>
                    <fullName>TIS</fullName>
                </value>
                <value>
                    <fullName>GOI</fullName>
                </value>
                <value>
                    <fullName>CNN</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>FAS</fullName>
                </value>
                <value>
                    <fullName>PLA</fullName>
                </value>
                <value>
                    <fullName>CWN</fullName>
                </value>
                <value>
                    <fullName>4IS</fullName>
                </value>
                <value>
                    <fullName>XMA</fullName>
                </value>
                <value>
                    <fullName>WAR</fullName>
                </value>
                <value>
                    <fullName>UND</fullName>
                </value>
                <value>
                    <fullName>SPE</fullName>
                </value>
                <value>
                    <fullName>UMB</fullName>
                </value>
                <value>
                    <fullName>NEX</fullName>
                </value>
                <value>
                    <fullName>NOI</fullName>
                </value>
                <value>
                    <fullName>RAF</fullName>
                </value>
                <value>
                    <fullName>PAN</fullName>
                </value>
                <value>
                    <fullName>SHS</fullName>
                </value>
                <value>
                    <fullName>ALT</fullName>
                </value>
                <value>
                    <fullName>SIR</fullName>
                </value>
                <value>
                    <fullName>HAL</fullName>
                </value>
                <value>
                    <fullName>BRI</fullName>
                </value>
                <value>
                    <fullName>LAW</fullName>
                </value>
                <value>
                    <fullName>ACA</fullName>
                </value>
                <value>
                    <fullName>FST</fullName>
                </value>
                <value>
                    <fullName>INT</fullName>
                </value>
                <value>
                    <fullName>UNC</fullName>
                </value>
                <value>
                    <fullName>SAI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <externalId>true</externalId>
        <label>Codice Ordine OLO</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EOF_Data_Notifica__c</fullName>
        <label>Data Notifica</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Prevista_Attivazione__c</fullName>
        <label>Data Prevista Attivazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EOF_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da lavorare</fullName>
                </value>
                <value>
                    <fullName>Appuntamento Fissato</fullName>
                </value>
                <value>
                    <fullName>Da contattare</fullName>
                </value>
                <value>
                    <fullName>Desospeso</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione</fullName>
                </value>
                <value>
                    <fullName>In Verifica BO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Sospeso BO</fullName>
                </value>
                <value>
                    <fullName>Sospeso Tecn.</fullName>
                </value>
                <value>
                    <fullName>In assegnazione</fullName>
                </value>
                <value>
                    <fullName>Espletato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato KO</fullName>
                </value>
                <value>
                    <fullName>Espletato KO</fullName>
                </value>
                <value>
                    <fullName>Accettato KO</fullName>
                </value>
                <value>
                    <fullName>In Verifica Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Network Creation</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Delivery</fullName>
                </value>
                <value>
                    <fullName>Completato</fullName>
                </value>
                <value>
                    <fullName>Offerta Creata</fullName>
                </value>
                <value>
                    <fullName>Offerta Presentata</fullName>
                </value>
                <value>
                    <fullName>Richiesta modifica offerta da Cliente</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Referente Fattibilità</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Tecnico Fattibilità</fullName>
                </value>
                <value>
                    <fullName>Sospeso OM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_GPON_Attestazione__c</fullName>
        <label>GPON Attestazione</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_GPON_Vincolante__c</fullName>
        <label>GPON Vincolante</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_ID_Building_WS__c</fullName>
        <externalId>true</externalId>
        <label>ID Building</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Id_Notifica__c</fullName>
        <label>Id Notifica</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Identificativo_del_POP__c</fullName>
        <label>Identificativo del POP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EOF_Numero_Civico_WS__c</fullName>
        <label>Numero Civico</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Numero_Telefonico_Principale_Linea__c</fullName>
        <label>Numero Telefonico Principale Linea</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Orario_Appuntamento__c</fullName>
        <label>Orario Appuntamento</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Recapito_Test_Linea__c</fullName>
        <label>Recapito Test Linea</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_SLA_Premium_Assurance__c</fullName>
        <label>SLA Premium Assurance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Telefono_Referente_OLO_Onfield_Notec__c</fullName>
        <label>Telefono Referente OLO Onfield Notech</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipologia_Apparato__c</fullName>
        <label>Tipologia Apparato</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipologia_Servizio__c</fullName>
        <label>Tipologia Servizio</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO_SA_Portale__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portale</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>EOF_CODICE_MOTIVAZIONE__c</fullName>
        <label>Codice Motivazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_COgnome_CLiente__c</fullName>
        <label>Cognome Cliente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_EOF__c</fullName>
        <label>Codice Ordine EOF</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <label>Codice Ordine OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_DATA_PREVISTA_ATTIVAZIONE__c</fullName>
        <label>Data Prevista Attivazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Notifica__c</fullName>
        <label>Data Notifica</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EOF_GPON_Attestazione__c</fullName>
        <label>GPON Attestazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_GPON_VINCOLANTE__c</fullName>
        <label>GPON Vincolante</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Notifica__c</fullName>
        <label>ID Notifica</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_MOTIVAZIONE__c</fullName>
        <label>Motivazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_NUMERO_TELEFONICO_PRINCIPALE_LINEA__c</fullName>
        <label>Numero Telefonico Principale Linea</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Nome_Cliente__c</fullName>
        <label>Nome Cliente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ORARIO_APPUNTAMENTO__c</fullName>
        <label>Orario Appuntamento</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_PIN_INTERVENTO_A_VUOTO__c</fullName>
        <label>Pin Intervento A Vuoto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_RECAPITO_TELEFONICO_CLIENTE__c</fullName>
        <label>Recapito Telefonico Cliente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_RECAPITO_TEST_LINEA__c</fullName>
        <label>Recapito Test Linea</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_SLA_PREMIUM_ASSURANCE__c</fullName>
        <label>Sla Premium Assurance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_STATO_ORDINE__c</fullName>
        <label>Stato Ordine</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_TELEFONO_REFERENTE_OLO_ONFIELD_NOTEC__c</fullName>
        <label>Telefono Referente OLO OnField NoTech</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_TIPOLOGIA_APPARATO__c</fullName>
        <label>Tipologia Apparato</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_TIPOLOGIA_SERVIZIO__c</fullName>
        <label>Tipologia Servizio</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipo_Comunicazione_String__c</fullName>
        <label>Tipo Comunicazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OF_SA_OM_SendToOLOTest.cls
@isTest
global class OF_SA_OM_SendToOLOTest {
    global static TestMethod Void MyUnitTest1(){
    	
    	TestDataFactory.CreateTestRecords(null,null,null);
        
        Test.startTest();
        // --- Account Creation-----
        String oloAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
        Account accOLO = new Account();
        accOLO.Name = 'Vodafone';
        accOLO.EOF_Codice_Operatore__c = 'VF';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = oloAccountRecordTypeId ;
        
        insert accOLO;
        
        //-------Case Creation-------------
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = accOLO.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = 'test12';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Acquisito';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.PO_SA_Portale__C=false;
        insert c; 
        OF_SA_GE_Utils.caseOriginale=c;
        
        EOF_EAI_Service_Log__c eof =  new EOF_EAI_Service_Log__c( );
        eof.EOF_Tipo_Comunicazione_String__C ='SF->OLO - StatusUpdate';
        eof.EOF_CODICE_OPERATORE__c = 'test1';
        eof.EOF_CODICE_ORDINE_OLO__c = 'test1';
        eof.EOF_CODICE_ORDINE_EOF__c = 'test1';
        //  eof.EOF_DATA_NOTIFICA__c = String.valueof(datetime.now());
        eof.EOF_ID_NOTIFICA__c = String.valueof(datetime.now());
        eof.EOF_STATO_ORDINE__c = 'test1';
        eof.EOF_CODICE_MOTIVAZIONE__c = 'test1';
        eof.EOF_MOTIVAZIONE__c = 'test1';
        eof.EOF_GPON_Attestazione__c = 'test1';
        eof.EOF_NOME_CLIENTE__c = 'test1';
        eof.EOF_COGNOME_CLIENTE__c = 'test1';
        eof.EOF_RECAPITO_TELEFONICO_CLIENTE__c = 'test1';
        eof.EOF_DATA_PREVISTA_ATTIVAZIONE__c  = System.Today();
        eof.EOF_ORARIO_APPUNTAMENTO__c = 'test1';
        eof.EOF_PIN_INTERVENTO_A_VUOTO__c = 'test1';
        eof.EOF_NOTE__c = 'test1';
        eof.EOF_NOME_REFERENTE_TECNICO_OLO__c = 'test1';
        eof.EOF_COGNOME_REFERENTE_TECNICO_OLO__c = 'test1';
        eof.EOF_TELEFONO_REFERENTE_TECNICO_OLO__c = 'test1';
        eof.EOF_EMAIL_REFERENTE_TECNICO_OLO__c  = 'test1';
        eof.EOF_TIPO_COMUNICAZIONE__c = 'test1';
        eof.EOF_TELEFONO_REFERENTE_OLO_ONFIELD_NOTEC__c = 'test1';
        eof.EOF_RECAPITO_TELEFONICO_CLIENTE_1__c = 'test1';
        eof.EOF_RECAPITO_TELEFONICO_CLIENTE_2__c = 'test1';
        eof.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c = 'test1';
        eof.EOF_ID_Case_Temp__c = c.Id;
        eof.EOF_CODICE_PROGETTO_SPECIALE__c = 'test1';
        eof.EOF_PROMOZIONE__c = 'test1';
        eof.EOF_CLUSTER_PROMOZIONE__c = 'test1';
        eof.EOF_ID_BUILDING__c = 'test1';
        eof.EOF_SCALA_PALAZZINA__c = 'test1';
        eof.EOF_NUMERO_TELEFONICO_PRINCIPALE_LINEA__c = 'test1';
        eof.EOF_RECAPITO_TEST_LINEA__c = 'test1';
        eof.EOF_ID_POP__c = 'test1';
        eof.EOF_PROFILO__c = 'test1' ; 
        
        EOF_EAI_Service_Log__c eof1 =  new EOF_EAI_Service_Log__c( );
         eof1.EOF_Tipo_Comunicazione_String__C ='CPE';
        eof1.EOF_CODICE_OPERATORE__c = 'test1' ;
        eof1.EOF_CODICE_ORDINE_OLO__c  = 'test1' ;            
        eof1.EOF_CODICE_ORDINE_EOF__c = 'test1' ;
        eof1.EOF_DATA_NOTIFICA__c = System.today();
        eof1.EOF_ID_NOTIFICA__c = String.valueof(datetime.now());
        eof1.EOF_STATO_ORDINE__c = 'test1' ; 
        eof1.EOF_CODICE_MOTIVAZIONE__c = 'test1' ;
        eof1.EOF_MOTIVAZIONE__c = 'test1' ;
        eof1.EOF_NOME_CLIENTE__c = 'test1' ;
        eof1.EOF_COGNOME_CLIENTE__c  = 'test1' ;
        eof1.EOF_RECAPITO_TELEFONICO_CLIENTE__c = 'test1' ;
        eof1.EOF_DATA_PREVISTA_ATTIVAZIONE__c  = System.today();
        eof1.EOF_ORARIO_APPUNTAMENTO__c = 'test1' ; 
        eof1.EOF_PIN_INTERVENTO_A_VUOTO__c = 'test1' ;
        eof1.EOF_NOTE__c = 'test1' ;
        eof1.EOF_NOME_REFERENTE_TECNICO_OLO__c = 'test1' ;
        eof1.EOF_COGNOME_REFERENTE_TECNICO_OLO__c = 'test1' ;
        eof1.EOF_TELEFONO_REFERENTE_TECNICO_OLO__c = 'test1' ;
        eof1.EOF_EMAIL_REFERENTE_TECNICO_OLO__c = 'test1' ;
        eof1.EOF_TELEFONO_REFERENTE_OLO_ONFIELD_NOTEC__c = 'test1' ;
        eof1.EOF_RECAPITO_TELEFONICO_CLIENTE_1__c  = 'test1' ;
        eof1.EOF_RECAPITO_TELEFONICO_CLIENTE_2__c = 'test1' ;
        eof1.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c = 'test1' ;
        eof1.EOF_CODICE_PROGETTO_SPECIALE__c = 'test1' ;
        eof1.EOF_PROMOZIONE__c = 'test1' ;
        eof1.EOF_CLUSTER_PROMOZIONE__c = 'test1' ;
        eof1.EOF_ID_BUILDING__c = 'test1' ;
        eof1.EOF_SCALA_PALAZZINA__c = 'test1' ;
        eof1.EOF_NUMERO_TELEFONICO_PRINCIPALE_LINEA__c = 'test1' ;
        eof1.EOF_RECAPITO_TEST_LINEA__c = 'test1' ;
        eof1.EOF_ID_POP__c = 'test1' ;
        eof1.EOF_PROFILO__c = 'test1' ;
        eof1.EOF_SORGENTE__c = 'test1' ; 
        eof1.EOF_SLA_DATE__c = 'test1' ;
        eof1.EOF_GPON_ATTESTAZIONE__c = 'test1' ;
        eof1.EOF_GPON_VINCOLANTE__c = 'test1' ;
        eof1.EOF_ID_RISORSA__c = 'test1' ;
        eof1.EOF_OPZIONE_SYSTEM_UNICO__c = 'test1' ;
        eof1.EOF_TIPO_COMUNICAZIONE__c = 'test1' ;
        eof1.EOF_COLLEGAMENTO_P2P__c = 'test1' ;
        eof1.EOF_TRACCIATO__c = 'test1' ;
        eof1.EOF_ID_SERVIZIO__c = 'test1' ; 
        eof1.EOF_PROVINCIA__c = 'test1' ; 
        eof1.EOF_COMUNE__c = 'test1' ;
        eof1.EOF_INDIRIZZO__c = 'test1' ;
        eof1.EOF_NUMERO_CIVICO__c = 'test1' ;
        eof1.EOF_PARTICELLA_TOPONOMASTICA__c = 'test1' ;
        eof1.EOF_SLA_PREMIUM_ASSURANCE__c = 'test1' ;
        eof1.EOF_ID_Case_Temp__c = c.Id ;
        eof1.EOF_Tipo_Comunicazione_String__c = 'test1' ;
        //EOF_ID_Case_Temp__c
        
        
        String eofStr;
        String eofStr1;
        try
        {
            insert eof;
            insert eof1;
            eofStr = String.valueOf(eof.Id);
            eofStr1 = String.valueOf(eof1.Id);
            
            List<EOF_EAI_Service_Log__c> eoflst = new List<EOF_EAI_Service_Log__c>();
            eoflst.add(eof);
            
            /**Step1**/
            Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());
            OF_SA_OM_SendToOLO.OM_CreateAckNackNotifyStatusUpdate( eof);
            
            eof1.EOF_Tipo_Comunicazione_String__c = 'SF->OM - Deactivation' ;
            update eof1;
            String eofStr01 = String.valueOf(eof1.Id);
            OF_SA_OM_SendToOLO.OM_CreateAckNackNotifyStatusUpdate( eof1 );
                      
          Test.stopTest();

            
        }
        catch(exception e){
            system.debug('error message----->'+e.getStackTraceString());
        }  
    }
    global static TestMethod Void MyUnitTest2()
    {
        TestDataFactory.CreateTestRecords(null,null,null);
        // --- Account Creation-----
        String oloAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
        Account accOLO = new Account();
        accOLO.Name = 'Vodafone';
        accOLO.EOF_Codice_Operatore__c = 'VF';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = oloAccountRecordTypeId ;
        
        insert accOLO;
        
        //-------Case Creation-------------
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = accOLO.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = 'test12';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Acquisito';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.PO_SA_Portale__C=false;
        insert c;
        OF_SA_GE_Utils.caseOriginale=c;
        
         EOF_EAI_Service_Log__c eof =  new EOF_EAI_Service_Log__c( );
        eof.EOF_Tipo_Comunicazione_String__C ='SF->OLO - StatusUpdate';
        eof.EOF_CODICE_OPERATORE__c = 'test1';
        eof.EOF_CODICE_ORDINE_OLO__c = 'test1';
        eof.EOF_CODICE_ORDINE_EOF__c = 'test1';
        //  eof.EOF_DATA_NOTIFICA__c = String.valueof(datetime.now());
        eof.EOF_ID_NOTIFICA__c = String.valueof(datetime.now());
        eof.EOF_STATO_ORDINE__c = 'test1';
        eof.EOF_CODICE_MOTIVAZIONE__c = 'test1';
        eof.EOF_MOTIVAZIONE__c = 'test1';
        eof.EOF_GPON_Attestazione__c = 'test1';
        eof.EOF_NOME_CLIENTE__c = 'test1';
        eof.EOF_COGNOME_CLIENTE__c = 'test1';
        eof.EOF_RECAPITO_TELEFONICO_CLIENTE__c = 'test1';
        eof.EOF_DATA_PREVISTA_ATTIVAZIONE__c  = System.Today();
        eof.EOF_ORARIO_APPUNTAMENTO__c = 'test1';
        eof.EOF_PIN_INTERVENTO_A_VUOTO__c = 'test1';
        eof.EOF_NOTE__c = 'test1';
        eof.EOF_NOME_REFERENTE_TECNICO_OLO__c = 'test1';
        eof.EOF_COGNOME_REFERENTE_TECNICO_OLO__c = 'test1';
        eof.EOF_TELEFONO_REFERENTE_TECNICO_OLO__c = 'test1';
        eof.EOF_EMAIL_REFERENTE_TECNICO_OLO__c  = 'test1';
        eof.EOF_TIPO_COMUNICAZIONE__c = 'test1';
        eof.EOF_TELEFONO_REFERENTE_OLO_ONFIELD_NOTEC__c = 'test1';
        eof.EOF_RECAPITO_TELEFONICO_CLIENTE_1__c = 'test1';
        eof.EOF_RECAPITO_TELEFONICO_CLIENTE_2__c = 'test1';
        eof.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c = 'test1';
        eof.EOF_ID_Case_Temp__c = c.Id;
        eof.EOF_CODICE_PROGETTO_SPECIALE__c = 'test1';
        eof.EOF_PROMOZIONE__c = 'test1';
        eof.EOF_CLUSTER_PROMOZIONE__c = 'test1';
        eof.EOF_ID_BUILDING__c = 'test1';
        eof.EOF_SCALA_PALAZZINA__c = 'test1';
        eof.EOF_NUMERO_TELEFONICO_PRINCIPALE_LINEA__c = 'test1';
        eof.EOF_RECAPITO_TEST_LINEA__c = 'test1';
        eof.EOF_ID_POP__c = 'test1';
        eof.EOF_PROFILO__c = 'test1' ;
        
        EOF_EAI_Service_Log__c eof1 =  new EOF_EAI_Service_Log__c( );
        eof1.EOF_Tipo_Comunicazione_String__C ='CPE';
        eof1.EOF_CODICE_OPERATORE__c = 'test1' ;
        eof1.EOF_CODICE_ORDINE_OLO__c  = 'test1' ;            
        eof1.EOF_CODICE_ORDINE_EOF__c = 'test1' ;
        eof1.EOF_DATA_NOTIFICA__c = System.today();
        eof1.EOF_ID_NOTIFICA__c = String.valueof(datetime.now());
        eof1.EOF_STATO_ORDINE__c = 'test1' ; 
        eof1.EOF_CODICE_MOTIVAZIONE__c = 'test1' ;
        eof1.EOF_MOTIVAZIONE__c = 'test1' ;
        eof1.EOF_NOME_CLIENTE__c = 'test1' ;
        eof1.EOF_COGNOME_CLIENTE__c  = 'test1' ;
        eof1.EOF_RECAPITO_TELEFONICO_CLIENTE__c = 'test1' ;
        eof1.EOF_DATA_PREVISTA_ATTIVAZIONE__c  = System.today();
        eof1.EOF_ORARIO_APPUNTAMENTO__c = 'test1' ; 
        eof1.EOF_PIN_INTERVENTO_A_VUOTO__c = 'test1' ;
        eof1.EOF_NOTE__c = 'test1' ;
        eof1.EOF_NOME_REFERENTE_TECNICO_OLO__c = 'test1' ;
        eof1.EOF_COGNOME_REFERENTE_TECNICO_OLO__c = 'test1' ;
        eof1.EOF_TELEFONO_REFERENTE_TECNICO_OLO__c = 'test1' ;
        eof1.EOF_EMAIL_REFERENTE_TECNICO_OLO__c = 'test1' ;
        eof1.EOF_TELEFONO_REFERENTE_OLO_ONFIELD_NOTEC__c = 'test1' ;
        eof1.EOF_RECAPITO_TELEFONICO_CLIENTE_1__c  = 'test1' ;
        eof1.EOF_RECAPITO_TELEFONICO_CLIENTE_2__c = 'test1' ;
        eof1.EOF_INFORMAZIONI_LOGISTICA_APPARATI__c = 'test1' ;
        eof1.EOF_CODICE_PROGETTO_SPECIALE__c = 'test1' ;
        eof1.EOF_PROMOZIONE__c = 'test1' ;
        eof1.EOF_CLUSTER_PROMOZIONE__c = 'test1' ;
        eof1.EOF_ID_BUILDING__c = 'test1' ;
        eof1.EOF_SCALA_PALAZZINA__c = 'test1' ;
        eof1.EOF_NUMERO_TELEFONICO_PRINCIPALE_LINEA__c = 'test1' ;
        eof1.EOF_RECAPITO_TEST_LINEA__c = 'test1' ;
        eof1.EOF_ID_POP__c = 'test1' ;
        eof1.EOF_PROFILO__c = 'test1' ;
        eof1.EOF_SORGENTE__c = 'test1' ; 
        eof1.EOF_SLA_DATE__c = 'test1' ;
        eof1.EOF_GPON_ATTESTAZIONE__c = 'test1' ;
        eof1.EOF_GPON_VINCOLANTE__c = 'test1' ;
        eof1.EOF_ID_RISORSA__c = 'test1' ;
        eof1.EOF_OPZIONE_SYSTEM_UNICO__c = 'test1' ;
        eof1.EOF_TIPO_COMUNICAZIONE__c = 'test1' ;
        eof1.EOF_COLLEGAMENTO_P2P__c = 'test1' ;
        eof1.EOF_TRACCIATO__c = 'test1' ;
        eof1.EOF_ID_SERVIZIO__c = 'test1' ; 
        eof1.EOF_PROVINCIA__c = 'test1' ; 
        eof1.EOF_COMUNE__c = 'test1' ;
        eof1.EOF_INDIRIZZO__c = 'test1' ;
        eof1.EOF_NUMERO_CIVICO__c = 'test1' ;
        eof1.EOF_PARTICELLA_TOPONOMASTICA__c = 'test1' ;
        eof1.EOF_SLA_PREMIUM_ASSURANCE__c = 'test1' ;
        eof1.EOF_ID_Case_Temp__c = c.Id ;
        eof1.EOF_Tipo_Comunicazione_String__c = 'SF->OM - Deactivation' ;
        
        insert eof;
        insert eof1;
        
        String eofStr = String.valueOf(eof.Id);
        String eofStr1 = String.valueOf(eof1.Id);
        OF_SA_GE_Utils.slSFOLO=eof;
		Test.startTest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupNACK());
        OF_SA_OM_SendToOLO.OM_CreateAckNackNotifyStatusUpdate( eof);
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());
        OF_SA_OM_SendToOLO.OM_CreateAckNackNotifyStatusUpdate( eof);
        Test.stopTest();
       
    }
    
    global static TestMethod Void MyUnitTest3()
    {
    	TestDataFactory.CreateTestRecords(null,null,null);
      // --- Account Creation-----
        String oloAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
        Account accOLO = new Account();
        accOLO.Name = 'Vodafone';
        accOLO.EOF_Codice_Operatore__c = 'VF';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = oloAccountRecordTypeId ;
        
        insert accOLO;
        
        //-------Case Creation-------------
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = accOLO.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = 'test12';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Acquisito';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.PO_SA_Portale__C=false;
        insert c;
        OF_SA_GE_Utils.caseOriginale=c;
        
        OF_SA_WS_IN_OM_StatusUpdate.OM_Notify_StatusUpdate var = new OF_SA_WS_IN_OM_StatusUpdate.OM_Notify_StatusUpdate();
        var.CODICE_OPERATORE='TIS';
        var.CODICE_ORDINE_OLO='1234';
        var.CODICE_ORDINE_OF='12';
        var.DATA_NOTIFICA=String.valueOf(system.now());
        var.ID_NOTIFICA='test';
        var.STATO_ORDINE='test';
        var.CODICE_MOTIVAZIONE='test';
        var.MOTIVAZIONE='test';
        var.GPON_DI_ATTESTAZIONE='test';
        var.NOME_CLIENTE='test';
        var.COGNOME_CLIENTE='test';
        var.RECAPITO_TELEFONICO_CLIENTE='test';
        var.DATA_PREVISTA_ATTIVAZIONE=String.valueOf(system.now());
        var.ORARIO_APPUNTAMENTO='18:00:00';
        var.PIN_INTERVENTO_A_VUOTO='test';
        var.NOTE='test';
        var.APPARATO = new List<OF_SA_WS_IN_OM_StatusUpdate.APPARATO>();
        var.VLAN = new List<OF_SA_WS_IN_OM_StatusUpdate.VLAN>(); 
        
        Test.startTest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());        
        OF_SA_OM_SendToOLO.OM_CreateAckNackStatusUpdateDaOM( c , var );
        Test.stopTest();
    }

    global static TestMethod Void MyUnitTest4()
    {
    	TestDataFactory.CreateTestRecords(null,null,null);
      // --- Account Creation-----
        String oloAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
        Account accOLO = new Account();
        accOLO.Name = 'Vodafone';
        accOLO.EOF_Codice_Operatore__c = 'VF';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = oloAccountRecordTypeId ;
        
        insert accOLO;
        
        //-------Case Creation-------------
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = accOLO.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = 'test12';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Acquisito';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.PO_SA_Portale__C=false;
        insert c;
        OF_SA_GE_Utils.caseOriginale=c;
        
        OF_SA_WS_IN_OM_StatusUpdate.OM_Notify_StatusUpdate var = new OF_SA_WS_IN_OM_StatusUpdate.OM_Notify_StatusUpdate();
        var.CODICE_OPERATORE='TIS';
        var.CODICE_ORDINE_OLO='1234';
        var.CODICE_ORDINE_OF='12';
        var.DATA_NOTIFICA=String.valueOf(system.now());
        var.ID_NOTIFICA='test';
        var.STATO_ORDINE='test';
        var.CODICE_MOTIVAZIONE='test';
        var.MOTIVAZIONE='test';
        var.GPON_DI_ATTESTAZIONE='test';
        var.NOME_CLIENTE='test';
        var.COGNOME_CLIENTE='test';
        var.RECAPITO_TELEFONICO_CLIENTE='test';
        var.DATA_PREVISTA_ATTIVAZIONE=String.valueOf(system.now());
        var.ORARIO_APPUNTAMENTO='18:00:00';
        var.PIN_INTERVENTO_A_VUOTO='test';
        var.NOTE='test';
        var.APPARATO = new List<OF_SA_WS_IN_OM_StatusUpdate.APPARATO>();
        var.VLAN = new List<OF_SA_WS_IN_OM_StatusUpdate.VLAN>(); 
        
        Test.startTest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupNACK());        
        OF_SA_OM_SendToOLO.OM_CreateAckNackStatusUpdateDaOM( c , var );
        Test.stopTest();
    }
    
    global static TestMethod Void MyUnitTest5()
    {
    	TestDataFactory.CreateTestRecords(null,null,null);
      // --- Account Creation-----
        String oloAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
        Account accOLO = new Account();
        accOLO.Name = 'Vodafone';
        accOLO.EOF_Codice_Operatore__c = 'VF';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = oloAccountRecordTypeId ;
        
        insert accOLO;
        
        //-------Case Creation-------------
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = accOLO.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = 'test12';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Acquisito';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.PO_SA_Portale__C=false;
        insert c;
        OF_SA_GE_Utils.caseOriginale=c;
        
        OF_SA_WS_IN_OM_Reschedule.OM_Notify_Reschedule var = new OF_SA_WS_IN_OM_Reschedule.OM_Notify_Reschedule();
        var.CODICE_OPERATORE='TIS';
        var.CODICE_ORDINE_OLO='1234';
        var.CODICE_ORDINE_OF='12';
        var.DATA_NOTIFICA=String.valueOf(system.now());
        var.ID_NOTIFICA='test';
        var.CODICE_MOTIVAZIONE='test';
        var.MOTIVAZIONE='test';
        var.NOME_CLIENTE='test';
        var.COGNOME_CLIENTE='test';
        var.DATA_PREVISTA_ATTIVAZIONE=String.valueOf(system.now());
        var.ORARIO_APPUNTAMENTO='18:00:00';
        var.NOTE='test';
        
        Test.startTest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());        
        OF_SA_OM_SendToOLO.OM_CreateAckNackReschedule( c , var );
        Test.stopTest();
    }
    global static TestMethod Void MyUnitTest6()
    {
    	TestDataFactory.CreateTestRecords(null,null,null);
      // --- Account Creation-----
        String oloAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
        Account accOLO = new Account();
        accOLO.Name = 'Vodafone';
        accOLO.EOF_Codice_Operatore__c = 'VF';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = oloAccountRecordTypeId ;
        
        insert accOLO;
        
        //-------Case Creation-------------
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = accOLO.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = 'test12';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Acquisito';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.PO_SA_Portale__C=false;
        insert c;
        OF_SA_GE_Utils.caseOriginale=c;
        
        OF_SA_WS_IN_OM_Reschedule.OM_Notify_Reschedule var = new OF_SA_WS_IN_OM_Reschedule.OM_Notify_Reschedule();
        var.CODICE_OPERATORE='TIS';
        var.CODICE_ORDINE_OLO='1234';
        var.CODICE_ORDINE_OF='12';
        var.DATA_NOTIFICA=String.valueOf(system.now());
        var.ID_NOTIFICA='test';
        var.CODICE_MOTIVAZIONE='test';
        var.MOTIVAZIONE='test';
        var.NOME_CLIENTE='test';
        var.COGNOME_CLIENTE='test';
        var.DATA_PREVISTA_ATTIVAZIONE=String.valueOf(system.now());
        var.ORARIO_APPUNTAMENTO='18:00:00';
        var.NOTE='test';

        Test.startTest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupNACK());        
        OF_SA_OM_SendToOLO.OM_CreateAckNackReschedule( c , var );
        Test.stopTest();
    }
    global static TestMethod Void MyUnitTest7()
    {
    	TestDataFactory.CreateTestRecords(null,null,null);
      // --- Account Creation-----
        String oloAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
        Account accOLO = new Account();
        accOLO.Name = 'Vodafone';
        accOLO.EOF_Codice_Operatore__c = 'VF';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = oloAccountRecordTypeId ;
        
        insert accOLO;
        
        //-------Case Creation-------------
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = accOLO.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = 'test12';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Acquisito';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.PO_SA_Portale__C=false;
        insert c;
        OF_SA_GE_Utils.caseOriginale=c;
        
        OF_SA_WS_IN_OM_CompletionOrder.OM_Notify_CompletionOrder var = new OF_SA_WS_IN_OM_CompletionOrder.OM_Notify_CompletionOrder();
        var.CODICE_OPERATORE='TIS';
        var.CODICE_ORDINE_OLO='1234';
        var.CODICE_ORDINE_OF='12';
        var.DATA_NOTIFICA=String.valueOf(system.now());
        var.ID_NOTIFICA='test';
        var.CODICE_MOTIVAZIONE='test';
        var.MOTIVAZIONE='test';
       
        var.NOTE='test';
        
        Test.startTest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());        
        OF_SA_OM_SendToOLO.OM_CreateAckNackCompletionOrder( c , var );
        Test.stopTest();
    }
    global static TestMethod Void MyUnitTest8()
    {
    	TestDataFactory.CreateTestRecords(null,null,null);
      // --- Account Creation-----
        String oloAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('OLO').getRecordTypeId();
        Account accOLO = new Account();
        accOLO.Name = 'Vodafone';
        accOLO.EOF_Codice_Operatore__c = 'VF';
        accOLO.Type = 'OLO';
        accOLO.Industry = 'Telecommunications';
        accOLO.RecordTYpeId = oloAccountRecordTypeId ;
        
        insert accOLO;
        
        //-------Case Creation-------------
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = accOLO.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = 'test12';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Acquisito';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.PO_SA_Portale__C=false;
        insert c;
        OF_SA_GE_Utils.caseOriginale=c;
        
        OF_SA_WS_IN_OM_CompletionOrder.OM_Notify_CompletionOrder var = new OF_SA_WS_IN_OM_CompletionOrder.OM_Notify_CompletionOrder();
        var.CODICE_OPERATORE='TIS';
        var.CODICE_ORDINE_OLO='1234';
        var.CODICE_ORDINE_OF='12';
        var.DATA_NOTIFICA=String.valueOf(system.now());
        var.ID_NOTIFICA='test';
        var.CODICE_MOTIVAZIONE='test';
        var.MOTIVAZIONE='test';
        
        var.NOTE='test';

        Test.startTest();
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupNACK());        
        OF_SA_OM_SendToOLO.OM_CreateAckNackCompletionOrder( c , var );
        Test.stopTest();
    }
    
	/*public static testMethod void CodeCoverage(){
    	test.starttest();
		OF_SA_OM_SendToOLO.CodeCoverage(2);
		test.stoptest();
    }*/
    
}