objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OLO</fullName>
        <active>true</active>
        <description>Use this account to store OLO information.</description>
        <label>OLO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>EOF_ID_Risorsa__c</fullName>
        <label>ID Risorsa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Identificativo_del_POP__c</fullName>
        <formula>Network_Inventory__r.EOF_Pop__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Identificativo del POP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ProfiloOpenStream__c</fullName>
        <label>Profilo Open Stream</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Risorsa</fullName>
        <active>true</active>
        <label>Risorsa</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Codice_Ordine_EOF__c</fullName>
        <formula>if(AND(NOT(EOF_Order_Manager__c),OR( RecordType.DeveloperName = &apos;EOF Caso - Attivazione&apos;,RecordType.DeveloperName = &apos;EOF Caso - Cessazione&apos;)),  Id, CASESAFEID(Id))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Codice Ordine EOF</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Account_OLO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLO</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>OLO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Operatore_WS__c</fullName>
        <label>Codice Operatore</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VF</fullName>
                </value>
                <value>
                    <fullName>WN</fullName>
                </value>
                <value>
                    <fullName>TIS</fullName>
                </value>
                <value>
                    <fullName>GOI</fullName>
                </value>
                <value>
                    <fullName>CNN</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>FAS</fullName>
                </value>
                <value>
                    <fullName>PLA</fullName>
                </value>
                <value>
                    <fullName>CWN</fullName>
                </value>
                <value>
                    <fullName>4IS</fullName>
                </value>
                <value>
                    <fullName>XMA</fullName>
                </value>
                <value>
                    <fullName>WAR</fullName>
                </value>
                <value>
                    <fullName>UND</fullName>
                </value>
                <value>
                    <fullName>SPE</fullName>
                </value>
                <value>
                    <fullName>UMB</fullName>
                </value>
                <value>
                    <fullName>NEX</fullName>
                </value>
                <value>
                    <fullName>NOI</fullName>
                </value>
                <value>
                    <fullName>RAF</fullName>
                </value>
                <value>
                    <fullName>PAN</fullName>
                </value>
                <value>
                    <fullName>SHS</fullName>
                </value>
                <value>
                    <fullName>ALT</fullName>
                </value>
                <value>
                    <fullName>SIR</fullName>
                </value>
                <value>
                    <fullName>HAL</fullName>
                </value>
                <value>
                    <fullName>BRI</fullName>
                </value>
                <value>
                    <fullName>LAW</fullName>
                </value>
                <value>
                    <fullName>ACA</fullName>
                </value>
                <value>
                    <fullName>FST</fullName>
                </value>
                <value>
                    <fullName>INT</fullName>
                </value>
                <value>
                    <fullName>UNC</fullName>
                </value>
                <value>
                    <fullName>SAI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <externalId>true</externalId>
        <label>Codice Ordine OLO</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EOF_Data_Notifica__c</fullName>
        <label>Data Notifica</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Prevista_Attivazione__c</fullName>
        <label>Data Prevista Attivazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EOF_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da lavorare</fullName>
                </value>
                <value>
                    <fullName>Appuntamento Fissato</fullName>
                </value>
                <value>
                    <fullName>Da contattare</fullName>
                </value>
                <value>
                    <fullName>Desospeso</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione</fullName>
                </value>
                <value>
                    <fullName>In Verifica BO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Sospeso BO</fullName>
                </value>
                <value>
                    <fullName>Sospeso Tecn.</fullName>
                </value>
                <value>
                    <fullName>In assegnazione</fullName>
                </value>
                <value>
                    <fullName>Espletato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato KO</fullName>
                </value>
                <value>
                    <fullName>Espletato KO</fullName>
                </value>
                <value>
                    <fullName>Accettato KO</fullName>
                </value>
                <value>
                    <fullName>In Verifica Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Network Creation</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Delivery</fullName>
                </value>
                <value>
                    <fullName>Completato</fullName>
                </value>
                <value>
                    <fullName>Offerta Creata</fullName>
                </value>
                <value>
                    <fullName>Offerta Presentata</fullName>
                </value>
                <value>
                    <fullName>Richiesta modifica offerta da Cliente</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Referente Fattibilità</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Tecnico Fattibilità</fullName>
                </value>
                <value>
                    <fullName>Sospeso OM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_GPON_Vincolante__c</fullName>
        <label>GPON Vincolante</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_ID_Building_WS__c</fullName>
        <externalId>true</externalId>
        <label>ID Building</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Id_Notifica__c</fullName>
        <label>Id Notifica</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Id_Risorsa__c</fullName>
        <label>Id Risorsa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Identificativo_del_POP__c</fullName>
        <label>Identificativo del POP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OF_Bonifica_Locked_Row__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bonifica Locked Row</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_SA_CODICE_PROGETTO_SPECIALE__c</fullName>
        <label>Codice Progetto Speciale</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Cluster_Promozione__c</fullName>
        <label>Cluster Promozione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_ID_Servizio__c</fullName>
        <label>ID Servizio</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Motivazione__c</fullName>
        <label>Motivazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Profilo__c</fullName>
        <label>Profilo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Promozione__c</fullName>
        <label>Promozione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_SA_Portale__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portale</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <label>Codice Ordine OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_DATA_PREVISTA_ATTIVAZIONE__c</fullName>
        <label>Data Prevista Attivazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Notifica__c</fullName>
        <label>Data Notifica</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EOF_GPON_VINCOLANTE__c</fullName>
        <label>GPON Vincolante</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Notifica__c</fullName>
        <label>ID Notifica</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Risorsa__c</fullName>
        <label>ID Risorsa</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_NOTE__c</fullName>
        <label>Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OLO_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_Olo_Id__c</fullName>
        <label>Olo Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>OLO ID</label>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>OF_ProfiloOpenStream__c</fullName>
        <label>Profilo Open Stream</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OF_CO_OLO_AsyncChecks.cls
public class OF_CO_OLO_AsyncChecks {     
    
    //PG - 21-05 - Controlli asincroni Change Order
    @future(callout=true)  
    public static void OLO_AsyncChangeOrder(String caseId, String idserviceLog){   
        EOF_EAI_Service_Log__C sl_log;
        OF_CO_GE_Utils.slSFOLO = sl_log;
        System.debug('START - CHECK ASINCRONI');
        Case c = [Select Id, PO_SA_Portale__c, CaseNumber, Status, EOF_ID_Risorsa__c,Codice_ordine_Eof__c, EOF_Account_OLO__c,
                EOF_Codice_Ordine_Olo__c,EOF_Codice_Operatore_WS__c,EOF_Data_Prevista_Attivazione__c,
                EOF_Data_Notifica__c, EOF_Id_Notifica__c,recordtype.developername, 
                EOF_Identificativo_del_POP__c,EOF_ID_Building_WS__c,EOF_FASE__c,
                EOF_GPON_Vincolante__c,OF_SA_Motivazione__c,OF_SA_CODICE_PROGETTO_SPECIALE__c, OF_SA_Promozione__c, 
                OF_SA_Cluster_Promozione__c, EOF_Note__c, OF_SA_Profilo__c ,OF_Bonifica_Locked_Row__c
                from Case 
                where id=:caseId];

        OF_CO_GE_Utils.caseOriginale = c;
        OLO_ID__c oloId = OLO_ID__c.getInstance(OF_CO_GE_Utils.caseOriginale.EOF_Codice_Operatore_WS__c);
        OF_CO_GE_Utils.caseOriginale.EOF_Account_OLO__c = oloId.OF_Olo_Id__c;              
        System.debug('***Eccomi***');
        //Verificare l'asset
        List<Asset> assetList = [select Id, name, status, Account.EOF_Codice_Operatore__c, 
                                OF_ProfiloOpenStream__c,EOF_Id_Risorsa__c
                                from Asset                               
                                where recordtype.name = 'Open Stream'
                                and Account.EOF_Codice_Operatore__c=:c.EOF_Codice_Operatore_WS__c
                                and Name=:c.EOF_ID_Risorsa__c];
        System.debug('çççç__Vediamo__çççç');
        //Verificare se sia presente una richiesta di cessazione in corso
        /*List<Case> listCaseCessazione = [Select id, recordtypeId, recordtype.name, status, asset.name
                                         from Case
                                         where recordtype.name = 'EOF_Caso_Cessazione_OPENSTREAM'
                                         and asset.name =:c.EOF_Id_Risorsa__c];
        */

        List<Case> listCase = [Select id, recordtypeId, recordtype.name, status, asset.name, OF_SA_ID_Servizio__c
                                         from Case
                                         where ( (recordtype.name = 'EOF_Caso_Cessazione_OPENSTREAM' and status = 'Acquisito') OR (recordtype.name = 'EOF_Caso_Attivazione_OPENSTREAM' and status='Espletato'))
                                         and asset.name =:c.EOF_Id_Risorsa__c];

        /*List<OF_CommercialElementIstanziato__c> listVLAN = [Select id, name, OF_Case__c, OF_KITCONSEGNAVLAN__C,
                                                            OF_USERVLAN__C, OF_SERVICEVLAN__C, 
                                                            OF_PROFILOVLAN__C, OF_CUSTOMERVLAN__C, OF_MODELLODISERVIZIOVLAN__C,
                                                            OF_INFORMAZIONIVLAN__C  
                                                            from OF_CommercialElementIstanziato__c                                                           
                                                            where RecordType.DeveloperName = 'OF_VLAN'
                                                            and OF_Case__c =: c.id];*/
        //AA: Recupero la lista di sLog rappresentativi delle VLAN
        System.debug('---Prima di sLogList---');
        List<EOF_EAI_Service_Log__c> sLogList = [SELECT OF_SA_KIT_CONSEGNA_VLAN__c, OF_SA_USER_VLAN__C, OF_SA_SERVICE_VLAN__C, OF_SA_PROFILO_VLAN__c, OF_SA_CUSTOMER_VLAN__c, OF_SA_MODELLO_DI_SERVIZIO_VLAN__c, OF_SA_INFORMAZIONI_VLAN__c
                                                 FROM EOF_EAI_Service_Log__c
                                                 WHERE OF_SA_VLan_Log__c = :idserviceLog];
        System.debug('°°°Prima della chiamata di generateVLAN°°°: '+slogList.size());
        //Done AA: POPOLARE LISTA VLAN con il metodo creato
        
        List<OF_CommercialElementIstanziato__c> listVLAN = OF_CO_OLO_AsyncChecks.generateVLANbysLog(sLogList, caseId);
        System.debug('°°°Dopo la chiamata di generateVLAN°°°');
        List<EOF_EAI_Service_Log__c> list_serviceLogs = [Select id, EOF_PROFILO__c, EOF_ID_Notifica__c
                                                         from EOF_EAI_Service_Log__c
                                                         where id =: idserviceLog];

        System.debug(']]]]list_serviceLogs: '+list_serviceLogs.size());

        // CONTROLLI ASINCRONI CON ESITO KO
        //se la lista è vuota (asset non presente)
        if(assetList.isEmpty())
        {
            c.OF_SA_Motivazione__c = 'ID Risorsa da modificare inesistente/errato';
            c.EOF_Causale_Errore__c = 'ID Risorsa da modificare inesistente/errato';
            c.OF_SA_Codice_Motivazione__c = 'D13';
            c.EOF_Codice_Errore__c = 'D13'; 
            System.debug(c.OF_SA_Motivazione__c);
            c.status = 'Modificato KO';
            System.debug('ASSET_LIST VUOTA');
            sl_log = OF_CO_GE_Utils.CreateAcquisition_Log(c);
            System.debug('**** AA Service log ASSET LIST VUOTA!! ' + sl_log);
            OF_CO_GE_Utils.makeCalloutOLOOM(sl_log); //effettua la callOut  
            System.debug('**** RESPONSE DA OLO!! ' + c.OF_Response_Da_OLO__c + '\n*****OGGETTO CASE ' + c);
            
        }
        else{ 
        	c.AssetId = assetList.get(0).Id;
        	if(assetList.get(0).status.equalsIgnoreCase('In Modifica')){ //verifico se sia presente una richiesta   
	            c.OF_SA_Motivazione__c = 'Richiesta di modifica già aperta';    
	            c.EOF_Causale_Errore__c = 'Richiesta di modifica già aperta';
	            c.OF_SA_Codice_Motivazione__c = 'D16';
	            c.EOF_Codice_Errore__c = 'D16'; 
	            c.status = 'Modificato KO';                       
	            System.debug('--IN MODIFICA--');                              
	            sl_log = OF_CO_GE_Utils.CreateAcquisition_Log(c);
	            OF_CO_GE_Utils.makeCalloutOLOOM(sl_log); //effettua la callOut  
	            
	        }
	        else if(assetList.get(0).status.equalsIgnoreCase('Cessato')){//verifico se sia un asset cessato
	            c.OF_SA_Motivazione__c = 'Servizio cessato';   
	            c.EOF_Causale_Errore__c = 'Servizio cessato';
	            c.OF_SA_Codice_Motivazione__c = 'D15';
	            c.EOF_Codice_Errore__c = 'D15'; 
	            c.status = 'Modificato KO';                       
	            System.debug('--IN MODIFICA--');                              
	            sl_log = OF_CO_GE_Utils.CreateAcquisition_Log(c);
	            OF_CO_GE_Utils.makeCalloutOLOOM(sl_log); //effettua la callOut  
	            
	        }
	    }
        if (!c.status.equalsIgnoreCase('Modificato KO')){
            //Popolo la lista di cessazioni
            System.debug('@@@Test');
            List<Case> listCaseCessazione = new List<Case>();
            for (Case cas : [Select id, recordtypeId, recordtype.name, status, asset.name, OF_SA_ID_Servizio__c
                                                from Case
                                                where ( (recordtype.name = 'EOF_Caso_Cessazione_OPENSTREAM' and status = 'Acquisito') OR (recordtype.name = 'EOF_Caso_Attivazione_OPENSTREAM' and status='Espletato'))
                                                and asset.name =:c.EOF_Id_Risorsa__c] ){
                                                 System.debug('@@@cas'+cas.recordtype.name);
                                                    System.debug('@@@cas'+asset.name);
                if (cas.recordtype.name.equalsIgnoreCase('EOF_Caso_Cessazione_OPENSTREAM')){
                    listCaseCessazione.add(cas);
                }else if(cas.recordtype.name.equalsIgnoreCase('EOF_Caso_Attivazione_OPENSTREAM')) {
                    OF_CO_GE_Utils.caseOriginale.OF_SA_ID_Servizio__c = cas.OF_SA_ID_Servizio__c;
                }
            }
            // si verifica se è presente un case di Cessazione
            if( !listCaseCessazione.isEmpty() )
            {
                c.OF_SA_Motivazione__c = 'Presenza di una richiesta di Cessazione';
                c.EOF_Causale_Errore__c = 'Presenza di una richiesta di Cessazione';
                c.OF_SA_Codice_Motivazione__c = 'D16';
                c.EOF_Codice_Errore__c = 'D16';
                c.status = 'Modificato KO';
                System.debug('####Presenza di una richiesta di Cessazione###');
                sl_log = OF_CO_GE_Utils.CreateAcquisition_Log(c);
                OF_CO_GE_Utils.makeCalloutOLOOM(sl_log); //effettua la callOut 
                
            }
            
        }
        System.debug('--------Prima dell\'if della chiamata ad OM----');
        //Controlli asincroni superati
        if (!c.status.equalsIgnoreCase('Modificato KO')){
            //Se i controlli Asincroni vengono superati viene richiamato OM
            System.debug('--------Prima della chiamata ad OM----');
            
            c.status = 'Acquisito'; 
            
            //chiamare webService SF->OM e dopo procedere alla creazione dell'ordine
            String OM_Resp = OF_CO_OLO_SendToOM.OM_CreateAckNackRequestActivation(c, listVLAN);
            
            update c;
            assetList.get(0).status = 'In Modifica'; 
            update assetList.get(0);
            //Done AA : INSERT LISTA VLAN
            insert listVLAN;
        }else{//Se è stato trovato un errore vengono inseriti i log di statusupdate verso OLO e viene aggiornato lo stato del case
            //Done AA : SPOSTARE TUTTE LE INSERT/UPDATE DI MODIFICATO KO E INSERIRE LISTA VLAN
            insert sl_log; //Log che viene inviato da SF-->OLO
            System.debug('**** ASYNC CHECKS REQUEST LOG ' + sl_log);
            OF_CO_GE_Utils.slSFOLOResp.EOF_SL_Riferimento__c = sl_log.Id;
            insert OF_CO_GE_Utils.slSFOLOResp;
            System.debug('**** ASYNC CHECKS RESPONSE LOG ' + OF_CO_GE_Utils.slSFOLOResp);
            
            update c;
            //Done AA : INSERT LISTA VLAN
            insert listVLAN;
        }
    }
    //Done AA : Creare un metodo che dati i sLog, creino la lista di vlan 
    public static List<OF_CommercialElementIstanziato__c> generateVLANbysLog(List<EOF_EAI_Service_Log__c> sLogList, String caseId){
        
        //Lista di VLAN da restituire 
        List<OF_CommercialElementIstanziato__c> ceiList = new List<OF_CommercialElementIstanziato__c>();
        //RECUPERO L'Id del Commercial Element relativo alle VLAN
        Id vlanCEId = [SELECT Id 
                        FROM OF_CommercialElement__c 
                        WHERE OF_Servizio__r.Name='Open Stream' 
                        AND Name='VLAN' LIMIT 1].Id;
        System.debug('Sono qui:'+vlanCEid);
        //('OSCRM OK');
        if(!OF_CO_GE_Utils.checkRTMap){
            //vado a creare la mappa dei recordtype per poi utilizzarla
            OF_CO_GE_Utils.RTMap = new  map<String,String>();

            for(recordtype rt : [select id,developername from recordtype]){
                OF_CO_GE_Utils.RTMap.put(rt.developername,rt.id);
            }
            OF_CO_GE_Utils.checkRTMap=true;
        } 
        System.debug('***Size sLogList***:' +sLogList);
        for (EOF_EAI_Service_Log__C sLog : sLogList){
            //CEI che aggiungerò alla lista da restituire
            OF_CommercialElementIstanziato__c cei = new OF_CommercialElementIstanziato__c();   
                cei.recordtypeid=OF_CO_GE_Utils.rtMap.get('OF_VLAN');
                cei.OF_KITCONSEGNAVLAN__C = sLog.OF_SA_KIT_CONSEGNA_VLAN__c;
                cei.OF_USERVLAN__C = sLog.OF_SA_USER_VLAN__C;
                cei.OF_SERVICEVLAN__C = sLog.OF_SA_SERVICE_VLAN__C;
                cei.OF_PROFILOVLAN__C = sLog.OF_SA_PROFILO_VLAN__c;
                cei.OF_CUSTOMERVLAN__C = sLog.OF_SA_CUSTOMER_VLAN__c;
                cei.OF_MODELLODISERVIZIOVLAN__C = sLog.OF_SA_MODELLO_DI_SERVIZIO_VLAN__c;
                cei.OF_INFORMAZIONIVLAN__C = sLog.OF_SA_INFORMAZIONI_VLAN__c;
                //Lego le VLAN al Case
                cei.OF_Case__c = caseId;
                cei.OF_SA_VLAN__c = caseId;
                //Imposto il CEI di tipologia VLAN
                cei.OF_CommercialElement__c = vlanCEId;
            
            ceiList.add(cei);
        }
        return ceiList;
    }
}