objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Data_Notifica__c</fullName>
        <label>Data Notifica</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EOF_Id_Notifica__c</fullName>
        <label>Id Notifica</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_Cos_Class__c</fullName>
        <label>Cos Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_Cos_Type__c</fullName>
        <label>Cos Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_Cos_remarking__c</fullName>
        <label>Cos_Remarking</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_DHCP_Option82__c</fullName>
        <label>Dhcp Option 82</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_NomeKit__c</fullName>
        <label>Nome KIT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>Banda_Interfaccia__c</fullName>
        <label>Banda</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>EAI Service Logs (Caso)</relationshipLabel>
        <relationshipName>EAI_Service_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Notifica__c</fullName>
        <label>Data Notifica</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Notifica__c</fullName>
        <label>ID Notifica</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Stato_Richiesta__c</fullName>
        <label>Stato Richiesta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipo_Comunicazione_String__c</fullName>
        <label>Tipo Comunicazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nome_del_KIT__c</fullName>
        <label>Nome KIT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POP__c</fullName>
        <label>POP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_ID_Richiesta_testo__c</fullName>
        <label>ID Richiesta testo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_Interfaccia__c</fullName>
        <label>Interfaccia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_POP_raccolta__c</fullName>
        <label>POP di raccolta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_Progressivo_Ordine__c</fullName>
        <label>Progressivo Ordine</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PO_PP_User_VLAN__c</fullName>
        <label>User VLAN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_cos_class__c</fullName>
        <label>Cos Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_cos_remarking__c</fullName>
        <label>Cos Remarking</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_cos_type__c</fullName>
        <label>Cos Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_dhcp_Option82__c</fullName>
        <label>Dhcp Option 82</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Traffico__c</fullName>
        <label>Traffico</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <recordTypes>
        <fullName>OF_PP_VLAN_ActivationRequest</fullName>
        <active>true</active>
        <description>recordtype log di servizio tra OLO e SF e tra SF e OM</description>
        <label>OF - PP - VLAN - ActivationRequest</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Puntamento_Callout__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_OGW__c</fullName>
        <label>OGW</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Puntamento Callout</label>
</CustomObject>

objects/POP__c.object
<CustomObject>
    <label>POP</label>
    <nameField>
        <label>POP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OF_PP_WS_VLAN_OM_Activation_TEST.cls
@isTest
private class OF_PP_WS_VLAN_OM_Activation_TEST { 

    public static EOF_EAI_Service_Log__c richiestaLogCreation()
    {
        EOF_EAI_Service_Log__c richiestaLog = new EOF_EAI_Service_Log__c();
        String rtId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF RichiestaVLAN').getRecordTypeId();
        richiestaLog.recordTypeId = rtId;
        richiestaLog.EOF_Codice_Operatore__c = 'TIS';
        richiestaLog.EOF_Tipo_Comunicazione_String__c = 'Richiesta VLAN';
        return richiestaLog;
    }

    public static EOF_EAI_Service_Log__c vlanLogCreation()
    {
        EOF_EAI_Service_Log__c log = new EOF_EAI_Service_Log__c();
        String rtId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - PP - VLAN - ActivationRequest').getRecordTypeId();
        log.recordTypeId = rtId;
        log.Nome_del_KIT__c = 'TEST_K';
        log.EOF_Codice_Operatore__c = 'TIS';
        log.POP__c = 'pop_c_01';
        log.PO_PP_POP_raccolta__c = 'pop_r_01';  
        log.Traffico__c = 'VULA Openstream Direct';
        log.Banda_Interfaccia__c = '400';
        log.PO_PP_Interfaccia__c = '1 Giga';
        log.EOF_Stato_Richiesta__c = 'Inserita Portale';
        log.PO_PP_Progressivo_Ordine__c = 1;
        log.PO_PP_User_VLAN__c = 'vlan_01';
        log.EOF_ID_NOTIFICA__c = 'A123456';
        log.PO_PP_cos_class__c = 'MonoCOS';
        log.PO_PP_cos_type__c = '5';
        log.PO_PP_cos_remarking__c = 'SI';
        log.PO_PP_dhcp_Option82__c = 'NO';
        log.EOF_DATA_NOTIFICA__c = System.Today();
        return log;
    }
    
    public static Case caseCreation(Account acc)
    {
        Case c = new Case();
        String rTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PO PreProvisioning KITConsegna').getRecordTypeId();
        c.RecordTypeId = rTypeId;
        c.PO_PP_NomeKit__c = 'TEST_K';
        c.accountId = acc.id;
        c.Status = 'Accettato';
        insert c;
        return c;
    }
    
    public static Account tiscaliAccountCreation()
    {
        Account a = new Account();
        a.name = 'Tiscali';
        a.EOF_Codice_Operatore__c = 'TIS';
        insert a;
        return a;
    }
    
    public static EOF_EAI_Service_Log__c cosLogCreation()
    {
        EOF_EAI_Service_Log__c log = new EOF_EAI_Service_Log__c ();
        Id rtId = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - PP - COS').getRecordTypeId();
        log.recordTypeId = rtId;
        log.PO_PP_cos_class__c = 'MonoCOS';
        return log;
    }

	static testmethod void testMethod1()
    {
        OF_Puntamento_Callout__c p = new OF_Puntamento_Callout__c();
        p.Name='OGW';
        p.OF_OGW__c='OFS-SVIL-WS';
        insert p;
        
        String endpoint_x = 'https://OFS-SVIL-WS.ENEL.COM:44300/Business/Services/PreProvisioning/Resource/GW_Activation_PreProvisioning_OpenStream.serviceagent/Activation_PreProvisioning_OpenStreamPortTypeEndpoint0';
        
        String[] ns_map_type_info = new String[]{'http://www.tibco.com/schemas/OLO_Gat_ChangeOrder/SharedResources/CommonSchema/PreProvisioning/Activation_PreProvisioning_OpenStream.xsd2', 'wwwTibcoComSchemasOloGatChangeorde_v2', 'http://xmlns.example.com/1531227217802', 'xmlnsExampleCom1531227217802_v2', 'http://www.tibco.com/schemas/OLO_Gat_ChangeOrder/SharedResources/CommonSchema/PreProvisioning/Esito.xsd3', 'wwwTibcoComSchemasOloGatChangeorde_v2'};
        
        
        RecordType rt = [Select id, name, DeveloperName
                        from RecordType
                        where name = 'OF - PP - VLAN - ActivationRequest'];
        
        
        EOF_EAI_Service_Log__c log = vlanLogCreation();
        //log.recordType = rt;
        EOF_EAI_Service_Log__c richiestaLog = richiestaLogCreation();
        insert richiestaLog;
        log.PO_PP_ID_Richiesta_testo__c = richiestaLog.id;
        
        Account a = tiscaliAccountCreation();
        Case c = caseCreation(a);
        log.caso__c = c.id;
        
        List<EOF_EAI_Service_Log__c> listLogs = new List<EOF_EAI_Service_Log__c>();
        
        listLogs.add(log);
        insert listLogs;
        
        
        Map<String,id> recordTypeMap = new map<String,Id>();
        recordTypeMap.put('OF_PP_VLAN_ActivationRequest',rt.id);
        OF_PP_GE_Utils.rtMap = recordTypeMap;
        OF_PP_GE_Utils.slSFOM = new EOF_EAI_Service_Log__c();
        
        test.startTest();
        
        Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());	
        OF_PP_WS_VLAN_OM_Activation.AsyncActivation_PreProvisioning_OpenStreamPortTypeEndpoint0 actPP = new OF_PP_WS_VLAN_OM_Activation.AsyncActivation_PreProvisioning_OpenStreamPortTypeEndpoint0();

        actPP.Activation_PreProvisioning_OpenStream(listLogs);
        
        test.stopTest();
    }
}