objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OLO</fullName>
        <active>true</active>
        <description>Use this account to store OLO information.</description>
        <label>OLO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Account_OLO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLO</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>OLO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Operatore_WS__c</fullName>
        <label>Codice Operatore</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VF</fullName>
                </value>
                <value>
                    <fullName>WN</fullName>
                </value>
                <value>
                    <fullName>TIS</fullName>
                </value>
                <value>
                    <fullName>GOI</fullName>
                </value>
                <value>
                    <fullName>CNN</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>FAS</fullName>
                </value>
                <value>
                    <fullName>PLA</fullName>
                </value>
                <value>
                    <fullName>CWN</fullName>
                </value>
                <value>
                    <fullName>4IS</fullName>
                </value>
                <value>
                    <fullName>XMA</fullName>
                </value>
                <value>
                    <fullName>WAR</fullName>
                </value>
                <value>
                    <fullName>UND</fullName>
                </value>
                <value>
                    <fullName>SPE</fullName>
                </value>
                <value>
                    <fullName>UMB</fullName>
                </value>
                <value>
                    <fullName>NEX</fullName>
                </value>
                <value>
                    <fullName>NOI</fullName>
                </value>
                <value>
                    <fullName>RAF</fullName>
                </value>
                <value>
                    <fullName>PAN</fullName>
                </value>
                <value>
                    <fullName>SHS</fullName>
                </value>
                <value>
                    <fullName>ALT</fullName>
                </value>
                <value>
                    <fullName>SIR</fullName>
                </value>
                <value>
                    <fullName>HAL</fullName>
                </value>
                <value>
                    <fullName>BRI</fullName>
                </value>
                <value>
                    <fullName>LAW</fullName>
                </value>
                <value>
                    <fullName>ACA</fullName>
                </value>
                <value>
                    <fullName>FST</fullName>
                </value>
                <value>
                    <fullName>INT</fullName>
                </value>
                <value>
                    <fullName>UNC</fullName>
                </value>
                <value>
                    <fullName>SAI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <externalId>true</externalId>
        <label>Codice Ordine OLO</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EOF_Data_Notifica__c</fullName>
        <label>Data Notifica</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Prevista_Attivazione__c</fullName>
        <label>Data Prevista Attivazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EOF_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da lavorare</fullName>
                </value>
                <value>
                    <fullName>Appuntamento Fissato</fullName>
                </value>
                <value>
                    <fullName>Da contattare</fullName>
                </value>
                <value>
                    <fullName>Desospeso</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione</fullName>
                </value>
                <value>
                    <fullName>In Verifica BO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Sospeso BO</fullName>
                </value>
                <value>
                    <fullName>Sospeso Tecn.</fullName>
                </value>
                <value>
                    <fullName>In assegnazione</fullName>
                </value>
                <value>
                    <fullName>Espletato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato KO</fullName>
                </value>
                <value>
                    <fullName>Espletato KO</fullName>
                </value>
                <value>
                    <fullName>Accettato KO</fullName>
                </value>
                <value>
                    <fullName>In Verifica Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Network Creation</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Delivery</fullName>
                </value>
                <value>
                    <fullName>Completato</fullName>
                </value>
                <value>
                    <fullName>Offerta Creata</fullName>
                </value>
                <value>
                    <fullName>Offerta Presentata</fullName>
                </value>
                <value>
                    <fullName>Richiesta modifica offerta da Cliente</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Referente Fattibilità</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Tecnico Fattibilità</fullName>
                </value>
                <value>
                    <fullName>Sospeso OM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_GPON_Vincolante__c</fullName>
        <label>GPON Vincolante</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_ID_Building_WS__c</fullName>
        <externalId>true</externalId>
        <label>ID Building</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Id_Notifica__c</fullName>
        <label>Id Notifica</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Identificativo_del_POP__c</fullName>
        <label>Identificativo del POP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Numero_Civico_WS__c</fullName>
        <label>Numero Civico</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Numero_Telefonico_Principale_Linea__c</fullName>
        <label>Numero Telefonico Principale Linea</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Orario_Appuntamento__c</fullName>
        <label>Orario Appuntamento</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Recapito_Test_Linea__c</fullName>
        <label>Recapito Test Linea</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_SLA_Premium_Assurance__c</fullName>
        <label>SLA Premium Assurance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Telefono_Referente_OLO_Onfield_Notec__c</fullName>
        <label>Telefono Referente OLO Onfield Notech</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipologia_Apparato__c</fullName>
        <label>Tipologia Apparato</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipologia_Servizio__c</fullName>
        <label>Tipologia Servizio</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OF_Bonifica_Locked_Row__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bonifica Locked Row</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <label>Codice Ordine OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_DATA_PREVISTA_ATTIVAZIONE__c</fullName>
        <label>Data Prevista Attivazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EOF_GPON_VINCOLANTE__c</fullName>
        <label>GPON Vincolante</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Notifica__c</fullName>
        <label>ID Notifica</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_NUMERO_TELEFONICO_PRINCIPALE_LINEA__c</fullName>
        <label>Numero Telefonico Principale Linea</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ORARIO_APPUNTAMENTO__c</fullName>
        <label>Orario Appuntamento</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_RECAPITO_TEST_LINEA__c</fullName>
        <label>Recapito Test Linea</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_SLA_PREMIUM_ASSURANCE__c</fullName>
        <label>Sla Premium Assurance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_TELEFONO_REFERENTE_OLO_ONFIELD_NOTEC__c</fullName>
        <label>Telefono Referente OLO OnField NoTech</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_TIPOLOGIA_APPARATO__c</fullName>
        <label>Tipologia Apparato</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_TIPOLOGIA_SERVIZIO__c</fullName>
        <label>Tipologia Servizio</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipo_Comunicazione_String__c</fullName>
        <label>Tipo Comunicazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Direzione_Flusso__c</fullName>
        <label>Direzione Flusso</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <recordTypes>
        <fullName>ACK</fullName>
        <active>true</active>
        <label>ACK</label>
    </recordTypes>
    <recordTypes>
        <fullName>FiberRequest</fullName>
        <active>true</active>
        <label>FiberRequest</label>
    </recordTypes>
    <recordTypes>
        <fullName>NACK</fullName>
        <active>true</active>
        <label>NACK</label>
    </recordTypes>
    <recordTypes>
        <fullName>OF_PP_VLAN_ACK</fullName>
        <active>true</active>
        <label>OF - PP - VLAN - ACK</label>
    </recordTypes>
    <recordTypes>
        <fullName>OF_PP_VLAN_NACK</fullName>
        <active>true</active>
        <label>OF - PP - VLAN - NACK</label>
    </recordTypes>
    <recordTypes>
        <fullName>OF_SA_FiberRequest</fullName>
        <active>true</active>
        <label>OF - SA - FiberRequest</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Enable_PO_UpdateOppCase_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_Enable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Enable PO_UpdateOppCase Trigger</label>
</CustomObject>

objects/OF_Puntamento_Callout__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_OGW__c</fullName>
        <label>OGW</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Puntamento Callout</label>
</CustomObject>

objects/OF_Tibco_userID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Metodo per recuperare lo UserID di Tibco</description>
    <fields>
        <fullName>OF_Tibco_ID__c</fullName>
        <label>Tibco ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Tibco userID</label>
</CustomObject>

classes/OF_PP_OLO_SendToOM_Test1.cls
@isTest
public class OF_PP_OLO_SendToOM_Test1{
@testSetup 
    public static void testSetUpData() {
        Insert new OF_Puntamento_Callout__c(Name = 'OGW',OF_OGW__c = 'Test');
        Insert new OF_Tibco_userID__c(Name = 'Tibco UserID',OF_Tibco_ID__c= 'Test');
        Insert new OF_Enable_PO_UpdateOppCase_Trigger__c(Name = 'Status',OF_Enable_Trigger__c= true);
        
    }
    
    public static testMethod void OM_CreateAckNackRequestActivation_0(){
        
        Account acc = new Account();
        acc.name = 'Test';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'Test';
        con.Email = 'abcd@gmail.com';
        insert con;
        
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = acc.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = '02112016_37';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Accettato';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test1';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.Account = acc;
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.OF_Bonifica_Locked_Row__c = True;
        insert c;
        OF_PP_GE_Utils.caseOriginale = c;
       
        Id EofRecordType = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - PP - VLAN - ACK').getRecordTypeId(); 
        System.debug('@@@EofRecordType'+EofRecordType);
        EOF_EAI_Service_Log__c eof = new EOF_EAI_Service_Log__c();
        eof.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        eof.RecordTypeId = EofRecordType ;
        eof.EOF_Codice_Ordine_OLo__C = 'Test';
        eof.OF_SA_Direzione_Flusso__c='SF-OM';
        eof.EOF_Codice_Operatore__c = 'TIS';
        eof.EOF_Data_Notifica__c = dateTime.now();
        eof.EOF_Stato_Richiesta__c = 'OK';
        eof.EOF_ID_Notifica__c = 'test_01';
        insert eof;
         
        List<EOF_EAI_Service_Log__c>  eofList = new List<EOF_EAI_Service_Log__c>();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = EofRecordType ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq.EOF_Codice_Operatore__c = 'TIS';
        slfiberReq.EOF_Data_Notifica__c = dateTime.now();
        slfiberReq.EOF_Stato_Richiesta__c = 'OK';
        slfiberReq.EOF_ID_Notifica__c = 'test_01';
        slFiberReq.OF_SA_Cpe_Log__c =eof.id;
        eofList.add(slFiberReq);
        insert eofList;
        OF_PP_GE_Utils.slSFOM = slFiberReq;
        map<String,Id> RTMap = new  map<String,Id>();
        rtMap.put('OF_PP_VLAN_ACK',EofRecordType);
        OF_PP_GE_Utils.rtMap = rtMap;
        // Test.startTest();
        // Test.setMock(WebServiceMock.class, new OF_PP_OLO_SendToOM_mock ());
        OF_PP_OLO_SendToOM.OM_CreateAckNackRequestActivation(eofList);
        Test.startTest();
        Test.setMock(WebServiceMock.class, new OF_PP_OLO_SendToOM_mock());
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestStatusUpdate(eof);
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestReschedule(eof);
        Test.stopTest();
    }

    
    public static testMethod void OM_CreateAckNackRequestActivation_1(){
        
        Account acc = new Account();
        acc.name = 'Test';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'Test';
        con.Email = 'abcd@gmail.com';
        insert con;
        
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = acc.Id;
        c.OF_Bonifica_Locked_Row__c = false;
        insert c;
        OF_PP_GE_Utils.caseOriginale = c;
       
        Id EofRecordType = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - PP - VLAN - NACK').getRecordTypeId(); 
        System.debug('@@@EofRecordType'+EofRecordType);
        EOF_EAI_Service_Log__c eof = new EOF_EAI_Service_Log__c();
        eof.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        eof.RecordTypeId = EofRecordType ;
        eof.EOF_Codice_Ordine_OLo__C = 'Test';
        eof.OF_SA_Direzione_Flusso__c='SF-OM';
        eof.EOF_Codice_Operatore__c = 'TIS';
        eof.EOF_Data_Notifica__c = dateTime.now();
        eof.EOF_Stato_Richiesta__c = 'KO';
        eof.EOF_ID_Notifica__c = 'test_01';
        insert eof;
         
        List<EOF_EAI_Service_Log__c>  eofList = new List<EOF_EAI_Service_Log__c>();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = EofRecordType ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq.EOF_Codice_Operatore__c = 'TIS';
        slfiberReq.EOF_Data_Notifica__c = dateTime.now();
        slfiberReq.EOF_Stato_Richiesta__c = 'OK';
        slfiberReq.EOF_ID_Notifica__c = 'test_01';
        slFiberReq.OF_SA_Cpe_Log__c =eof.id;
        eofList.add(slFiberReq);
        insert eofList;
        OF_PP_GE_Utils.slSFOM = slFiberReq;
        map<String,Id> RTMap = new  map<String,Id>();
        rtMap.put('OF_PP_VLAN_NACK',EofRecordType);
        OF_PP_GE_Utils.rtMap = rtMap;
        
        Test.startTest();
        Test.setMock(WebServiceMock.class, new OF_PP_OLO_SendToOM_mock1());
        OF_PP_OLO_SendToOM.OM_CreateAckNackRequestActivation(eofList);
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestStatusUpdate(eof);
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestReschedule(eof);
        Test.stopTest();
    }
    
    /*
    public static testMethod void AsyncChecksMethod1(){
        
        Account acc = new Account();
        acc.name = 'Test';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'Test';
        con.Email = 'abcd@gmail.com';
        insert con;
        
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = acc.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = '02112016_37';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Accettato';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test1';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.Account = acc;
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.OF_Bonifica_Locked_Row__c = True;
        insert c;
        OF_PP_GE_Utils.caseOriginale = c;
        
       
        Id EofRecordType = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - PP - VLAN - ACK').getRecordTypeId(); 
        System.debug('@@@EofRecordType'+EofRecordType);
        EOF_EAI_Service_Log__c eof = new EOF_EAI_Service_Log__c();
        eof.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        eof.RecordTypeId = EofRecordType ;
        eof.EOF_Codice_Ordine_OLo__C = 'Test';
        eof.OF_SA_Direzione_Flusso__c='SF-OM';
        eof.EOF_Codice_Operatore__c = 'TIS';
        eof.EOF_Data_Notifica__c = dateTime.now();
        eof.EOF_Stato_Richiesta__c = 'OK';
        eof.EOF_ID_Notifica__c = 'test_01';
        insert eof;
         
        List<EOF_EAI_Service_Log__c>  eofList = new List<EOF_EAI_Service_Log__c>();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = EofRecordType ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq.EOF_Codice_Operatore__c = 'TIS';
        slfiberReq.EOF_Data_Notifica__c = dateTime.now();
        slfiberReq.EOF_Stato_Richiesta__c = 'OK';
        slfiberReq.EOF_ID_Notifica__c = 'test_01';
        slFiberReq.OF_SA_Cpe_Log__c =eof.id;
        eofList.add(slFiberReq);
        insert eofList;
        OF_PP_GE_Utils.slSFOM = slFiberReq;
        map<String,Id> RTMap = new  map<String,Id>();
        rtMap.put('OF_PP_VLAN_ACK',EofRecordType);
        OF_PP_GE_Utils.rtMap = rtMap; 
       
        Test.startTest();
        Test.setMock(WebServiceMock.class, new OF_PP_OLO_SendToOM_mock1());
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestStatusUpdate(eof);
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestReschedule(eof);
        Test.stopTest();
    }
    
        public static testMethod void AsyncChecksMethod2(){
        
        Account acc = new Account();
        acc.name = 'Test';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'Test';
        con.Email = 'abcd@gmail.com';
        insert con;
        
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = acc.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = '02112016_37';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Accettato';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test1';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.Account = acc;
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.OF_Bonifica_Locked_Row__c = True;
        insert c;
        OF_PP_GE_Utils.caseOriginale = c;
        
       
        Id EofRecordType = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - PP - VLAN - ACK').getRecordTypeId(); 
        System.debug('@@@EofRecordType'+EofRecordType);
        EOF_EAI_Service_Log__c eof = new EOF_EAI_Service_Log__c();
        eof.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        eof.RecordTypeId = EofRecordType ;
        eof.EOF_Codice_Ordine_OLo__C = 'Test';
        eof.OF_SA_Direzione_Flusso__c='SF-OM';
        eof.EOF_Codice_Operatore__c = 'TIS';
        eof.EOF_Data_Notifica__c = dateTime.now();
        eof.EOF_Stato_Richiesta__c = 'OK';
        eof.EOF_ID_Notifica__c = 'test_01';
        insert eof;
         
        List<EOF_EAI_Service_Log__c>  eofList = new List<EOF_EAI_Service_Log__c>();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = EofRecordType ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq.EOF_Codice_Operatore__c = 'TIS';
        slfiberReq.EOF_Data_Notifica__c = dateTime.now();
        slfiberReq.EOF_Stato_Richiesta__c = 'OK';
        slfiberReq.EOF_ID_Notifica__c = 'test_01';
        slFiberReq.OF_SA_Cpe_Log__c =eof.id;
        eofList.add(slFiberReq);
        insert eofList;
        OF_PP_GE_Utils.slSFOM = slFiberReq;
        map<String,Id> RTMap = new  map<String,Id>();
        rtMap.put('OF_PP_VLAN_ACK',EofRecordType);
        OF_PP_GE_Utils.rtMap = rtMap;
       // Test.startTest();
       // Test.setMock(WebServiceMock.class, new OF_PP_OLO_SendToOM_mock ());
        
        Test.startTest();
        Test.setMock(WebServiceMock.class, new OF_PP_OLO_SendToOM_mock());
      
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestReschedule(eof);
        Test.stopTest();
    }
        public static testMethod void AsyncChecksMethod3(){
        
        Account acc = new Account();
        acc.name = 'Test';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'Test';
        con.Email = 'abcd@gmail.com';
        insert con;
        
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = acc.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = '02112016_37';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Accettato';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test1';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.Account = acc;
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.OF_Bonifica_Locked_Row__c = True;
        insert c;
        OF_PP_GE_Utils.caseOriginale = c;
        
       
        Id EofRecordType = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - PP - VLAN - ACK').getRecordTypeId(); 
        System.debug('@@@EofRecordType'+EofRecordType);
        EOF_EAI_Service_Log__c eof = new EOF_EAI_Service_Log__c();
        eof.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        eof.RecordTypeId = EofRecordType ;
        eof.EOF_Codice_Ordine_OLo__C = 'Test';
        eof.OF_SA_Direzione_Flusso__c='SF-OM';
        eof.EOF_Codice_Operatore__c = 'TIS';
        eof.EOF_Data_Notifica__c = dateTime.now();
        eof.EOF_Stato_Richiesta__c = 'OK';
        eof.EOF_ID_Notifica__c = 'test_01';
        insert eof;
         
        List<EOF_EAI_Service_Log__c>  eofList = new List<EOF_EAI_Service_Log__c>();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = EofRecordType ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq.EOF_Codice_Operatore__c = 'TIS';
        slfiberReq.EOF_Data_Notifica__c = dateTime.now();
        slfiberReq.EOF_Stato_Richiesta__c = 'OK';
        slfiberReq.EOF_ID_Notifica__c = 'test_01';
        slFiberReq.OF_SA_Cpe_Log__c =eof.id;
        eofList.add(slFiberReq);
        insert eofList;
        OF_PP_GE_Utils.slSFOM = slFiberReq;
        map<String,Id> RTMap = new  map<String,Id>();
        rtMap.put('OF_PP_VLAN_ACK',EofRecordType);
        OF_PP_GE_Utils.rtMap = rtMap;
       
        Test.startTest();
        Test.setMock(WebServiceMock.class, new OF_PP_OLO_SendToOM_mock1());
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestReschedule(eof);
        Test.stopTest();
    }
    public static testMethod void AsyncChecksMethod4(){
        
        Account acc = new Account();
        acc.name = 'Test';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'Test';
        con.Email = 'abcd@gmail.com';
        insert con;
        
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = acc.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = '02112016_37';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Accettato';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test1';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.Account = acc;
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.OF_Bonifica_Locked_Row__c = True;
        insert c;
        OF_PP_GE_Utils.caseOriginale = c;
        
       
        Id EofRecordType = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId(); 
        System.debug('@@@EofRecordType'+EofRecordType);
        EOF_EAI_Service_Log__c eof = new EOF_EAI_Service_Log__c();
        eof.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        eof.RecordTypeId = EofRecordType ;
        eof.EOF_Codice_Ordine_OLo__C = 'Test';
        eof.OF_SA_Direzione_Flusso__c='SF-OM';
        eof.EOF_Codice_Operatore__c = 'TIS';
        eof.EOF_Data_Notifica__c = dateTime.now();
        eof.EOF_Stato_Richiesta__c = 'OK';
        eof.EOF_ID_Notifica__c = 'test_01';
        eof.EOF_Richiesta_Notifica__c = 'Test';
        insert eof;
         
        List<EOF_EAI_Service_Log__c>  eofList = new List<EOF_EAI_Service_Log__c>();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = EofRecordType ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq.EOF_Codice_Operatore__c = 'TIS';
        slfiberReq.EOF_Data_Notifica__c = dateTime.now();
        slfiberReq.EOF_Stato_Richiesta__c = 'OK';
        slfiberReq.EOF_ID_Notifica__c = 'test_01';
        slFiberReq.OF_SA_Cpe_Log__c =eof.id;
        slFiberReq.EOF_Richiesta_Notifica__c = 'Test';
        eofList.add(slFiberReq);
        insert eofList;
        OF_PP_GE_Utils.slSFOM = slFiberReq;
        
        map<String,Id> RTMap = new  map<String,Id>();
        rtMap.put('OF_SA_FiberRequest',EofRecordType);
        OF_PP_GE_Utils.rtMap = rtMap;
       
        Test.startTest();
        Test.setMock(WebServiceMock.class, new OF_PP_OLO_SendToOM_mock());
      
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestDeactivation(eofList);
        Test.stopTest();
    }
    
        public static testMethod void AsyncChecksMethod5(){
        
        Account acc = new Account();
        acc.name = 'Test';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'Test';
        con.Email = 'abcd@gmail.com';
        insert con;
        
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = acc.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = '02112016_37';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Accettato';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test1';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.Account = acc;
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.OF_Bonifica_Locked_Row__c = True;
        insert c;
        OF_PP_GE_Utils.caseOriginale = c;
        
       
        Id EofRecordType = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId(); 
        System.debug('@@@EofRecordType'+EofRecordType);
        EOF_EAI_Service_Log__c eof = new EOF_EAI_Service_Log__c();
        eof.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        eof.RecordTypeId = EofRecordType ;
        eof.EOF_Codice_Ordine_OLo__C = 'Test';
        eof.OF_SA_Direzione_Flusso__c='SF-OM';
        eof.EOF_Codice_Operatore__c = 'TIS';
        eof.EOF_Data_Notifica__c = dateTime.now();
        eof.EOF_Stato_Richiesta__c = 'OK';
        eof.EOF_ID_Notifica__c = 'test_01';
        eof.EOF_Richiesta_Notifica__c = 'Test';
        insert eof;
         
        List<EOF_EAI_Service_Log__c>  eofList = new List<EOF_EAI_Service_Log__c>();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = EofRecordType ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq.EOF_Codice_Operatore__c = 'TIS';
        slfiberReq.EOF_Data_Notifica__c = dateTime.now();
        slfiberReq.EOF_Stato_Richiesta__c = 'OK';
        slfiberReq.EOF_ID_Notifica__c = 'test_01';
        slFiberReq.OF_SA_Cpe_Log__c =eof.id;
        slFiberReq.EOF_Richiesta_Notifica__c = 'Test';
        eofList.add(slFiberReq);
        insert eofList;
        OF_PP_GE_Utils.slSFOM = slFiberReq;
        //OF_SA_GE_Utils.slSFOM = slfiberReq;
        
        map<String,Id> RTMap = new  map<String,Id>();
        rtMap.put('OF_SA_FiberRequest',EofRecordType);
        //OF_SA_GE_Utils.rtMap = rtMap;
       
        Test.startTest();
        Test.setMock(WebServiceMock.class, new OF_PP_OLO_SendToOM_mock1());
      
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestDeactivation(eofList);
        Test.stopTest();
    }
    
        public static testMethod void AsyncChecksMethod6(){
        
        Account acc = new Account();
        acc.name = 'Test';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'Test';
        con.Email = 'abcd@gmail.com';
        insert con;
        
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = acc.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = '02112016_37';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Accettato';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test1';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.Account = acc;
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.OF_Bonifica_Locked_Row__c = True;
        insert c;
        OF_PP_GE_Utils.caseOriginale = c;
        
       
        Id EofRecordType = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId(); 
        System.debug('@@@EofRecordType'+EofRecordType);
        EOF_EAI_Service_Log__c eof = new EOF_EAI_Service_Log__c();
        eof.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        eof.RecordTypeId = EofRecordType ;
        eof.EOF_Codice_Ordine_OLo__C = 'Test';
        eof.OF_SA_Direzione_Flusso__c='SF-OM';
        eof.EOF_Codice_Operatore__c = 'TIS';
        eof.EOF_Data_Notifica__c = dateTime.now();
        eof.EOF_Stato_Richiesta__c = 'OK';
        eof.EOF_ID_Notifica__c = 'test_01';
        eof.Caso__c = c.id;
        eof.EOF_Richiesta_Notifica__c = 'Test';
        insert eof;
         
        List<EOF_EAI_Service_Log__c>  eofList = new List<EOF_EAI_Service_Log__c>();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = EofRecordType ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq.EOF_Codice_Operatore__c = 'TIS';
        slfiberReq.EOF_Data_Notifica__c = dateTime.now();
        slfiberReq.EOF_Stato_Richiesta__c = 'OK';
        slfiberReq.EOF_ID_Notifica__c = 'test_01';
        slFiberReq.OF_SA_Cpe_Log__c =eof.id;
        slFiberReq.EOF_Richiesta_Notifica__c = 'Test';
        slFiberReq.Caso__c = c.id;
        eofList.add(slFiberReq);
        insert eofList;
        OF_PP_GE_Utils.slSFOM = slFiberReq;
        //OF_SA_GE_Utils.slSFOM = slfiberReq;
        OF_PP_GE_Utils.slSFOM = slfiberReq;
        
        map<String,Id> RTMap = new  map<String,Id>();
        rtMap.put('OF_SA_FiberRequest',EofRecordType);
        OF_PP_GE_Utils.rtMap = rtMap;
       
        Test.startTest();
        Test.setMock(WebServiceMock.class, new OF_PP_OLO_SendToOM_mock());
      
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestDeactivation(eofList[0].id);
        Test.stopTest();
    }
    
       public static testMethod void AsyncChecksMethod7(){
        
        Account acc = new Account();
        acc.name = 'Test';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'Test';
        con.Email = 'abcd@gmail.com';
        insert con;
        
        String CaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EOF Caso - Attivazione').getRecordTypeId();
        Case c = new Case();
        c.EOF_Account_OLO__c = acc.Id;
        c.Subject = 'Richiesta di attivazione';
        c.EOF_Codice_Ordine_OLO__c = '02112016_37';
        c.EOF_Data_Prevista_Attivazione__c = system.today();
        c.EOF_Orario_Appuntamento__c = DateTime.now().getTime()+'';
        c.Status = 'Accettato';
        c.EOF_Fase__c = 'In Verifica BO';
        c.Type = '1';
        c.EOF_Tipologia_Servizio__c = 'test1';
        c.EOF_Codice_Operatore_WS__c = 'VF';
        c.EOF_SLA_Premium_Assurance__c ='Y';
        c.Account = acc;
        c.EOF_Identificativo_del_POP__c = 'PG_01';
        c.EOF_ID_Building_WS__c = '10_054_054039_8000064301_40';
        c.EOF_Numero_Civico_WS__c = '7';
        c.EOF_Telefono_Referente_OLO_Onfield_Notec__c = '0123456789';
        c.EOF_Numero_Telefonico_Principale_Linea__c = '111';
        c.EOF_Recapito_Test_Linea__c = '111';
        c.EOF_Tipologia_Apparato__c = 'test';
        c.OwnerId = userInfo.getUserId();
        c.RecordTypeId = CaseRecordTypeId;
        c.EOF_Id_Notifica__c = 'test_01';
        c.Origin = 'Web';
        c.Priority = 'Medium';
        c.EOF_GPON_Vincolante__c = 'Y';
        c.OF_Bonifica_Locked_Row__c = True;
        insert c;
        OF_PP_GE_Utils.caseOriginale = c;
        
       
        Id EofRecordType = Schema.SObjectType.EOF_EAI_Service_Log__c.getRecordTypeInfosByName().get('OF - SA - FiberRequest').getRecordTypeId(); 
        System.debug('@@@EofRecordType'+EofRecordType);
        EOF_EAI_Service_Log__c eof = new EOF_EAI_Service_Log__c();
        eof.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        eof.RecordTypeId = EofRecordType ;
        eof.EOF_Codice_Ordine_OLo__C = 'Test';
        eof.OF_SA_Direzione_Flusso__c='SF-OM';
        eof.EOF_Codice_Operatore__c = 'TIS';
        eof.EOF_Data_Notifica__c = dateTime.now();
        eof.EOF_Stato_Richiesta__c = 'OK';
        eof.EOF_ID_Notifica__c = 'test_01';
        eof.Caso__c = c.id;
        eof.EOF_Richiesta_Notifica__c = 'Test';
        insert eof;
         
        List<EOF_EAI_Service_Log__c>  eofList = new List<EOF_EAI_Service_Log__c>();
        EOF_EAI_Service_Log__c slFiberReq = new EOF_EAI_Service_Log__c();
        slFiberReq.eof_tipo_comunicazione_String__c='OLO->SF - ActivationRequest';
        slFiberReq.RecordTypeId = EofRecordType ;
        slFiberReq.EOF_Codice_Ordine_OLo__C = 'Test';
        slfiberReq.OF_SA_Direzione_Flusso__c='SF-OM';
        slFiberReq.EOF_Codice_Operatore__c = 'TIS';
        slfiberReq.EOF_Data_Notifica__c = dateTime.now();
        slfiberReq.EOF_Stato_Richiesta__c = 'OK';
        slfiberReq.EOF_ID_Notifica__c = 'test_01';
        slFiberReq.OF_SA_Cpe_Log__c =eof.id;
        slFiberReq.EOF_Richiesta_Notifica__c = 'Test';
        slFiberReq.Caso__c = c.id;
        eofList.add(slFiberReq);
        insert eofList;
        OF_PP_GE_Utils.slSFOM = slFiberReq;
        
        map<String,Id> RTMap = new  map<String,Id>();
        rtMap.put('OF_SA_FiberRequest',EofRecordType);
        OF_PP_GE_Utils.rtMap = rtMap;
       
        Test.startTest();
        Test.setMock(WebServiceMock.class, new OF_PP_OLO_SendToOM_mock1());
      
        //OF_PP_OLO_SendToOM.OM_CreateAckNackRequestDeactivation(eofList[0].id);
        Test.stopTest();
    }    
    */
}