objects/Account.object
<CustomObject>
    <fields>
        <fullName>OF_BillingSyncronized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Serve per segnalare che c&apos;è stata almeno una sincronizzazione con il billing</description>
        <label>OF_BillingSyncronized</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Accordo_Operativo__c</fullName>
        <description>The same value of Accordo Operativo of parent Case Richiesta Fattibilità</description>
        <label>Accordo Operativo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comune__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Avvio_Fatturazione__c</fullName>
        <label>Data Avvio Fatturazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Risorsa__c</fullName>
        <label>ID Risorsa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ID Risorsa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.OF_ServizioRichiesto__c</field>
                <operation>equals</operation>
                <valueField>Asset.RecordType.Name</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Servizi Extra</relationshipLabel>
        <relationshipName>Asset_Extra</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_Civico__c</fullName>
        <label>Civico</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Comune__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_DataAttivazione2__c</fullName>
        <label>Data Attivazione</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OF_DataAttivazione__c</fullName>
        <label>Data Attivazione OLD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataCessazione__c</fullName>
        <label>Data Cessazione OLD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataSospensione__c</fullName>
        <label>Data Sospensione</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OF_ID_Building__c</fullName>
        <label>ID Building</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Indirizzo__c</fullName>
        <label>Indirizzo</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Particella_Toponomastica__c</fullName>
        <label>Particella Toponomastica</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ProfiloOpenStream__c</fullName>
        <label>Profilo Open Stream</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Stato__c</fullName>
        <label>Stato</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attivo</fullName>
                </value>
                <value>
                    <fullName>Cessato</fullName>
                </value>
                <value>
                    <fullName>Sospeso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OF_SyncNoVert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OF_SyncNoVert</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EOF_Notify__c.object
<CustomObject>
    <fields>
        <fullName>EOF_ID_Risorsa__c</fullName>
        <label>ID Risorsa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>indice__c</fullName>
        <label>indice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Notifica</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notify Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifiche</pluralLabel>
    <recordTypes>
        <fullName>EOF_BILL_Asset</fullName>
        <active>true</active>
        <description>Record Type per la gestione del WS per la sincronizzazione del billing degli Asset</description>
        <label>EOF_BILL_Asset</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_CommercialElement__c.object
<CustomObject>
    <fields>
        <fullName>OF_Commercial_Element_Code__c</fullName>
        <label>Commercial Element Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_DataFineValidita__c</fullName>
        <label>Data fine validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataInizioValidita__c</fullName>
        <label>Data inizio validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Servizio</label>
        <referenceTo>OF_Servizio__c</referenceTo>
        <relationshipLabel>Commercial elements</relationshipLabel>
        <relationshipName>CommercialElements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Commercial element</label>
    <nameField>
        <label>Commercial element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_CommercialElementIstanziato__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Verticale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Verticale</label>
        <referenceTo>OF_Asset_Verticale__c</referenceTo>
        <relationshipLabel>Commercial element istanziati</relationshipLabel>
        <relationshipName>Commercial_element_istanziati</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Civico__c</fullName>
        <formula>Asset_Verticale__r.Civico__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Civico</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_IAV__c</fullName>
        <label>Code_IAV</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comune__c</fullName>
        <formula>Asset_Verticale__r.Comune__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Comune</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Descrizione_IAV__c</fullName>
        <label>Descrizione IAV</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_DB_Building__c</fullName>
        <formula>Asset_Verticale__r.ID_DB_Building__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ID DB Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_DB_Scala_Palazzina__c</fullName>
        <formula>Asset_Verticale__r.ID_DB_Scala_Palazzina__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ID DB Scala Palazzina</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_GIS_Scala_Palazzina__c</fullName>
        <formula>Asset_Verticale__r.ID_GIS_Scala_Palazzina__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ID GIS Scala Palazzina</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Indirizzo__c</fullName>
        <formula>Asset_Verticale__r.Indirizzo__c</formula>
        <label>Indirizzo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Commercial element istanziati</relationshipLabel>
        <relationshipName>Commercial_element_istanziati</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_BillingSyncronized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OF_BillingSyncronized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CommercialElement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial element</label>
        <referenceTo>OF_CommercialElement__c</referenceTo>
        <relationshipLabel>Commercial element istanziati</relationshipLabel>
        <relationshipName>Commercial_element_istanziati</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_DataAttivazione__c</fullName>
        <label>Data attivazione</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OF_DataCessazione__c</fullName>
        <label>Data cessazione</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OF_DataSospensione__c</fullName>
        <label>Data sospensione</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OF_Stato__c</fullName>
        <label>Stato</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attivo</fullName>
                </value>
                <value>
                    <fullName>Cessato</fullName>
                </value>
                <value>
                    <fullName>Sospeso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OF_TT_Number__c</fullName>
        <label>OF_TT_Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OLO_Comm_Code__c</fullName>
        <label>OLO_Comm_Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Particella_Toponomastica__c</fullName>
        <formula>Asset_Verticale__r.Particella_Toponomastica__c</formula>
        <label>Particella Toponomastica</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provincia__c</fullName>
        <formula>Asset_Verticale__r.Provincia__c</formula>
        <label>Provincia</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UI_Scala_Palazzina__c</fullName>
        <formula>Asset_Verticale__r.UI_Scala_Palazzina__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UI Scala Palazzina</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UpdateBilling__c</fullName>
        <defaultValue>true</defaultValue>
        <label>UpdateBilling</label>
        <type>Checkbox</type>
    </fields>
    <label>Commercial element istanziato</label>
    <nameField>
        <displayFormat>CEI-{00000}</displayFormat>
        <label>Commercial element istanziato Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial element istanziati</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Servizio__c.object
<CustomObject>
    <label>Servizio</label>
    <nameField>
        <label>Servizio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servizi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>OF_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_Civico__c</fullName>
        <label>Civico</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Comune__c</fullName>
        <label>Comune</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Indirizzo__c</fullName>
        <label>Indirizzo</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ProfiloOpenStream__c</fullName>
        <label>Profilo Open Stream</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Verticali__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>RecorTypesList__c</fullName>
        <description>All&apos;interno sono presenti i Record Type dei CEI separati da una virgola per effettuare la sincronizzazione verso il BILLING. Il nome deve essere compreso tra singoli apici</description>
        <label>RecorTypesList</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceList__c</fullName>
        <label>ServiceList</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>callWsBillingBatchSize__c</fullName>
        <inlineHelpText>Definisce quanti batch del billing che inviano le notifiche devono stare in esecuzione contemporaneamente</inlineHelpText>
        <label>callWsBillingBatchSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>createNotifyBatchLimit__c</fullName>
        <inlineHelpText>limit usato nello start del batch di creazione notifiche per il billing</inlineHelpText>
        <label>createNotifyBatchLimit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Verticali</label>
</CustomObject>

classes/OF_SyncBillingFattibilitaBatch.cls
global class OF_SyncBillingFattibilitaBatch implements Database.AllowsCallouts,Database.Batchable<sObject>, Database.Stateful {
    
    private List<String> idAsset;
    
    global Integer scopeSize;
    global Integer firstIndex;
    
    public OF_SyncBillingFattibilitaBatch(List<string> assetId) {
        idAsset = assetId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('@@@@ Inizio Fattibilita Batch: ' + system.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ'));
        
        Verticali__c verticaliCS = Verticali__c.getOrgDefaults();
        Integer lim = verticaliCS.createNotifyBatchLimit__c.intValue();
        
        String rTypes = verticaliCS.RecorTypesList__c;
        String ServiceList = verticaliCS.serviceList__c;
        String query = 'SELECT id, RecordType.DeveloperName, OF_DataAttivazione__c,OF_Stato__c,'
            +'Name,Asset_Verticale__c,LastModifiedDate,OF_BillingSyncronized__c,Code_IAV__c,Descrizione_IAV__c,OF_TT_Number__c,OLO_Comm_Code__c,'
            +'Provincia__c,Comune__c,Indirizzo__c,OF_DataCessazione__c,Civico__c,Particella_Toponomastica__c,'
            +'OF_CommercialElement__r.OF_Commercial_Element_Code__c,'
            +'OF_CommercialElement__r.OF_Servizio__r.OF_Servizio_Code__c,'
            +'OF_CommercialElement__r.OF_Servizio__r.OF_DataInizioValidita__c,'
            +'OF_CommercialElement__r.OF_Servizio__r.OF_DataFineValidita__c,'
            +'OF_CommercialElement__r.Name,ID_GIS_Scala_Palazzina__c,ID_DB_Building__c,ID_DB_Scala_Palazzina__c,UI_Scala_Palazzina__c,'
            +'OF_Asset__c,OF_Asset__r.name,OF_Asset__r.Account.name,'
            +'OF_Asset__r.Account.AccountNumber,'
            +'OF_Asset__r.Data_Avvio_Fatturazione__c,'
            +'OF_Asset__r.OF_DataAttivazione2__c,'
            +'OF_Asset__r.Accordo_Operativo__c,'
            +'OF_Asset__r.OF_Provincia__c,'
            +'OF_Asset__r.OF_Comune__c,'
            +'OF_Asset__r.OF_Indirizzo__c,'
            +'OF_Asset__r.OF_Civico__c,'
            +'OF_Asset__r.OF_Particella_Toponomastica__c,'
            +'OF_Asset__r.EOF_ID_Risorsa__c,'
            +'OF_Asset__r.Status,'
            +'OF_Asset__r.OF_ID_Building__c,'
            +'OF_Asset__r.OF_Contract__c,'
            +'OF_Asset__r.recordType.name,'
            +'OF_Asset__r.recordType.developername,'
            +'OF_DataSospensione__c,OF_Asset__r.OF_ProfiloOpenStream__c'
            + ' FROM OF_CommercialElementIstanziato__c WHERE RecordType.DeveloperName in ( '+rTypes+' ) and OF_CommercialElement__r.OF_Servizio__r.Name IN ( '+ServiceList+' ) and UpdateBilling__c =true and OF_Asset__c != null and OF_Stato__c != \'Sospeso\'';
        if (!idAsset.isEmpty()) {
            query = query + ' and OF_Asset__c in :idAsset LIMIT :lim';
        }        
        
        system.debug('@@@@@DOPO: '+ query);
        List<EOF_Notify__c> n = [SELECT Id, indice__c FROM EOF_Notify__c WHERE RecordType.DeveloperName = 'EOF_BILL_Asset'
                                 AND indice__c != null ORDER BY indice__c DESC LIMIT 1];
        Decimal i = 1;
        if (!n.isEmpty()) {
            i = n.get(0).indice__c + 1;
        }
        firstIndex = i.intValue();
        rTypes = rTypes.replaceAll('\'','') ;
        List<string> RecorTypes = rTypes.split(',');
        
        AggregateResult size = [SELECT count(Id) tot FROM OF_CommercialElementIstanziato__c
                                WHERE RecordType.DeveloperName in :RecorTypes and UpdateBilling__c = true];
        scopeSize = Integer.valueOf(size.get('tot'));
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<OF_CommercialElementIstanziato__c> scope) {
        
        system.debug('@@@@@scope: '+ scope.size());
        SyncBillingAssetUtils.callWSAssetFattibilitaCustom(scope);
    }
    
    global void finish(Database.BatchableContext BC) {
        //se non è vuoto vuol dire che la chiamata è fatta dal tasto
        if (!idAsset.isEmpty()) {
            List<Asset> assets = [SELECT id, OF_SyncNoVert__c FROM Asset WHERE Id IN :idAsset];
            for (Asset asse : assets) {
                asse.OF_SyncNoVert__c = false;
            }
            
            update assets;
            
            List<EOF_Notify__c> n = [SELECT Id, indice__c FROM EOF_Notify__c WHERE RecordType.DeveloperName = 'EOF_BILL_Asset'
                                     AND indice__c != null ORDER BY indice__c DESC LIMIT 1];
            
            if(!n.isEmpty()){
                OF_CallWSFattibilita batchable = new OF_CallWSFattibilita(firstIndex, n.get(0).Indice__c.intValue());
                Database.executeBatch(batchable, 1);
                return;
            }
        }//end !idAsset.isEmpty
        
        Verticali__c verticaliCS = Verticali__c.getOrgDefaults();
        Integer numBatch = verticaliCS.callWsBillingBatchSize__c.intvalue();
        
        List<OF_CallWSFattibilitaBatch_Sched> schedList = new List<OF_CallWSFattibilitaBatch_Sched>();
        if (scopeSize >= numBatch) {
            Integer offset = scopeSize / numBatch;
            Integer startIndex = firstIndex;
            Integer endIndex = startIndex + offset;
            
            for (Integer i = 1; i < numBatch; i++) {
                schedList.add(new OF_CallWSFattibilitaBatch_Sched(startIndex, endIndex));
                startIndex = endIndex + 1;
                endIndex += offset;
            }
            
            schedList.add(new OF_CallWSFattibilitaBatch_Sched(startIndex, firstIndex + scopeSize));
            
        } else if (scopeSize > 0) {
            schedList.add(new OF_CallWSFattibilitaBatch_Sched(firstIndex, firstIndex + scopeSize));
        }
        
        if (!schedList.isEmpty()) {
            for (CronTrigger ct : [SELECT Id, CronJobDetail.Name, CronJobDetail.JobType
                                   FROM CronTrigger
                                   WHERE CronJobDetail.Name like 'CALL WS BILLING FATTIBILITA %' LIMIT :numBatch]) {
                                       
                                       System.abortJob(ct.id);
                                   }
             
            Integer i = 1;
            DateTime t = System.now().addSeconds(29);
            for (OF_CallWSFattibilitaBatch_Sched s : schedList) {
                String nextFireTime = getCRONExpression(t.addSeconds(i));
                System.schedule('CALL WS BILLING FATTIBILITA ' + i, nextFireTime, s);
                i++;
            }
        }
    }
    
    public static String getCRONExpression(Datetime dt) {
        return ('' + dt.second() + ' ' + dt.minute() + ' ' + dt.hour() + ' ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year());
    }
}