objects/Account.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OLO</fullName>
        <active>true</active>
        <description>Use this account to store OLO information.</description>
        <label>OLO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Account_OLO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLO</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>OLO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <externalId>true</externalId>
        <label>Codice Ordine OLO</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EOF_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da lavorare</fullName>
                </value>
                <value>
                    <fullName>Appuntamento Fissato</fullName>
                </value>
                <value>
                    <fullName>Da contattare</fullName>
                </value>
                <value>
                    <fullName>Desospeso</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione</fullName>
                </value>
                <value>
                    <fullName>In Verifica BO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Sospeso BO</fullName>
                </value>
                <value>
                    <fullName>Sospeso Tecn.</fullName>
                </value>
                <value>
                    <fullName>In assegnazione</fullName>
                </value>
                <value>
                    <fullName>Espletato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato KO</fullName>
                </value>
                <value>
                    <fullName>Espletato KO</fullName>
                </value>
                <value>
                    <fullName>Accettato KO</fullName>
                </value>
                <value>
                    <fullName>In Verifica Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Network Creation</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Delivery</fullName>
                </value>
                <value>
                    <fullName>Completato</fullName>
                </value>
                <value>
                    <fullName>Offerta Creata</fullName>
                </value>
                <value>
                    <fullName>Offerta Presentata</fullName>
                </value>
                <value>
                    <fullName>Richiesta modifica offerta da Cliente</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Referente Fattibilità</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Tecnico Fattibilità</fullName>
                </value>
                <value>
                    <fullName>Sospeso OM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OF_SA_WS_IN_OLO_StatusUpdate_Test.cls
@isTest
public class OF_SA_WS_IN_OLO_StatusUpdate_Test {
    
    static testmethod Map<String,String> RecordType()
    { 
        List<RecordType> rtypes = [Select Name, Id From RecordType where (sObjectType='Case' OR sObjectType='Account')  and isActive=true];
        
        Map<String,String> RecordType = new Map<String,String>{};
		
		for(RecordType rt: rtypes)
    		RecordType.put(rt.Name,rt.Id);
                
       return RecordType;
    }
    
   static testMethod void testOF_SA_WS_IN_OLO_StatusUpdate(){
			
			Map<String,String> RecordTypeMap = RecordType();
	           
            /**Account**/
            Account accOloWIND = new Account();       
            accOloWIND.Name = 'Wind';
            accOloWIND.EOF_Codice_Operatore__c = 'WN';
            accOloWIND.Type = 'OLO';
            accOloWIND.Industry = 'Telecommunications';
            accOloWIND.RecordTYpeId = RecordTypeMap.get('OLO');
            insert accOloWIND;
            /**End Account**/
           
            /**Case**/
            Case c = new Case();
            c.RecordTypeId = RecordTypeMap.get('EOF_Caso_Attivazione_OPENSTREAM');
            c.EOF_Account_OLO__c = accOloWIND.id;
            c.EOF_Codice_Ordine_OLO__c = 'Test';
            c.status = 'Ricevuto';
            c.EOF_FASE__C = 'NA';
            insert c;
            /**End Case**/
       
            
       
            OF_SA_WS_IN_OLO_StatusUpdate.OLO_StatusUpdateRequest RescheduleRequest = new OF_SA_WS_IN_OLO_StatusUpdate.OLO_StatusUpdateRequest();
           
           
            RescheduleRequest.CODICE_ORDINE_OF = 'Test';
            RescheduleRequest.CODICE_OPERATORE = 'WN';
            RescheduleRequest.CODICE_ORDINE_OLO = 'Test';
            RescheduleRequest.DATA_NOTIFICA = '2017-06-01T18:30:15+01:00';
            RescheduleRequest.ID_NOTIFICA = 'Test';
            RescheduleRequest.NOME_CLIENTE = 'Test';
            RescheduleRequest.COGNOME_CLIENTE = 'Test';
            RescheduleRequest.RECAPITO_TELEFONICO_CLIENTE_1 = 'Test';
            RescheduleRequest.RECAPITO_TELEFONICO_CLIENTE_2 = 'Test';
            RescheduleRequest.DATA_PREVISTA_ATTIVAZIONE = '2018-11-15';
            RescheduleRequest.ORARIO_APPUNTAMENTO = 'Test';
            RescheduleRequest.NOTE = 'Test';
            RescheduleRequest.CODICE_MOTIVAZIONE = 'T'; 
            RescheduleRequest.MOTIVAZIONE = 'T';
            RescheduleRequest.AZIONE = '1';
       
           OF_SA_WS_IN_OLO_StatusUpdate.OLO_StatusUpdateResponse respnce =  new OF_SA_WS_IN_OLO_StatusUpdate.OLO_StatusUpdateResponse();
           respnce.ID_NOTIFICA = 'test';
           respnce.ESITO = 'test';
           respnce.CODICE_MOTIVAZIONE = 'test'; 
           respnce.MOTIVAZIONE = 'test';
           
           Test.startTest();
           Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());
           OF_SA_WS_IN_OLO_StatusUpdate.OLO_StatusUpdate(RescheduleRequest);
           //OF_SA_WS_IN_OLO_Activation.OLO_ActivationResponse respUp = OF_SA_OLO_EntryChecks.SyncChecksStatusUpdate(RescheduleRequest);
           Test.stopTest(); 
           
    }
    
    static testMethod void testOF_SA_WS_IN_OLO_StatusUpdate1(){
			
			OF_SA_WS_IN_OLO_StatusUpdate.OLO_StatusUpdateRequest RescheduleRequest = new OF_SA_WS_IN_OLO_StatusUpdate.OLO_StatusUpdateRequest();
           
           
            RescheduleRequest.CODICE_ORDINE_OF = 'Test';
            RescheduleRequest.CODICE_OPERATORE = 'WN';
            RescheduleRequest.CODICE_ORDINE_OLO = 'Test';
            RescheduleRequest.DATA_NOTIFICA = '2017-06-01T18:30:15+01:00';
            RescheduleRequest.ID_NOTIFICA = 'Test';
            RescheduleRequest.NOME_CLIENTE = 'Test';
            RescheduleRequest.COGNOME_CLIENTE = 'Test';
            RescheduleRequest.RECAPITO_TELEFONICO_CLIENTE_1 = 'Test';
            RescheduleRequest.RECAPITO_TELEFONICO_CLIENTE_2 = 'Test';
            RescheduleRequest.DATA_PREVISTA_ATTIVAZIONE = '2018-11-15';
            RescheduleRequest.ORARIO_APPUNTAMENTO = 'Test';
            RescheduleRequest.NOTE = 'Test';
            RescheduleRequest.CODICE_MOTIVAZIONE = 'T'; 
            RescheduleRequest.MOTIVAZIONE = 'T';
            RescheduleRequest.AZIONE = '1';
       
           OF_SA_WS_IN_OLO_StatusUpdate.OLO_StatusUpdateResponse respnce =  new OF_SA_WS_IN_OLO_StatusUpdate.OLO_StatusUpdateResponse();
           respnce.ID_NOTIFICA = 'test';
           respnce.ESITO = 'test';
           respnce.CODICE_MOTIVAZIONE = 'test'; 
           respnce.MOTIVAZIONE = 'test';
           
           Test.startTest();
           Test.setMock(WebServiceMock.class, new NotifyServiceMockupcls());
           OF_SA_WS_IN_OLO_StatusUpdate.OLO_StatusUpdate(RescheduleRequest);
           //OF_SA_WS_IN_OLO_Activation.OLO_ActivationResponse respUp = OF_SA_OLO_EntryChecks.SyncChecksStatusUpdate(RescheduleRequest);
           Test.stopTest(); 
           
    }

}