objects/Asset.object
<CustomObject>
    <fields>
        <fullName>OF_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ID Risorsa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.OF_ServizioRichiesto__c</field>
                <operation>equals</operation>
                <valueField>Asset.RecordType.Name</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Servizi Extra</relationshipLabel>
        <relationshipName>Asset_Extra</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_DataAttivazione__c</fullName>
        <label>Data Attivazione OLD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataCessazione2__c</fullName>
        <label>Data Cessazione</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OF_DataCessazione__c</fullName>
        <label>Data Cessazione OLD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_Stato__c</fullName>
        <label>Stato</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attivo</fullName>
                </value>
                <value>
                    <fullName>Cessato</fullName>
                </value>
                <value>
                    <fullName>Sospeso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OF_Asset_Verticale__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset Verticali</relationshipLabel>
        <relationshipName>Asset_Verticali</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Asset Verticali</relationshipLabel>
        <relationshipName>Asset_Verticali</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cardinalita_Scala__c</fullName>
        <label>Cardinalità Scala</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ID_GIS_Scala_Palazzina__c</fullName>
        <label>ID GIS Scala Palazzina</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Update_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Update Billing</label>
        <type>Checkbox</type>
    </fields>
    <label>Asset Verticale</label>
    <nameField>
        <label>Asset Verticale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Verticali</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Billing_Element_Verticale__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Verticale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Verticale</label>
        <referenceTo>OF_Asset_Verticale__c</referenceTo>
        <relationshipLabel>Billing Elements Verticale</relationshipLabel>
        <relationshipName>Billing_Elements_Verticale</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Billing Elements Verticale</relationshipLabel>
        <relationshipName>Billing_Elements_Verticale</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Update_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Update_Billing</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Element Verticale</label>
    <nameField>
        <label>Billing Element Verticale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Elements Verticale</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_BillingElement__c.object
<CustomObject>
    <fields>
        <fullName>OF_Attivo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attivo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CommercialElement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Commercial element</label>
        <referenceTo>OF_CommercialElement__c</referenceTo>
        <relationshipLabel>Billing elements</relationshipLabel>
        <relationshipName>BillingElements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; OF_CommercialElement__r.OF_Servizio__c, OF_CommercialElement__r.OF_Servizio__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servizio</label>
        <type>Text</type>
    </fields>
    <label>Billing element</label>
    <nameField>
        <label>Billing element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_CommercialElement__c.object
<CustomObject>
    <fields>
        <fullName>OF_Attivo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attivo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Servizio</label>
        <referenceTo>OF_Servizio__c</referenceTo>
        <relationshipLabel>Commercial elements</relationshipLabel>
        <relationshipName>CommercialElements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Commercial element</label>
    <nameField>
        <label>Commercial element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_CommercialElementIstanziato__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Verticale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Verticale</label>
        <referenceTo>OF_Asset_Verticale__c</referenceTo>
        <relationshipLabel>Commercial element istanziati</relationshipLabel>
        <relationshipName>Commercial_element_istanziati</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cardinalita_Scala__c</fullName>
        <formula>Asset_Verticale__r.Cardinalita_Scala__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cardinalita Scala</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ID_GIS_Scala_Palazzina__c</fullName>
        <formula>Asset_Verticale__r.ID_GIS_Scala_Palazzina__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ID GIS Scala Palazzina</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Commercial element istanziati</relationshipLabel>
        <relationshipName>Commercial_element_istanziati</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_CommercialElement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial element</label>
        <referenceTo>OF_CommercialElement__c</referenceTo>
        <relationshipLabel>Commercial element istanziati</relationshipLabel>
        <relationshipName>Commercial_element_istanziati</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_DataAttivazione__c</fullName>
        <label>Data attivazione</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OF_DataCessazione__c</fullName>
        <label>Data cessazione</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OF_IDRisorsa__c</fullName>
        <label>ID Risorsa</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Stato__c</fullName>
        <label>Stato</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attivo</fullName>
                </value>
                <value>
                    <fullName>Cessato</fullName>
                </value>
                <value>
                    <fullName>Sospeso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Commercial element istanziato</label>
    <nameField>
        <displayFormat>CEI-{00000}</displayFormat>
        <label>Commercial element istanziato Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial element istanziati</pluralLabel>
    <recordTypes>
        <fullName>Verticale</fullName>
        <active>true</active>
        <label>Verticale</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_ContrattoServizio__c.object
<CustomObject>
    <fields>
        <fullName>OF_Contract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Servizi sottoscritti</relationshipLabel>
        <relationshipName>Contratti_Servizi</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Servizio</label>
        <referenceTo>OF_Servizio__c</referenceTo>
        <relationshipLabel>Servizi sottoscritti</relationshipLabel>
        <relationshipName>Contratti_Servizi</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Servizio sottoscritto</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Contratto Servizio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Servizi sottoscritti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Servizio__c.object
<CustomObject>
    <fields>
        <fullName>OF_Attivo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attivo</label>
        <type>Checkbox</type>
    </fields>
    <label>Servizio</label>
    <nameField>
        <label>Servizio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servizi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>OF_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Billing Elements</relationshipLabel>
        <relationshipName>Price_Book_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_CommercialElementIstanziato__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial element istanziato</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.OF_Asset__c</field>
                <operation>equals</operation>
                <valueField>OF_CommercialElementIstanziato__c.OF_Asset__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OF_CommercialElementIstanziato__c</referenceTo>
        <relationshipLabel>Price Book Entries</relationshipLabel>
        <relationshipName>Price_Book_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_DataCessazione2__c</fullName>
        <label>Data cessazione</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OF_IDRisorsa__c</fullName>
        <formula>OF_Asset__r.EOF_ID_Risorsa__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ID Risorsa</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>OF_BillingElement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing element</label>
        <referenceTo>OF_BillingElement__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_CommercialElement__c</fullName>
        <formula>OF_BillingElement__r.OF_CommercialElement__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial element</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <formula>OF_BillingElement__r.OF_CommercialElement__r.OF_Servizio__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servizio</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Verticali__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>giorniTolleranza__c</fullName>
        <defaultValue>-2</defaultValue>
        <label>giorniTolleranza</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Verticali</label>
</CustomObject>

classes/OF_PNI_GIS_Obsoleti_Check_Bonifica.cls
public class OF_PNI_GIS_Obsoleti_Check_Bonifica {

	private final Datetime creationDateThresold;
	private final Datetime now;

	private final List<OF_Billing_Element_Verticale__c> validBEV;
	private final Map<String, List<OF_Billing_Element_Verticale__c>> mapScala_Bev;
	private final List<OF_Billing_Element_Verticale__c> invalidBEV;
	private final Map<Id, PricebookEntry> mapPbe;
	private final Map<Id, PricebookEntry> mapPbeS;
	private final Map<Id, OF_Asset_Verticale__c> mapAV;
	private final Map<Id, OF_ContrattoServizio__c> mapServizi;
	private final Map<Id, OF_CommercialElementIstanziato__c> mapIdCeiv;
	private final Map<Id, OF_CommercialElement__c> mapCeXidServ;
	private final Map<String, Set<String>> mapScalaOloName;

	private final Map<Id, OF_Asset_Verticale__c> avToUpdate;
	private final Map<Id, OF_Billing_Element_Verticale__c> bevToUpdate;
	private final List<PricebookEntry> pbToUpdate;
	private final List<PricebookEntry> pbsToUpdate;
	private final List<OF_CommercialElementIstanziato__c> ceiToUpdate;

	private final Set<PricebookEntry> pbeToInsert;
	private final List<OF_CommercialElementIstanziato__c> ceiToInsert;
	private final List<Product2> prodToInsert;
	private final List<BillingData> wrapList;

	private final List<OF_Billing_Element_Verticale__c> bevToDelete;

	private final RecordType rtCei;
	private final OF_BillingElement__c be_Storno;
	private final OF_BillingElement__c be_Contributo;
	private final Pricebook2 standardPb;

	class BillingData {
		private OF_CommercialElementIstanziato__c c {get; set;}
		private Product2 prod {get; set;}
		private PricebookEntry pb {get; set;}

		public BillingData(OF_CommercialElementIstanziato__c cei, Product2 p, PricebookEntry pbe) {
			c = cei;
			prod = p;
			pb = pbe;
		}
	}

	// Used only for debug
	private String idScala_Olo = null;

	public OF_PNI_GIS_Obsoleti_Check_Bonifica() {

		Verticali__c verticaliCS = Verticali__c.getOrgDefaults();
		system.debug('Minuti Tolleranza: ' + verticaliCS.giorniTolleranza__c.intvalue());
		creationDateThresold = System.now().addMinutes(verticaliCS.giorniTolleranza__c.intvalue());
		now = System.now();
		validBEV = new List<OF_Billing_Element_Verticale__c>();
		mapScala_Bev = new Map<String, List<OF_Billing_Element_Verticale__c> >();
		invalidBEV = new List<OF_Billing_Element_Verticale__c>();
		mapPbe = new Map<Id, PricebookEntry>();
		mapPbeS = new Map<Id, PricebookEntry>();
		mapAV = new Map<Id, OF_Asset_Verticale__c>();
		mapServizi = new Map<Id, OF_ContrattoServizio__c>();
		mapIdCeiv = new Map<Id, OF_CommercialElementIstanziato__c>();
		mapCeXidServ = new Map<Id, OF_CommercialElement__c>();
		mapScalaOloName = new Map<String, Set<String> >();

		avToUpdate = new Map<Id, OF_Asset_Verticale__c>();
		bevToUpdate = new Map<Id, OF_Billing_Element_Verticale__c>();
		pbToUpdate = new List<PricebookEntry>();
		pbsToUpdate = new List<PricebookEntry>();
		ceiToUpdate = new List<OF_CommercialElementIstanziato__c>();

		pbeToInsert = new Set<PricebookEntry>();
		ceiToInsert = new List<OF_CommercialElementIstanziato__c>();
		prodToInsert = new List<Product2>();
		wrapList = new List<BillingData>();

		bevToDelete = new List<OF_Billing_Element_Verticale__c>();

		rtCei = [SELECT id, name, SobjectType
				 FROM RecordType
				 WHERE name = 'Verticale' AND SobjectType = 'OF_CommercialElementIstanziato__c'];

		be_Storno = [SELECT id, name, OF_CommercialElement__c, OF_Attivo__c
					 FROM OF_BillingElement__c
					 WHERE name = 'Contributo di storno Verticale' LIMIT 1];

		be_Contributo = [SELECT id, name, OF_CommercialElement__c, OF_Attivo__c
						 FROM OF_BillingElement__c
						 WHERE name = 'Contributo Verticale' LIMIT 1];

		standardPb = [SELECT id
					  FROM Pricebook2
					  WHERE isStandard = true LIMIT 1];
	}

	private void populateMaps(List<OF_Billing_Element_Verticale__c> listaBEV) {
		Set<Id> avIdSet = new Set<Id>();
		Set<Id> assetIdList = new Set<Id>();
		for (OF_Billing_Element_Verticale__c bev : listaBEV) {
			avIdSet.add(bev.Asset_Verticale__c);
			assetIdList.add(bev.Asset__c);
		}

		List<PricebookEntry> pbe_list = [SELECT id, name, Product2Id, OF_CommercialElementIstanziato__c, OF_Asset__c, IsActive,
										 OF_DataCessazione2__c
										 FROM PricebookEntry
										 WHERE Product2.Name = 'Contributo Verticale' AND IsActive = true AND OF_Asset__c IN :assetIdList];

		List<PricebookEntry> pbes_list = [SELECT id, name, Product2Id, OF_CommercialElementIstanziato__c, OF_Asset__c, IsActive,
										  OF_DataCessazione2__c
										  FROM PricebookEntry
										  WHERE Product2.Name = 'Contributo Storno Verticale' AND IsActive = true AND OF_Asset__c IN :assetIdList];

		for (PricebookEntry p : pbe_list) {
			mapPbe.put(p.OF_Asset__c, p);
		}
		for (PricebookEntry p : pbes_list) {
			mapPbeS.put(p.OF_Asset__c, p);
		}

		List<OF_Asset_Verticale__c> assetV_totali = [SELECT id, Name, Account__c, Cardinalita_Scala__c, Update_Billing__c, ID_GIS_Scala_Palazzina__c
													 FROM OF_Asset_Verticale__c
													 WHERE id IN :avIdSet];

		for (OF_Asset_Verticale__c av : assetV_totali) {
			mapAV.put(av.id, av);
		}

		List<OF_ContrattoServizio__c> listaContrattiServizio = [SELECT OF_Servizio__c, OF_Servizio__r.Id, OF_Contract__c
																FROM OF_ContrattoServizio__c
																WHERE OF_Servizio__r.Name like '%VERTICALE%'];


		Set<Id> listaServizioId = new Set<Id>();
		for (OF_ContrattoServizio__c cs : listaContrattiServizio) {
			mapServizi.put(cs.OF_Contract__c, cs);
			listaServizioId.add(cs.OF_Servizio__c);
		}

		List<OF_CommercialElementIstanziato__c> ceiv_totali = [SELECT Id, CreatedDate, Asset_Verticale__c, OF_Asset__c, OF_Stato__c, OF_DataCessazione__c, OF_DataAttivazione__c, OF_IDRisorsa__c, RecordTypeId, OF_BillingSyncronized__c
															   FROM OF_CommercialElementIstanziato__c
															   WHERE OF_CommercialElement__r.name = 'Servizio Verticale'
																   AND OF_Stato__c = 'Attivo' AND OF_Asset__c IN :assetIdList];

		for (OF_CommercialElementIstanziato__c cei : ceiv_totali) {
			mapIdCeiv.put(cei.OF_Asset__c, cei);
		}

		List<OF_CommercialElement__c> listaCEVert_totali = [SELECT id, name, OF_Servizio__c
															FROM OF_CommercialElement__c
															WHERE OF_Servizio__r.name LIKE '%VERTICALE%' AND OF_Servizio__c IN :listaServizioId];

		for (OF_CommercialElement__c ce : listaCEVert_totali) {
			mapCeXidServ.put(ce.OF_Servizio__c, ce);
		}

	}

	public void run(List<OF_Billing_Element_Verticale__c> listaBEV) {

		populateMaps(listaBEV);

		String prevOLO = null;
		String prevIdScala = null;

		for (OF_Billing_Element_Verticale__c bev : listaBEV) {
			String idScala = bev.Asset_Verticale__r.ID_GIS_Scala_Palazzina__c;
			String olo = bev.OLO__r.name;
			idScala_Olo = 'idScala: [' + bev.Asset_Verticale__c + '] - Olo: [' + olo + '] - idRisorsa: [' + bev.ID_Risorsa__c + ']';

			if (idScala.equals(prevIdScala)) {
				if (olo.equals(prevOLO)) {
					// Se già ho trovato un BEV per questa coppia <IdScala, OLO>
					// sicuramente sarà da eliminare perché la lista in input è ordinata per Data_Attivazione
					addStorno(bev, idScala, olo);
				} else {
					// Prima volta che incontro questo OLO per questa scala, quindi il bev sarà quello da tenere
					saveValidBev(bev, idScala);
				}
			} else {
				// Prima volta che incontro questa scala, quindi il bev sarà quello da tenere
				saveValidBev(bev, idScala);
			}

			prevIdScala = idScala;
			prevOLO = olo;
		}

		for (OF_Billing_Element_Verticale__c bev : invalidBEV) {
			bev.OF_Status__c = 'INATTIVO';
			bev.Update_Billing__c = true;
			bev.Asset_Verticale__c = null;
		}

		addBeiAndStornoToValidBev();
		updateDB();
	}

	private void saveValidBev(OF_Billing_Element_Verticale__c bev, String idScala) {
		List<OF_Billing_Element_Verticale__c> bevScalaList = mapScala_Bev.get(idScala);
		if (bevScalaList == null) {
			bevScalaList = new List<OF_Billing_Element_Verticale__c>();
			mapScala_Bev.put(idScala, bevScalaList);
		}
		bevScalaList.add(bev);
		validBEV.add(bev);
	}

	private void addBeiAndStornoToValidBev() {
		for (OF_Billing_Element_Verticale__c bev : validBEV) {
			String idScala = bev.Asset_Verticale__r.ID_GIS_Scala_Palazzina__c;
			String olo = bev.OLO__r.name;
			Set<String> oloList = mapScalaOloName.get(idScala);
			// se c'erano più record per questo OLO su questa scala
			if ((oloList != null) && oloList.contains(olo)) {
				idScala_Olo = 'idScala: [' + bev.Asset_Verticale__c + '] - Olo: [' + olo + '] - idRisorsa: [' + bev.ID_Risorsa__c + ']';
				System.debug('Valid - ' + idScala_Olo);
				System.debug('Già presente su questa scala? ' + (bev.LastModifiedDate < creationDateThresold));

				// Se il bev non esisteva già su questa scala devo creare cei & co
				if (bev.LastModifiedDate > creationDateThresold) {

					OF_CommercialElementIstanziato__c oldCei = mapIdCeiv.get(bev.Asset__c);
					// Se il bev è stato spostato aggiungo il bei e lo storno
					Boolean spostato = (bev.CreatedDate < creationDateThresold);
					System.debug('Spostato? ' + spostato);
					Boolean ceiCreatoDalloStep2 = (oldCei != null) && (oldCei.CreatedDate > creationDateThresold);
					System.debug('ceiCreatoDalloStep2? ' + ceiCreatoDalloStep2);
					if (spostato && !ceiCreatoDalloStep2) {
						createContributoStornoVerticale(bev, be_Storno, standardPb);
					}
					if ((spostato && !ceiCreatoDalloStep2) || (oldCei == null)) {
						// Se non c'era alcun CEI associato al bev, non c'era nemmeno un bei
						OF_CommercialElementIstanziato__c cei = createCEI(bev, rtCei);
						createContributoVerticale(bev, cei, be_Contributo, standardPb);
					} else if ((oldCei != null) && !mapPbe.containsKey(bev.Asset__c)) {
						// Se non è presente un BEI per questo CEI
						System.debug('Esisteva solo il CEI ma non il BEI per l\'asset ' + bev.Asset__c);
						createContributoVerticale(bev, oldCei, be_Contributo, standardPb);
					}
				} // altrimenti non faccio nulla perché l'ha già fatto lo step precedente
			}
		}
	}

	private void updateDB() {
		insert ceiToInsert;
		insert prodToInsert;
		for (BillingData bd : wrapList) {
			bd.pb.OF_CommercialElementIstanziato__c = bd.c.Id;
			bd.pb.Product2Id = bd.prod.Id;
		}

		List<OF_Asset_Verticale__c> avList = avToUpdate.values();
		for (OF_Asset_Verticale__c av : avList) {
			List<OF_Billing_Element_Verticale__c> bevScalaList = mapScala_Bev.get(av.ID_GIS_Scala_Palazzina__c);
			av.Cardinalita_Scala__c = bevScalaList.size();
		}

		if (!bevToDelete.isEmpty()) {
			List<OF_CommercialElementIstanziato__c> ceiToDelete = new List<OF_CommercialElementIstanziato__c>();
			List<PricebookEntry> pbeToDelete = new List<PricebookEntry>();
			for (OF_Billing_Element_Verticale__c bev : bevToDelete) {

				OF_CommercialElementIstanziato__c cei = mapIdCeiv.get(bev.Asset__c);
				if ((cei != null) && cei.Asset_Verticale__c.equals(bev.Asset_Verticale__c)) {
					ceiToDelete.add(cei);
					PricebookEntry pbToRemove = mapPbe.remove(bev.Asset__c);
					if ((pbToRemove != null) && pbToRemove.OF_CommercialElementIstanziato__c.equals(cei.id)) {
						pbeToDelete.add(pbToRemove);
					}
				}
			}

			List<Id> product2IdList = new List<Id>();
			for (PricebookEntry pbe : pbeToDelete) {
				product2IdList.add(pbe.Product2Id);
			}
			List<Product2> productToDelete = [SELECT Id FROM Product2 WHERE Id IN :product2IdList];

			delete pbeToDelete;
			delete productToDelete;
			delete ceiToDelete;
			delete bevToDelete;
		}

		insert new List<PricebookEntry>(pbeToInsert);
		update avList;
		update invalidBEV;
		update bevToUpdate.values();
		update pbToUpdate;
		update pbsToUpdate;
		update ceiToUpdate;
	}

	private void addStorno(OF_Billing_Element_Verticale__c bev, String idScala, String olo) {
		Set<String> oloList = mapScalaOloName.get(idScala);
		if (oloList == null) {
			oloList = new Set<String>();
			mapScalaOloName.put(idScala, oloList);
		}
		oloList.add(olo);

		Boolean isNew = (bev.CreatedDate > creationDateThresold);
		System.debug('Invalid - ' + idScala_Olo);
		System.debug('Is new? ' + isNew);

		OF_Asset_Verticale__c av = mapAV.get(bev.Asset_Verticale__c);
		if (av != null) {
			avToUpdate.put(av.Id, av);
		}

		// Se il bev è stato creato dallo step 2
		if (isNew) {
			// Devo cancellare BEV, CEI e BEI
			bevToDelete.add(bev);
		} else {
			invalidBEV.add(bev);
			// Altrimenti devo invalidare il CEI, aggiungere lo storno e cessare il CEI
			inactiveContributoVerticale(bev.Asset__c);
			if (av != null) {
				av.Update_Billing__c = true;
			}
			createContributoStornoVerticale(bev, be_Storno, standardPb);
			inactiveCEI(mapIdCeiv.remove(bev.Asset__c));
		}
	}

	private void inactiveContributoVerticale(Id assetId) {
		System.debug('* Inactive Contributo Verticale in corso *');

		PricebookEntry pbToRemove = mapPbe.remove(assetId);
		// Inattivo Contributo Verticale
		if (pbToRemove != null) {
			pbToUpdate.add(pbToRemove);
			pbToRemove.IsActive = false;
			pbToRemove.OF_DataCessazione2__c = now;
		}
	}

	private void inactiveContributoStornoVerticale(Id assetId) {
		System.debug('* Inactive Contributo Storno Verticale in corso *');

		PricebookEntry pbToRemoveS = mapPbeS.remove(assetId);
		// Inattivo Contributo Storno Verticale
		if ((pbToRemoveS != null) && !pbeToInsert.remove(pbToRemoveS)) {
			// Se il pbe non è stato creato da questo batch, allora è da modificare
			pbsToUpdate.add(pbToRemoveS);
			pbToRemoveS.IsActive = false;
			pbToRemoveS.OF_DataCessazione2__c = now;
		}
	}

	/* Creazione del CommercialElementIstanziato */
	private OF_CommercialElementIstanziato__c createCEI(OF_Billing_Element_Verticale__c bev, RecordType rtCei) {
		System.debug('* Ricerca CommercialElementIstanziato in corso *');

		OF_ContrattoServizio__c cs_curr = mapServizi.get(bev.Asset__r.OF_Contract__c);
		OF_CommercialElement__c servizioVerticale = mapCeXidServ.get(cs_curr.OF_Servizio__c);
		OF_Asset_Verticale__c av = mapAV.get(bev.Asset_Verticale__c);

		OF_CommercialElementIstanziato__c old_cei = mapIdCeiv.get(bev.Asset__c);
		inactiveCEI(old_cei);
		if (old_cei != null) {
			mapIdCeiv.remove(old_cei.OF_Asset__c);
			// return old_cei;
		}

		System.debug('* Creazione CommercialElementIstanziato in corso *');
		OF_CommercialElementIstanziato__c cei = new OF_CommercialElementIstanziato__c();
		cei.RecordTypeId = rtCei.id;
		cei.OF_Stato__c = 'Attivo';
		cei.OF_CommercialElement__c = servizioVerticale.id;
		cei.OF_Asset__c = bev.Asset__c;
		cei.OF_IDRisorsa__c = bev.ID_Risorsa__c;
		cei.OF_DataAttivazione__c = now;
		cei.OF_BillingSyncronized__c = false;
		if (av != null) {
			cei.Asset_Verticale__c = av.Id;
		}

		ceiToInsert.add(cei);

		mapIdCeiv.put(cei.OF_Asset__c, cei);

		return cei;
	}

	private void inactiveCEI(OF_CommercialElementIstanziato__c oldCeiv) {
		if (oldCeiv != null) {
			System.debug('* Cessazione CommercialElementIstanziato OLD in corso *');
			ceiToUpdate.add(oldCeiv);
			oldCeiv.OF_Stato__c = 'Cessato';
			oldCeiv.OF_DataCessazione__c = now;
		}
	}

	//Creazione del Product/PricebookEntry Contributo Storno Verticale
	private PricebookEntry createContributoStornoVerticale(OF_Billing_Element_Verticale__c bev, OF_BillingElement__c be, Pricebook2 standardPb) {
		inactiveContributoStornoVerticale(bev.Asset__c);
		System.debug('* Creazione Contributo Storno Verticale in corso *');

		OF_CommercialElementIstanziato__c cei = mapIdCeiv.get(bev.Asset__c);

		if (cei == null) {
			System.debug('* Nessun CEI per bev.Asset__c: ' + bev.Asset__c);
			return null;
		}
		Product2 p = createProd2(be.id, 'Contributo Storno Verticale');

		PricebookEntry pbe = createBEI(p.id, standardPb.id, cei, now);
		mapPbeS.put(pbe.OF_Asset__c, pbe);

		//bev.Update_Billing__c = true;
		//bevToUpdate.put(bev.Id, bev);

		wrapList.add(new BillingData(cei, p, pbe));

		return pbe;
	}

	private PricebookEntry createContributoVerticale(OF_Billing_Element_Verticale__c bev, OF_CommercialElementIstanziato__c cei, OF_BillingElement__c be, Pricebook2 standardPb) {
		inactiveContributoVerticale(bev.Asset__c);
		System.debug('* Creazione Contributo Verticale in corso *');

		Product2 p = createProd2(be.id, 'Contributo Verticale');

		PricebookEntry pbe = createBEI(p.id, standardPb.id, cei, now);
		mapPbe.put(pbe.OF_Asset__c, pbe);

		bev.Update_Billing__c = true;
		bevToUpdate.put(bev.Id, bev);

		wrapList.add(new BillingData(cei, p, pbe));

		return pbe;
	}

	private PricebookEntry createBEI(Id productId, Id standardPbId, OF_CommercialElementIstanziato__c cei, DateTime dataAttivazione) {
		PricebookEntry pbe = new PricebookEntry();
		pbe.Pricebook2Id = standardPbId;
		pbe.OF_DataAttivazione2__c = dataAttivazione;
		pbe.isActive = true;
		pbe.UseStandardPrice = false;
		pbe.UnitPrice = -9999;
		pbe.OF_Asset__c = cei.OF_Asset__c;
		pbe.OF_CommercialElementIstanziato__c = cei.id;
		pbe.Product2Id = productId;

		pbeToInsert.add(pbe);
		return pbe;
	}

	private Product2 createProd2(Id beId, String prodName) {
		Product2 p = new Product2();
		p.name = prodName;
		p.OF_BillingElement__c = beId;
		p.IsActive = true;

		prodToInsert.add(p);
		return p;
	}
}