objects/Asset.object
<CustomObject>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ID Risorsa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.OF_ServizioRichiesto__c</field>
                <operation>equals</operation>
                <valueField>Asset.RecordType.Name</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Servizi Extra</relationshipLabel>
        <relationshipName>Asset_Extra</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_Civico__c</fullName>
        <label>Civico</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ClusterPromozione__c</fullName>
        <label>Cluster Promozione</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_CodiceProgettoSpeciale__c</fullName>
        <label>Codice Progetto Speciale</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Comune__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IDServizio__c</fullName>
        <label>ID Servizio</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Indirizzo__c</fullName>
        <label>Indirizzo</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ProgettoSpeciale__c</fullName>
        <label>Progetto Speciale</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Promozione__c</fullName>
        <label>Promozione</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Rinnovabile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rinnovabile</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>PO_Asset_P2P_Attiva_KIT</fullName>
        <active>true</active>
        <label>P2P Attiva KIT</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da lavorare</fullName>
                </value>
                <value>
                    <fullName>Appuntamento Fissato</fullName>
                </value>
                <value>
                    <fullName>Da contattare</fullName>
                </value>
                <value>
                    <fullName>Desospeso</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione</fullName>
                </value>
                <value>
                    <fullName>In Verifica BO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Sospeso BO</fullName>
                </value>
                <value>
                    <fullName>Sospeso Tecn.</fullName>
                </value>
                <value>
                    <fullName>In assegnazione</fullName>
                </value>
                <value>
                    <fullName>Espletato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato KO</fullName>
                </value>
                <value>
                    <fullName>Espletato KO</fullName>
                </value>
                <value>
                    <fullName>Accettato KO</fullName>
                </value>
                <value>
                    <fullName>In Verifica Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Network Creation</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Delivery</fullName>
                </value>
                <value>
                    <fullName>Completato</fullName>
                </value>
                <value>
                    <fullName>Offerta Creata</fullName>
                </value>
                <value>
                    <fullName>Offerta Presentata</fullName>
                </value>
                <value>
                    <fullName>Richiesta modifica offerta da Cliente</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Referente Fattibilità</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Tecnico Fattibilità</fullName>
                </value>
                <value>
                    <fullName>Sospeso OM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_SA_Profilo__c</fullName>
        <label>Profilo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Case_Collegamento__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case Collegamento</description>
        <label>Case Collegamento</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases (Case Collegamento)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_Data_Espletamento_Ordine__c</fullName>
        <label>Data Espletamento Ordine</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_KIT_Consegna_VLAN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KIT Consegna VLAN</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Collegamenti</relationshipLabel>
        <relationshipName>Collegamenti_del_KIT</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>PO_Ordine_P2P_Attiva</fullName>
        <active>true</active>
        <businessProcess>PO_Support_Process</businessProcess>
        <label>PO Ordine P2P Attiva</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Rinnovabile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rinnovabile</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PO_Collegamento__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collegamento</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>PO Collegamento P2P, PO Collegamento Fiber Lease, PO Collegamento Fiber link, PO Collegamento IRU, PO Collegamento Misto Fiber Lease-Link per Fastweb</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>PO_SalesPrice__c</fullName>
        <label>SalesPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>NS_Rif__c</fullName>
        <label>NS. Rif.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Apparato__c</fullName>
        <label>Apparato</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_Civico__c</fullName>
        <label>Civico</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ClusterPromozione__c</fullName>
        <label>Cluster Promozione</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_CodiceProgettoSpeciale__c</fullName>
        <label>Codice Progetto Speciale</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Comune__c</fullName>
        <label>Comune</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_DataEsito__c</fullName>
        <label>Data esito</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_EsitoConsegnaApparato__c</fullName>
        <label>Esito consegna apparato</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Esito__c</fullName>
        <label>Esito</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>KO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OF_GPONAttestazione__c</fullName>
        <label>GPON Attestazione</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IDBuilding__c</fullName>
        <label>ID Building</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IDCaso__c</fullName>
        <formula>IF( OF_Type__c = &apos;INORDER&apos;,  OF_CaseID__c  ,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ID caso</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IDOrdineEOF__c</fullName>
        <label>ID Ordine EOF</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IDOrdineOLO__c</fullName>
        <label>ID Ordine OLO</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IDRisorsa__c</fullName>
        <label>ID Risorsa</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IDServizio__c</fullName>
        <label>ID Servizio</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IDSplitterSecondario__c</fullName>
        <label>IDSplitterSecondario</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_IdentificativoDelPOP__c</fullName>
        <label>Identificativo del POP</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Indirizzo__c</fullName>
        <label>Indirizzo</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ParticellaToponomastica__c</fullName>
        <label>Particella toponomastica</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_PasswordApparato__c</fullName>
        <label>Password Apparato</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_PosizioneSplitterSecondario__c</fullName>
        <label>PosizioneSplitterSecondario</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ProgettoSpeciale__c</fullName>
        <label>Progetto Speciale</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Promozione__c</fullName>
        <label>Promozione</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Provincia__c</fullName>
        <label>Provincia</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ScalaPalazzina__c</fullName>
        <label>Scala palazzina</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SlaPremiumAssurance__c</fullName>
        <label>SLA PREMIUM ASSURANCE</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>OF_INORDER</fullName>
        <active>true</active>
        <label>INORDER</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Billing_element__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing element</label>
        <referenceTo>OF_BillingElement__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_Commercial_element__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial element</label>
        <referenceTo>OF_CommercialElement__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

classes/PO_ServiziFattDOMKitHandler.cls
public without sharing class PO_ServiziFattDOMKitHandler extends PO_ServiziFattDOM {
    public PO_ServiziFattDOMKitHandler(String rTypeDevName) {
        super(rTypeDevName);
    }

    public override Id espletamentoOK(Case theCase) {
        theCase.Status = ESPLETATO_OK;
		theCase.EOF_Fase__c = ESPLETATO_OK;
		theCase.PO_Data_Espletamento_Ordine__c  = System.today();
        update theCase;
        System.debug('##### PO_ServiziFattDOMKitHandler.espletamentoOK - case updated ' + theCase.Id);
        return espletamento(theCase, true);
    }

    public override Id espletamento(Case theCase, Boolean esitoOK) {
        System.debug('##### PO_ServiziFattDOMKitHandler.espletamentoOK - START');
        Map<String, Id> map_rTypeDevNameId = PO_ServFatt_OpportunityHandler.getRtDevNameIdMap();

        Case caseOrdine = getCaseOrdine(theCase);
        Order orderCaseOrdine = getOrder(caseOrdine.OF_Order__c);
        String name = String.isNotBlank(orderCaseOrdine.OF_IDRisorsa__c) ? 
			orderCaseOrdine.OF_IDRisorsa__c : orderCaseOrdine.OF_IDOrdineEOF__c;
        
        Order orderKit = createOrderKit(theCase, orderCaseOrdine, map_rTypeDevNameId.get('OF_INORDER'), caseOrdine.OF_SA_Profilo__c);
        Asset assetKit = createAsset(orderKit, map_rTypeDevNameId.get('PO_Asset_P2P_Attiva_KIT'), 
			orderKit.OF_IDRisorsa__c, theCase, orderCaseOrdine.Contract.OF_Rinnovabile__c);

        List<OpportunityLineItem> oppLinItemList = [SELECT Id, PricebookEntryId, Price_Book__c, Price_Book__r.PO_Commercial_element__c, 
				Price_Book__r.PO_Commercial_element__r.Name, Price_Book__r.Billing_element__r.Name, Price_Book__r.Billing_element__c, 
				Quantity, Discount, ListPrice, PO_SalesPrice__c, TotalPrice, UnitPrice, Product2Id
			FROM OpportunityLineItem
			WHERE Opportunity.PO_Collegamento__c = :theCase.PO_Case_Collegamento__c 
			AND Price_Book__c != null
			AND Price_Book__r.PO_Commercial_element__r.Name =: KIT_COMMERCIAL_EL_NAME];
        System.debug('##### PO_ServiziFattDOMKitHandler.espletamentoOK  -- oppLinItemList from query : ' + oppLinItemList);

        String ceiRtId = map_rTypeDevNameId.get(srvData.ceiDevName__c);
		createBEI(assetKit, ceiRtId, oppLinItemList);
        System.debug('##### PO_ServiziFattDOMKitHandler.espletamentoOK - END');
        update theCase;
        //aggiornaLog(theCase);
        return assetKit.Id;
    }

    private Case getCaseOrdine(Case caseKit) {

		List<Case> l_ordine = [SELECT Id, OF_Order__c, OF_SA_Profilo__c FROM Case WHERE PO_KIT_Consegna_VLAN__c =: caseKit.Id
			AND RecordType.DeveloperName = 'PO_Ordine_P2P_Attiva'];
		System.debug('##### PO_ServiziFattDOMKitHandler.getCaseOrdine: ordine associato al kit: ' + l_ordine);
		return (l_ordine.isEmpty()) ? null : l_ordine[0];		
	}

    private static Order getOrder(Id oId) {
		List<Order> l_order = [SELECT Id, ContractId, Contract.OF_Rinnovabile__c, Contract.NS_Rif__c, AccountId, RecordTypeId, Status, OF_Esito__c, OF_Apparato__c,
				   OF_Asset__c, OF_DataEsito__c, OF_EsitoConsegnaApparato__c, OF_ScalaPalazzina__c,
				   OF_GPONAttestazione__c, OF_IDBuilding__c, OF_IDOrdineEOF__c, OF_IDOrdineOLO__c,
				   OF_IDRisorsa__c, OF_IDSplitterSecondario__c, OF_IdentificativoDelPOP__c,
				   OF_Provincia__c, OF_Comune__c, OF_ParticellaToponomastica__c, OF_Indirizzo__c, OF_Civico__c,
				   OF_PosizioneSplitterSecondario__c, OF_SlaPremiumAssurance__c, OF_ClusterPromozione__c,
				   OF_CodiceProgettoSpeciale__c, OF_IDCaso__c, OF_IDServizio__c, OF_PasswordApparato__c,
				   OF_ProgettoSpeciale__c, OF_Promozione__c, OF_TipologiaApparato__c, OF_ProfiloOpenStream__c,
				   PO_Attenuazione__c, PO_DataAttivazioneOrdine__c, PO_LunghezzaOttica__c, OF_Profilo__c,
				   OF_DescrizioneKO__c, effectiveDate, CreatedDate, OF_IDContratto__c,
				   NS_Rif__c,  // FD 2019-02-27
				   PO_PosizioneRilascioCircuitoOSU__c, OF_CodiceKO__c, (SELECT Accordo_Operativo__c FROM Cases__r)
				   FROM Order WHERE Id =: oId];
		return (l_order.isEmpty()) ? null : l_order[0];
	}

    private static Order createOrderKit(Case caseKit, Order o, String rtId, String profilo) {
		if (caseKit == null) {
			return null;
		}

		System.debug('createOrderKit for CaseKit: ' + caseKit.Id);

		Order orderKit = new Order();
		orderKit.recordtypeId = rtId;
		orderKit.OF_IdentificativoDelPOP__c = caseKit.EOF_Identificativo_del_POP__c;
		orderKit.OF_Esito__c = 'OK';
		orderKit.status = 'Chiuso';
		orderKit.OF_IDRisorsa__c = 'KIT_' + caseKit.EOF_Codice_Ordine_OLO__c; // caseKit.PO_PP_NomeKit__c; // Billing
		orderKit.OF_DataEsito__c = System.today(); // Billing
		orderKit.OF_IDOrdineOLO__c = caseKit.EOF_Codice_Ordine_OLO__c; // Billing
		orderKit.OF_Comune__c = o.OF_Comune__c; // Billing
		orderKit.OF_Provincia__c = o.OF_Provincia__c; // Billing
		orderKit.OF_Indirizzo__c = o.OF_Indirizzo__c; // Billing
		orderKit.OF_Civico__c = o.OF_Civico__c; // Billing
		orderKit.AccountId = o.AccountId; // Billing
		orderKit.ContractId = o.ContractId; // Billing
		orderKit.OF_ProfiloOpenStream__c = profilo;
		orderKit.effectiveDate = o.effectiveDate;
		orderKit.NS_Rif__c = String.isNotBlank(o.NS_Rif__c) ? o.NS_Rif__c : o.Contract.NS_Rif__c;
		if (o.PO_DataAttivazioneOrdine__c != null) {
			orderKit.PO_DataAttivazioneOrdine__c = o.PO_DataAttivazioneOrdine__c;
		}
		if (String.isNotBlank(o.OF_Profilo__c)) {
			orderKit.OF_Profilo__c = o.OF_Profilo__c;
		}

		insert orderKit;
		caseKit.OF_Order__c = orderKit.Id;

		return orderKit;
	}


}