objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Apparato__c</fullName>
        <label>Apparato</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Comune_WS__c</fullName>
        <label>Comune</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Comunicazioni_con_OLO__c</fullName>
        <label>Comunicazioni con OLO</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EOF_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da lavorare</fullName>
                </value>
                <value>
                    <fullName>Appuntamento Fissato</fullName>
                </value>
                <value>
                    <fullName>Da contattare</fullName>
                </value>
                <value>
                    <fullName>Desospeso</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione</fullName>
                </value>
                <value>
                    <fullName>In Verifica BO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Sospeso BO</fullName>
                </value>
                <value>
                    <fullName>Sospeso Tecn.</fullName>
                </value>
                <value>
                    <fullName>In assegnazione</fullName>
                </value>
                <value>
                    <fullName>Espletato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato KO</fullName>
                </value>
                <value>
                    <fullName>Espletato KO</fullName>
                </value>
                <value>
                    <fullName>Accettato KO</fullName>
                </value>
                <value>
                    <fullName>In Verifica Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Network Creation</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Delivery</fullName>
                </value>
                <value>
                    <fullName>Completato</fullName>
                </value>
                <value>
                    <fullName>Offerta Creata</fullName>
                </value>
                <value>
                    <fullName>Offerta Presentata</fullName>
                </value>
                <value>
                    <fullName>Richiesta modifica offerta da Cliente</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Referente Fattibilità</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Tecnico Fattibilità</fullName>
                </value>
                <value>
                    <fullName>Sospeso OM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_GPON_Attestazione__c</fullName>
        <label>GPON Attestazione</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Building_WS__c</fullName>
        <externalId>true</externalId>
        <label>ID Building</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Id_Risorsa__c</fullName>
        <label>Id Risorsa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Identificativo_del_POP__c</fullName>
        <label>Identificativo del POP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Indirizzo_WS__c</fullName>
        <label>Indirizzo</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Note_Interne__c</fullName>
        <label>Note Interne</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EOF_Note_Operatore__c</fullName>
        <label>Note Operatore</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EOF_Numero_Civico_WS__c</fullName>
        <label>Numero Civico</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Particella_Toponomastica_WS__c</fullName>
        <label>Particella Toponomastica</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Password_Apparato__c</fullName>
        <label>Password Apparato</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Progetto_Speciale__c</fullName>
        <label>Progetto Speciale</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Provincia_WS__c</fullName>
        <label>Provincia</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_SLA_Premium_Assurance__c</fullName>
        <label>SLA Premium Assurance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EOF_Scala_Palazzina_WS__c</fullName>
        <label>Scala Palazzina</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Tipologia_Apparato__c</fullName>
        <label>Tipologia Apparato</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note_Sospensione_Operatore__c</fullName>
        <label>Note Sospensione Operatore</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OF_Esito_Consegna_Apparato__c</fullName>
        <label>Esito Consegna Apparato</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_SA_CODICE_PROGETTO_SPECIALE__c</fullName>
        <label>Codice Progetto Speciale</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Cluster_Promozione__c</fullName>
        <label>Cluster Promozione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Codice_Motivazione__c</fullName>
        <label>Codice Motivazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Motivazione__c</fullName>
        <label>Motivazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Profilo__c</fullName>
        <label>Profilo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Promozione__c</fullName>
        <label>Promozione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Assegnazione_Area_Geografica__c</fullName>
        <label>Assegnazione Referente Area Geografica</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nord Est</fullName>
                </value>
                <value>
                    <fullName>Nord Ovest</fullName>
                </value>
                <value>
                    <fullName>Centro</fullName>
                </value>
                <value>
                    <fullName>Sud</fullName>
                </value>
                <value>
                    <fullName>Isole</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO_Attenuazione__c</fullName>
        <label>Attenuazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_BB_1_interessato__c</fullName>
        <label>BB 1° interessato (m)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PO_Data_Attivazione_Ordine__c</fullName>
        <label>Data Attivazione Ordine</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Drop_FL_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Drop FL (1)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PO_Esito_collegamento__c</fullName>
        <label>Esito collegamento</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SI Inf. + Scavo</fullName>
                </value>
                <value>
                    <fullName>SI Inf. Esistente</fullName>
                </value>
                <value>
                    <fullName>SI Inf. OP</fullName>
                </value>
                <value>
                    <fullName>SI in FTTH</fullName>
                </value>
                <value>
                    <fullName>SI On Net</fullName>
                </value>
                <value>
                    <fullName>SI Scavo</fullName>
                </value>
                <value>
                    <fullName>KO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO_Lunghezza_Ottica__c</fullName>
        <label>Lunghezza Ottica (m)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PO_Lunghezza_m__c</fullName>
        <label>Lunghezza Drop FL 1 (m)</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PO_Note_Network_Creation__c</fullName>
        <label>Note Network Creation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PO_Note_Referente_Fattibilita__c</fullName>
        <label>Note Referente Fattibilità</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Note_Sospensione_OF__c</fullName>
        <inlineHelpText>Descrivere le motivazioni di sospensione che verranno comunicate all&apos;Operatore</inlineHelpText>
        <label>Note Sospensione OF</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PO_Note_Supporto_Vendite__c</fullName>
        <label>Note Supporto Vendite</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Note_Tecnico_Fattibilita__c</fullName>
        <label>Note Tecnico Fattibilità</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Note_fattibilit__c</fullName>
        <label>Note fattibilità</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PO_Owner_Originario__c</fullName>
        <label>Owner Originario</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_P2P_Attiva__c</fullName>
        <defaultValue>false</defaultValue>
        <label>P2P Attiva</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PO_Posa_1_nuovo_Drop__c</fullName>
        <label>Posa 1 nuovo Drop (m)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PO_Posizione_Rilascio_Circuito_OSU__c</fullName>
        <label>Posizione RIlascio Circuito OSU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Richiesta_a_fattibilit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Richiesta a fattibilità</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Collegamenti</relationshipLabel>
        <relationshipName>Collegamenti</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>View_PopUp_PSM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>View_PopUp_PSM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isPSM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox che identifica un case di tipo PSM.</description>
        <label>isPSM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>view_error_file_PSM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>view_error_file_PSM</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PO_Attenuazione__c</fullName>
        <label>Attenuazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PO_ServFatt_CRMHandler_P2PAttiva_Test.cls
@isTest
public class PO_ServFatt_CRMHandler_P2PAttiva_Test {

	public static testMethod void testCRMHandler() {
		PO_ServFatt_DataFactory.WrapData data = PO_ServFatt_DataFactory.createP2PAttivaData();

		Case caseColleg = [SELECT Id, recordtypeid, EOF_Note_Operatore__c, Status, EOF_Note_Interne__c, EOF_Comunicazioni_con_OLO__c, recordType.Name,
						   EOF_Note__c, recordType.DeveloperName, PO_Note_fattibilit__c, PO_Assegnazione_Area_Geografica__c, EOF_Fase__c,
						   PO_Richiesta_a_fattibilit__c,PO_Richiesta_a_fattibilit__r.caseNumber, PO_Note_Network_Creation__c, PO_Note_Sospensione_OF__c, PO_Esito_collegamento__c,
						   PO_Data_Attivazione_Ordine__c, EOF_Id_Risorsa__c, PO_Note_Referente_Fattibilita__c, PO_Note_Tecnico_Fattibilita__c,
						   PO_Note_Supporto_Vendite__c, PO_BB_1_interessato__c, PO_Posa_1_nuovo_Drop__c, PO_Owner_Originario__c, PO_Drop_FL_1__c,
						   PO_Lunghezza_m__c, Owner.Id, Owner.Type, Note_Sospensione_Operatore__c, EOF_GPON_Attestazione__c, EOF_SLA_Premium_Assurance__c,
						   EOF_Apparato__c, EOF_Progetto_Speciale__c, EOF_Tipologia_Apparato__c, EOF_Password_Apparato__c, OF_SA_Profilo__c, OF_SA_Promozione__c,
						   OF_SA_CODICE_PROGETTO_SPECIALE__c, OF_SA_Cluster_Promozione__c, OF_Esito_Consegna_Apparato__c, OF_SA_Codice_Motivazione__c,
						   OF_SA_Motivazione__c, EOF_ID_Building_WS__c, EOF_Identificativo_del_POP__c, EOF_Comune_WS__c, EOF_Provincia_WS__c,
						   EOF_Particella_Toponomastica_WS__c, EOF_Indirizzo_WS__c, EOF_Numero_Civico_WS__c, EOF_Scala_Palazzina_WS__c, PO_Attenuazione__c,
						   PO_Lunghezza_Ottica__c, PO_Posizione_Rilascio_Circuito_OSU__c, OF_Order__c,view_PopUp_PSM__c,view_error_file_PSM__c, ParentId, PO_P2P_Attiva__c,
						   isPsm__c,isClosed,EOF_Codice_Operatore_WS__c,PO_Numero_fibre_richieste__c,PO_Tipo_percorso__c,PO_Costi_aggiuntivi_collegamento__c,
                           PO_Case_Collegamento__r.PO_Assegnazione_Area_Geografica__c,PO_KIT_Consegna_VLAN__c,PO_KIT_Consegna_VLAN__r.assetId,EOF_Codice_Ordine_OLO__c, AccountId,
                           OF_Order__r.ContractId, PO_Richiesta_a_fattibilit__r.PO_Offerta__c, PO_Costo_lavori_civili__c, PO_Costo_lavori_ottici__c, OF_IDContratto__c, PO_Accordo_Quadro__c, PO_Tipo_di_collegamento__c, PO_Tipologia_Offerta_ordine__c, PO_Offerta__c // RDG
                           FROM Case WHERE Id = :data.caseCollegamento.Id LIMIT 1];
        EOF_VLAN__c vlanObj = new EOF_VLAN__c();
        vlanObj.Caso__c = caseColleg.Id;
        insert vlanObj;
        
        Pricebook2 pb = new Pricebook2(
            Id = Test.getStandardPricebookId(),
			IsActive = true
		);

		update pb;

		Test.startTest();
		try {
			new PO_ServFatt_CRMHandler(null);
		} catch (InvalidParameterValueException e) {
			System.assertEquals(true, String.isNotBlank(e.getMessage()));
		}
		Opportunity oc = PO_ServFatt_OpportunityHandler.createOppChild(caseColleg);
		PO_ServFatt_CRMHandler_P2PAttiva crmh = new PO_ServFatt_CRMHandler_P2PAttiva(data.cs.caseDevName__c);
		crmh.espletamento(data.casePadre, true);
		crmh.espletamento(data.casePadre, false);
		Test.stopTest();
	}
}