objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Da lavorare</fullName>
                </value>
                <value>
                    <fullName>Appuntamento Fissato</fullName>
                </value>
                <value>
                    <fullName>Da contattare</fullName>
                </value>
                <value>
                    <fullName>Desospeso</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione</fullName>
                </value>
                <value>
                    <fullName>In Verifica BO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Sospeso BO</fullName>
                </value>
                <value>
                    <fullName>Sospeso Tecn.</fullName>
                </value>
                <value>
                    <fullName>In assegnazione</fullName>
                </value>
                <value>
                    <fullName>Espletato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato OK</fullName>
                </value>
                <value>
                    <fullName>Cessato KO</fullName>
                </value>
                <value>
                    <fullName>Espletato KO</fullName>
                </value>
                <value>
                    <fullName>Accettato KO</fullName>
                </value>
                <value>
                    <fullName>In Verifica Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Network Creation</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Delivery</fullName>
                </value>
                <value>
                    <fullName>Completato</fullName>
                </value>
                <value>
                    <fullName>Offerta Creata</fullName>
                </value>
                <value>
                    <fullName>Offerta Presentata</fullName>
                </value>
                <value>
                    <fullName>Richiesta modifica offerta da Cliente</fullName>
                </value>
                <value>
                    <fullName>In Lavorazione Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Supporto Vendite</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Referente Fattibilità</fullName>
                </value>
                <value>
                    <fullName>In Attesa Presa In Carico Tecnico Fattibilità</fullName>
                </value>
                <value>
                    <fullName>Sospeso OM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO_PP_Banda__c</fullName>
        <label>Banda</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_Interfaccia_Kit__c</fullName>
        <label>Interfaccia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_NomeKit__c</fullName>
        <label>Nome KIT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_POP__c</fullName>
        <label>POP di consegna</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_Posizione_ODF__c</fullName>
        <label>Posizione ODF</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_PP_Traffico__c</fullName>
        <label>Servizio Commerciale</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VULA Openstream Direct</fullName>
                </value>
                <value>
                    <fullName>BITSTREAM</fullName>
                </value>
                <value>
                    <fullName>VULA</fullName>
                </value>
                <value>
                    <fullName>VULA Direct</fullName>
                </value>
                <value>
                    <fullName>VULA Openstream City Edge</fullName>
                </value>
                <value>
                    <fullName>BITSTREAM - Openstream Regional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PO_PP_EditFieldsCaseKit.cls
public class PO_PP_EditFieldsCaseKit {

    public String idCaseKit {get;set;}
    public Case caseKit {get;set;}

    public SelectOption[] elencoTraffico {
    	public get;
    	private set;
    }
    public SelectOption[] elencoInterfacce {
    	public get;
    	private set;
    }
    
    //costruttore    
    public PO_PP_EditFieldsCaseKit(ApexPages.StandardController stdController)
    {
        //caseKit = (Case)stdController.getRecord();
     	idCaseKit = ApexPages.currentPage().getParameters().get('Id');
     
     	System.debug(']]]]idCaseKit]]]]: '+idCaseKit);
        
     	//Query sul Case
     	caseKit = [Select id, status, PO_PP_Posizione_ODF__c,PO_PP_NomeKit__c, PO_PP_POP__c, PO_PP_Traffico__c, PO_PP_Banda__c,
     	           PO_PP_Interfaccia_Kit__c, EOF_Fase__c
                   from Case
                   where id=:idCaseKit
 	              ];
 	    
 	    String[] traffico = new String[]{'VULA','VULA Direct','BITSTREAM'};
		this.elencoTraffico = new SelectOption[]{};
		
		for (String t: traffico) {
			this.elencoTraffico.add(new SelectOption(t,t));
		}
		
		String[] interfaccia = new String[]{'None','1 Giga','10 Giga'};
		this.elencoInterfacce = new SelectOption[]{};
		
        for (String i: interfaccia) {
			this.elencoInterfacce.add(new SelectOption(i,i));
		}
    }
    
    public pageReference aggiornaDati()
    {
        update caseKit;
        PageReference pg = new PageReference('/'+caseKit.id);
        return pg;   
    }
    
    public pageReference annulla()
    {
        PageReference pg = new PageReference('/'+caseKit.id);
        return pg;   
    }
}