objects/Case.object
<CustomObject>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <externalId>true</externalId>
        <label>Codice Ordine OLO</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_VLAN__c.object
<CustomObject>
    <fields>
        <fullName>Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>VLAN</relationshipLabel>
        <relationshipName>VLAN1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVLANID__c</fullName>
        <label>SVLANID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>VLAN</label>
    <nameField>
        <displayFormat>VLAN-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VLANs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StatusUpdateP2PHelper.cls
public without sharing class StatusUpdateP2PHelper {

    public StatusUpdateP2PHelper() {

    }

    public Id updateVlan(String codeOrdineOlo, String svlanId) {
        System.debug('updateVlan, start updating...');
        Id collegId = findCollegamentoByOrdine(codeOrdineOlo);
        EOF_VLAN__c vlan = findVlan(collegId);
        vlan.svlanId__c = svlanId;
        update vlan;
        System.debug('svlanId__c field updated...');
        return vlan.Id;
    }

    public Id findCollegamentoByOrdine(String codeOrdineOlo) {
        System.debug('findCollegamentoByOrdine, searching case ordine...EOF_Codice_Ordine_OLO__c: ' + codeOrdineOlo);
        List<Case> ordine = [SELECT parentId FROM Case WHERE EOF_Codice_Ordine_OLO__c =: codeOrdineOlo];
        if(!ordine.isEmpty()) {
            System.debug('Case ordine found, id: ' + ordine[0].Id);
            return ordine[0].parentId;
        } else {
            throw new InvalidParameterValueException('StatusUpdateP2PHelper.findCollegamentoByOrdine', 'Case ordine not found. codeOrdineOlo: ' + codeOrdineOlo);
        }
    }

    public EOF_VLAN__c findVlan(Id collegamentoId) {
        System.debug('findVlan, searching vlan...id collegamento: ' + collegamentoId);
        List<EOF_VLAN__c> vlans = [SELECT svlanId__c FROM EOF_VLAN__c WHERE Caso__c =: collegamentoId];
        if(!vlans.isEmpty()) {
            System.debug('Vlan found, id: ' + vlans[0].Id);
            return vlans[0];
        } else {
            throw new InvalidParameterValueException('StatusUpdateP2PHelper.findVlan', 'Vlan not found. Caso__c: ' + collegamentoId);
        }
    } 
}