objects/Case.object
<CustomObject>
    <fields>
        <fullName>OF_Bonifica_Locked_Row__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bonifica Locked Row</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_Bypassa_SLA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypassa SLA</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>EAI Service Logs (Caso)</relationshipLabel>
        <relationshipName>EAI_Service_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_Tipo_Comunicazione_String__c</fullName>
        <label>Tipo Comunicazione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_Metodo__c</fullName>
        <label>Metodo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <recordTypes>
        <fullName>FiberRequest</fullName>
        <active>true</active>
        <label>FiberRequest</label>
    </recordTypes>
    <recordTypes>
        <fullName>OF_SA_FiberRequest</fullName>
        <active>true</active>
        <label>OF - SA - FiberRequest</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OF_SyncCaseInviato_step02_Batch.cls
//GB OK

global class OF_SyncCaseInviato_step02_Batch implements Database.AllowsCallouts,Database.Batchable<sObject>, Database.Stateful {
        
    private Set<String> logDevNames = new Set<String>{'OF_SA_FiberRequest', 'FiberRequest'};
    private Set<String> tipoComunicazione = new Set<String>{'OLO->SF - ActivationRequest', 'OLO->SF - FiberRequest - Attivazione', 'OLO->SF - FiberRequest - Cessazione', 'OLO->SF - DeactivationRequest'};


    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('@@@@ Inizio Batch 2: ' + system.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ'));
            
        String query = 'SELECT Id, Caso__r.Id, RecordType.DeveloperName, OF_SA_Metodo__c'
            + ' FROM EOF_EAI_Service_Log__c ';
        if(Test.isRunningTest()){
          query = query +'order by createddate desc limit 1';
        }    
        else{
          query = query + ' WHERE Caso__r.status=\'Inviato\' and Caso__r.OF_Bonifica_Locked_Row__c=true and Caso__r.OF_bypassa_SLA__c=true AND RecordType.DeveloperName IN :logDevNames AND EOF_Tipo_Comunicazione_String__c IN :tipoComunicazione ORDER BY createdDate ASC';
            //query = query + ' WHERE Caso__c=\'5004E000009IWumQAG\' AND RecordType.DeveloperName IN :logDevNames AND EOF_Tipo_Comunicazione_String__c IN :tipoComunicazione ORDER BY createdDate ASC';
        }
        system.debug('@@@@query ' + query);

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<EOF_EAI_Service_Log__c> scope) {
        
        for(EOF_EAI_Service_Log__c sl : scope){
            try{
            if('FiberRequest'.equalsIgnoreCase(sl.RecordType.DeveloperName)){
                OM_GW_Utils.checkAsyncSync(sl.Caso__r.Id, sl.Id);
            } else if('OF_SA_FiberRequest'.equalsIgnoreCase(sl.RecordType.DeveloperName)) {
                if('OLO_ActivationSetup_OpenStream'.equalsIgnoreCase(sl.OF_SA_Metodo__c)){
                    OF_SA_OLO_AsyncChecks.OLO_AsyncActivationSync(sl.Caso__r.Id, sl.Id);
                } else  if('OLO_DeactivationOrder'.equalsIgnoreCase(sl.OF_SA_Metodo__c)){
                    OF_SA_OLO_AsyncChecks.OLO_AsyncDeactivationSync(sl.Caso__r.Id, sl.Id);
                }
            }
            }
            catch(Exception e){
              system.debug('e'+e);
            }
        }
    }

    global void finish(Database.BatchableContext BC) {
        
    }
}