objects/Case.object
<CustomObject>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <description>Campo che indica il tipo di servizio (GPON Passiva o Open Stream).
Utilizzato per filtrare i casi negli asset intervento a vuoto</description>
        <label>Servizio</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Costi_aggiuntivi_collegamento__c</fullName>
        <formula>PO_Costo_lavori_civili__c +  PO_Costo_lavori_ottici__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Costi Totali</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO_Incluso_nell_offerta__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Incluso nell&apos;offerta</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>PO_Collegamento_P2P_Attiva</fullName>
        <active>true</active>
        <businessProcess>PO_Support_Process</businessProcess>
        <label>PO Collegamento P2P Attiva</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OF_CommercialElement__c.object
<CustomObject>
    <fields>
        <fullName>ID_Prod__c</fullName>
        <externalId>true</externalId>
        <label>ID Prod</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Attivo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attivo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_DataFineValidita__c</fullName>
        <label>Data fine validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataInizioValidita__c</fullName>
        <label>Data inizio validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Servizio</label>
        <referenceTo>OF_Servizio__c</referenceTo>
        <relationshipLabel>Commercial elements</relationshipLabel>
        <relationshipName>CommercialElements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Commercial element</label>
    <nameField>
        <label>Commercial element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_CommercialElementIstanziato__c.object
<CustomObject>
    <fields>
        <fullName>OF_ClusterPromozione__c</fullName>
        <formula>OF_Case__r.OF_SA_Cluster_Promozione__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster Promozione</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_CodiceProgettoSpeciale__c</fullName>
        <formula>OF_Case__r.OF_SA_CODICE_PROGETTO_SPECIALE__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Codice Progetto Speciale</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_CommercialElement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial element</label>
        <referenceTo>OF_CommercialElement__c</referenceTo>
        <relationshipLabel>Commercial element istanziati</relationshipLabel>
        <relationshipName>Commercial_element_istanziati</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_Promozione__c</fullName>
        <formula>OF_Case__r.OF_SA_Promozione__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Promozione</label>
        <type>Text</type>
    </fields>
    <label>Commercial element istanziato</label>
    <nameField>
        <displayFormat>CEI-{00000}</displayFormat>
        <label>Commercial element istanziato Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commercial element istanziati</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Listino__c.object
<CustomObject>
    <fields>
        <fullName>ID_Prod__c</fullName>
        <externalId>true</externalId>
        <label>ID Prod</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Attivo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attivo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_ClusterPromozione__c</fullName>
        <label>Cluster Promozione</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_CodiceProgettoSpeciale__c</fullName>
        <label>Codice Progetto Speciale</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_CommercialElement__c</fullName>
        <formula>IF(
OF_ServizioBillingElement__c != null, OF_ServizioBillingElement__r.OF_BillingElement__r.OF_CommercialElement__r.Name,
   IF(
     PO_Servizio_Billing_Element_Fattibilita__c != null, 
     PO_Servizio_Billing_Element_Fattibilita__r.OF_BillingElement__r.OF_CommercialElement__r.Name,
     &apos;&apos;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial element</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_DataFineValidita__c</fullName>
        <label>Data fine validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataInizioValidita__c</fullName>
        <label>Data inizio validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_IDContract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ID Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Listini</relationshipLabel>
        <relationshipName>Listini</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_ListinoDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Listino Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_ProgettoSpeciale__c</fullName>
        <label>Progetto Speciale</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Promozione__c</fullName>
        <label>Promozione</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_ServizioBillingElement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Element</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.OF_IDContract__c</field>
                <operation>equals</operation>
                <valueField>OF_ServizioBillingElement__c.OF_Contract__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>OF_ServizioBillingElement__c</referenceTo>
        <relationshipLabel>Listini</relationshipLabel>
        <relationshipName>Listini</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <formula>IF( 
OF_ServizioBillingElement__c != null, OF_ServizioBillingElement__r.OF_BillingElement__r.OF_CommercialElement__r.OF_Servizio__r.Name, 
 IF( 
 PO_Servizio_Billing_Element_Fattibilita__c != null, 
 PO_Servizio_Billing_Element_Fattibilita__r.OF_BillingElement__r.OF_CommercialElement__r.OF_Servizio__r.Name, 
 &apos;&apos;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servizio</label>
        <type>Text</type>
    </fields>
    <label>Listino</label>
    <nameField>
        <label>Listino Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listini</pluralLabel>
    <recordTypes>
        <fullName>OF_Open_Stream</fullName>
        <active>true</active>
        <label>Open Stream</label>
    </recordTypes>
    <recordTypes>
        <fullName>PO_Fattibilita</fullName>
        <active>true</active>
        <label>Fattibilità</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_Servizio__c.object
<CustomObject>
    <fields>
        <fullName>OF_Attivo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attivo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_DataFineValidita__c</fullName>
        <label>Data fine validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_DataInizioValidita__c</fullName>
        <label>Data inizio validità</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Servizio</label>
    <nameField>
        <label>Servizio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servizi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OF_ServizioBillingElement__c.object
<CustomObject>
    <fields>
        <fullName>OF_CommercialElement__c</fullName>
        <formula>OF_BillingElement__r.OF_CommercialElement__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial element</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Servizio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Servizio</label>
        <referenceTo>OF_Servizio__c</referenceTo>
        <relationshipLabel>Servizi Billing Elements</relationshipLabel>
        <relationshipName>Servizi_Billing_Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Servizio Billing Element</label>
    <nameField>
        <label>Billing Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servizi Billing Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PO_Canone_collegamento__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Canone collegamento</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO_Collegamento__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collegamento</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>PO Collegamento P2P, PO Collegamento Fiber Lease, PO Collegamento Fiber link, PO Collegamento IRU, PO Collegamento Misto Fiber Lease-Link per Fastweb</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_Contratto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contratto</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_Contributo_attivazione_collegamento__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Contributo attivazione collegamento</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO_Costi_aggiuntivi_collegamento__c</fullName>
        <formula>PO_Collegamento__r.PO_Costi_aggiuntivi_collegamento__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Costi aggiuntivi collegamento</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO_Incluso_nell_offerta__c</fullName>
        <formula>PO_Collegamento__r.PO_Incluso_nell_offerta__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Incluso nell&apos;offerta</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PO_Offerta_totale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offerta totale</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_Richiesta_fattibilit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Richiesta fattibilità</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>PO Richiesta a servizio a fattibilità</value>
            </filterItems>
            <filterItems>
                <field>$Source.PO_Collegamento__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities (Richiesta fattibilità)</relationshipLabel>
        <relationshipName>Offerta_richiesta_fattibilit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_Sconto_costi_aggiuntivi_collegamento__c</fullName>
        <formula>PO_Offerta_totale__r.PO_Sconto_costi_aggiuntivi__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sconto costi aggiuntivi collegamento %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PO_Special_Terms__c</fullName>
        <defaultValue>&quot;60 giorni data fattura mediante bonifico bancario;&quot; &amp; BR() &amp; &quot;I.V.A. esclusa, da applicare a norma di legge.&quot;</defaultValue>
        <label>Special Terms</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PO_Totale_canoni__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Totale canoni</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO_Totale_contributi_attivazione__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Totale contributi attivazione</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO_Totale_costi_aggiuntivi__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Totale costi aggiuntivi</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO_oppty_validit_offerta__c</fullName>
        <defaultValue>&quot;30 giorni dalla data della presente;&quot;</defaultValue>
        <label>Validità Offerta</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>PO_Oppty_Richiesta_fattibilit</fullName>
        <active>true</active>
        <businessProcess>PO Oppty collegamenti</businessProcess>
        <label>PO Oppty Richiesta fattibilità</label>
    </recordTypes>
    <recordTypes>
        <fullName>PO_Oppty_collegamenti</fullName>
        <active>true</active>
        <businessProcess>PO Oppty collegamenti</businessProcess>
        <label>PO Oppty collegamenti</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PO_P2P_Attiva_Utils.cls
public class PO_P2P_Attiva_Utils {
//     public static boolean checkRTMap = false;
//     public static map<String,Id> RTMap;
//     public static String specialTerms= '60 giorni data fattura mediante bonifico bancario; I.V.A. esclusa, da applicare a norma di legge.';
//     public static String OpptyValiditaOfferta='30 giorni dalla data della presente;';
//     public static String rtCollCaseDevName='PO_Oppty_collegamenti';
//     public static String rtFattCaseDevName='PO_Oppty_Richiesta_fattibilit';
//     public static ID pb2Id;
//     public static OF_Listino__c listino;
   
    public  PO_P2P_Attiva_Utils (){
        
    }
//     public static void creaP2PAttOpportunity(Case fattCase, Case collCase){
//         PO_P2P_Attiva_Utils.RTMap = new map<String,Id>();
//         for(recordtype rt : [select id,developername from recordtype]){
//             PO_P2P_Attiva_Utils.RTMap.put(rt.developername,rt.id);
//         }
//         System.debug('@@@ FD collCase.RecordType.DeveloperName ' + collCase.RecordType.DeveloperName);
//         if(collCase.RecordType.DeveloperName=='PO_Collegamento_P2P_Attiva'){
            
//             Opportunity oppFatt = new Opportunity();
            
//             // oppFatt.ACCOUNTID=fattCase.Account;
//             oppFatt.RECORDTYPEID=PO_P2P_Attiva_Utils.RTMap.get(rtFattCaseDevName);
//             oppFatt.NAME='OffertaTotale';
//             oppFatt.STAGENAME='Prospecting';
//             oppFatt.PROBABILITY=10.0;
//             //oppFatt.PRICEBOOK2ID='';
//             oppFatt.OWNERID=userinfo.getUserId();
//             //oppFatt.PO_COLLEGAMENTO__C='';
//             //  oppFatt.PO_OFFERTA_TOTALE__C=20;
//             oppFatt.PO_RICHIESTA_FATTIBILIT__C= fattCase.id ;
//             oppFatt.PO_SPECIAL_TERMS__C=specialTerms;
//             oppFatt.PO_OPPTY_VALIDIT_OFFERTA__C= OpptyValiditaOfferta;
//             oppFatt.CloseDate=system.today().addDays(30);
//             insert oppFatt; 
            
//             Opportunity oppColl = new Opportunity();  
//             // oppColl.ACCOUNTID = collCase.Account;
//             oppColl.RECORDTYPEID = PO_P2P_Attiva_Utils.RTMap.get(rtCollCaseDevName);
//             oppColl.NAME = 'Offerta Collegamento';
//             oppColl.STAGENAME = 'Prospecting';
//             oppColl.PROBABILITY = 10.0;
//             //oppColl.PRICEBOOK2ID = pb2Id;
//             oppColl.OWNERID = userinfo.getUserId();
//             oppColl.PO_COLLEGAMENTO__C = collCase.id;
//             oppColl.PO_OFFERTA_TOTALE__C = oppFatt.id;
//             oppColl.PO_SPECIAL_TERMS__C = specialTerms;								
//             oppColl.PO_OPPTY_VALIDIT_OFFERTA__C = OpptyValiditaOfferta ;
//             oppColl.CloseDate=system.today().addDays(30);
//             insert oppColl; 
            
//             /*
// PO_Incluso_nell_offerta__c,PO_Offerta_totale__c, PO_Contratto__c, PO_Contributo_attivazione_collegamento__c,PO_Collegamento__c,
// PO_Canone_collegamento__c ,PO_Costi_aggiuntivi_collegamento__c,PO_Totale_canoni__c,
// PO_Sconto_costi_aggiuntivi_collegamento__c, //CRM 31/07/2017 Aggiunti campi
// PO_Totale_contributi_attivazione__c,PO_Totale_costi_aggiuntivi__c 
// */   
//         }   
        
//     }
//     /*
// 	public static Map<String,EmailTemplate> ritornaTemplates(List<String> listaNameTemplate){
// 		Map<String,EmailTemplate> mappaT=new Map<String,EmailTemplate>();
// 		List<EmailTemplate> et=[Select id, Name, subject, body, FolderId, Folder.Name, HtmlValue from 	EmailTemplate where Folder.Name=:eTfolderName and Name=:listaNameTemplate];
// 		for(EmailTemplate el:et){
// 		   mappaT.put(el.Name,el);
// 		}
// 		return mappaT;
// 	}
// 	*/
    
//     public static Map<String,OF_Listino__c> getListino(List<String> listaStringhe){
//         Map<String,OF_Listino__c> nListinoMap = NEW Map<String,OF_Listino__c>();
//         For(OF_Listino__c l1 :[Select id, Name, RecordTypeId, RecordType.DeveloperName, OF_Attivo__c,
//                               OF_ServizioBillingElement__c,OF_ClusterPromozione__c,OF_CodiceProgettoSpeciale__c,
//                               OF_CommercialElement__c,OF_DataFineValidita__c, OF_DataInizioValidita__c,OF_IDContract__c,
//                               ID_Prod__c,OF_ListinoDefault__c,OF_ProgettoSpeciale__c,OF_Promozione__c,OF_Servizio__c,
//                               PO_Servizio_Billing_Element_Fattibilita__c,OF_TipologiaApparato__c from OF_Listino__c where RecordType.DeveloperName =:listaStringhe]){ //OF_Servizio__c is a formulaField
//                               ///*'OF_Open_Stream' OR RecordType.DeveloperName='PO_Fattibilita'*/     
//                                   nListinoMap.put(l1.RecordType.DeveloperName,l1);                  
//                               }
// 	   //     listino= PO_P2P_Attiva_Utils.nListinoMap.get('');
//             return nListinoMap;
//     }
    
//     public Map<String,OF_CommercialElementIstanziato__c> mappaNomeCeI(){
//         Map<String,OF_CommercialElementIstanziato__c> nCeiMap = new Map<String,OF_CommercialElementIstanziato__c>();
//         for(OF_CommercialElementIstanziato__c cei: [Select id, Name from OF_CommercialElementIstanziato__c]){        
//             nCeiMap.put(cei.Name,cei); 
//         }
//         return nCeiMap;
//     }
    
   
}