objects/CQS_Allegati__c.object
<CustomObject>
    <description>this object has been created to &quot;customize&quot; attachment</description>
    <fields>
        <fullName>CQS_All_Tipo_Allegato__c</fullName>
        <label>Tipo di Allegato</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>----------------------------------</fullName>
                </value>
                <value>
                    <fullName>Documento Pre Ripristino</fullName>
                </value>
                <value>
                    <fullName>Documento Post Ripristino</fullName>
                </value>
                <value>
                    <fullName>Verbale Rilascio Ente Gestore</fullName>
                </value>
                <value>
                    <fullName>Altro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CQS_All_ev__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evento</label>
        <referenceTo>OF_CQS_Evento__c</referenceTo>
        <relationshipLabel>Allegati</relationshipLabel>
        <relationshipName>CQS_Allegati</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CQS_Ev_Allegato__c</fullName>
        <label>Allegato</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Allegato</label>
    <nameField>
        <label>Nome Allegato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allegati</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CQS_Progetto__c.object
<CustomObject>
    <description>This object is a CQS&apos;s Object. It is used to store Projects information. Events and Inspections are related with it. Furthermore it could be used to check new Events/Inspections insert</description>
    <fields>
        <fullName>CQS_Pro_Area__c</fullName>
        <label>Area/Lotto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Progetto</label>
    <nameField>
        <label>Progetto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progetti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OF_CQS_Anagrafica__c.object
<CustomObject>
    <fields>
        <fullName>CQS_Check_Affidataria__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Attributo che caratterizza un&apos; impresa titolare di contratto d’appalto con OF</inlineHelpText>
        <label>Affidataria</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Numero_Civico__c</fullName>
        <label>Numero Civico</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Anagrafica</label>
    <nameField>
        <label>Ragione Sociale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anagrafiche</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OF_CQS_Evento__c.object
<CustomObject>
    <fields>
        <fullName>CQS_Ev_Progetto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Progetto</label>
        <referenceTo>CQS_Progetto__c</referenceTo>
        <relationshipLabel>Eventi</relationshipLabel>
        <relationshipName>Eventi</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Data_Evento__c</fullName>
        <label>Data Evento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Diffida__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Diffida</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Impresa_Esecutrice_Eventi__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Selezionare Impresa esecutrice utilizzando il comando di ricerca</inlineHelpText>
        <label>Impresa Esecutrice</label>
        <referenceTo>OF_CQS_Anagrafica__c</referenceTo>
        <relationshipLabel>Eventi Impresa Esecutrice</relationshipLabel>
        <relationshipName>Eventi_Impresa_Esecutrice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Impresa_Mandataria__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Selezionare Impresa affidataria utilizzando il comando di ricerca.</inlineHelpText>
        <label>Impresa Affidataria</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 1)</booleanFilter>
            <filterItems>
                <field>OF_CQS_Anagrafica__c.CQS_Check_Affidataria__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>OF_CQS_Anagrafica__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Imprese in raggruppamento</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OF_CQS_Anagrafica__c</referenceTo>
        <relationshipLabel>Eventi Impresa Mandataria</relationshipLabel>
        <relationshipName>Eventi_Impresa_Mandataria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Inadempienze_Operative__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inadempienze Operative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Numero_Civico__c</fullName>
        <label>Numero Civico</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_CQS_Richiesta_Danni__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Richiesta Danni</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_CQS_ev_Segnalazione_Comune__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Segnalazione Comune</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VIA__c</fullName>
        <label>Indirizzo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Evento</label>
    <nameField>
        <displayFormat>Inc-{0000000}</displayFormat>
        <label>Evento Numero</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventi</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CQS_Allegato_customController_Test.cls
@isTest
public class CQS_Allegato_customController_Test{
    public static testMethod void CQSMethod(){
        Id RecordTypeIdeven = Schema.SObjectType.OF_CQS_Evento__c.getRecordTypeInfosByName().get('Bad Practice').getRecordTypeId();
        
        OF_CQS_Anagrafica__c ana = new OF_CQS_Anagrafica__c();
        ana.CQS_Check_Affidataria__c = true;
        ana.Name = 'TESTANA';
        insert ana;
        
        CQS_Progetto__c pro = new CQS_Progetto__c();
        pro.Name = 'Test';
        pro.CQS_Pro_Area__c = 'Test';
        insert pro;
        
        OF_CQS_Evento__c Evento = new OF_CQS_Evento__c();
        Evento.OF_CQS_Impresa_Esecutrice_Eventi__c = ana.Id;
        Evento.OF_CQS_Impresa_Mandataria__c = ana.Id;
        Evento.OF_CQS_Data_Evento__c = system.today();
        Evento.VIA__c = 'ROSSI';
        Evento.OF_CQS_Numero_Civico__c = '3';
        Evento.RecordTypeId = RecordTypeIdeven;
        Evento.OF_CQS_Diffida__c = FALSE;
        Evento.OF_CQS_Richiesta_Danni__c = FALSE;
        Evento.OF_CQS_Inadempienze_Operative__c = FALSE;
        Evento.OF_CQS_ev_Segnalazione_Comune__c= True;
        evento.CQS_Ev_Progetto__c = pro.Id;
        insert Evento;
        
        Attachment attach=new Attachment();     
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=Evento.id;
        insert attach;
        
        CQS_Allegati__c alle = new CQS_Allegati__c();
        alle.Name = 'MailError.PNG';
        alle.CQS_All_ev__c = Evento.Id;
        alle.CQS_All_Tipo_Allegato__c = 'Altro';
        alle.CQS_Ev_Allegato__c = '00P8E000005csd9UAA';
        insert alle;
        
        ApexPages.currentPage().getParameters().put('evId',Evento.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(Evento);
        CQS_Allegato_customController allega = new CQS_Allegato_customController (sc);
        allega.fileName = attach.name;
        allega.fileBody = attach.body;
        allega.back();
        allega.processUpload();
      //  public void callMethod(){
        //    if(Test.isRunningTest()){
        allega.callMethod();
     //       }
        //}
       
        //allega.saveStandardAttachment(attach.id);
        //
        //allega.saveCustomAttachment();
        
    }
    
    
    
}