objects/CQS_Progetto__c.object
<CustomObject>
    <description>This object is a CQS&apos;s Object. It is used to store Projects information. Events and Inspections are related with it. Furthermore it could be used to check new Events/Inspections insert</description>
    <fields>
        <fullName>CQS_Pro_Area__c</fullName>
        <label>Area/Lotto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Progetto</label>
    <nameField>
        <label>Progetto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progetti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OF_CQS_Ispezione__c.object
<CustomObject>
    <fields>
        <fullName>CQS_ISP_Accantieramento_conforme__c</fullName>
        <defaultValue>&quot;N/A&quot;</defaultValue>
        <inlineHelpText>L’accantieramento risulta conforme, ordinato e salubre</inlineHelpText>
        <label>Accantieramento conforme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sì</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CQS_ISP_Progetto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Progetto</label>
        <referenceTo>CQS_Progetto__c</referenceTo>
        <relationshipLabel>Ispezioni</relationshipLabel>
        <relationshipName>Ispezioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ispezione</label>
    <nameField>
        <displayFormat>Isp-{0000}</displayFormat>
        <label>Ispezione</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ispezioni</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CQS_Isp_SignatureComponentCtrl_Test.cls
@isTest
public class CQS_Isp_SignatureComponentCtrl_Test{
    public static testMethod void IspMethod(){
        
        
        CQS_Progetto__c pro = new CQS_Progetto__c();
        pro.Name = 'Test';
        pro.CQS_Pro_Area__c = 'Test';
        insert pro;
        
        List<OF_CQS_Ispezione__c> cqsList = new List<OF_CQS_Ispezione__c>();
        OF_CQS_Ispezione__c cqs = new OF_CQS_Ispezione__c();
        cqs.CQS_ISP_Accantieramento_conforme__c = 'Sì';
        cqs.CQS_ISP_Progetto__c = pro.Id;
        cqsList.add(cqs);
        insert cqsList;

        Attachment attach=new Attachment();     
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=cqsList[0].id;
        insert attach;
        
        
       ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(cqsList);
        CQS_Isp_SignatureComponentController  isp = new CQS_Isp_SignatureComponentController (stdSetController);
        
        
        //stdSetController.stdCntrlr (isp);
        
        CQS_Isp_SignatureComponentController.closeAfterSave();
        CQS_Isp_SignatureComponentController.saveSignature('Test',cqsList[0].Id);
    }
}