objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>EOF_ID_Notifica__c</fullName>
        <label>ID Notifica</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_PROFILO__c</fullName>
        <label>Profilo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OF_TTM_SendRetryTTM_Methods_Mock.cls
@isTest
global class OF_TTM_SendRetryTTM_Methods_Mock implements WebServiceMock {
       global void doInvoke(
           Object stub,
           Object request,
           Map<String, Object> response,
           String endpoint,
           String soapAction,
           String requestName,
           String responseNS,
           String responseName,
           String responseType) {
               
        EOF_EAI_Service_Log__c ser = new EOF_EAI_Service_Log__c();
        ser.EOF_PROFILO__c = 'Test';
        ser.EOF_ID_Notifica__c = 'Test';
        insert ser;
        
/*OF_TTM_ForwardRequest.SyncPortTypeEndpoint1 stub1 = new OF_TTM_ForwardRequest.SyncPortTypeEndpoint1();
stub1.timeout_x = 30000;
response.put('response_x', stub1); */
               
        //OF_TT_WS_Notifica.TroubleTicketNotifyResp_element resp = new OF_TT_WS_Notifica.TroubleTicketNotifyResp_element();
        OF_TTM_ForwardRequest_Element.TroubleTicketFwdResp_element resp = new OF_TTM_ForwardRequest_Element.TroubleTicketFwdResp_element();
        resp.Esito = '0';
        
        response.put('response_x', resp ); 
               
      
}
}