objects/EOF_EAI_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>EOF_CLUSTER_PROMOZIONE__c</fullName>
        <label>Cluster Promozione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_CODICE_PROGETTO_SPECIALE__c</fullName>
        <label>Codice Progetto Speciale</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_COGNOME_REFERENTE_TECNICO_OLO__c</fullName>
        <label>Cognome Referente Tecnico OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_COgnome_CLiente__c</fullName>
        <label>Cognome Cliente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Operatore__c</fullName>
        <label>Codice Operatore</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Codice_Ordine_OLO__c</fullName>
        <label>Codice Ordine OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_DATA_PREVISTA_ATTIVAZIONE__c</fullName>
        <label>Data Prevista Attivazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EOF_Data_Notifica__c</fullName>
        <label>Data Notifica</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EOF_EMAIL_REFERENTE_TECNICO_OLO__c</fullName>
        <label>Email Referente Tecnico OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_BUILDING__c</fullName>
        <label>ID Building</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Notifica__c</fullName>
        <label>ID Notifica</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Pop__c</fullName>
        <label>Identificativo del POP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Risorsa__c</fullName>
        <label>ID Risorsa</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_INFORMAZIONI_LOGISTICA_APPARATI__c</fullName>
        <label>Informazioni Logistica Apparati</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_NOME_REFERENTE_TECNICO_OLO__c</fullName>
        <label>Nome Referente Tecnico OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_NOTE__c</fullName>
        <label>Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_NUMERO_TELEFONICO_PRINCIPALE_LINEA__c</fullName>
        <label>Numero Telefonico Principale Linea</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Nome_Cliente__c</fullName>
        <label>Nome Cliente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_ORARIO_APPUNTAMENTO__c</fullName>
        <label>Orario Appuntamento</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_PROFILO__c</fullName>
        <label>Profilo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_PROMOZIONE__c</fullName>
        <label>Promozione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_RECAPITO_TELEFONICO_CLIENTE_1__c</fullName>
        <label>Recapito Telefonico Cliente 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_RECAPITO_TELEFONICO_CLIENTE_2__c</fullName>
        <label>Recapito Telefonico Cliente 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_RECAPITO_TEST_LINEA__c</fullName>
        <label>Recapito Test Linea</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_SCALA_PALAZZINA__c</fullName>
        <label>Scala Palazzina</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Stato_Richiesta__c</fullName>
        <label>Stato Richiesta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_TELEFONO_REFERENTE_OLO_ONFIELD_NOTEC__c</fullName>
        <label>Telefono Referente OLO OnField NoTech</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_TELEFONO_REFERENTE_TECNICO_OLO__c</fullName>
        <label>Telefono Referente Tecnico OLO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_CUSTOMER_VLAN__c</fullName>
        <label>Customer VLan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_INFORMAZIONI_VLAN__c</fullName>
        <label>Informazioni VLan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_KIT_CONSEGNA_VLAN__c</fullName>
        <label>Kit Consegna VLan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_MODELLO_DI_SERVIZIO_VLAN__c</fullName>
        <label>Modello Di Servizio VLan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_PROFILO_VLAN_PL__c</fullName>
        <label>Profilo VLan Picklist</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COS 0</fullName>
                </value>
                <value>
                    <fullName>COS 1</fullName>
                </value>
                <value>
                    <fullName>COS 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OF_SA_PROFILO_VLAN__c</fullName>
        <label>Profilo VLan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_SERVICE_VLAN__c</fullName>
        <label>Service VLan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_USER_VLAN__c</fullName>
        <label>User Vlan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_SA_VLan_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VLan Log</label>
        <referenceTo>EOF_EAI_Service_Log__c</referenceTo>
        <relationshipLabel>VLan Log</relationshipLabel>
        <relationshipName>OF_SA_VLan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EAI Service Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Codice Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EAI Service Logs</pluralLabel>
    <recordTypes>
        <fullName>OF_SA_Vlan</fullName>
        <active>true</active>
        <label>OF - SA - Vlan</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PO_COMP_InserimentoVLAN_Controller.cls
public class PO_COMP_InserimentoVLAN_Controller {
    public EOF_EAI_Service_Log__c slVlan{get;set;}  
    public static EOF_EAI_Service_Log__c slOrig{get;set;}
    public Map<String,Id> rtMap{get;set;}
    public boolean modifyMode{get;set;}
    public boolean insertMode{get;set;}
    public static String idVlan{get;set;}
    
    public List<SelectOption> getProfiloVLAN()  {
       List<SelectOption> options = new List<SelectOption>();
       Schema.DescribeFieldResult fieldResult = EOF_EAI_Service_Log__c.OF_SA_PROFILO_VLAN_PL__c.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
       for( Schema.PicklistEntry f : ple)
       {
               options.add(new SelectOption(f.getLabel(), f.getValue()));
       }     
       return options;
    }
    
    public PO_COMP_InserimentoVLAN_Controller(){
        modifyMode=false;
        insertMode=false;
        
        //EC ADD 2019 04 08
          slOrig=[select id,recordtype.developername,EOF_Codice_Operatore__c,EOF_Codice_Ordine_OLO__c,EOF_Data_Notifica__c,EOF_ID_Notifica__c,EOF_NOME_REFERENTE_TECNICO_OLO__c,
				EOF_COGNOME_REFERENTE_TECNICO_OLO__c,EOF_Telefono_Referente_OLO_Onfield_Notec__c,EOF_TELEFONO_REFERENTE_TECNICO_OLO__c,
				EOF_Nome_Cliente__c,EOF_COgnome_CLiente__c,EOF_RECAPITO_TELEFONICO_CLIENTE_1__c,EOF_RECAPITO_TELEFONICO_CLIENTE_2__c,
				EOF_INFORMAZIONI_LOGISTICA_APPARATI__c,EOF_DATA_PREVISTA_ATTIVAZIONE__c,EOF_ORARIO_APPUNTAMENTO__c,EOF_CODICE_PROGETTO_SPECIALE__c,
				EOF_PROMOZIONE__c,EOF_CLUSTER_PROMOZIONE__c,EOF_NOTE__c,EOF_ID_BUILDING__c,EOF_SCALA_PALAZZINA__c,EOF_NUMERO_TELEFONICO_PRINCIPALE_LINEA__c,
				EOF_RECAPITO_TEST_LINEA__c, EOF_ID_Pop__c,EOF_PROFILO__c,EOF_Email_Referente_Tecnico_OLO__c,EOF_ID_Risorsa__c
				from EOF_EAI_Service_Log__c 
				where ID=:ApexPages.currentPage().getParameters().get('origId')];
        //EC end ADD 2019 04 08
        
        if(idVlan!=null){
            slVlan=[select Id, OF_SA_KIT_CONSEGNA_VLAN__c,OF_SA_USER_VLAN__c,OF_SA_SERVICE_VLAN__c,
                    OF_SA_PROFILO_VLAN__c,OF_SA_PROFILO_VLAN_PL__c,OF_SA_CUSTOMER_VLAN__c,OF_SA_MODELLO_DI_SERVIZIO_VLAN__c,OF_SA_INFORMAZIONI_VLAN__c
                    from EOF_EAI_Service_Log__c where id=:idVlan];
            modifyPicklist();
            modifyMode=true;
        }
        else{
            insertMode=true;
            slVlan= new EOF_EAI_Service_Log__c();
            slVlan.OF_SA_VLan_Log__c=slOrig.Id;
            List<recordtype> rtList=[select Id,developerName from recordtype];                                                                               
            rtMap = new Map<String,Id>(); 
            for(recordtype rt :rtList){
                rtMap.put(rt.developerName, rt.Id); 
            }  
            
            slVlan.recordtypeId=rtMap.get('OF_SA_Vlan');
            slVlan.EOF_Stato_Richiesta__c='Bozza Portale';
            slVlan.EOF_Codice_Ordine_OLO__c=ApexPages.currentPage().getParameters().get('codOrdOlo');
        }
    }
    public PageReference annullaVLAN(){
        PageReference pageRef = new PageReference('/PO_OpenStreamService_InsertNewRequest');
        if(ApexPages.currentPage().getParameters().get('orig') =='ATT'){
            pageRef.getParameters().put('proc','attivazioneInserita');
            pageRef.getParameters().put('origId',ApexPages.currentPage().getParameters().get('origId'));
        }
        if(ApexPages.currentPage().getParameters().get('orig') =='CESS'){
            pageRef.getParameters().put('proc','cessazioneInserita');
            pageRef.getParameters().put('origId',ApexPages.currentPage().getParameters().get('origId'));
        }
        
        pageRef.setRedirect(true);
        return pageref;
    }
    //GB - 06.02.2018 Start
    private void mappingPicklist(){
        if(slVlan.OF_SA_PROFILO_VLAN__c=='COS 0')
                slVlan.OF_SA_PROFILO_VLAN__c='0';
        if(slVlan.OF_SA_PROFILO_VLAN__c=='COS 1')
                slVlan.OF_SA_PROFILO_VLAN__c='1';
        if(slVlan.OF_SA_PROFILO_VLAN__c=='COS 5')
                slVlan.OF_SA_PROFILO_VLAN__c='5';
    }
    public void modifyPicklist(){
        if(slVlan.OF_SA_PROFILO_VLAN__c=='0')
                slVlan.OF_SA_PROFILO_VLAN__c='COS 0';
        if(slVlan.OF_SA_PROFILO_VLAN__c=='1')
                slVlan.OF_SA_PROFILO_VLAN__c='COS 1';
        if(slVlan.OF_SA_PROFILO_VLAN__c=='5')
                slVlan.OF_SA_PROFILO_VLAN__c='COS 5';
    }
    //GB - 06.02.2018 Start
    public PageReference InserisciVLAN(){
        mappingPicklist();
        insert slVlan;
        PageReference pageRef = new PageReference('/PO_OpenStreamService_InsertNewRequest');
        if(ApexPages.currentPage().getParameters().get('orig') =='ATT'){
            pageRef.getParameters().put('proc','attivazioneInserita');
            pageRef.getParameters().put('origId',ApexPages.currentPage().getParameters().get('origId'));
        }
        if(ApexPages.currentPage().getParameters().get('orig') =='CESS'){
            pageRef.getParameters().put('proc','cessazioneInserita');
            pageRef.getParameters().put('origId',ApexPages.currentPage().getParameters().get('origId'));
        }
        pageRef.setRedirect(true);
        return pageref; 
    }
    public PageReference updateVLAN(){
        mappingPicklist();
        update slVlan;
        PageReference pageRef = new PageReference('/PO_OpenStreamService_InsertNewRequest');
        if(ApexPages.currentPage().getParameters().get('orig') =='ATT'){
            pageRef.getParameters().put('proc','attivazioneInserita');
            pageRef.getParameters().put('origId',ApexPages.currentPage().getParameters().get('origId'));
        }
        if(ApexPages.currentPage().getParameters().get('orig') =='CESS'){
            pageRef.getParameters().put('proc','cessazioneInserita');
            pageRef.getParameters().put('origId',ApexPages.currentPage().getParameters().get('origId'));
        }
        pageRef.setRedirect(true);
        return pageref;
    }
}