objects/EOF_Notify__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Notifiche</relationshipLabel>
        <relationshipName>Notifiche</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commercial_element_istanziato__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial element istanziato</label>
        <referenceTo>OF_CommercialElementIstanziato__c</referenceTo>
        <relationshipLabel>Notifiche</relationshipLabel>
        <relationshipName>Notifiche</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EOF_ID_Notifica__c</fullName>
        <label>ID Notifica</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EOF_Inviata__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inviata</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_isElaborato__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isElaborato</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>indice__c</fullName>
        <label>indice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Notifica</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notify Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifiche</pluralLabel>
    <recordTypes>
        <fullName>EOF_BILL_Asset</fullName>
        <active>true</active>
        <description>Record Type per la gestione del WS per la sincronizzazione del billing degli Asset</description>
        <label>EOF_BILL_Asset</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OF_CallWSFattibilita.cls
global class OF_CallWSFattibilita implements Database.AllowsCallouts,Database.Batchable<sObject>, Database.Stateful {
    
    private Integer firstIndex;
    private Integer lastIndex;
    
    public OF_CallWSFattibilita(Integer f, Integer l) {
        firstIndex = f;
        lastIndex = l;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {        
        String query = 'SELECT Id, Commercial_element_istanziato__c, EOF_ID_Notifica__c, Asset__c FROM EOF_Notify__c '
            + ' WHERE OF_isElaborato__c = true AND RecordType.DeveloperName =\'EOF_Bill_Asset\' AND indice__c >= :firstIndex AND indice__c <= :lastIndex';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<EOF_Notify__c> scope) {
        
        system.debug('@@@@@@secondo batch');
        // lo scope size è 1  quindi la query NON è in un ciclo For
        for (EOF_Notify__c noti : scope) {
            Boolean res = SyncBillingAssetUtils.callWSAssetVerticaleByCei(noti.Commercial_element_istanziato__c,noti.EOF_ID_Notifica__c);
            if(res)
            {

            }
            
            noti.OF_isElaborato__c = false;
            noti.EOF_Inviata__c = true;
        }
        
        update scope;
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
}