objects/Objects_Delete__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>DateTime_Check_Field__c</fullName>
        <label>DateTime Check Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nome_Oggetto__c</fullName>
        <label>Nome Oggetto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Delete_Records_Before__c</fullName>
        <label>Delete Records Before</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OF_Record_Limit__c</fullName>
        <label>Record Limit</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Objects Delete</label>
</CustomObject>

objects/TEMPLOG__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DataInserimento__c</fullName>
        <label>DataInserimento</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Desc__c</fullName>
        <label>Desc</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <label>Timestamp</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>TEMPLOG</label>
    <nameField>
        <label>TEMPLOG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TEMPLOG</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OF_BATCH_DeleteObjects.cls
global class OF_BATCH_DeleteObjects implements Database.Batchable<sObject>{
	
    global Database.QueryLocator start(Database.BatchableContext BC){
    	List<Objects_Delete__c> myCustomValues = Objects_Delete__c.getAll().Values();
        String query = 'SELECT Id FROM '+myCustomValues[0].Nome_Oggetto__c+' where '+myCustomValues[0].DateTime_Check_Field__c+' < '+myCustomValues[0].OF_Delete_Records_Before__c+' LIMIT '+myCustomValues[0].OF_Record_Limit__c;
        return Database.getQueryLocator(query);
    }
 
    global void execute(Database.BatchableContext BC, List<sObject> scope){		
    	if(scope!=null && !scope.isEmpty()){
    		delete scope;
    		Database.emptyRecycleBin(scope);
    	}
    }  
    global void finish(Database.BatchableContext BC){
		AsyncApexJob a = [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors
                    FROM AsyncApexJob WHERE ID =: BC.getJobId() ];
        system.debug('Processed ' +a.TotalJobItems +' batches with '+ a.NumberOfErrors + ' failures.');
    	Templog__c t = new Templog__c();
     	t.Type__c='T'; 
    	t.Name='Batch_DeleteObjects';
    	t.DataInserimento__c=system.now().format('YYYY-MM-dd HH:mm:ss');
    	t.Timestamp__c=system.now().format('YYYY-MM-dd HH:mm:ss');
    	t.Desc__c='Processed ' +a.TotalJobItems +' batches with '+ a.NumberOfErrors + ' failures.';
    	t.Class__c='OF_BATCH_DeleteObjects';
    	t.Method__c='execute';
    	insert t;
    }
}