objects/OF_CV_Regole_Vendita__c.object
<CustomObject>
    <fields>
        <fullName>Codice_OLO__c</fullName>
        <label>Codice_OLO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Regola__c</fullName>
        <label>Id_Regola</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Riga__c</fullName>
        <label>Riga</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Servizio__c</fullName>
        <label>Servizio</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attivo</fullName>
                </value>
                <value>
                    <fullName>Passivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isAttiva__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isAttiva</label>
        <type>Checkbox</type>
    </fields>
    <label>Regole Vendita</label>
    <nameField>
        <label>Regole Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regole Vendita</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OF_CV_ElencoRegole_Controller_Test.cls
@isTest
public class OF_CV_ElencoRegole_Controller_Test {
    static testMethod void testMethod1(){
        Test.startTest();
        List<OF_CV_Regole_Vendita__c> lst = new List<OF_CV_Regole_Vendita__c>();
        for(Integer i = 0; i < 5; i++){
            OF_CV_Regole_Vendita__c tmp = new OF_CV_Regole_Vendita__c(Id_Regola__c='Regola'+i, Codice_OLO__c='VF', isAttiva__c=true, Servizio__c='ATTIVO', Riga__c = i);
            lst.add(tmp);
        }
        insert lst;
        Test.setCurrentPage(Page.OF_CV_ElencoRegole);
        ApexPages.currentPage().getParameters().put('olo','VF');
        ApexPages.currentPage().getParameters().put('servizio','ATTIVO');
        
        OF_CV_ElencoRegole_Controller tmp = new OF_CV_ElencoRegole_Controller();
        tmp.olo = 'VF';
        tmp.servizio = 'ATTIVO';
        tmp.creaRegola();
        tmp.clonaRegola();
        tmp.annulla();
        tmp.modificaRegola();
        tmp.valorizzaDati();
        tmp.confermaScelta();
        tmp.lstRegole.get(0).isAttiva__c = false;
        tmp.confermaScelta();
        Test.stopTest();
    }
}