objects/OF_CV_Regole_Vendita__c.object
<CustomObject>
    <fields>
        <fullName>Codice_OLO__c</fullName>
        <label>Codice_OLO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Regola__c</fullName>
        <label>Id_Regola</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Servizio__c</fullName>
        <label>Servizio</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attivo</fullName>
                </value>
                <value>
                    <fullName>Passivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isAttiva__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isAttiva</label>
        <type>Checkbox</type>
    </fields>
    <label>Regole Vendita</label>
    <nameField>
        <label>Regole Vendita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regole Vendita</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OF_CV_Home_Controller_Test.cls
@isTest
public class OF_CV_Home_Controller_Test {
    
    static testMethod void testMethod1(){
        List<OF_CV_Regole_Vendita__c> lst = new List<OF_CV_Regole_Vendita__c>();
        for(Integer i = 0; i < 5; i++){
            OF_CV_Regole_Vendita__c tmp = new OF_CV_Regole_Vendita__c(Id_Regola__c='Regola'+i, Codice_OLO__c='VF', isAttiva__c=true, Servizio__c='ATTIVO');
            lst.add(tmp);
        }
        insert lst;
        OF_CV_Home_Controller tmp = new OF_CV_Home_Controller();
        tmp.operatore_selected = 'VF';
        tmp.stato_selected = 'ATTIVO';
        tmp.visualizzaRegole();
        tmp.creaNuovaRegola();
        tmp.valorizzaDati();
    }
    
    static testMethod void testMethod2(){
        OF_CV_Home_Controller tmp = new OF_CV_Home_Controller();
        tmp.visualizzaRegole();
    }
    
    static testMethod void test_estraiVendibilita(){
        
        Test.setCurrentPage(Page.OF_CV_Home);
        ApexPages.currentPage().getParameters().put('olo','VF');
        ApexPages.currentPage().getParameters().put('servizio','ATTIVO');

        Test.startTest();
        OF_CV_Home_Controller contr = new OF_CV_Home_Controller();
        PageReference p = contr.estraiVendibilita();
        Test.stopTest();
    }
}