objects/OF_Enable_PO_UpdateOppCase_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_Enable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Enable PO_UpdateOppCase Trigger</label>
</CustomObject>

objects/OF_Puntamento_Callout__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_OGW__c</fullName>
        <label>OGW</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Puntamento Callout</label>
</CustomObject>

objects/OF_Tibco_userID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Metodo per recuperare lo UserID di Tibco</description>
    <fields>
        <fullName>OF_Tibco_ID__c</fullName>
        <label>Tibco ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Tibco userID</label>
</CustomObject>

classes/OF_Billing_Outbound_Service3_Test.cls
@isTest
public class OF_Billing_Outbound_Service3_Test {
    
    @testSetup 
    public static void testSetUpData() {
        Insert new OF_Puntamento_Callout__c(Name = 'OGW',OF_OGW__c = 'Test');
        Insert new OF_Tibco_userID__c(Name = 'Tibco UserID',OF_Tibco_ID__c= 'Test');
        Insert new OF_Enable_PO_UpdateOppCase_Trigger__c(Name = 'Status',OF_Enable_Trigger__c= true);
        
    }

    public static testMethod void test(){
        
    Test.startTest(); 
    Test.setMock(WebServiceMock.class, new Billing_Outbound_Service3_Mock());
    OF_Billing_Outbound_Service3.BillingOrderManagerSOAP obj1 = new OF_Billing_Outbound_Service3.BillingOrderManagerSOAP();
    OF_Billing_Outbound_Schema3.BillingOrderManagerResponsetType obj2 = new OF_Billing_Outbound_Schema3.BillingOrderManagerResponsetType();
    OF_Billing_Outbound_Schema3.OrderItemType orderItem = new OF_Billing_Outbound_Schema3.OrderItemType();
          OF_Billing_Outbound_Schema3.OrderInstallmentDetailsType agree6 = new OF_Billing_Outbound_Schema3.OrderInstallmentDetailsType ();
    OF_Billing_Outbound_Schema3.OrderItemOtherType orderItemOther = new OF_Billing_Outbound_Schema3.OrderItemOtherType();
    OF_Billing_Outbound_Schema3.orderItemPrices_element orderItemPrices = new OF_Billing_Outbound_Schema3.orderItemPrices_element();
    obj1.OrderManager(orderItem, orderItemOther, orderItemPrices);
    obj1.OrderManager(orderItem, orderItemOther, orderItemPrices,agree6);
    Test.stopTest();
        
    }
}