objects/OF_Enable_PO_UpdateOppCase_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_Enable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Enable PO_UpdateOppCase Trigger</label>
</CustomObject>

objects/OF_Puntamento_Callout__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OF_OGW__c</fullName>
        <label>OGW</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Puntamento Callout</label>
</CustomObject>

objects/OF_Tibco_userID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Metodo per recuperare lo UserID di Tibco</description>
    <fields>
        <fullName>OF_Tibco_ID__c</fullName>
        <label>Tibco ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Tibco userID</label>
</CustomObject>

classes/OF_Billing_Outbound_Service_Test.cls
@isTest
public class OF_Billing_Outbound_Service_Test{
     @testSetup 
            public static void testSetUpData() {
                Insert new OF_Puntamento_Callout__c(Name = 'OGW',OF_OGW__c = 'Test');
                Insert new OF_Tibco_userID__c(Name = 'Tibco UserID',OF_Tibco_ID__c= 'Test');
                Insert new OF_Enable_PO_UpdateOppCase_Trigger__c(Name = 'Status',OF_Enable_Trigger__c= true);
                
            }
    public static testMethod void OF_Billing_Outbound_SchemaMethod(){
        Test.startTest();
        OF_Billing_Outbound_Service.BillingAccountManagerSOAP  accsoap = new  OF_Billing_Outbound_Service.BillingAccountManagerSOAP();
        Date dt = system.today();
        Test.setMock(WebServiceMock.class, new OF_Billing_Outbound_Service_mock ());
        accsoap.AccountManager('Test','Test','Test','Test','Test','Test','Test','Test','Test','Test','Test','Test','Test','Test','Test','Test','Test','Test','Test','Test');
        Test.stopTest();
    }
}