objects/Verticali__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Email_CC__c</fullName>
        <defaultValue>&apos;dl-it-atos-oftibco@atos.net&apos;</defaultValue>
        <description>dl-it-atos-oftibco@atos.net</description>
        <label>Email_CC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <defaultValue>&apos;openfiber.itsupport@enel.com&apos;</defaultValue>
        <description>Openfiber.itsupport@enel.com</description>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_from__c</fullName>
        <defaultValue>&apos;Delivery Services Openfiber&apos;</defaultValue>
        <label>Email_from</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextBody__c</fullName>
        <defaultValue>&quot;Ciao,in allegato il file contenente gli ID Risorsa CRM, per i quali vi chiedo cortesemente l estrazione dei dati toponomastici, gli identificativi building, palazzina e scala, secondo il tracciato condiviso.&quot;</defaultValue>
        <label>TextBody</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>delayAlgoritmo__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Il valore contenuto in questo campo rappresenta i minuti di delay utilizzato per lo scheduling del batch dell&apos;algoritmo</description>
        <label>delayAlgoritmo</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>delayBonifica__c</fullName>
        <defaultValue>240</defaultValue>
        <description>il valore indica i minuti con cui viene schedulata la classe di bonifica finale del processo</description>
        <label>delayBonifica</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>emailSubject__c</fullName>
        <defaultValue>&apos;Estrazione PNI per Verticali &apos;</defaultValue>
        <label>emailSubject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>giorniTolleranza__c</fullName>
        <defaultValue>-2</defaultValue>
        <label>giorniTolleranza</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>limitBatch__c</fullName>
        <defaultValue>10</defaultValue>
        <description>limite di righe elaborate per singolo run del batch dell&apos;algoritmo</description>
        <label>limitBatch</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Verticali</label>
</CustomObject>

classes/OF_WS_SEMAFORO_VERTICALE_Test.cls
@isTest
public class OF_WS_SEMAFORO_VERTICALE_Test {
    
    
    
    
    
    public static testmethod void test(){
        
        Test.startTest();
        
        
                Verticali__c cs = new Verticali__c();
        cs.Name='test';
        cs.delayAlgoritmo__c = 1;
        cs.delayBonifica__c = 240;
        cs.Email__c = 'test@test.org';
        cs.Email_CC__c = 'test@test.org';
        cs.Email_from__c = 'Delivery Services Openfiber';
        cs.emailSubject__c = 'subj';
        cs.giorniTolleranza__c = -2;
        cs.limitBatch__c = 10;
        cs.TextBody__c = 'text';
        
        insert cs;
        
        
        //Test.setMock(WebServiceMock.class, new OF_WS_SEMAFORO_VERTICALE_Mock()); 
        OF_WS_SEMAFORO_VERTICALE.OF_WS_SEMAFORO_VERTICALE_Request req = new OF_WS_SEMAFORO_VERTICALE.OF_WS_SEMAFORO_VERTICALE_Request();
        req.DESCRIZIONE='descrizione';
        req.ESITO_CARICAMENTO='OK';
        OF_WS_SEMAFORO_VERTICALE.StatusChiamata(req);
        test.stopTest();
        
    }
    
}